### ISSUE TITLE
NullSafety Iterable<Object>does not match 'Iterable<Object?>

### ISSUE THREAD

**Issue by neckaros** [google/built_value.dart#1002]
I have a package that use Built_value and has been migrated to Null Safety. In this package all is fine and tests are OK

But when i run in an application that is not Null Safe (Evironment:  sdk: ">=2.11.0 <3.0.0") i get the following error.
```
/C:/homeware/flutter/.pub-cache/hosted/pub.dartlang.org/anilist-2.0.0-NullSafety.1/lib/models/anilist_media.g.dart:264:70: Error: The parameter 'serialized' of the method '_$AnilistMediaSerializer.deserialize' **has type 'Iterable<Object>', which does not match the corresponding type, 'Iterable<Object?>'**, in the overridden method, 'StructuredSerializer.deserialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a supertype of 'Iterable<Object?>', or, for a covariant parameter, a subtype.
  AnilistMedia deserialize(Serializers serializers, Iterable<Object> serialized,

                                                                     ^
/C:/homeware/flutter/.pub-cache/hosted/pub.dartlang.org/built_value-8.0.2/lib/serializer.dart:356:5: Context: This is the overridden method ('deserialize').

  T deserialize(Serializers serializers, Iterable<Object?> serialized,
```
i have looked at source and generated code but i don't see any issue. non null Object should be usable as nullable Object.
should the generator produce 
```
@override
  AnilistMedia deserialize(Serializers serializers, Iterable<Object**?**> serialized,
      {FullType specifiedType = FullType.unspecified}) {
```
instead of what it produce right now:
```
@override
  AnilistMedia deserialize(Serializers serializers, Iterable<Object> serialized,
      {FullType specifiedType = FullType.unspecified}) {
```
to match overriden signature:
built_value-8.0.2\lib\serializer.dart:StructuredSerializer
```
T deserialize(Serializers serializers, Iterable<Object**?**> serialized,
      {FullType specifiedType = FullType.unspecified});
```
?

**Comment by kuhnroyal** [comment]
Did you previously use `8.0.0`? Then you may need to regenerate (`pub run build_runner build`).

**Comment by neckaros** [comment]
Thanks for the reply
i did in both. But anyway building in my app should not impact package classes right?

**Comment by kuhnroyal** [comment]
The signature of `StructuredSerializer` changed and your `AnilistMedia` serializer had old code that didn't match the new signature. Regenerating should solve this.

**Comment by davidmorgan** [comment]
Sorry about that. Strictly speaking `8.0.1` should have been a major version release. Because flutter users couldn't resolve `8.0.0` anyway, it needed deps bumps, I figured the pain of a breaking minor release would be less than the pain of a major versinon bump.

**Comment by neckaros** [comment]
I switched from
`built_value: ^8.0.0`
to
`built_value: ^8.0.2`

and it indeed fixed it!

Thanks @kuhnroyal and @davidmorgan
