### ISSUE TITLE
build_runner ^1.12.1 and built_value_generator ^8.0.2, version solving failed

### ISSUE THREAD

**Issue by ashim-k-saha** [google/built_value.dart#1003]
Because no versions of built_value_generator match >8.0.2 <9.0.0 and built_value_generator 8.0.2 depends on build ^1.0.0, built_value_generator ^8.0.2 requires build ^1.0.0.
And because build_runner >=1.12.0 depends on build >=2.0.0 <2.1.0, built_value_generator ^8.0.2 is incompatible with build_runner >=1.12.0.
So, because todo depends on both build_runner ^1.12.1 and built_value_generator ^8.0.2, version solving failed.

**Comment by davidmorgan** [comment]
Looks like `source_gen` needs a release first, filed https://github.com/dart-lang/source_gen/issues/516

**Comment by davidmorgan** [comment]
Released 8.0.3.

**Comment by ashim-k-saha** [comment]
Thanks :)
