### ISSUE TITLE
Why does deserializeWith return a nullable object?

### ISSUE THREAD

**Issue by lukaszciastko** [google/built_value.dart#1005]
With the recent built_value release, the `deserializeWith` now has a nullable return type. This seems like a potentially breaking change. What's the reason behind it? Previously, I relied on this method to always return an object or throw an error if the object cannot be deserialised. Did the behaviour change?

**Comment by davidmorgan** [comment]
It's to allow plugins to use nulls, which is sometimes necessary depending on the details of the json you're interacting with.

The default format didn't change.

I suggest either using `!` whenever you use deserializerWith, or adding your own extension method to do it for you.

Thanks.

**Comment by lukaszciastko** [comment]
Thank you for the clarification! I went with the `!` but wasn't sure whether this was the right approach.
