### ISSUE TITLE
Version solving failed on build_value_generator

### ISSUE THREAD

**Issue by himamis** [google/built_value.dart#1009]
I am trying to update json_serializable and built_value_generator to the latest versions, and I get this
```
Because json_serializable >=4.1.0 depends on source_gen ^1.0.0 and built_value_generator >=6.0.0 depends on source_gen ^0.9.0, json_serializable >=4.1.0 is incompatible with built_value_generator >=6.0.0.
So, because ***** depends on both json_serializable >=4.1.0 and built_value_generator >=8.0.0-nullsafety.0, version solving failed.
```
Would upgrading source_gen on built_value_generator to 1.0 solve this?

**Comment by marcos930807** [comment]
> I am trying to update json_serializable and built_value_generator to the latest versions, and I get this
> 
> ```
> Because json_serializable >=4.1.0 depends on source_gen ^1.0.0 and built_value_generator >=6.0.0 depends on source_gen ^0.9.0, json_serializable >=4.1.0 is incompatible with built_value_generator >=6.0.0.
> So, because ***** depends on both json_serializable >=4.1.0 and built_value_generator >=8.0.0-nullsafety.0, version solving failed.
> ```
> 
> Would upgrading source_gen on built_value_generator to 1.0 solve this?

I have the same problem but with auto_route_generator:
Because built_value_generator >=6.0.0 depends on source_gen ^0.9.0 and auto_route_generator >=1.0.2 depends on source_gen ^1.0.0, built_value_generator >=6.0.0 is incompatible with auto_route_generator >=1.0.2.
