### ISSUE TITLE
Collections with nullable values throw on deserialization

### ISSUE THREAD

**Issue by smkhalsa** [google/built_value.dart#1011]
First of all, thanks so much for the great library, and for all the additional work going into migrating to null-safety.

I'm trying to migrate [gql_build](https://pub.dev/packages/gql_build), a dart code generator for GraphQL which is used by the [ferry](https://github.com/gql-dart/ferry) GraphQL client.

I've seen some of the other issues (#984, #964) around null-safe deserialization as well as the changes made in #994 to address them.

However, we still have a use case that still appears to be broken: **collections with nullable values**.

Take the following example...

```dart
abstract class GReviewInput
    implements Built<GReviewInput, GReviewInputBuilder> {
  GReviewInput._();

  factory GReviewInput([Function(GReviewInputBuilder b) updates]) =
      _$GReviewInput;

  int get stars;
  String? get commentary;
  BuiltList<DateTime?>? get seenOn;  // <-- collection with nullable

  static Serializer<GReviewInput> get serializer => _$gReviewInputSerializer;
}
```
Trying to deserialize an instance of `GReviewInput`...
```dart
final input = GReviewInput((b) => b..stars = "5")

final serialized = serializers.toJson(GReviewInput.serializer, input);

final deserialized =
    serializers.fromJson(GReviewInput.serializer, serialized); // <-- throws exception
```
... throws the following exception.
```
type '_BuiltList<DateTime?>' is not a subtype of type 'BuiltList<Object>' in type cast
```

**Comment by davidmorgan** [comment]
`BuiltList` doesn't allow nulls; it would need updating first.

With null safety the original justification for rejecting nulls is gone, so that would make sense.

**Comment by smkhalsa** [comment]
@davidmorgan thanks for the lightning-fast response.

> `BuiltList` doesn't allow nulls; it would need updating first.
> 
> With null safety the original justification for rejecting nulls is gone, so that would make sense.

That would be great! I see that there were a few issues (https://github.com/google/built_collection.dart/issues/215, https://github.com/google/built_collection.dart/issues/140) about this pre-NNBD. Should this issue be moved to `built_collection`?

Would `built_value` serialization just work once nulls are allowed in `BuiltList`? Or would there still be an issue trying to cast `BuiltList<SomeType?>` to `BuiltList<Object>`?

**Comment by davidmorgan** [comment]
Filed https://github.com/google/built_collection.dart/issues/232 for `built_collection`.

I suspect there will need to be changes to `built_value` too once that is in.

Thanks.

**Comment by davidmorgan** [comment]
In the interests of setting expectations: I definitely _want_ to do this, but I don't know when I can get to it.

**Comment by davidmorgan** [comment]
Will handle this as https://github.com/google/built_value.dart/issues/1049

**Comment by davidmorgan** [comment]
`built_collection` change is released, and the upcoming `built_value` release supports it :)
