### ISSUE TITLE
The argument type 'Serializer<dynamic>?' can't be assigned to the parameter type 'Serializer<T>'.

### ISSUE THREAD

**Issue by rhyscoronado** [google/built_value.dart#1016]
```
T? deserialize<T>(dynamic value) => standardSerializers.deserializeWith<T>(
      standardSerializers.serializerForType(T),
      value,
    );

```

Using above code throws _The argument type 'Serializer<dynamic>?' can't be assigned to the parameter type 'Serializer<T>'. dart argument_type_not_assignable.

I can't seem to make it work no matter what I do.

**Comment by davidmorgan** [comment]
Try `standardSerializers.serializeForType(T)!` :)

**Comment by jaybryantc** [comment]
> Try `standardSerializers.serializeForType(T)!` :)

I tried this and does not work

**Comment by kuhnroyal** [comment]
You need to cast it to `Serializer<T>`.
