### ISSUE TITLE
Bad state: No serializer for 'CastList<dynamic, String>'.

### ISSUE THREAD

**Issue by elvisun** [google/built_value.dart#1017]
Serialization fails for the following code:

```
abstract class M implements Built<M, MBuilder> {
  List<String> get categories;

  static Serializer<M> get serializer =>
      _$mSerializer;
}
```

Error message is:
```
Bad state: No serializer for 'CastList<dynamic, String>'.
```

Once I changed the `List<String>` to `BuiltList<String>` it worked, is this the proper solution? Can we surface a better error message?

**Comment by davidmorgan** [comment]
Sorry about that.

It's because of https://github.com/google/built_value.dart/issues/675 ... the generator is actually supposed to stop you using `List` altogether, but that check broke and is a little hard to reland. I'll try to prioritize that.
