### ISSUE TITLE
Deserialisation fails for BuiltMap<String, BuiltSet<T>> with generated serializers

### ISSUE THREAD

**Issue by stefantds** [google/built_value.dart#1018]
Hi! I'm not 100% sure if the case described below is not supported or is a bug (even after spending some time searching through the docs/issues/articles). So I thought it might be worth reporting it as a potential issue. If this is indeed a bug and the description below is not enough I am happy to provide an example that tries to isolate the issue.

### Issue
I'm using a built value class with an attribute of type ```BuiltMap<String, BuiltSet<QuestionTag>>``` that I want to serialise. The problem is that the code generated by default fails when trying to deserialise (see result below). From what I see the built value class and builder look OK but the generated code doesn't add automatically a builder factory for ```BuiltSet<QuestionTag>``` to the `serializers.g.dart` file, it just adds a builder factory for ```BuiltMap<String, BuiltSet<QuestionTag>>```.

### Result
```
DeserializationError (Deserializing '[...]' to 'BuiltMap<String, BuiltSet<QuestionTag>>' failed due to: Deserializing '[difficult]' to 'BuiltSet<QuestionTag>' failed due to: Bad state: No builder factory for BuiltSet<QuestionTag>. Fix by adding one, see SerializersBuilder.addBuilderFactory.)
```

### Expected Result
I would expect this to work out of the box with the generated code.

### Workaround
I got it working by adding the builder factory manually to my `serializers.dart` file, which is what the error message seems to hint to.

```
@SerializersFor([
  ...
  QuestionTag,
])
final Serializers serializers = (_$serializers.toBuilder()
     ..addBuilderFactory(
         const FullType(BuiltSet, const [const FullType(QuestionTag)]),
         () => new SetBuilder<QuestionTag>())
    )
    .build();
```

**Comment by davidmorgan** [comment]
I'm afraid the workaround you found is the best option today; tracking issue is https://github.com/google/built_value.dart/issues/124

**Comment by davidmorgan** [comment]
Or, you could use a `BuiltSetMultimap<String, QuestionTag>`, that should work :)

**Comment by stefantds** [comment]
> I'm afraid the workaround you found is the best option today; tracking issue is #124

Fair enough, thanks for clarifying and for the link!

> Or, you could use a `BuiltSetMultimap<String, QuestionTag>`, that should work :)

Yeah, thanks! I also considered that option but `BuiltSetMultimap` doesn't seem supported by the `StandardJsonPlugin` unfortunately...
