### ISSUE TITLE
mark Built value field as ignored for equality/hash

### ISSUE THREAD

**Issue by dave-doty** [google/built_value.dart#1023]
Is there a way to put a field into a Built value, so that it is available and copied (just by reference) on `rebuild`, but mark it as ignored for equality and hash computation?

This would be similar to Python dataclass fields with `hash` and `compare` set to false: https://docs.python.org/3/library/dataclasses.html#dataclasses.field

**Comment by dave26199** [comment]
Yes, there's an annotation: https://pub.dev/documentation/built_value/latest/built_value/BuiltValueField-class.html

Sorry for short reply, posting from phone.

**Comment by dave-doty** [comment]
Great, thank you!

For reference, I found an example of how to use this in the examples:

https://github.com/google/built_value.dart/blob/20fc5c92ceb8b31eb6bf46d6071a4c6e88af9c84/built_value_test/test/values.dart#L39-L40
