### ISSUE TITLE
build_runner dependency update

### ISSUE THREAD

**Issue by 0ttik** [google/built_value.dart#1034]
```Because [app_name] depends on auto_route_generator 2.1.0 which depends on build_runner ^2.0.2, build_runner ^2.0.2 is required.```

Is there any plans to depend on build_runner >=2.0.2?

**Comment by davidmorgan** [comment]
Last version already allows any version up to `3`:

https://github.com/google/built_value.dart/blob/master/built_value_generator/pubspec.yaml

so I think it's something else blocking--please try `pub upgrade`.

**Comment by 0ttik** [comment]
Thank you for fast answer and sorry - I went completely blind mode, there is no issue with `build_runner` dependency in `built_value_generator`.
