### ISSUE TITLE
Non nullable fields can be null

### ISSUE THREAD

**Issue by svarlet** [google/built_value.dart#1038]
Hi,

I've got two classes declared with built_value like this:
```dart
abstract class Resource
    implements Built<Resource, ResourceBuilder>, ResourceParsingResult {
  ResourceMetadata get metadata;
  Resource._();
  factory Resource([void Function(ResourceBuilder rb) updates]) = _$Resource;
}

abstract class ResourceMetadata
    implements Built<ResourceMetadata, ResourceMetadataBuilder> {
  String get etag; // <---------------------------------------------this is not nullable
  bool get isCollection;
  int? get size;
  String? get contentType;
  Instant get ctime;
  Instant get mtime;
  ResourceMetadata._();
  factory ResourceMetadata(
          [void Function(ResourceMetadataBuilder rmb) updates]) =
      _$ResourceMetadata;
}
```

I found that I can write such code even if my `_parseEtag` method returns a `String?`:
```dart
return Resource((b) => b
      ..path = branchPath
      ..metadata.etag = _parseEtag(rawResource.etag) // <------------- the declaration of _parseEtag says it returns String?
      ..metadata.size = int.tryParse(rawResource.size ?? '')
      ..metadata.contentType = rawResource.contentType
      ..metadata.ctime = _parseCreationTime(rawResource.ctime)
      ..metadata.mtime = _parseModifiedTime(rawResource.mtime)
      ..metadata.isCollection = rawResource.isCollection);
```

This won't be reported by the analyser/compiler, but will crash at runtime with this exception:
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Tried to build class "Resource" but nested builder for field "metadata" threw: Tried to construct class "ResourceMetadata" with null field "etag". This is forbidden; to allow it, mark "etag" with @nullable.
```

This doesn't align well with the usual behaviour of sound null safety. In general, setting a String value with a String? value reports a problem and won't compile/run.

===

built_value: ^8.0.6
build_runner: ^1.12.2
built_value_generator: ^8.0.4

```
➜ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-2.0.pre.166, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by kuhnroyal** [comment]
Yes, because it is a builder. Every field is nullable until you call `build()`.

**Comment by svarlet** [comment]
Thanks for the clarification, then I suppose we'll never get a compile time error when we assign a non nullable field with a nullable value?

**Comment by davidmorgan** [comment]
Taken by itself, assigning a null value is a valid (but rare) operation--that's how you clear the field in the builder. The code will have to set a new value later.

I don't see a way to change that without switching to explicit 'clear' methods, which would change the API.

One possibility that might be interesting is to instead create a lint that fires for this case--it could notice that the builder is built immediately, and require you to use ! explicitly. It could also check if you forget to mention required fields.

I don't know if/when I'll have a chance to look at that, unfortunately.

**Comment by SteveAlexander** [comment]
“Taken by itself, assigning a null value is a valid (but rare) operation--that’s how you clear the field in the builder”

I understand the need for backwards compatibility. But, I'm having difficulty thinking of a consistent rule for the current behaviour.

If assigning a null value is how you clear a field in the builder, how does this work if the type of the field is actually nullable?

That is, does assigning null to a nullable field in the builder mean “set this to null” or “clear the field in the builder” ?

If it means “set this to null”, then I think it would make sense for non-nullable fields to disallow setting null in the builder.

If it means “clear the field” then it makes sense for non-nullable fields to use setting null to mean "clear the value". But then, how do you set a nullable field to null in a builder?

Did I misunderstand something about how this works?

**Comment by davidmorgan** [comment]
`null` and `clear` are the same in the builder; there is no distinction between a clear nullable field and a null nullable field.

(This is equivalent to saying nullable fields are optional, you don't have to set them explicitly to null).

**Comment by SteveAlexander** [comment]
Thanks for explaining, that makes sense.

I think I had in mind rebuilding — what does a null value mean in that case?

**Comment by davidmorgan** [comment]
If you rebuild inline, there is no use for setting to null for required fields--it will just fail. That's what we could potentially catch with a lint.

But rebuild uses the same builder as `toBuilder`; with that you might pass a builder around and modify it multiple times. In that context, setting a required field to null makes sense, you are saying it must be set later in the code before build is called.

**Comment by kuhnroyal** [comment]
Linking this just for a reference, basically the same thing was asked here: https://github.com/OpenAPITools/openapi-generator/issues/9197

**Comment by SteveAlexander** [comment]
Thanks for explaining — makes sense.

Another approach, for comparison:

I've been using Moor (a sqlite library) as well as built_value. Moor takes a different approach of using `Value(someValue)` and `Value.absent()` to allow distinguishing between `null` and absent values. While it's clear and allows that distinction, it's also less succinct than built_value.

**Comment by davidmorgan** [comment]
Closing for https://github.com/google/built_value.dart/issues/1050
