### ISSUE TITLE
Nullable fields serialization

### ISSUE THREAD

**Issue by radzish** [google/built_value.dart#1040]
Hello, I need an option for nullable fields to be serialized to JSON with null values, rather than not being included.
It was always working fine before we got null safety.
I looked at change history of 8.0.1 and it says:
```
Allow nulls when serializing/deserializing for better JSON interop.
```
Therefore I do not see how can I make it work. Could you please provide instructions on how to make it working.

**Comment by davidmorgan** [comment]
Closing for https://github.com/google/built_value.dart/issues/1049
