### ISSUE TITLE
Improve documentation for `_finalizeBuilder` and `_initializeBuilder`

### ISSUE THREAD

**Issue by cameron1024** [google/built_value.dart#1041]
In my team, the lack of a way to provide "default values" was recently given as a reason not to adopt `built_value`, despite `_initializeBuilder` existing. I myself didn't know about these functions for a while, until I stumbled across this issue #212 (which I somewhat frequently return to when I forget that both methods have a leading underscore). 

Given the usefulness of these functions, and how (anecdotally) obscure they currently are, is it worth putting them in a more prominent place, e.g. `examples` or even in the top-level `README.md`?

Happy to make a PR if you think this is worth doing 😁

**Comment by davidmorgan** [comment]
Makes sense--but I'd also like to tweak the feature a bit so you specify the hooks with an annotation. Closing in favour of https://github.com/google/built_value.dart/issues/1051
