### ISSUE TITLE
Nullable getters for builders in classes with instantiable: false

### ISSUE THREAD

**Issue by mattia-venturini** [google/built_value.dart#1043]
I have a model where an abstract class - i.e. with `@NestedBuilder(instantiable: false)` - is extended by other BuiltValue classes. When I `rebuild` the object, I find that the nested builders (along with other fields) are said to be _nullable_. This results in many null-check operations when I update my data.

Here is a minimal example:
```
// My base class
@BuiltValue(instantiable: false)
abstract class Vehicle {
  // some property
  VehicleColor get color;

  // common BuiltValue interface
  Vehicle rebuild(void Function(VehicleBuilder b) updates);
  VehicleBuilder toBuilder();
}

// A concrete class
abstract class Car implements Vehicle, Built<Car, CarBuilder> {
  Car._();

  factory Car([void Function(CarBuilder)? updates]) = _$Car;

  int get seatsCount;
}

// Some nested data
abstract class VehicleColor
    implements Built<VehicleColor, VehicleColorBuilder> {
  VehicleColor._();

  factory VehicleColor([void Function(VehicleColorBuilder)? updates]) =
      _$VehicleColor;

  String get label;
}
```

When I need to update an object declared as Vechicle, for example:
```
Vehicle repaintVehicle(Vehicle vehicle, String colorLabel) {
  final newColor = VehicleColor((builder) => builder..label = colorLabel);

  return vehicle.rebuild((b) => b.color.replace(newColor));
}
```
The getter color results to be nullable and can't be accessed without a null-check.

Looking at the generated model.g.dart I can see that in VechicleBuilder we have:
```
VehicleColorBuilder? get color;
```

But int the instantiable class CarBuilder we have:
```
VehicleColorBuilder get color => _$this._color ??= new VehicleColorBuilder();
```

So is it right to say that every implementation of VehicleBuilder will have a non-nullable getter for color? Why in parent class it's nullable?

**Comment by davidmorgan** [comment]
Will investigate as part of https://github.com/google/built_value.dart/issues/1052

**Comment by davidmorgan** [comment]
Looks like this was an oversight. Thanks for reporting! Sending a PR.
