### ISSUE TITLE
Test and fix support for serializing nulls

### ISSUE THREAD

**Issue by davidmorgan** [google/built_value.dart#1049]
There are various issues filed around nulls--collecting them here.

**Comment by larssn** [comment]
Combining https://github.com/google/built_value.dart/pull/1015 and https://github.com/google/built_value.dart/pull/1027 fixes #604, #1040 and #1013.

We've been using those two PR's for months in production, for what it's worth.

**Comment by davidmorgan** [comment]
Note to self: there is an issue w/ generated code for an `Object?` field.

**Comment by davidmorgan** [comment]
All the fixes have merged--will be in the next release.

**Comment by jscti** [comment]
@davidmorgan Digging in the closed issues, docs, and `BuiltValueField` properties but didn't found anything to enable null properties serialization to produce `field: null` instead of totally removing it.

Is it fixed ?

I'm on 8.1.4

Thanks

**Comment by kuhnroyal** [comment]
There is still https://github.com/google/built_value.dart/issues/912 open
