### ISSUE TITLE
Support chunked serialization / deserialization

### ISSUE THREAD

**Issue by ScottPierce** [google/built_value.dart#105]
Even though the generated serialization / deserialization logic may be very fast, on larger payloads it may hog the thread enough to cause missed frames on [flutter](https://flutter.io/). It'd be nice if there was an API to asynchronously decode a JSON response, and somehow intelligently split itself up over multiple smaller future callbacks, before returning the result.

**Comment by davidmorgan** [comment]
That makes sense. Have you seen it happen in practice?

I've been thinking of adding a flutter example to built_value. I think it's important to be able to benchmark before embarking on something like this, so, even more reason to do so.

**Comment by ScottPierce** [comment]
Yes. This is a bit of an uncommon situation, but a user in the flutter gitter channel was parsing an extremely large payload, trying several different parsing formats. He found that he was blocking the main thread for several seconds.

It'd be good to get some benchmarks of reasonable numbers.

It seems to me like it'd be good to be able to limit serialization / deserialization chunks to well under a millis before continuing to parse the payload in another future.

**Comment by davidmorgan** [comment]
Okay, now joined the flutter gitter channel :D ... I couldn't find the message you mentioned though.

Definitely makes sense. I guess I will do a "flutter day" sometime soon :)

**Comment by ScottPierce** [comment]
Joel had brought it up a few nights ago. He was trying to parse several
thousands of records of guitar tab data. We were struggling to find a good
solution.

**Comment by ScottPierce** [comment]
It was actually a somewhat difficult problem to solve. He couldn't spin up an isolate to do the work, because ultimately he has the serialize the data in the isolate and deserialize it again in his main isolate. He'd end up having to send the data over in pages, which starts to get pretty complicated.

Either way, I don't think it would be very difficult to proof out a more common example that a response would take several millis to deserialize where it would be advantageous to be able to chunk.

**Comment by davidmorgan** [comment]
One question -- is the JSON parse a problem? The built_value code transforms already-parsed JSON into objects. If the JSON parse has the same problem -- is blocking -- then we'll need an alternative for that, too.

**Comment by ScottPierce** [comment]
Yeah, I thought about that as well. You are correct.

**Comment by ScottPierce** [comment]
@davidmorgan What are the next steps for this? This would be a non-trivial change, but also an important one for flutter I believe.

**Comment by davidmorgan** [comment]
I think the next step is to figure out there answer for the underlying JSON parse. Let me ask around.

**Comment by ScottPierce** [comment]
Find anything?

**Comment by davidmorgan** [comment]
So it looks like the VM supports chunked JSON decoding. In js however the same code just decodes everything at the end.

https://dartpad.dartlang.org/e84a69922729cc813bf2cb1915d9017a 

 --> on VM: prints "adding pieces", there's a pause (it's actually decoding), then prints "closing" and "done"
 --> compiled to JS: browser blocks, all three are printed together

Could you give this code a try on flutter to confirm that it provides chunked decoding? If so we should be able to do something. Thanks!

**Comment by ScottPierce** [comment]
```
I/flutter ( 1775): Adding pieces.
I/flutter ( 1775): Closing.
I/flutter ( 1775): Done.
```

What should I be looking for?

**Comment by davidmorgan** [comment]
The timing of what's printed -- if it's all printed at the same time, then it's not doing chunked decoding. If you see "adding pieces", then a pause, then "closing" -- then it's working.

(I should have made it print timestamps...)

**Comment by ScottPierce** [comment]
I added timestamps with the difference of the start time.

```
I/flutter ( 5387): Adding pieces. 1
I/flutter ( 5387): Closing. 10521
I/flutter ( 5387): Done. 10522
```

**Comment by davidmorgan** [comment]
That looks good -- it's doing chunked decoding. Thanks.

So for the VM and Flutter all that's needed is for built_value to also support chunked decoding. And, until I have a flutter example, I can use a VM test.

I'll see if I can take a look this week.

**Comment by davidmorgan** [comment]
I had a look at this -- unfortunately it doesn't seem at all straightforward.

Serialization can be made chunked -- because the result of serialization is Iterable, which can be lazy.

But deserialization doesn't have that possibility -- unless we added "lazy" value types and collections. It's an interesting idea, which I'll give more thought to, but it might not work out.

The other option would be to write a parallel implementation of built_value that uses Futures/async. I can't see a good way to share code between the two, though, so it's not a very attractive option.

**Comment by ScottPierce** [comment]
@davidmorgan Any more thoughts to this? I view this as a pretty critical piece to ensuring flutter has as few dropped frames as possible.

**Comment by davidmorgan** [comment]
Thanks Scott. Definitely planning on working on this. The lazy approach seems good from lots of angles -- it benefits the web as well as Flutter.

I'll try to take a look in the next month.

**Comment by eseidelGoogle** [comment]
FYI @zanderso who was asking me yesterday what (if anything) the VM should do to support improved JSON handling on mobile (there are options on the table, including passing objects between isolates w/o a copy, but we don't currently have recommended json handling implementation on mobile to profile and see if VM work is even needed).

**Comment by ScottPierce** [comment]
@davidmorgan Any movement on this, or anything I could do to help?

**Comment by davidmorgan** [comment]
Sorry, no progress. Definitely something I plan on tackling at some point -- but I have to find quite a chunk of time. Maybe in December, there's usually a slow week or two.

I do have some more ideas, though. One thing that would be neat would be to supplement JSON to make it possible to parse the structure without parsing the whole thing. i.e. add an index to the beginning. This would potentially allow lazy parsing on the web as well as on flutter.

**Comment by davidmorgan** [comment]
I think I have something that should work and be much simpler than the other ideas discussed. Please see `BuiltListAsyncDeserializer` added in the linked PR, and see if it works for you.

If you need another type as the top level serialized type it should be possible to add equivalent async deserializers for these, without having to change the rest of the system. Please let me know.

**Comment by zanderso** [comment]
For JSON data, does `BuiltListAsyncDeserializer` drill down to [JsonDecoder.startChunkedConversion](https://api.dartlang.org/stable/1.24.3/dart-convert/JsonDecoder/startChunkedConversion.html) somewhere? If so, could you help me find where? If not, could you explain how the chunking happens? Does the client have to pre-chunk the JSON? Thanks!

**Comment by dave26199** [comment]
JSON decoding is handled by you; in the examples we always call JSON.decode
but you can handle it however you like. You'll need to pass an Iterable to
BuiltListAsyncDeserializer which you have already JSON-decoded.

Hope that helps :) can give more detail if not. (Apologies for brevity,
sent from my phone...)

Zachary Anderson <notifications@github.com> schrieb am Mi., 27. Dez. 2017,
19:05:
