### ISSUE TITLE
Support Built mixins

### ISSUE THREAD

**Issue by parren-google** [google/built_value.dart#1071]
I'd like to be able to do this:

```
@BuiltValue(nestedBuilders: false, instantiable: false)
abstract class Parent {
  BuiltList<Object> get noNestedBuilder;
}

@BuiltValue(nestedBuilders: false)
abstract class Child with Parent implements Built<Child, ChildBuilder> {
  ...
}
```

It requires:
* respect `nestedBuilders` in generated abstract builder classes
* pick up mixins similarly to implemented interfaces and make generated builders mix in the parent builders again

There is a workaround for the second issue above by saying `abstract class Child with Parent implements Built<Child, ChildBuilder>, Parent`. It will do `ChildBuilder implements ParentBuilder` rather than `ChildBuilder with ParentBuilder`, but that's OK if there are only generated builders at play.

Google specific: The necessary fixes are outlined in cl/379939823.

**Comment by parren-google** [comment]
Thanks David, I think the fix for respecting `nestedBuilders` in generated abstract builder classes got lost. It's in cl/379939823 in `value_source_class.dart` starting on line 1159.

**Comment by davidmorgan** [comment]
Thanks! As discussed, I happened to land that exact change independently already this week :)
