### ISSUE TITLE
Allow factory constructor to be named

### ISSUE THREAD

**Issue by xavierhainaux** [google/built_value.dart#108]
The buit_value generator requires the class to have a factory constructors declared like this:

```dart
factory MyValue([updates(MyValueBuilder b)]) = _$MyValue;
```

I would like to allow the factory to be a named constructor.
It would allow us to use the default name to write a more user friendly constructor:

```dart
  // Required for BuiltValue
  factory MyValue._fromBuilder([updates(MyValueBuilder b)]) = _$MyValue;
  MyValue._();

  // Custom user-friendly constructor
  factory MyValue(num value1, {@required num value2}) {
    return new MyValue._fromBuilder((b) => b
      ..value1 = value1
      ..value2 = value2);
  }
```

**Comment by davidmorgan** [comment]
Thanks for the suggestion.

I think this would be a clear improvement for classes with a small number of fields. Right now, I usually create a factory constructor called "of" for single-field classes.

```new MyValue.of('foo')```

It would be nicer to be able to write:

```new MyValue(foo)```

I'll take a look. There are quite a few open issues right now, though, so it might take a little while to get to this one.
