### ISSUE TITLE
Generated code produces lint warning: cast_nullable_to_non_nullable

### ISSUE THREAD

**Issue by filiph** [google/built_value.dart#1101]
This is low priority, because I think most people exclude generated files from analysis. I wouldn't even see this if my exclude wasn't incorrectly setup just now.

The lint warning [is listed](https://dart-lang.github.io/linter/lints/cast_nullable_to_non_nullable.html) as experimental (as of December 16, 2021) but seems to be included by default in `package:lint`. It does seem like a good practice:

| Don't cast a nullable value to a non nullable type 

<img width="395" alt="Screen Shot 2021-12-16 at 10 20 33" src="https://user-images.githubusercontent.com/919717/146343616-e7a91d18-d418-414f-a961-108cf73d9169.png">

Right now, built_value generates deserialization code like this:

```dart
  @override
  Something deserialize(
      Serializers serializers, Iterable<Object?> serialized,
      {FullType specifiedType = FullType.unspecified}) {
    final result = new SomethingBuilder();

    final iterator = serialized.iterator;
    while (iterator.moveNext()) {
      final key = iterator.current as String;   // LINT HERE
      iterator.moveNext();
      final Object? value = iterator.current;
      switch (key) {
        case 'blah':
          result.blah = serializers.deserialize(value,
              specifiedType: const FullType(bool)) as bool;   // LINT HERE
          break;
      }
    }

    return result.build();
  }
```

The fix would be to add a null assert, for example:

```dart
final key = iterator.current! as String;
```

**Comment by davidmorgan** [comment]
Thanks! Makes sense, will take a look ... at some point ;)
