### ISSUE TITLE
Multi generic types

### ISSUE THREAD

**Issue by fishead** [google/built_value.dart#1108]
~~Is it possible to use multi generic types? not sure how to do it.~~

checkout my code [here](https://github.com/fishead/dart_playground). 
`Payload` has an optional `meta` field, `response1` does not have `meta` field and `response2` does have one. 

After run 
```shell
dart ./bin/go.dart
```

The output is
```
Deserializing '[data, {field1: response 1 field 1}]' to 'Payload<Response1Data, void>' failed due to: Bad state: No builder factory for Payload<Response1Data, void>. Fix by adding one, see SerializersBuilder.addBuilderFactory.
response2.meta.reason: cause i can
response2.data.field1: response 2 field 1
```

So `response2` got decoded properly, but `response1` with optional `meta` field did not work. How to solve this problem?

edit: replace inline code with [repo](https://github.com/fishead/dart_playground).

**Comment by davidmorgan** [comment]
Multiple generics should work fine; not sure about the `fromJson` method. What happens when you try it?

**Comment by fishead** [comment]
@davidmorgan I'm on my way home, I'll make a repo to explain it ASAP.

**Comment by fishead** [comment]
@davidmorgan updated my question. Sorry for the delay.

**Comment by dave26199** [comment]
Per the error message, you need to install a builder factory for every combination of generics that might be deserialized.

**Comment by fishead** [comment]
But `response1` does not have a `meta` field. so I provide a `void`. Is it the right way to do it?

### **serializers.dart**
```dart
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';
import 'payload.dart';
import 'response_1_data.dart';
import 'response_2_data.dart';
import 'response_2_meta.dart';

part 'serializers.g.dart';

@SerializersFor([
  Payload,
  Response1Data,
  Response2Data,
  Response2Meta,
])
final Serializers serializers = (_$serializers.toBuilder()
      // is it right to use `void`?
      ..addBuilderFactory(
        const FullType(
          Payload,
          [FullType(Response1Data)],
        ),
        () => PayloadBuilder<Response1Data, void>(),
      )
      ..addBuilderFactory(
        const FullType(
          Payload,
          [FullType(Response2Data), FullType(Response2Meta)],
        ),
        () => PayloadBuilder<Response2Data, Response2Meta>(),
      )
      ..addPlugin(StandardJsonPlugin()))
    .build();
```

**Comment by dave26199** [comment]
If it works, sure :)

**Comment by fishead** [comment]
I mean it's not work with `void`, sorry for my poor English if you misunderstand it.

**Comment by dave26199** [comment]
Ah, I think I see the problem. Please try changing

```
[FullType(Response1Data)],
```

to

```
[FullType(Response1Data), FullType(void)],
```

--does that work?

**Comment by fishead** [comment]
No luck, it's syntax error.

After run
```
dart run build_runner build
```

I got
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 539ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 111ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 679ms

[INFO] Running build...
[INFO] Running build completed, took 27ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 40ms

[SEVERE] built_value_generator:built_value on lib/serializers.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:dart_playground/serializers.dart (or an existing part) contains the following errors.
serializers.dart:22:46: Expected an identifier.
serializers.dart:22:46: Expected to find ')'.

Try fixing the errors and re-running the build.

[SEVERE] Failed after 88ms
```

**Comment by dave26199** [comment]
Ah, I see, void doesn't work here ... perhaps `Null` or `Never` will work instead?

**Comment by fishead** [comment]
background: 
- `Null safety` enabled.
- linter enabled with rule `package:lints/recommended.yaml`.

After tried different combinations with `Null`, `Never`, `void` and `dynamic`, found `Never` is the answer with some adjustments to my code.

Final code updated [here](https://github.com/fishead/dart_playground).

@dave26199 thanks for your time and patient.

**Comment by dave26199** [comment]
Great,  glad I could help :)
