### ISSUE TITLE
Serialisation of Dart DateTime

### ISSUE THREAD

**Issue by rayk** [google/built_value.dart#111]
I am sure this issue has been covered some where was just not able to find it in the closed issues.

In an attempt to keep things simple I tend to use ```new DateTime.now()``` relative frequently directly in the builders, it works find because I am often used DateTime to calculate difference in relatively short time period.

To handle serialisation of this I could go the whole ```specifiedType = const FullType```  route and build a custom serialised for DateTime. But just feeling a bit over an over kill. Alternative of defining DateTime as an int and doing inline convert when I want to use ```DateTime``` or ```Duration``` is also messy. (Serialisation of DateTime is always a pain, I am happy with int or string in ISO format going over the wired).

Any ideas? I think if I my model centralised (one namespace/library) the custom serializer would be  ok, after all it is just one type. But that is not my use case. I have different model parts located in different isolates and I have DateTime all over the place.

Your guidance is appreciated... (not a blocking issues, just getting BuiltValue and Collection and finding it so good, I am probably over driven to find the ideal solution.)

**Comment by davidmorgan** [comment]
Makes sense.

Looking at DateTime, it's immutable, it has reasonable hashCode, operator== and toString, so it makes sense to use it in a built_value, and perhaps to have it be supported for serialization by default.

The only issue I see is utc vs local. It doesn't make sense to serialize times in local timezone. One approach would be to simply throw if an attempt is made to serialize a non-utc date. What do you think?

**Comment by rayk** [comment]
To be honest I never really got why the API lets me create a DateTime object that is not pinned to UTC. For me it make more sense that ```new DateTime.now()``` would be in UTC and if I wanted the local I would call ```myDateTimeObject.toLocal```. Reason being the local is a relative concept and the last thing I want to do is call ```myDateTimeObject.isBefore(yourDateObject)``` if your object was great in a different locale then my one.

So yes, I would agree that the ```myDateTime = new DateTime.now().toUtc()``` should auto serialize and ```myDateTime = new DateTime.new()``` should throw. I know on the surface it looks weird, but that is because the default ```new DateTime.now()``` anchors itself to local time zone. 

I hope makes sense.... if so that would be great, built would be able handle serialisation of the all the basic type... which is very cool....  

R.
