### ISSUE TITLE
Properties of Generated Builder are all optional

### ISSUE THREAD

**Issue by hffmnn** [google/built_value.dart#1113]
I am trying to convert a project to null-safety. Starting with the models, I replaced `@nullable` annotations with `?`. When running `flutter packages pub run build_runner build --delete-conflicting-outputs` it generates the expected value class but the builder has all properties set to optional.

To verify, I copied the `SimpleValue` from the example code in this repository:

```
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'values.g.dart';

abstract class SimpleValue implements Built<SimpleValue, SimpleValueBuilder> {
  static Serializer<SimpleValue> get serializer => _$simpleValueSerializer;

  int get anInt;

  String? get aString;

  factory SimpleValue([void Function(SimpleValueBuilder) updates]) =
      _$SimpleValue;
  SimpleValue._();
}
```

The generated class looks like this:

```
class _$SimpleValue extends SimpleValue {
  @override
  final int anInt;
  @override
  final String? aString;

  factory _$SimpleValue([void Function(SimpleValueBuilder)? updates]) =>
      (new SimpleValueBuilder()..update(updates)).build();

  _$SimpleValue._({required this.anInt, this.aString}) : super._() {
    BuiltValueNullFieldError.checkNotNull(anInt, 'SimpleValue', 'anInt');
  }

...overrides...
```

but the Builder looks like this:

```
class SimpleValueBuilder implements Builder<SimpleValue, SimpleValueBuilder> {
  _$SimpleValue? _$v;

  int? _anInt;
  int? get anInt => _$this._anInt;
  set anInt(int? anInt) => _$this._anInt = anInt;

  String? _aString;
  String? get aString => _$this._aString;
  set aString(String? aString) => _$this._aString = aString;
...
```

The generated code in this repo looks like this:

```
class SimpleValueBuilder implements Builder<SimpleValue, SimpleValueBuilder> {
  _$SimpleValue _$v;

  int _anInt;
  int get anInt => _$this._anInt;
  set anInt(int anInt) => _$this._anInt = anInt;

  String _aString;
  String get aString => _$this._aString;
  set aString(String aString) => _$this._aString = aString;
...
```

Any ideas why this might be? Is there a command-line option I am missing? Might there

## Setup

Latest versions in `pubspec.yaml`:
```
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  built_value: 8.1.4
  built_collection: 5.1.1
...
dev_dependencies:
  build_runner: 2.1.7
  built_value_generator: 8.1.4
```

```
❯ flutter doctor                                                               
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.5)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

---

I also tried the same with a new flutter project with the same result.

Any ideas?

**Comment by kuhnroyal** [comment]
The value in the builder need to be nullable, because you add them one by one in a builder pattern. Otherwise it is just like a constructor call with all required values.

**Comment by hffmnn** [comment]
They are not nullable in the generated code in this repo. Please have a look here: https://github.com/google/built_value.dart/blob/ee569def1fc0d0a630038cce18f562e31f6dc7c1/example/lib/values.g.dart#L354-L356

**Comment by kuhnroyal** [comment]
Well, what you linked there is pre NNBD, see `@nullable` in `values.dart`.

**Comment by dave26199** [comment]
Peter is correct, with the move to null safety the builder fields are always nullable.

This was necessary to keep backwards compatibility. It's allowed to set a required builder field to null provided you set it again to a non-null value before building. So the type has to be nullable.

This is a slightly awkward corner of the API that I'd like to revisit at some point, but as with any breaking change to a widely used package it's hard to predict if it will actually happen.

Thanks.

**Comment by hffmnn** [comment]
Ah, ok. Got it. So I would get runtime errors when trying to set `null` on a not nullable property, just like before the compiler understood nullability.

**Comment by dave26199** [comment]
Yes,  exactly.
