### ISSUE TITLE
[Feature Requested] Null Safety !

### ISSUE THREAD

**Issue by ayezarniaung** [google/built_value.dart#1114]

**Comment by davidmorgan** [comment]
Ehm. We do support Null Safety ... could you be more specific, please? :)

**Comment by ayezarniaung** [comment]
When I generated a file with Null Safety like '?' , generated .g.file can't  decide ? null .So I used to add everytime ? sign in g.file . How to resolve this issue.


func(Function? pressed)



*****.g.file*****

func(Function pressed) <= Generated


so , I added manually '?' sign on it.

**Comment by dave26199** [comment]
I don't understand,  sorry. Could you please give a more detailed example?

**Comment by bradyt** [comment]
@ayezarniaung Although built_value might not generate the `?` character, I think you will see a difference in the generated file if the original file does or does not contain a `?` there.

For example, in `./example/lib/values.g.dart`, the non-nullable `anInt` has `BuiltValueNullFieldError.checkNotNull` applied, whereas the nullable `aString` does not.

Presumably, editing the generated files by hand is not recommended.
