### ISSUE TITLE
How to include a NULL value in json when serializing

### ISSUE THREAD

**Issue by marcos930807** [google/built_value.dart#1117]
I have a use case in which I need the values of my serialized built_value model if they are null to be implicitly present with the json to send it to the server via rest. The current behavior is that they are ignored.
In summary my requirement is that all the properties of my models are present when serializing it even if they are null.
Is there is need more info let me know.

I think that json_serializable has a prop for that configurable via build.yaml (include_if_null: true)

**Comment by kuhnroyal** [comment]
See https://github.com/google/built_value.dart/issues/912
I believe this is possible globally but not per entity/field.

**Comment by marcos930807** [comment]
@kuhnroyal In fact it is possible to do it by entity.
annotating only the serializer in it. Thanks again closing the issue.
