### ISSUE TITLE
Upgrade to pkg:build 0.3.0 to resolve watcher race condition

### ISSUE THREAD

**Issue by filiph** [google/built_value.dart#114]
Issue https://github.com/dart-lang/build/issues/175 was resolved in 0.3.0 (via https://github.com/dart-lang/build/pull/185). Please upgrade to that version.

**Comment by jakemac53** [comment]
See https://github.com/google/built_value.dart/pull/113

**Comment by davidmorgan** [comment]
Resolved. Thanks!

**Comment by filiph** [comment]
When trying to upgrade, I get this:

```
Incompatible version constraints on built_value:
- built_value_generator 0.0.1 depends on version ^0.0.1
- <my project> depends on version ^0.5.3
```

Can you update built_value_generator as well?

**Comment by filiph** [comment]
Oh! I just removed `built_value_generator` from my dependencies and it resolved the issue. I guess I should be reading release notes...

**Comment by filiph** [comment]
And again, I spoke too soon. I need `BuiltValueGenerator` to actually generate the code, don't I. I thought that might have been moved into this package, but it's not here AFAIK.

**Comment by filiph** [comment]
So, the dep hell was unrelated to built_value (it was quiver/string_scanner via several transitive dependencies of the project). I'm really glad we're working on improving those pub error messages...

Nothing to see here. Carry on, please.

**Comment by davidmorgan** [comment]
:)

FWIW -- the travis run includes doing a "pub get" for the examples / end to end tests / chat app. So the pubspecs there certainly work.
