### ISSUE TITLE
[Bug] Generating a class that contains special character `$` will generate faulty code

### ISSUE THREAD

**Issue by ahmednfwela** [google/built_value.dart#1143]
generating this class: `pizza.dart`
```dart
@BuiltValue(instantiable: true)
abstract class $Pizza implements Built<$Pizza, $PizzaBuilder> {
  $Pizza._();

  @BuiltValueField(wireName: r'pizzaSize')
  num get pizzaSize;

  factory $Pizza([void Function($PizzaBuilder)? updates]) = _$$Pizza;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults($PizzaBuilder b) => b;
}
```

will cause faulty code to be generated at `pizza.g.dart`
1) in class `_$$Pizza` constructor, for every non-nullable type
`BuiltValueNullFieldError.checkNotNull(pizzaSize, '$Pizza', 'pizzaSize');`
should be 
`BuiltValueNullFieldError.checkNotNull(pizzaSize, r'$Pizza', 'pizzaSize');`
2) in class `_$$Pizza` `toString`
`newBuiltValueToStringHelper('$Pizza')` should be
`newBuiltValueToStringHelper(r'$Pizza')`
3) in class `$PizzaBuilder` `build`, for every non-nullable type
`pizzaSize: BuiltValueNullFieldError.chckNotNull(pizzaSize, '$Pizza', 'pizzaSize')`
should be
`pizzaSize: BuiltValueNullFieldError.chckNotNull(pizzaSize, r'$Pizza', 'pizzaSize')`

**Comment by ahmednfwela** [comment]
there is also a bug when generating a serializer
the serializer name for the above class is `_$$PizzaSerializer`, which leads to:
```dart
Serializer<$Pizza> _$$PizzaSerializer = new _$$PizzaSerializer();
```
this will require fixing `_toCamelCase` in `serializer_source_class.dart`

**Comment by davidmorgan** [comment]
Thanks. Use of `$` in names is limited by convention to generated code, so I didn't worry too much about allowing for it.

Out of interest, is there some particular use case you have in mind? e.g. are you running `built_value` on generated code?

**Comment by ahmednfwela** [comment]
this popped up while I was working on https://github.com/OpenAPITools/openapi-generator/pull/12295

since I needed to generate a public class e.g. `$Addressable` that's closely related to another class `Addressable`

instead of naming it `AddressablePublic` which might cause conflicts and confusion

**Comment by davidmorgan** [comment]
That makes sense; will take a look at the PR. Thanks.
