### ISSUE TITLE
Support `implicit-dynamic: false` in generated code

### ISSUE THREAD

**Issue by DanTup** [google/built_value.dart#118]
If I disable `implicit-dynamic` I get errors in the generated code. It'd be nice to not have to allow implicit any for just the generated code (I did try adding the generated files to `exclude` in `analysis_options.yaml` but [that didn't seem to work](https://github.com/dart-lang/sdk/issues/28754)).

![Errors in generated code](https://cloud.githubusercontent.com/assets/1078012/22863799/83b50680-f13e-11e6-8e30-d54b1e7dd99c.png)

**Comment by davidmorgan** [comment]
Thanks for reporting. Agreed this is bad -- I think the correct way is to fix for everyone rather than to add an option for it. I'll take a look.

I'm on vacation right now, though, so it will be in a week or so.
