### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by blexo** [google/built_value.dart#1216]
Hello all - this looks like a great library and it looks like it was updated within the last year...  but I notice that the build is failing and none of the examples have been updated to deal with null safety.  Is this dying?

**Comment by dave26199** [comment]
It's very much alive :)

I work full time on the Dart team, so I have plenty of time to work on this kind of thing; but it's a side effort, not my main work. So I usually only work on it if something urgent comes up, and do occasional batches of fixes/improvements.

The build failure is do to a new analyzer hint, nothing too serious. I'll fix it :)

Thanks for pointing out that I missed updating the examples, I'll do that too :)

**Comment by davidmorgan** [comment]
Build is now green and examples updated :) thanks!
