### ISSUE TITLE
Support absent in builders

### ISSUE THREAD

**Issue by davidmorgan** [google/built_value.dart#126]
For use when building a field that is nullable.

new FooBuilder.absent() --> starts absent
fooBuilder.replace(null) --> builder becomes absent
fooBuilder.field = foo --> builder stops being absent
fooBuilder.clear()/reset()/replace() --> reinitializes as if new, no longer absent
fooBuilder.build() --> throws if absent
fooBuilder.buildOrAbsent() --> returns null if absent

**Comment by wangyizhuo** [comment]
+1

**Comment by wangyizhuo** [comment]
Today, if I have two built value classes, Parent and Child, and child is a nullable field in Parent. How can I make it null?

Looks like a instance of Child is always instantiated, even if I did builder..child = null.

Since in ParentBuilder, child field is a builder, I cannot make it null. Should not in ParentBuilder, child is just a Child instance instead of ChildBuilder? This would solve my problem too.

**Comment by davidmorgan** [comment]
`builder..child = null` should work. What might be causing confusion is that _reading_ from `child` will cause it to be instantiated. So for example if you wrote:

```
builder
  ..child = null
  ..child.childField = 3
```

then child will be set to null but then reset to a builder to allow you to access `childField`. Because of that, if you're doing any kind of check on the field, you'll hit an odd behaviour:

```
build.child = null;
if (builder.child == null) {
  // Never returns true! Reading it causes it to be instantiated.
}
```

This is all designed to make instantiating/updating values as nice as possible. If this isn't what you want, you could, as you say, make ParentBuilder hold a Child instead of a ChildBuilder. The way to do this is to write the interface to the ParentBuilder class yourself; then you can decide for each field whether it should be a nested builder or a simple field.

`ValueWithDefaults` here is an example of writing the builder interface explicitly:

https://github.com/google/built_value.dart/blob/master/example/lib/values.dart#L134

...because it also lets you set defaults for builder fields.

**Comment by wangyizhuo** [comment]
When I need to set a null, I found using the constructor directly is easier.

For example:
Parent.noChild() => new _$Parent(child:null);

I am not sure if it's the intended usage.

**Comment by davidmorgan** [comment]
@wangyizhuo Yes, using the constructor directly is fine; as you've found it's useful for creating convenience constructors.

**Comment by bolein** [comment]
Any updates on this?

**Comment by davidmorgan** [comment]
I think we'll likely want to wait for NNBD to land, as nullability of nested builders might help us clear things up. i.e. we can mark them non-nullable to make it clear you can't set them null; then give you another way to clear them...

**Comment by bolein** [comment]
What is NNBD?

**Comment by davidmorgan** [comment]
None Null By Default :)

e.g. `int` will no longer mean 'int or null', but exactly `int`. If you want 'int or null' you'll write it `int?`.

https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/roadmap.md

**Comment by bolein** [comment]
Anyways, what is the current workaround to rebuild an object with a null nested BuiltValue?

**Comment by davidmorgan** [comment]
Hmm, I misread; `parent.rebuild((b) => b..child = null)` should work provided `child` is a `@nullable` field. If you have a case where that's not working, could you post more detail, please?
