### ISSUE TITLE
Getting enum by wire name

### ISSUE THREAD

**Issue by vixez** [google/built_value.dart#1261]
Hello,

When I'm trying to convert to an enum from a String, it doesn't seem to accept the wire name.

For example I have
```
  @BuiltValueEnumConst(wireName: 'driving-license')
  static const DocumentType drivingLicense = _$drivingLicense;
```

To get this to work I need to pass the variable name as a parameter
```
DocumentType documentType = DocumentType.valueOf('drivingLicense');
```

But for a special edge case, I get the data from the server as a map, not directly deserialized to a model.
So in this case I would do
```
DocumentType documentType = DocumentType.valueOf(document['type'])
```

Which equals to

```
DocumentType documentType = DocumentType.valueOf('driving-license')
```

This does not work, it will not find this `DocumentType` as `drivingLicense`.

Is there a way I can get `DocumentType` from the wire name?

Thanks in advance

**EDIT:**

As a dirty fix I added
```
  String toEnumName(String value) {
    var result = value[0].toLowerCase();
    for (int i = 1; i < value.length; i++) {
      result = value[i - 1] == "-"
          ? result + value[i].toUpperCase()
          : result + value[i];
    }
    return result.replaceAll('-', '');
  }

DocumentType documentType =
        DocumentType.valueOf(toEnumName(document['type']));
```

**Comment by davidmorgan** [comment]
You'll need to use the serializer, that's the only place the `wireName` ends up.

So something like: `DocumentType.serializer.deserialize(serializers, value)`.

**Comment by vixez** [comment]
Hey @davidmorgan,

Okay that worked, thanks!

```
DocumentType documentType =
        (DocumentType.serializer as PrimitiveSerializer).deserialize(
      serializers,
      document['type'],
    )
```
