### ISSUE TITLE
Int32 serializers

### ISSUE THREAD

**Issue by Leptopoda** [google/built_value.dart#1270]
Hi `@davidmorgan`,
We need  support to serialize `Int32` values from the [fixnum](https://pub.dev/packages/fixnum) package.
As built_value already ships a serializer for `Int64` I'd like to know if you are interested in having this upstream.
I'd love to contribute it back.

**Comment by davidmorgan** [comment]
Hi Nikolas,

The `int64` serializer represents the type on the wire as a string, but for `Int32` I guess it would make sense to use just a number?

Sure, I'd be happy to accept a PR for that.

Thanks!
