### ISSUE TITLE
Allow record serialization (or bypass the error when generating)

### ISSUE THREAD

**Issue by Leptopoda** [google/built_value.dart#1278]
Hi dave,
we currently try to migrate some code to records and would love built_value_generator not to quit when encountering them.
I understand that finding a fitting wire format is hard but as we have custom needs for the records we will write custom serializes anyways.
Sadly the generator still refuses to run resulting in us generating code that is (other than some formatting) identical to what the built_value_generator would've produced.

I propose adding another property to the `BuiltValueField` annotation to handle this case. 
Are you interested in such an addition? Is there anything obvious I'm missing.

As always thanks for your work on this package. I really love it :heart:

**Comment by dave26199** [comment]
Makes sense, can you please give a little more detail about exactly which case should succeed that currently fails?

**Comment by Leptopoda** [comment]
```dart
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';

part 'test.g.dart';

typedef MyRecord = ({int? $int, double? $double, String? string});

abstract class TestClass implements Built<TestClass, TestClassBuilder> {
  TestClass._();
  factory TestClass([void Function(TestClassBuilder) updates]) = _$TestClass;

  MyRecord get myRecord;

  static Serializer<TestClass> get serializer => _$testClassSerializer;
}

@SerializersFor([
  TestClass,
])
final Serializers serializers = (_$serializers.toBuilder()
      ..addPlugin(StandardJsonPlugin())
      ..add(_$MyRecordSerializer))
    .build();
```

Which currently fails with:
```sh
[SEVERE] built_value_generator:built_value on lib/src/test.dart:
Error in BuiltValueGenerator for /test_dart/lib/src/test.dart.
Please make the following changes to use built_value serialization:

1. Record fields are not (yet) serializable. Remove "myRecord" or mark it "@BuiltValueField(serialize: false)".
```
But applying the suggested annotation completely excludes the field from serialization.

For context: 
We are using records to allow a field to have multiple types at once (but still have typesafety). Yes `JsonObject` is cool but we value the ability to have a limited set of valid values.
The custom `_$MyRecordSerializer` could look something like the following code but this shouldn't matter that much.
```dart
class _$MyRecordSerializer implements PrimitiveSerializer<MyRecord> {
  @override
  final Iterable<Type> types = const [MyRecord];

  @override
  final String wireName = 'MyRecord';

  @override
  Object serialize(
    final Serializers serializers,
    final MyRecord object, {
    final FullType specifiedType = FullType.unspecified,
  }) {
    dynamic value = object.$int;
    if (value != null) {
      return serializers.serialize(value, specifiedType: const FullType(int))!;
    }

    value = object.$double;
    if (value != null) {
      return serializers.serialize(value,
          specifiedType: const FullType(double))!;
    }

    value = object.string;
    if (value != null) {
      return serializers.serialize(value,
          specifiedType: const FullType(String))!;
    }

    throw Error();
  }

  @override
  MyRecord deserialize(
    final Serializers serializers,
    final Object data, {
    final FullType specifiedType = FullType.unspecified,
  }) {
    int? $int;
    double? $double;
    String? string;

    try {
      final value = serializers.deserialize(data,
          specifiedType: const FullType(int))! as int;
      $int = value;
    } catch (_) {}
    try {
      final value = serializers.deserialize(data,
          specifiedType: const FullType(double))! as double;
      $double = value;
    } catch (_) {}
    try {
      final value = serializers.deserialize(data,
          specifiedType: const FullType(String))! as String;
      string = value;
    } catch (_) {}

    return ($int: $int, $double: $double, string: string);
  }
}
```

**Comment by dave26199** [comment]
Does marking the serializer declarstion with

https://pub.dev/documentation/built_value/latest/built_value/BuiltValueSerializer-class.html

work? You can set `custom: true` to say you will write the serializer yourself.

**Comment by Leptopoda** [comment]
Sure we can definitely write a custom serializer for `TestClass` but it is 100% identical to what the built_value_generator would've produced (this is what we decided to do for now).
As we develop a generator ourselves this is not that big of a problem but it's adding a huge surface where we can introduce bugs.

It might not have been clear but `TestClass` can also hold other normal fields that just need the normal serialization.

**Comment by davidmorgan** [comment]
Sorry, I'm still not quite understanding how it should be ... you want the `TestClass` serializer generated, you don't want to skip serializing it ... so how does serializing it work?

Is it that you write your own serializer for `MyRecord` and install that manually?

If that works, cool, I was not expecting that :)

**Comment by davidmorgan** [comment]
Yes, I think it makes sense to support.

I think removing the check entirely makes sense: people will discover at runtime that the type is not serializable unless they add a custom serializer, but that's the same with other unknown types. Maybe there can be an extra hint at runtime that records always need a custom serializer.

I'll try to take a look tomorrow. Thanks!

**Comment by Leptopoda** [comment]
Thank you very much

**Comment by davidmorgan** [comment]
Release `8.8.0` should do what you want, please let me know if it does not :) thanks!

**Comment by Leptopoda** [comment]
From a quick look it does the job.
I'll further test it in the coming days.
