### ISSUE TITLE
Support typedefs in factory constructor

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#129]
```dart
part 'account.g.dart';

typedef dynamic BuilderUpdates(AccountBuilder b);

abstract class Account implements Built<Account, AccountBuilder> {
  Account._();

  factory Account([BuilderUpdates b]) = _$Account;
}
```
still causes
```
// Error: Please make the following changes to use BuiltValue:
//
//        1. Make class have factory: factory Account([updates(AccountBuilder b)]) = _$Account;
```
Currently I haven't found a way to create a way to create a function type parameter using https://pub.dartlang.org/packages/code_builder

It might be a good idea to provide the typedef in built_value

**Comment by zoechi** [comment]
also 
```dart
factory Account([dynamic updates(AccountBuilder b)]) = _$Account;
```
should be allowed, to silence the linter about missing return types

**Comment by davidmorgan** [comment]
The way to silence the linter is

factory Account([void updates(AccountBuilder b))]) = _$Account

-- is there any advantage to "dynamic"? This is easy to add, if so.

I'm not sure I follow the argument for the typedef -- if it's just that code_builder doesn't support it, shouldn't that be a feature request there? Or, is there another advantage to the typedef?

Thanks!

**Comment by zoechi** [comment]
> -- is there any advantage to "dynamic"? This is easy to add, if so.

I didn't have a closer look what the best return type would be. If `void` works, then this is fine.

> I'm not sure I follow the argument for the typedef

I would find `[BuilderUpdates<AccountBuilder> b]` or `[UpdatesFn<AccountBuilder> b]` much easier to read `[void updates(AccountBuilder b)]`
Function typed parameters are not very common and beginners sometimes have a hard time understanding what's going on when they see them.

> shouldn't that be a feature request there?

Yes, I created one.

**Comment by davidmorgan** [comment]
I'm going to close this in favour of fixing code_builder. Please re-open if this is blocking for you. Thanks!
