### ISSUE TITLE
Can you add private properties to a built_value class?

### ISSUE THREAD

**Issue by TheFriendlyCoder** [google/built_value.dart#1311]
I've just started using built_value to simplify some classes I'm writing that model data loaded from a REST API. Sometimes my classes need to store supplemental or helper data not directly related to the raw JSON data returned by the API. For example, a class that wraps some JSON data may need to also hold a reference to an HTTP session in order to perform operations on the data. A basic example class would look something like this:

```
class RestObject {
   // supplementary data
   final HTTPSession _session;

   // REST API response data
   String id;
   String name;
}
```

Is there any way for me to annotate my class / properties so that I can pass in reference objects like `_session` from the caller to the constructor, and have the other properties like `id` and `name` parsed from JSON data? I am looking to achieve something that might look like this:

```
var jsonData = jsonDecode(response.body);  // { "id": "1234", "name": "John Doe" }
var session = createHTTPSession();

var obj = serializers.deserializeWith(RestObject.serializer, session, jsonData);
```

I've tried searching through the docs but couldn't quite find anything that looked like what am describing here. If I've missed it, feel free to share the links with me. 

For reference, my first couple of attempts at this have yielded warnings from built_value asking that I make `_session` public (which I'd prefer not to do) and/or to add a getter to the value, which I also would prefer not to do. 

Thanks in advance for the help.

**Comment by dave26199** [comment]
You can mark fields with the BuiltValueField annotation to make them never serialized; but they will have to be public. I think that's as close as you can get with fields.

If they are session scoped, could you instead put them in the Zone? You can launch code in a new Zone and introduce scoped "global" variables that way.

**Comment by TheFriendlyCoder** [comment]
> You can mark fields with the BuiltValueField annotation to make them never serialized; but they will have to be public. I think that's as close as you can get with fields.
Can you give an example of what the syntax for that would look like?

> If they are session scoped, could you instead put them in the Zone? You can launch code in a new Zone and introduce scoped "global" variables that way.
I think you are assuming my project is intended for use in an HTTP server application, but it is a client side HTTP application that I am building, so sessions / zones don't apply. Unless I'm misunderstanding your suggestion.

**Comment by davidmorgan** [comment]
Just

```
@BuiltValueField(serialize: false)
```

on a field. https://pub.dev/documentation/built_value/latest/built_value/BuiltValueField-class.html

**Comment by TheFriendlyCoder** [comment]
Thanks for the advice. I'll give it a try.
