### ISSUE TITLE
Is it possible to exhaustively Switch on EnumClass 

### ISSUE THREAD

**Issue by SharbelOkzan** [google/built_value.dart#1315]
### Desired Behavior:

```Dart
class Foo extends EnumClass {  /*... */ }

String mapFooToString(Foo foo) {
    switch (foo) {
      case TypeEnum.on:
        return "foo is on";

      case TypeEnum.off:
        return "foo is off";
    }
}
```
### Motivation:

I'm using [openapi-generator](https://openapi-generator.tech/docs/generators/dart-dio) to generate an API client. It uses build_value in the generated code thus extends `EnumClass`  for Enums.

Currently, the analyzer complains about the example above
> The body might complete normally, causing 'null' to be returned

P.S I don't want to add a `default` case so I get an **error** (not a linter warning) when a new enum is added and not handled. 

Is that possible?

**Comment by davidmorgan** [comment]
I don't think there's a way to do that, because the `EnumClass` is just a class that could be implemented / instantiated leading to other values.

**Comment by SharbelOkzan** [comment]
Makes sense, thanks. Closing.
