### ISSUE TITLE
[Question] Is it normal to see duplicates in the debugger?

### ISSUE THREAD

**Issue by obayit** [google/built_value.dart#1317]
I noticed that every value is duplicated, is this normal?

![Screenshot from 2024-06-10 13-14-00](https://github.com/google/built_value.dart/assets/20386024/5f25f6fb-83ba-4833-800b-0009cb7d96b7)

For example the id is show twice.
My model name is Pos

**Comment by obayit** [comment]
Closing because it is not caused by this repo.

**Comment by davidmorgan** [comment]
Thanks for figuring this out before I got around to looking at it :) @obayit
