### ISSUE TITLE
How to ignore class implementations that extend Fake? (from mocktail)

### ISSUE THREAD

**Issue by mattia-venturini** [google/built_value.dart#1330]
In my app I have a lot of model classes implemented with BuiltValue. Many of them are quite complex, so I wanted to create some Fake classes to be used in some of my unit tests using [mocktail](https://pub.dev/packages/mocktail), but then I get an error while running build_runner.

For example if I have a model class like this:
```
abstract class User implements Built<User, UserBuilder> {
  factory User([Function(UserBuilder b)? updates]) = _$User;

  User._();

  int get id;

  String get name;
}
```

So in my to test I create the Fake class like this
```
class _FakeUser extends Fake implements User {}
```

But when I run build_runner in the project I get the following error:
```
[SEVERE] built_value_generator:built_value on test/unit/my_service_test.dart:
Error in BuiltValueGenerator for class _FakeUser extends Fake implements User.
Please make the following changes to use BuiltValue:

1. Import generated part: part 'my_service_test.g.dart';
2. Make class abstract.
3. Make class implement Built<_FakeUser, _FakeUserBuilder>.
4. Make class have exactly one constructor: _FakeUser._();
5. Add a factory so your class can be instantiated. Example:

factory _FakeUser([void Function(_FakeUserBuilder)? updates]) = _$FakeUser;
```

In practice, when I use _FakeUser in the unit tests, it works fine, so I would like only to tell BuiltValueGenerator to ignore that class. How can I achieve that?

**Comment by davidmorgan** [comment]
Possibly you can use a `build.yaml` file to configure which files the generator runs for?

https://github.com/dart-lang/build/blob/master/build_config/README.md

**Comment by davidmorgan** [comment]
Glad I could help, thanks for posting the full answer :)
