### ISSUE TITLE
Change generation of built classes to support full strong mode

### ISSUE THREAD

**Issue by ranquild** [google/built_value.dart#142]
With following 
```
strong-mode:
  implicit-casts: false
  implicit-dynamic: false
```
analyzer options code generated by built_value_generator code will be reported as error. 
`factory _$Settings([updates(SettingsBuilder b)])` 
`ERROR: Missing return type for 'updates'.`

Can you specify `void` type as return type for `updates` function? This will allow everybody who use built_value to enable full strong mode in project.

**Comment by dave26199** [comment]
I believe this is already fixed -- please check you're on the latest version. (Pub upgrade). Thanks!

**Comment by ranquild** [comment]
@dave26199 Checked examples and generated code - you are right! Thanks!
