### ISSUE TITLE
Add serializer plugin that does renames

### ISSUE THREAD

**Issue by vadimtsushko** [google/built_value.dart#144]
That is one of requirements,  that probably appears only when one works with external API.
In my case models have many String fields that can have values only from some predefined list:
For example, the field chartType can have values

-   table
-   barchart
-   linechart
-  pivot-table

and so on. Ideally, I would like to use Enums for such fields, but some of the possible values (pivot-table in above example) are not valid dart identifiers. 

It would be great If we could change serialized value of Enum by some annotation. 

For example, given enum 

``` Dart

class SecondTestEnum extends EnumClass {
  static const SecondTestEnum yes = _$ys;
  static const SecondTestEnum no = _$n;
  static const SecondTestEnum definitely = _$definitely;
  @SerializedAs('no-thanks')
  static const SecondTestEnum noThanks = _$noThanks;
  const SecondTestEnum._(String name) : super(name);
  static Serializer<SecondTestEnum> get serializer => _$secondTestEnumSerializer;
  static BuiltSet<SecondTestEnum> get values => _$vls;
  static SecondTestEnum valueOf(String name) => _$vlOf(name);
}

```
Its implementation would be:

``` Dart
const SecondTestEnum _$ys = const SecondTestEnum._('yes');
const SecondTestEnum _$n = const SecondTestEnum._('no');
const SecondTestEnum _$definitely = const SecondTestEnum._('definitely');
const SecondTestEnum _$noThanks = const SecondTestEnum._('no-thanks');

SecondTestEnum _$vlOf(String name) {
  switch (name) {
    case 'yes':
      return _$ys;
    case 'no':
      return _$n;
    case 'definitely':
      return _$definitely;
    case 'no-thanks':
      return _$noThanks;
    default:
      throw new ArgumentError(name);
  }
}

...
```

**Comment by vadimtsushko** [comment]
I've made some naive implementation and added related snipped in example project - it works as required in that scenario. I've not managed to add tests though.

**Comment by vadimtsushko** [comment]
Ups, I've omitted some file in commit

**Comment by davidmorgan** [comment]
Thanks! It definitely makes sense to support this somehow.

There's one alternative path I'd like to explore: using a serializer plugin. These run before/after each serialization/deserialization and can modify values, e.g.:

https://github.com/google/built_value.dart/blob/master/built_value/lib/standard_json_plugin.dart

So for example I can see writing something like

```
final mySerializers = (serializers.toBuilder()..addPlugin(
    (new EnumRenamerPlugin()
        ..add(SecondTestEnum, {'no-thanks': 'noThanks'})).build(), 
  ).build();
```

This makes the serialization format separate from the class definition -- you could have different plugins for different ways you want to serialize. And, it's more general -- we can add plugins for various tweaks that you might need to make serialization compatible.

But, perhaps it's less convenient. What do you think?

**Comment by vadimtsushko** [comment]
I just added skipped file to commits in my repo.

I think plugins would be OK for renaming enum values, but annotations seem to be slightly more convenient in that case

**Comment by vadimtsushko** [comment]
With regard to plugins I think it makes sense to consider another scenario - renaming field name in serialization. Say we want to use Built_value for CSS models. Field in our models would be camelCased (as fontWidth) and in serialized form they should look like font-width

**Comment by vadimtsushko** [comment]
Hm, probably in that scenario both approaches would work too. Plugins would be slightly slower in runtime, I guess?

**Comment by vadimtsushko** [comment]
And some errors that could be checked in generation time with the annotiation approach, would be checked in the runtime with plugins. For example duplication of enum values or field names

**Comment by vadimtsushko** [comment]
Well, plugin approach has a bit plus - it can be easily integrated into a working system.
I created a simple plugin, that suits my immediately needs well, so I may try it and get a feeling - how it works

``` Dart
import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';

class EnumRenamerPlugin implements SerializerPlugin {
  final FullType fullType;
  final Map<String, String> mappings;
  final Map<String, String> reverseMappings = {};
  EnumRenamerPlugin(this.fullType, this.mappings) {
    for (var key in mappings.keys) {
      reverseMappings[mappings[key]] = key;
    }
  }

  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (specifiedType == fullType) {
      if (mappings.containsKey(object)) {
        return mappings[object];
      }
    }
    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (specifiedType == fullType) {
      if (reverseMappings.containsKey(object)) {
        return reverseMappings[object];
      }
    }
    return object;
  }

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    return object;
  }
}

```

**Comment by dave26199** [comment]
Great, I look forward to hearing how it works out. Thanks!

**Comment by zoechi** [comment]
Is there a smart way to find whether the current object is an enum?

**Comment by davidmorgan** [comment]
I'm not quite sure what you're asking -- do you mean in the context of a serializer plugin?

**Comment by zoechi** [comment]
Exactly, I want to do some replacements only for enum values but not for normal built_value instances.

**Comment by zoechi** [comment]
there doesn't seem to be a way to check if `specifiedType` is `EnumClass`

**Comment by zoechi** [comment]
For example I have an enum value `null` that I implemented as `null_ => _$null`. Now when deserializing, how can I know that I should convert `null` to `'null_'`

**Comment by zoechi** [comment]
It's not too serious. There were only a handful and I hardcoded the types in the serializer plugin.

**Comment by davidmorgan** [comment]
Yeah, I think hardcoding is the only way to do it for now.

We could potentially add the information when doing codegen -- but it's not quite clear where it would go.

**Comment by zoechi** [comment]
It was a bit cumbersome because importing the classes caused transitive imports which caused some serializers be generated for classes that were supposed to be treated separately (in another directory).
I used `specified.type.toString()` and compared with string names to avoid the need of importing classes into the serializer plugin.

**Comment by ScottPierce** [comment]
I just came across the need for this, and I'm finding that the plugin approach lacking. It separates the name away from the model class too much. It makes it pretty inconvenient to rename a variable, and it also makes it difficult to maintain, as if the model or class changes, I might not clean up the rename as well.

At the end of the day, the class is a direct representation of that json request / response. I think it's ok if the renaming is tightly coupled to the model via annotations. And as I mentioned above, I think it's far more convenient, and maintainable. Using an annotation would also follow suit with other popular json parsing libraries, i.e. gson.

**Comment by dave26199** [comment]
@ScottPierce Thanks. Makes sense. I think the right way to build annotation support would be on top of plugin support -- i.e. to generate a plugin. That way you keep the flexibility -- in particular you get the freedom to use, ignore or supplement the annotations.

I'll plan to work on both together at some point.

**Comment by davidmorgan** [comment]
(We should also have a base implementation of the serializer plugin, to save some typing).

**Comment by nodinosaur** [comment]
Thanks to @vadimtsushko for the initial code, with my colleague @JanKn we have modified the code a little to handle renaming `JSON` field names:

```dart
import 'package:built_value/serializer.dart';

class JsonFieldRenamerPlugin implements SerializerPlugin {
  final FullType fullType;
  final Map<String, String> mappings;
  final Map<String, String> reverseMappings = {};

  JsonFieldRenamerPlugin(this.fullType, this.mappings) {
    for (var key in mappings.keys) {
      reverseMappings[mappings[key]] = key;
    }
  }

  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (specifiedType == fullType) {
      if (mappings.containsKey(object)) {
        return mappings[object];
      }
    }
    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (specifiedType == fullType && object is List) {
      for (var i = 0; i < object.length; i += 2) {
        if (reverseMappings.containsKey(object[i])) {
          object[i] = reverseMappings[object[i]];
        }
      }
    }
    return object;
  }

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    return object;
  }
}
```

### Usage
We wanted to change `24h_volume_btc` to `volume_24h_btc`
```dart
library serializers;

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';
import 'package:my_app/api/ticker.dart';
import 'package:my_app/serializer_plugins/json_field_renamer_plugin.dart';

part 'serializers.g.dart';

@SerializersFor(const [
  Ticker
])
final Serializers serializers = (_$serializers.toBuilder()
  ..addPlugin(new StandardJsonPlugin())..addPlugin(
      new JsonFieldRenamerPlugin(
          const FullType(Ticker),
          {
            // "toFieldName": "fromFieldName"
            "volume_24h_btc": "24h_volume_btc",
          }))
)
    .build();
```

`Ticker value object`:
```dart
library ticker;

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'ticker.g.dart';

abstract class TickerItems implements Built<TickerItems, TickerItemsBuilder> {
  BuiltList<Ticker> get data;
  TickerItems._();
  factory TickerItems([updates(TickerItemsBuilder b)]) = _$TickerItems;
  static Serializer<TickerItems> get serializer => _$tickerItemsSerializer;
}

abstract class Ticker implements Built<Ticker, TickerBuilder> {
 
  // actual field name is"24h_volume_btc" 
  String get volume_24h_btc;
  // other values omitted for brevity

  Ticker._();
  factory Ticker([updates(TickerBuilder b)]) = _$Ticker;
  static Serializer<Ticker> get serializer => _$tickerSerializer;

}
```

posting it here incase it helps someone until a nicer solution comes along  :)

**Comment by adamlofts** [comment]
Can I put in a vote to implement this in the core library rather than a plugin using an annotation like in #279. As you mention above a generic implementation of this as a plugin would require generating the plugin in the build step. 

I understand that putting non-core functionality in as plugins makes sense. I just think that this functionality is fundamental to a library providing serialisation to JSON and eventually most users of the library will need it to support external APIs and code refactoring.

**Comment by srsudar** [comment]
I am also trying to find a way to perform renames, but I am struggling to find example usage of the options discussed above.

I am working with an api that spits out JSON with field names like `site_url` and `site_id`. I am trying to map these to fields in my `built_value` classes that are `siteUrl` and `id`. I might expect something like:

```
@WireName('site_id')
String get id;
@WireName('site_url')
String get siteUrl;
```

I can't seem to find what that method would be, however. Is nodinosaur's reponse above, with the `JsonFieldRenamerPlugin`, the recommended way to do this? I agree that it is extremely generalizable, but it is also quite heavy.

Once I figure out how to do this I would be happy to submit a PR for an example use case.

**Comment by dave26199** [comment]
The annotation that lets you set value type field wire names is called BuiltValueField:

https://pub.dartlang.org/documentation/built_value/latest/built_value/BuiltValueField-class.html

It would make sense to explain this and the other three related annotations on the main README    file, I think.
