### ISSUE TITLE
rename fields from JSON deserialization

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#150]
I have to deserialize JSON that contains `case` as field name which is a reserved word in Dart and therefore I can't use that as field name in a built_value class.

Is a custom serializer like explained in https://github.com/google/built_value.dart/issues/134#issuecomment-284340569 a possible approach to solve that, or is there something better?

**Comment by davidmorgan** [comment]
It should work to rename fields using a serializer plugin, as in this request to support renaming enum values:

https://github.com/google/built_value.dart/issues/144

Please let me know if that works. It would make sense to have standard plugins for doing this be part of built_value.

**Comment by zoechi** [comment]
Great! Yes, a standard way would be great. 
Perhaps some field decorator and a way to get it's value during deserialization. 
I'll try the custom serializer for now.

**Comment by zoechi** [comment]
I created a plugin for that and it's working fine.
Not even sure anymore if it really needs a standard plugin. Perhaps a plugin example, like the one from #144 would be enough.

**Comment by davidmorgan** [comment]
Thanks! Probably we need at least a set of examples, yes. I'll leave this issue open for that.

**Comment by davidmorgan** [comment]
I'm going to merge into #144.
