### ISSUE TITLE
Dart2js optimization

### ISSUE THREAD

**Issue by Aetet** [google/built_value.dart#155]
Is there any plans for optimizing this library for dart2js? For example for Iterable and use them as JSarray ?

**Comment by davidmorgan** [comment]
Could you give more detail about what sort of optimizations you're thinking about, please?

In particular -- do you have a specific use case that you want to speed up?

**Comment by ranquild** [comment]
This should go to built_collection repository probably. I too have issues with built collection & dart2js. Consider following code:
```
List<int> array = <int>[1, 2, 3];
BuiltList<int> list = new BuiltList<int>(array);

int total = 0;

for (int number in array) total += number;
for (int number in list) total += number;

print(total);
```
Compile it with `dart2js main.dart --trust-primitives --trust-type-annotations`
```
for (t1 = array.length, total = 0, _i = 0; t2 = array.length, _i < t2; t2 === t1 || (0, H.throwConcurrentModificationError)(array), ++_i)
  total += array[_i];
for (t1 = list._list, t1 = new J.ArrayIterator(t1, t1.length, 0, null); t1.moveNext$0();)
  total += t1._current;
```

There is huge performance penalty for using iterator vs using direct array access in a loop. Still, dart2js is able to recognize that there is native array behind list, but not able to generate same efficient code as for using array directly. This is just specific case, but probably same issue is with other methods.

**Comment by davidmorgan** [comment]
Created an issue over at built_collection. Please continue discussion there.

**Comment by davidmorgan** [comment]
Closing, please reopen if there are built_value specific issues. (As opposed to built_collection). Thanks!
