### ISSUE TITLE
Enum generator doesn't recognize the `valueOf` method when it is implemented with a block body

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#159]
>   2. Add method: static AuthRegisterLocationAccuracy valueOf(String name) => _$valueOf(name)
```dart
  static AuthRegisterLocationAccuracy valueOf(String name) {
    return _$valueOf(name);
  }
```
but code_builder currently doesn't support to create method with a shorthand function (at least I haven't found it)

**Comment by davidmorgan** [comment]
Sounds like it would be better to fix this in code_builder -- the block body form is much less idiomatic Dart, I'm not too enthusiastic about allowing it.

**Comment by zoechi** [comment]
I also think this should be supported in code_builder, but I found it a bit pedantic from built_value to not recognize semantic identical code ;-)
I have no idea how much work this would cause, if it's complicated I also think it's not worth it.

The error message produces for not complying to the requirements are very helpful :+1:

**Comment by davidmorgan** [comment]
Yes, it's a little awkward ;)

Supporting more than one way of writing the same thing means adding more code here:

https://github.com/google/built_value.dart/blob/master/built_value_generator/lib/src/enum_source_class.dart#L52

It's not a huge amount of work but it does add complexity -- and makes the whole thing a bit more complex for users, too. Generally I'm happy to add variations when they add value (e.g. help people pass certain lint checks). In this case though I think the inline version is always better.

**Comment by zoechi** [comment]
Don't worry. If you don't think it's worth it, just close the issue.

**Comment by davidmorgan** [comment]
Thanks :)
