### ISSUE TITLE
How does one activate StandardJsonPlugin or any other plugin?

### ISSUE THREAD

**Issue by Pacane** [google/built_value.dart#171]
Hi,

so far I've followed the examples, and I ended up with a `serializers.dart` file containing: 

```dart
library serializers;

import 'package:built_value/serializer.dart';
import '...';

part 'serializers.g.dart';

/// Collection of generated serializers for the built_json chat example.
Serializers serializers = _$serializers;
```

Where should I call the `addPlugin()` method? I've got it working by adding it manually to the `serializers.g.dart` that has the generated `toBuilder()` call, but that gets overwritten by the watch/build script. (duh!)

**Comment by davidmorgan** [comment]
Like this:

```
  final standardSerializers =
      (serializers.toBuilder()..addPlugin(new StandardJsonPlugin())).build();
```

As in the example:

https://github.com/google/built_value.dart/blob/master/example/lib/example.dart#L67

**Comment by Pacane** [comment]
Hmm won't that leave me with my custom serializers not added to the standard ones?

I came up with this and it fixed the problem, although I was wondering if you knew if there was any downside of doing this:

in serializers.dart:

```dart
Serializers get serializers {
  var newBuilder = _$serializers.toBuilder();
  newBuilder.addPlugin(new StandardJsonPlugin());
  return newBuilder.build();
}
```
```dart
Serializers _$serializers = (new Serializers().toBuilder()
      ..add(AccessToken.serializer)
      ..add(Credentials.serializer)
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>()))
    .build();
```

This way I end up with and I also have the plugin added to that serializers list.

**Comment by davidmorgan** [comment]
In my example -- "serializers" comes from your serializers.dart. So you could do e.g.:

```

library serializers;

import 'package:built_value/serializer.dart';
import '...';

part 'serializers.g.dart';

/// Collection of generated serializers for the built_json chat example.
Serializers serializers = _$serializers;

Serializers standardSerializers = 
    (serializers.toBuilder()..addPlugin(new StandardJsonPlugin())).build();
```

**Comment by Pacane** [comment]
Ok! Thanks for the clarification. Great work btw with this lib.

**Comment by davidmorgan** [comment]
Glad I could help. Thanks :)

**Comment by feinstein** [comment]
@davidmorgan in my case I just want a JSON serializer and nothing more, sure I can do things as you demonstrated, but isn't it there a more efficient way? A one-liner? Or something where I don't end up with `serializers` and `standardSerializers` variables, where only `standardSerializers` is actually used?

I came up with:

```dart
final Serializers serializers = (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();
```

Is this ok or are there any side effects I should be aware of?

**Comment by davidmorgan** [comment]
Yes, that's the right way to do it. Sorry, it's a bit awkward :)
