### ISSUE TITLE
Workflow for build process

### ISSUE THREAD

**Issue by Aetet** [google/built_value.dart#172]
What is the best workflow process for build? All files must be generated at build phase or at develop phase? Is files must be at git repo or not? How to handle with .dart_tool folder?

**Comment by davidmorgan** [comment]
I'd say it depends on what else you're doing.

If you're using dart as part of a larger project with another build system, it probably makes sense to integrate the generation into that build system. Of course that will depend on what you're using.

If you're using just dart+pub, I would suggest:

1. Generate while you're developing, using a watcher script
2. Ignore generated files for the git repo
3. But, note that if you publish anything to pub, you need to include generated files here
4. The .dart_tool folder is temporary files -- ignore for git, and you may need to delete this when upgrading versions of package:build

**Comment by Aetet** [comment]
I use dart+pub, I'm really interested in how you setting up your developer-build process with large dart-only projects.

**Comment by davidmorgan** [comment]
With just Dart, it should work to just run a watcher script; then you'll get updates to generated code as you develop.

For that setup I'd ignore the files for the git repo.

Does that work for you?

**Comment by davidmorgan** [comment]
Please reopen if you need more information / pointers. Thanks.
