### ISSUE TITLE
Using short function syntax to get rid of linter hints

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#174]
![image](https://user-images.githubusercontent.com/405837/27033268-e2b4d0fa-4f78-11e7-9002-81e4988960de.png)

info: Use => for short members whose body is a single return statement. (prefer_expression_function_bodies at [datingnode] lib/src/queries_enums.g.dart:4650)

Alternatively some way to get `// ignore_for_file: ...` comments added to generated code to suppress such lints and errors would help as well.

**Comment by davidmorgan** [comment]
Thanks! Sent a PR.

**Comment by zoechi** [comment]
As always super fast response. I love to use built_value.
