### ISSUE TITLE
built_value depends on dart 1.21+ for Generic Method syntax

### ISSUE THREAD

**Issue by jefftougas** [google/built_value.dart#178]
First off, thanks for this awesome library. I'm really digging it.

It looks like built_value.dart is incompatible with dart older than 1.21 due to the use of generics in a couple of convenience methods (deserializeWith and serializeWith in serializers.dart and built_json_serializers.dart). Does that sound right to you or am I missing something?

If my understanding is correct, then I will submit a PR to correct built_value's pubspec sdk requirement to reflect this (right now it calls for >1.8.0), and also I'll create a branch in my fork for legacy dart support that simply removes those convenience methods whilst leaving the sdk requirement as is. If you'd be willing to incorporate said legacy support branch into your repo and perhaps publish a patch on pub to one of the older major versions (or similar), that'd be really helpful as it'd allow me to go on referencing the main pub repo from my pubspec.yaml instead of pointing to my fork / branch, but obviously no worries if you don't think that makes sense for whatever reason.

**Comment by davidmorgan** [comment]
Thanks for catching. Yes, the pubspec should be updated -- please do send a PR.

If I understand correctly what you'd like is for a version to be published to pub with the generics moved back to comments? Makes sense. Do you need it to be on github or is just the pub package enough? I'll take a look on Monday.

**Comment by jefftougas** [comment]
> Yes, the pubspec should be updated -- please do send a PR.

Thanks for confirming - will send in a PR shortly.

> If I understand correctly what you'd like is for a version to be published to pub with the generics moved back to comments? Makes sense. Do you need it to be on github or is just the pub package enough?

I had in mind commenting out (or removing) the 4 methods that use generics, but perhaps you're referring to [this functionality](https://github.com/dart-archive/dev_compiler/blob/master/doc/GENERIC_METHODS.md#using-generic-method-parameters)? In either case, yes, a version being published to pub that *somehow* is compatible with older dart is my ideal outcome here, and the pub package would be sufficient - no need to publish to github in that scenario.

**Comment by jefftougas** [comment]
PR opened. Also FYI, I pushed the commented generic syntax to my fork with 64ee528, which I'll be using in my dart 1.15 project until you get a chance to publish a special version with a similar change to pub. Thanks again!

**Comment by davidmorgan** [comment]
This should now be done -- release v1.1.3 with the old syntax and v1.1.4 with the new syntax and the SDK constraint.

Please let me know if you have any problems.

Thanks!

**Comment by jefftougas** [comment]
Great, thank you! I've verified 1.1.3 in my Dart 1.15 project and its working perfectly. I really appreciate your quick turnaround on this.

**Comment by davidmorgan** [comment]
Great. By the way, if you can share, I'm curious as to what's keeping you on 1.15. If not, no need to reply :)
