### ISSUE TITLE
Non-instantiable Built doesn't quite work with generics

### ISSUE THREAD

**Issue by joshua-i** [google/built_value.dart#189]
For example:
```
@BuiltValue(instantiable: false)
abstract class SomeIface<T> implements Built<SomeIface<T>, SomeIfaceBuilder<T>> {
  String get str;
}

abstract class ImplA implements Built<ImplA, ImplABuilder>, SomeIface<String> {

  String get value;

  ImplA._();

  factory ImplA([updates(ImplABuilder b)]) = _$ImplA;
}
```

will have ImplABuilder defined as
`class ImplABuilder implements Builder<ImplA, ImplABuilder>, SomeIface<String>Builder {`
Obviously, it should be `SomeIfaceBuilder<String>`

**Comment by dave26199** [comment]
Thanks -- yes, not quite right :) -- will fix next week.

joshua-i <notifications@github.com> schrieb am Fr., 7. Juli 2017, 21:21:
