### ISSUE TITLE
Support byte arrays (i.e. dart:typed_data Uint8List) in JSON serialization

### ISSUE THREAD

**Issue by jt70** [google/built_value.dart#194]
Support Uint8List by transparently converting to and from base64 encoded strings.  If you want this I'll sign a CLA and submit a pull request.

**Comment by dave26199** [comment]
Sounds good, go ahead. I'll likely be slow to review though as I'm on vacation until next week. Thanks!

**Comment by dave26199** [comment]
One thought though -- we probably want to introduce a wrapper for Uint8List to make it immutable. This would go in built_collection. What do you think?

**Comment by jt70** [comment]
Yes definitely, thanks!

**Comment by long1eu** [comment]
Any news on this?

**Comment by davidmorgan** [comment]
Nothing from my side.

**Comment by long1eu** [comment]
That was fast.
