### ISSUE TITLE
The chat example doesn't seem to be up-to-date with 2.0.0

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#203]
The build scripts and model classes seem to require changes.

**Comment by davidmorgan** [comment]
They should be up to date ... could you give an example please?

Thanks :)

**Comment by zoechi** [comment]
Ups, sorry. Seems I got an old version shown but didn't check "Branch" dropdown in GitHub.
Sorry for the noise.

**Comment by davidmorgan** [comment]
No worries. Thanks :)
