### ISSUE TITLE
single statement methods `hashCode` and `toString` with a '{}` body cause linter warnings 

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#208]
```
info: Use => for short members whose body is a single return statement. (prefer_expression_function_bodies at [my_proj] lib/src/model/brand.g.dart:162)
```
for `prefer_expression_function_bodies`

**Comment by zoechi** [comment]
I also get this one
```
info: Sort constructor declarations before method declarations. (sort_constructors_first at [my_proj] lib/src/model/brand.g.dart:225)
```
but I'm not sure how to handle these. I don't think this is an official style rule.

Perhaps being able to add custom 

```
// ignore_for_file: some_warning
```
would be a solution.

**Comment by davidmorgan** [comment]
Thanks! Will take a look.

**Comment by davidmorgan** [comment]
Sent a PR so we can easily have a list of 'ignore_for_file', and added both of these lints.

The "prefer_expression_function_bodies" lint is a bit strong for my taste; it triggers even when the function body is one very long statement; in this case it seems weird to use the arrow form.

I'm not a fan of "sort_constructors_first", I'd generally prefer to have getters before the constructor when they're acting like fields.

Re: custom ignores -- maybe this is something we'll need at some point -- in the meantime please file issues for any lints that are annoying you. Thanks!

**Comment by zoechi** [comment]
Great 👍 

I think custom ignores, for example like
```dart 
@IgnoreForFile(const ['sort_constructor_first'])
library somelib;
```
that result in ignore comments in the generated files would be really great.

There are several rules like `sort_constructors_first` where (some on) the Flutter team has(ve) a strong opinion.
I guess such rules can become more over time.  
If other developers start following their example, they'll get lots of clutter in the analyser view and no way to get rid of it (except disabling the linter rule for the whole application)

**Comment by davidmorgan** [comment]
That seems a lot to ask people to do.

It should be possible to generate code that either meets or ignores all the lints ... then it's solved for everyone. Right now though I've been too lazy to try to do this actively :)

**Comment by zoechi** [comment]
It could also be a single place like `@SerializersFor()`

**Comment by davidmorgan** [comment]
I think the right single place is in built_value_generator.dart :) ... but, indeed, if that seems a better way to go at some point, we could do that. Thanks.

**Comment by zoechi** [comment]
Didn't think of that, but a parameter to `new BuiltValueGenerator()` would be a nice idea as well.
