### ISSUE TITLE
memoize hashCode

### ISSUE THREAD

**Issue by davidmarne** [google/built_value.dart#210]
It would make sense to memoize the result of hashCode like you do in built_collection.

Is there any reason you do not?  Would the performance gains be negligible? I'm not sure how expensive those bit-wise operations are in dart but it seems like it would be work memoizing, especially when using built_value with dart2js.

**Comment by davidmorgan** [comment]
Well, we'd have to measure to know the performance gains :) ... if you have a particular case in mind you could hack the .g.dart files yourself and try it.

You'd save the most time where you're using built_value for a large structure that does _not_ rely on built_collection; for example if you're build a tree out of built_value Nodes. But, you'd also pay a lot for memory use.

The way Guava's `@AutoValue` does this is to allow you to redeclare hashCode as abstract then annotate to make it memoized.

https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/extension/memoized/Memoized.java

Then you can decide for yourself. How does that sound?

I was already planning on adding this at some point.

Related: when using both on the server and the client, it might make sense to calculate the hashCode server side and serialize it: https://github.com/google/built_value.dart/issues/195
