### ISSUE TITLE
Add fields from mixins

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#214]
```dart
/// Common interface and implementation for entity classes.
abstract class EntityMixin {
  /// The id of the entity.
  String get id;
}
```

```dart
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'entity_mixin.dart';

part 'user_account.g.dart';

abstract class UserAccount extends Object with EntityMixin
    implements
        Built<UserAccount, UserAccountBuilder> {
  factory UserAccount([dynamic updates(UserAccountBuilder b)]) =
  _$UserAccount;

  UserAccount._();

  static Serializer<UserAccount> get serializer => _$userAccountSerializer;
}
```

I found https://github.com/google/built_value.dart/blob/8b3a7a437c146eabd0014714b23010bd34ac16e5/end_to_end_test/lib/polymorphism.dart, but isn't exactly what I ant.

If I specify that `UserAccount` implements `EntityMixin`, the generated code contains the `id` field.

Should my use case work?
Did I forget something?

**Comment by zoechi** [comment]
I just saw I can mix in **and** implement the same at the same time, to get code generated for `id` and get other implementation from the mixin:

```dart
abstract class UserAccount extends Object with EntityMixin
    implements
        Built<UserAccount, UserAccountBuilder>, EntityMixin {
```
The works as a workaround, but is a bit ugly.

**Comment by davidmorgan** [comment]
Yes, I was just going to suggest that :)

Yes, it would make sense to pick up on the mixin directly. I'll take a look. Thanks!
