### ISSUE TITLE
Error with new requirement of sub-types with built collections and serialization

### ISSUE THREAD

**Issue by serates** [google/built_value.dart#227]
If the class you are serializing contains a BuiltMap,BuiltSet, etc the generated filed for serializers has a compile error in it because these types now require the full type specification so using FullType with the root type alone causes an error, example:

BuiltList<String> get names; in a class results in a builder factory being added:

```
..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>())
```

The BuiltList above errors with the following error:
```
expression is not a valid compile-time constant
          const FullType(BuiltList, const [const FullType(String)]),
```

**Comment by davidmorgan** [comment]
I'm not sure I follow -- was there a language/analyzer change that made omitting the full type an error?

Is it possible you're missing an import of package:built_collection/built_collection.dart?

Thanks!

**Comment by xavierhainaux** [comment]
I had this problem too.
When you write this:

```dart
library serializers;

import 'package:built_value/serializer.dart';
import 'message.dart';

part 'serializers.g.dart';

@SerializersFor(const [
  Message,
])
final Serializers serializers = _$serializers;
```

And your class Message contains a `BuiltList`. The generator generates code like this:

```dart
part of serializers;

// **************************************************************************
// Generator: BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(Message.serializer)
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>()))
    .build();
```

Now, because the generated file ends with `.g.dart`, it is hidden in the analysis view (we don't see the error in them). So we don't realize that we need to import `built_collection.dart` in *our* hand written file for a class referenced in the generated part.

**Comment by davidmorgan** [comment]
Thanks. Hmm. I was under the impression the analyzer _would_ report on errors in generated files; this is what I see with my local project. Do you have some configuration in analysis_options.yaml to turn that off?

I've submitted quite a few PRs to make sure the generated code is lint free so you can run the analyzer over it -- but perhaps this is not the right way to do things.

**Comment by xavierhainaux** [comment]
After checking, you are right we can see the errors in '.g.dart'. My analyzer was simply busy.
Sorry for the confusion

**Comment by davidmorgan** [comment]
Thanks. Still not a great experience though.

Will have a think if there's any way to do better. Suggestions welcome :)

**Comment by serates** [comment]
I can confirm adding the import of built_collections to the top where my serializers are generated fixed the issue.
