### ISSUE TITLE
Support built collections of builders in builders

### ISSUE THREAD

**Issue by Andersmholmgren** [google/built_value.dart#23]
e.g.

```
class FooBuilder ... {
  SetBuilder<BarBuilder> bar;
}
```

I have a complex build process that makes it very handy to have builders in my collections. Calling `fooBuilder.build()` then would ideally first build all the `BarBuilders` then build the set

**Comment by Andersmholmgren** [comment]
Maybe it is cleaner for Built Collections to have knowledge of Built Values so that `setBuilder.build()` will build any child objects that are built objects.

Maybe that will create a circular dependency though

**Comment by davidmorgan** [comment]
Makes sense. Will have a think.
