### ISSUE TITLE
new linter rules ;-)

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#230]
- `always_put_control_body_on_new_line`

![image](https://user-images.githubusercontent.com/405837/30472109-8414765e-99fb-11e7-8a44-1ce91baeef82.png)

This one doesn't make much sense, because dartfmt moves it back anyway, but the rule exists.
AFAIR requested by flutter. 

- `avoid_annotating_with_dynamic`

![image](https://user-images.githubusercontent.com/405837/30472137-9bc5bb32-99fb-11e7-8c52-37a2445b378d.png)

- `avoid_returning_this`

![image](https://user-images.githubusercontent.com/405837/30472495-f7a1bde2-99fc-11e7-8627-f59de463f012.png)

- `omit_local_variable_types`

![image](https://user-images.githubusercontent.com/405837/30472528-251ab36e-99fd-11e7-911e-194eb4d20752.png)

**Comment by davidmorgan** [comment]
Thanks! I think those two dynamic avoids are directly contradictory to the "no implicit dynamic" lint :) ... oh well. Time for the ignore bucket...

**Comment by zoechi** [comment]
related https://github.com/dart-lang/source_gen/issues/275
