### ISSUE TITLE
cope with instance loops during build process

### ISSUE THREAD

**Issue by Andersmholmgren** [google/built_value.dart#24]
Consider a case like

```
class Foo implements Built<....> {
  Foo get anotherFoo;
}

class FooBuilder implements Builder<....> {
  FooBuilder anotherFoo;
}

doBuild() {
  final fooBuilder = new FooBuilder();

  fooBuilder.anotherFoo = fooBuilder;
}
```

The intention is to build an instance of `Foo` whose `anotherFoo` property points to itself. Obviously this is a trivial example and loops can be much more complex than that.

It would be awesome if the process of building could cope with this, although it would necessitate something like

```
class _$Foo ... {
  Foo _anotherFoo;
  Foo get anotherFoo => _anotherFoo;
}
```

Could introduce an annotation to mark fields (or a whole class) that should support this sort of initialisation

**Comment by Andersmholmgren** [comment]
At some stage I'd like to reimplement https://bitbucket.org/andersmholmgren/constrain to use `built_value` and code gen. It has to cope with these sorts of loops

**Comment by davidmorgan** [comment]
I'd like to understand the use case better for this one, since supporting loops makes equality, hashCode and serialization harder.

Do you need just self loops or arbitrary loops?

One way of faking loops is to add an ID field, and have loops go via a lookup from IDs to instances. This may or may not work for what you're doing.

**Comment by davidmorgan** [comment]
( "constrain" looks fun. I hosted an intern who built something similar for Java as an intern project: https://github.com/nhatminhle/cofoja )

**Comment by Andersmholmgren** [comment]
I've been hitting this issue currently when working with meta models.

Take a simple `built_value` class such as

```
class Person implements Built<Person, PersonBuilder>, Primate {
  String get name;
}
```

If you look at https://github.com/Andersmholmgren/vcore/blob/master/lib/src/model/model.dart#L159

`ValueClass` is an abstract representation of a simple meta model for a `built_value` class such as `Person`

It has a set of `properties` like `name` and set of superTypes like `Primate`.

Referring to these [Meta object levels](https://www.google.com.au/imgres?imgurl=https%3A%2F%2Fwww.tech-arts.co.jp%2Fassets%2Fimages%2Ftechnology%2Fobject_oriented%2Fomg%2Ffigure01_en.png&imgrefurl=https%3A%2F%2Fwww.tech-arts.co.jp%2Fen%2FTechnologies%2Fnew-technologies%2F826%2Fmeta-modeling.html&docid=zzEapoYs0V-D5M&tbnid=oYCS73UD286coM%3A&w=2223&h=1461&itg=1&bih=778&biw=1440&ved=0ahUKEwit4ZnE4rjMAhVkGqYKHTCeDqwQMwgnKAswCw&iact=mrc&uact=8) then `Person` and `Primate` are at the `M1` level and `ValueClass` is at the `M2` level.

Since the type of `superTypes` is the same class (`ValueClass`) this is in effect a type loop. That's ok cause Dart supports that.

But if you step up to the `M3` level then that type loop turns into an instance loop. At the `M3` level I'm using the same model to represent itself. *This is what OMG's EMOF and Eclipse's ECORE do.*

You can see this represented at https://github.com/Andersmholmgren/vcore/blob/master/lib/src/vcore_metamodel/metamodel.dart#L179

To avoid the instance loop I introduced an extra class called `ValuableClass` (just a hacky name). 

Now I am trying to represent [ECORE](https://www.google.com.au/search?q=ECORE&rlz=1C5CHFA_enAU618AU618&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj3lcmW5rjMAhWi46YKHYOvB00Q_AUIBygB&biw=1440&bih=778#imgrc=90sSnJTZHedt6M%3A) as an instance of my `M3` model and it is also loops. Not surprising if you look at a [more detailed diagram of ECORE](https://www.google.com.au/search?q=ECORE&rlz=1C5CHFA_enAU618AU618&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj3lcmW5rjMAhWi46YKHYOvB00Q_AUIBygB&biw=1440&bih=778#imgrc=YcLqw6JMUMR4iM%3A).

With constrain I know I'll hit similar issues because it creates a model for the ConstraintDescriptors against an arbitrary domain model.

**Comment by Andersmholmgren** [comment]
cofoja looks interesting. This stuff is much easier in Dart though as annotations are much more powerful. I blogged about that when I first release constrain http://aholmgrendart.blogspot.com.au/2014/04/constraints-in-dart.html

**Comment by davidmorgan** [comment]
I'm going to mark this "won't fix". Loops would requiring changing all the other code (operator==, toString, hashCode, serialization), and it's not needed for the main use cases.

Happy to look at again if enough people need it, of course.
