### ISSUE TITLE
Allow subclasses to hard code fields

### ISSUE THREAD

**Issue by dave26199** [google/built_value.dart#245]
When using polymorphism, allow a subclass to hard code a value for a field -- expressed as a concrete getter or a (maybe?) final field.

This field should then be handled specially in the builder, since it can't be modified.

**Comment by zoechi** [comment]
And use it as discriminator in JSON deserialization?

**Comment by davidmorgan** [comment]
Hmm, that's not needed with the default JSON format -- that already writes enough information to deserialize.

The "standard JSON" format doesn't do this; we should probably follow an existing format there such as https://github.com/google/built_value.dart/issues/102

**Comment by dave26199** [comment]
On second thoughts I don't think this feature request is a good idea; when using polymorphism (instantiate=false), you should only add fields in the base class that you expect to always be buildable.

If you want more flexibility, you should stop fully generating the builder and write the builder interface yourself. I expect that at some point there will be an analyzer plugin that will make this easy to do -- and then it will be the default/recommended way anyway.

Filed https://github.com/google/built_value.dart/issues/249 which is somewhat related.
