### ISSUE TITLE
Variable annotated with @SerializersFor must be named "serializers"

### ISSUE THREAD

**Issue by xavierhainaux** [google/built_value.dart#260]
When we write: 

```dart
@SerializersFor(const [MyClass])
final Serializers serializers = _$serializers;
```

It seems the generator only recognized it if the variable is named `serializers`.

It prevents to have several Serializers in the same file. 
I would like the annotation to be enougth for the generator to pick it.

```dart
@SerializersFor(const [MyClass1, MyClass2])
final Serializers mySerializers1 = _$mySerializers1;

@SerializersFor(const [OtherClass1, OtherClass2])
final Serializers mySerializers2 = _$mySerializers2;
```

**Comment by dave26199** [comment]
Seems reasonable. Should be easy enough.
