### ISSUE TITLE
deserialize DateTime from ISO 8601 string

### ISSUE THREAD

**Issue by amardeep** [google/built_value.dart#272]
I want to consume an existing JSON api which uses ISO8601 strings for DateTime (as parseable by DateTime.parse).

How do i use built_value to deserialize such a json object.

Eg., if my json looks like:
{
  "numLikes": 10,
  "lastActiveTimestamp": "2016-05-31T10:02:35Z"
}

**Comment by davidmorgan** [comment]
You should be able to do this using a `SerializerPlugin`.

Something like

```
class DateTimeSerializerPlugin implements SerializerPlugin {
  Object beforeSerialize(Object object, FullType specifiedType) {
    if (FullType.root != DateTime) return object;
    return DateTime.parse(object as String).toUtc().microsecondsSinceEpoch;
  }

  Object afterSerialize(Object object, FullType specifiedType) => object;
  Object beforeDeserialize(Object object, FullType specifiedType) => object;
  Object afterDeserialize(Object object, FullType specifiedType) => object;
}
```

then to use the plugin

```
  var mySerializers = (serializers.toBuilder()..addPlugin(new DateTimeSerializerPlugin()))
      .build()
```

please let me know if this works :)

**Comment by davidmorgan** [comment]
Did this work for you in the end? Thanks. @amardeep

**Comment by amardeep** [comment]
I think it is ok to close this bug.

Sorry, haven't tried it yet - as trying to figure out a better solution for serializing / deserializing json objects primarily for json http apis.

Swagger/opanapi looked like a better option to declare api models. It has a [dart generator](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/dart/swagger) but it uses dartson which doesn't work with flutter.

I will try to write a swagger codegen which uses built_value, but not sure when i will. When i do that, i will try this approach and update if i face any issues.

Though on a separate note - a lot of people consuming json apis in flutter end up looking at built_value. With json apis - it is much more common to use ISO8601 strings for DateTime, so it would be great if this can be supported by default without needing to write this plugin.

**Comment by dave26199** [comment]
Thanks. Definitely interested in swagger support--please let me know if you get around to looking into it.

Re: ISO8601, it should be easy enough to offer as an option. I'll look into it. (At some point.) Thanks!
