### ISSUE TITLE
JSON serialization example

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#275]
A standard JSON serialization plugin example like the one asked for on SO might be a good addition to https://github.com/google/built_value.dart/blob/0f131d8cedb271405a52652f9b5eaa61c2c589aa/example/lib/polymorphism.dart

https://stackoverflow.com/questions/47674213/how-to-serialize-list-of-polymorphic-objects-using-built-value-and-standardjsonp

**Comment by davidmorgan** [comment]
Thanks for flagging!

StandardJsonPlugin doesn't support polymorphism yet.

See #92 and related issues :)

**Comment by zoechi** [comment]
I assumed that can be handles by a custom StandardJsonPlugin implementation.
I thought this would be a good example to demonstrate such a customized (de)serialization

**Comment by davidmorgan** [comment]
Closing in favour of #276
