### ISSUE TITLE
StandardJsonPlugin serialization of list of polymorphic objects

### ISSUE THREAD

**Issue by adamlofts** [google/built_value.dart#276]
I want to use StandardJsonPlugin to generate a map I can save to a document database on the server side. It needs to be structured as a map so I can create indexes on the data in the database. However the objects I want to serialize are polymorphic.

So given a class hierarchy of animals like in the [built_value polymorphism example][1]:

    Animal
        - Cat
        - Fish

I want to be able to (de)serialize a list of animals to JSON

    class Zoo implements Built<Zoo, ZooBuilder>  {
        static Serializer<Zoo> get serializer => _$zooSerializer;
        BuiltList<Animal> animals;
    }

I would like the type of animal to be encoded in each item. For example the json output could look like:

    {
    "animals": [
        {"type": "cat", "legs": 2},
        {"type": "fish", "fins": 3}
    ]}

For the moment I am working around this by creating an intermediate object like and removing the polymorphic-ness of the objects:

    class AnAnimal {
        @nullable
        Cat cat;
        @nullable
        Fish fish;
    }

  [1]: https://github.com/google/built_value.dart/blob/0f131d8cedb271405a52652f9b5eaa61c2c589aa/example/lib/polymorphism.dart

**Comment by davidmorgan** [comment]
Sounds reasonable, thanks. I will try to experiment in the next few days to see how easy/feasible this is.

**Comment by mekhri-codex** [comment]
@davidmorgan So can't find proper example of this concrete logic from the issue, is there something?
