### ISSUE TITLE
Is there something to merge values?

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#278]
Is there something simple that I'm missing for

```dart
var oldState = loadPersistedState();
var defaults = MyStore.defaultValue;
var newState = defaults.merge(oldState);
```
so that `newState` contains all values from `oldState` and also the values from fields in `defaults` where the fields in `oldState` are `null`?

The structure is several levels deep.

**Comment by davidmorgan** [comment]
There's nothing built in. You could serialize, merge in a general way and then deserialize.

We could add something for this; I worry that it might be too specialized to always generate it, though.

Protocol buffers have `mergeFrom` methods, but it's worth noting that they concatenate lists--it's not clear that that's the best thing to do. (Or maybe it is?)

https://developers.google.com/protocol-buffers/docs/javatutorial

Thoughts/opinions welcome, as ever :)

**Comment by zoechi** [comment]
Right, lists make ut complicated. I wouldn't need merging of lists. 
Only if a property of `oldState` is `null`, pass the value from `defaults`
