### ISSUE TITLE
Serialisation: Provide way to override the wireName of a field

### ISSUE THREAD

**Issue by adamlofts** [google/built_value.dart#279]
I can't figure out if this is possible so I'm filing an issue.

It would be cool to have a way to annotate a field to override its `wireName`. For example:

```dart
class Dog {
    static Serializer<Dog> get serializer => _$dogSerializer;
    @wirename("dog_name")
    String get name;
}
```
Would serialize as:
```json
{
    "dog_name": "rufus"
}
```

This is useful so I can write dart code using `camelCase` when the API I am connecting with is written in `lower_case`.

It would also be handy so you can refactor dart code without changing the wire format.

**Comment by davidmorgan** [comment]
You can use a SerializerPlugin. There is a detailed example here:

https://github.com/google/built_value.dart/issues/144

and I have a TODO to add such a plugin to the repo :)

Closing in favour of the linked issue.

Thanks!
