### ISSUE TITLE
Unable to resolve asset ID for "dart:ui"

### ISSUE THREAD

**Issue by yathit** [google/built_value.dart#282]
When running a build, if the model file contains 'import 'dart:ui';" the code generator output SEVERE log. The output file is still fine though.

` [SEVERE] Instance of 'PartBuilder' on dartsugar|lib/models/module_data.dart: Unable to resolve asset ID for "dart:ui"`

```
[✓] Flutter (on Mac OS X 10.12.6 16G1114, locale en-US, channel alpha)
    • Flutter at /Users/kyawtun/flutter
    • Framework revision 8f65fec5f5 (4 days ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e
```

**Comment by davidmorgan** [comment]
Thanks for reporting!

This is a fun problem. We want to analyze code that's targeted at flutter using code on the VM. I will file over at package:build and see if anyone there has ideas.

**Comment by ride4sun** [comment]
Same problem here. not sure how to work around that.

**Comment by davidmorgan** [comment]
yathit said the output was still okay, so presumably he didn't need a workaround. Is that not working for you? Thanks.

**Comment by ride4sun** [comment]
In my case the code generation gets hangs.

**Comment by dave26199** [comment]
Can you give the exact command(s) you are running, please?

>

**Comment by zoechi** [comment]
As a workaround the built value classes could be moved to another package

**Comment by ride4sun** [comment]
I moved the file in a separate package and than the generation works again. Thx @zoechi 

@dave26199 I run this:
```
import 'dart:async';
import 'package:build_runner/build_runner.dart';
import 'package:built_value_generator/built_value_generator.dart';
//import 'package:built_redux/generator.dart' show BuiltReduxGenerator;
import 'package:source_gen/source_gen.dart';


Future main([List<String> args]) async {
  await build(phases(), deleteFilesByDefault: true);
}

/// builder phases for built_value
List<BuildAction> phases() => [
      new BuildAction(
          new PartBuilder([
            const BuiltValueGenerator(),
            //new BuiltReduxGenerator(),
          ]),
          'home_test',
          inputs: const ['lib/**/*.dart'])
    ];
```

the file I moved contains this:
```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:meta/meta.dart';

typedef void ShowFeedbackTextCallback(String text, int seconds);

abstract class ComponentController {

  // The name of the Device. This will be shown in the
  // device list to select from. e.g. Eagle Gateway
  String get displayName;

  // The Model of the Device. This will be shown in the
  // device list to select from. e.g E456-123
  String get modelName;

  //identifies the component after the component was created
  String get id;

  //update rate
  int get updateIntervalInSeconds;

  //renders the component
  Widget renderComponent({@required BuildContext context});

/*
  //shows the feedback [text] for n [seconds]
  void showFeedbackText(String text, int seconds);
*/

  //builds up the component to get ready to get rendered
  Future<ComponentController> build();
}
```

**Comment by rrousselGit** [comment]
I faced the same issue on a custom code generator.

I solved it by testing `DartType.isUndefined` and look into the `Token` myself:

```dart
ParameterElement element;
String label = element.type.isUndefined
  ? element.computeNode().beginToken.toString() 
  : element.displayName;
```

Not the best solution ever. But works

**Comment by baoxiehao** [comment]
> I faced the same issue on a custom code generator.
> 
> I solved it by testing `DartType.isUndefined` and look into the `Token` myself:
> 
> ```dart
> ParameterElement element;
> String label = element.type.isUndefined
>   ? element.computeNode().beginToken.toString() 
>   : element.displayName;
> ```
> 
> Not the best solution ever. But works

No longer works now.

[INFO] Running build...
[INFO] 1.0s elapsed, 0/5 actions completed.
[SEVERE] dynamic_widget_generator:dynamic_widget_generator on lib/src/widget/image_widget.dart:
Error running DynamicWidgetGenerator
NoSuchMethodError: Class 'RestrictedAnalysisContext' has no instance method 'resolveCompilationUnit' with matching arguments.
Receiver: Instance of 'RestrictedAnalysisContext'
Tried calling: resolveCompilationUnit(Instance of 'FileSource', Instance of 'LibraryElementImpl')
Found: resolveCompilationUnit(Source, LibraryElement) => CompilationUnit
[SEVERE] dynamic_widget_generator:dynamic_widget_generator on lib/src/widget/text_widget.dart:
Error running DynamicWidgetGenerator
NoSuchMethodError: Class 'RestrictedAnalysisContext' has no instance method 'resolveCompilationUnit' with matching arguments.
Receiver: Instance of 'RestrictedAnalysisContext'
Tried calling: resolveCompilationUnit(Instance of 'FileSource', Instance of 'LibraryElementImpl')
Found: resolveCompilationUnit(Source, LibraryElement) => CompilationUnit
[INFO] Running build completed, took 8.4s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 44ms

**Comment by davidmorgan** [comment]
@baoxiehao the Dart analyzer API has changed; you'll need to either pin to an older version of the analyzer or update that code. Here is an example of doing such an update:

https://github.com/google/built_value.dart/commit/07d6374f2ed06a6f31079fbc838b8305caeea693#diff-a751f1cf186b5c6d32356c83bd77e30a

**Comment by vitor-gyant** [comment]
@davidmorgan Is there any workaround for this issue ? I've a model with several Color variables that I'd like to parse from json. thanks.

**Comment by davidmorgan** [comment]
Not that I know of I'm afraid; you'll need to create your own `Color` class outside of Flutter...

**Comment by Tzxhy** [comment]
For now, we can mock a `Color` implemention out of the flutter. In need-generate file, just import that mock file. works for me for now。

**Comment by rrousselGit** [comment]
The related issue on dart SDK has been closed (https://github.com/dart-lang/build/issues/733).

I haven't tested it, but it may be possible to do workarounds

**Comment by davidmorgan** [comment]
Looks like `package:build` handles this case now--please re-open if you still see issues. Thanks!
