### ISSUE TITLE
Include class name in "Must not be null" error message

### ISSUE THREAD

**Issue by ddrone** [google/built_value.dart#301]
Just finished figuring out a confusing error in a following situation: one file, two build_value classes (say A and B), both have a non-nullable field with the same name (say "field"). When B constructed without "field" here is an error message built_value would return:

> Invalid argument(s) (field): Must not be null

I think it would be better to have a more descriptive error message mentioning class name, like "Invalid argument(s) (field) while constructing B: Must not be null"

**Comment by davidmorgan** [comment]
Sounds reasonable. We're already using the class name for toString, so it won't increase code size; we should be careful to reuse the class name via a shared string so that it doesn't end up compiled into the code twice.
