### ISSUE TITLE
Auto-generated web forms via angular integration 

### ISSUE THREAD

**Issue by adamlofts** [google/built_value.dart#303]
This is a crazy idea so feel free to close if it doesn't fit the project direction.

In our web app we use AngularDart with a combination of the material components and custom components to give end users a really good experience. It all works really well and we are very happy.

We also have a second requirement for some back office functionality where we don't care so much about the quality of the experience. It will only be used a few times a year and by its nature there will be lots of fiddly options. The priority is to get the UI up and running fast and in a way which works well enough for experts to use it.

The process of writing this backoffice UI is quite mechanical. For example lets say we have a `BuiltValue` like this:

```dart
class Model implements Built {
    String name;
    DateTime start;
    DateTime end;
    ModelEnum modelType;
    bool isAwesome;
}
```

This maps directly to a web form which looks something like:

```
Name:    [           ]
Start:   [ 1 Jan ]
End:     [ 1 Jan ]
[ Type  ▼ ]
[x]      Is Awesome
```

The component itself usually has an interface like:

```dart
class ModelComponent {
    @Input()
    Model model;

    @Output()
    Stream<Model> changed;
}
```

It would be awesome if I could ask `built_value` to generate this component for me. For a real world example of this the Django framework automatically generates an admin interface in a similar way (https://docs.djangoproject.com/en/2.0/ref/contrib/admin/)

**Comment by davidmorgan** [comment]
I'm generally in favour of more angular integration--as long as it doesn't slow down anything else.

The big question seems to be whether you want your generation to happen at compile time ... or whether you would want the tool to dump your skeleton UI code so that you can go on to modify it.

If the former, the right mechanism is the one built_value_generator already uses.

If the latter, then we need something new. Maybe a layer to execute templates based on built_value structures? That would be kinda cool.

This doesn't seem particularly high priority, but it's good to kick ideas around.

**Comment by adamlofts** [comment]
I was thinking it could all be generated in the build step. In the spirit of kicking ideas around -

```dart
@BuiltValue(component: DefaultComponent)
class Value implements Built {
    // Ask built value to generate an angluar component for this value type. The generated component 
    // will be a subclass of the component specified in the built value annotation. This would allow the
    // user to customize the component template & behaviour.
    ValueComponent get component => _$valueComponent;

    // A string field would default to a StringComponent which renders as a 
    // MaterialInputComponent. You could change the component like below.
    @BuiltValueField(component: StringComponent)
    String get s;

    DateTime get dt;
}
```

Could generate code like:

```dart
@Component(
    selector: "value-component",
    template: '''
<string-component
    (change)="change()"
    [(ngModel)]="s"></string-component>
<date-time-component
    (change)="change()"
    [(ngModel)]="dt"></date-time-component>
'''
    directives: const [StringComponent]
)
class $ValueComponent extends DefaultComponent {
    String s;
    DateTime dt;

    @Input()
    set value(Value v) {
        s = v.s;
        dt = v.dt;
    }

    void change() {
        ValueBuilder b = new ValueBuilder()
            ..s = s
            ..dt = dt;
        changeStream.add(b.build());
    }
}
```

So how is the template generated? 
 1. It could just be the concatenation of the component tags.
 1. You could require that the component has a static field or method which returns the template code at build time.

**Comment by davidmorgan** [comment]
This seems unlikely to happen at this point.
