### ISSUE TITLE
Support JSON serialization of Sets

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#330]
Seems to be straight-forward to serialize sets to JSON arrays.

**Comment by zoechi** [comment]
I thought this was working for the built-in serializer previously but just not for standard JSON serialization.
Now I also get an exception for built-in serialization when serializing `BuiltSet<Foo>`

      error: Bad state: No builder for BuiltSet<GroupMessageReadBy>.

**Comment by davidmorgan** [comment]
For the default serializer you may need to register the builders yourself if the codegen is not smart enough to do it; see #124. You can do this using the `addBuilderFactory` method, something like:

`var serializersWithBuilder = (serializers.toBuilder()..addBuilderFactory(
    const FullType(BuiltSet, const[const FullType(GroupMessageReadBy)]))
    .build()`

For `StandardJsonPlugin`, the suggestion is to just serialize them the same as BuiltList? That seems reasonable.
