### ISSUE TITLE
Incremental builds (and watcher) do not work for me in version 4.6.1

### ISSUE THREAD

**Issue by vadimtsushko** [google/built_value.dart#331]
Hi.
Recently I've upgraded my project from very old version of built_value. By most part upgrade went without troubles. New features are great. (I've tried combination of polymorphic collections and Standard JSON serialization in built_highcharts and it works great)
There is one problem though. When I run `build.dart` and `watch.dart` scripts I get warning like this
```
[WARNING] BuildScriptUpdates: model|../../../../C:/project/infovizion/sense/model/tool/watch_model.dart was not found in the asset graph, incremental builds will not work.
```
After that `build.dart` run and generate files as expected
But `watch.dart` run first cycle only. On any change in source file I get message 

```
[SEVERE] Watch: Terminating builds due to build script update
```
and after that script terminates. So effectively `watch` works in `build` mode now.

I've cloned current (4.6.1.) version of bild_value.dart and tried to the same on `end_to_end` project and got the same result.
Here is full output from watch.dart in `end_to_end` project 

```
c:\project\_backup\built_value.dart\end_to_end_test>dart tool\watch.dart
[INFO] Watch: Setting up file watchers...
[INFO] Watch: Setting up file watchers completed, took 38ms
[INFO] BuildDefinition: Initializing inputs
[INFO] BuildDefinition: Building new asset graph...
[INFO] BuildDefinition: Building new asset graph completed, took 55ms
[INFO] BuildDefinition: Recording initial build script state...
[WARNING] BuildScriptUpdates: end_to_end_test|../../../../c:/project/_backup/built_value.dart/end_to_end_test/tool/watch.dart was not found in the asset graph, incremental builds will not work.
 This probably means you don't have your dependencies specified fully in your pubspec.yaml.
[INFO] BuildDefinition: Recording initial build script state completed, took 411ms
[INFO] Build: Checking for stale files...
[INFO] Build: Deleting 10 declared outputs which already existed on disk.
[INFO] Build: Checking for stale files completed, took 19ms
[INFO] Build: Running build...
[INFO] Build: Running build completed, took 7342ms
[INFO] Build: Caching finalized dependency graph...
[INFO] Build: Caching finalized dependency graph completed, took 65ms
[INFO] Build: Succeeded after 7430ms with 10 outputs


[INFO] Watch: Checking build script for updates...
[INFO] BuildScriptUpdates: Unable to read asset end_to_end_test|../../../../c:/project/_backup/built_value.dart/end_to_end_test/tool/watch.dart, falling back on full rebuild.
[SEVERE] Watch: Terminating builds due to build script update
[INFO] Watch: Checking build script for updates completed, took 562ms
[INFO] Watch: Terminating. No further builds will be scheduled
[INFO] Build: Updating asset graph...
[INFO] Build: Updating asset graph completed, took 13ms
[INFO] Build: Running build...
[INFO] Build: Running build completed, took 468ms
[INFO] Build: Caching finalized dependency graph...
[INFO] Build: Caching finalized dependency graph completed, took 23ms
[INFO] Build: Succeeded after 512ms with 2 outputs


[INFO] Watch: Builds finished. Safe to exit
```

I'm on Windows 10, Dart VM version: 1.24.3 (Wed Dec 13 18:05:29 2017) on "windows_x64"

**Comment by davidmorgan** [comment]
Thanks for reporting.

These work for me on Linux. I'll open an issue over at package:build, since it's presumably something about how we're using that.

**Comment by davidmorgan** [comment]
Looks like it's a package:build bug. Fix should be to update package:build ... which will actually get rid of the "build" and "watch" scripts altogether. I already have an issue to do that:

https://github.com/google/built_value.dart/issues/311 

I'll aim to take a look when the current batch of PRs have landed. (Next week, at best guess).

Thanks!

**Comment by davidmorgan** [comment]
@vadimtsushko

Version 5.2.0 now uses the latest build_runner; this ought to work fully on windows. If not, since we're now on the latest version, we can file an issue.

You'll need to use the latest SDK (2.0.0-dev) to use it, though.

Please let me know if this helps. Thanks!

**Comment by vadimtsushko** [comment]
Ironically I've switched to Ubuntu on my new laptop :) But anyway I have plenty of Windows server systems   so I'll try it there soon.
Right now I cloned build_value.dart into new directory and executing `pub get` `pub upgrade` on subprojects `build_value_generator` and `example` give me and error

```
Resolving dependencies... (1.6s)
Package built_value has no versions that match >=5.2.0 <6.0.0 derived from:
- example depends on version ^5.2.0
```
```
dart --version 
Dart VM version: 2.0.0-dev.23.0 (Unknown timestamp) on "linux_x64"
```

**Comment by davidmorgan** [comment]
Thanks.

Hmm, "pub upgrade" works for me:

```
pub version
Pub 2.0.0-dev.23.0
```

It needs to use the v2 dependency override, though. This should work by default. You haven't set env variable `PUB_ALLOW_PRERELEASE_SDK` to false, by any chance?

I recommend https://pub.dartlang.org/packages/pub_mediator which will figure out a much better error message for the dependency failure.

**Comment by vadimtsushko** [comment]
Weird stuff. I did not set PUB_ALLOW_PRERELEASE_SDK
Just activated pub_mediator an try it on sample project
$mediator breaks with error
```
vts@vts-ubuntu2:~/project/github/built_value.dart/example$ mediator
Unhandled exception:
FormatException: Unexpected character (at character 1)
Not Found
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/dart:convert/convert_patch.dart:1362)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/dart:convert/convert_patch.dart:1258)
#2      _ChunkedJsonParser.parse (dart:convert-patch/dart:convert/convert_patch.dart:926)
#3      _parseJson (dart:convert-patch/dart:convert/convert_patch.dart:29)
#4      JsonDecoder.convert (dart:convert/json.dart:511)
#5      JsonCodec.decode (dart:convert/json.dart:138)
#6      resolvePubspec (package:pub_mediator/src/diagnose.dart:149)
<asynchronous suspension>
#7      diagnoseConflicts.<anonymous closure> (package:pub_mediator/src/diagnose.dart:44)
#8      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#9      diagnoseConflicts (package:pub_mediator/src/diagnose.dart:39)
#10     main (file:///home/vts/.pub-cache/hosted/http%2558%2547%2547pub.infovizion.ru%25588111/pub_mediator-1.0.1/bin/main.dart:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

**Comment by vadimtsushko** [comment]
Well, looking at the stacktrace, I think mediator have some troubles with private pub servers.
Maybe original problem too related to the fact that we recently started to use private pub server.
I'll give it a try

**Comment by davidmorgan** [comment]
Maybe the packages haven't replicated to your private pub serve yet?

**Comment by vadimtsushko** [comment]
Most probably. First of all i will try to switch to general pub server tomorrow.

**Comment by vadimtsushko** [comment]
So I've found and deleted global variable PUB_HOSTED_URL from my environment and all works just fine now. `pub run build_runner` output is pretty nice. So it's a definitely a problem with a private pub hosting. I'll probably try to switch to a private hosting just for our private repos now.

**Comment by davidmorgan** [comment]
SG. Looks like this issue can be closed, then.

Thanks for reporting! It's very helpful to have feedback from use on other platforms.
