### ISSUE TITLE
Non-instantiable Builder interface ignores nestedBuilders:false

### ISSUE THREAD

**Issue by joshua-i** [google/built_value.dart#349]
If I have a class like
```dart
@BuiltValue(instantiable: false, nestedBuilders: false)
abstract class Test implements Built<Test, TestBuilder> {
  ListBuilder<String> get list;
}
```
the following (incorrect) Builder interface will be generated:
```dart
abstract class TestBuilder implements Builder<Test, TestBuilder> {
  ListBuilder<String> get list;
  set list(ListBuilder<String> list);
}
```
The same thing happens for nested Builts. It should respect the nestedBuilters setting. Otherwise, subclasses that want nestedBuilders:false do not override the TestBuilder interface and fail to compile.

**Comment by davidmorgan** [comment]
Thanks, I'll take a look.

It should be possible to work around this for now by writing the builder by hand, i.e. just write `TestBuilder` yourself with the correct interface.

**Comment by davidmorgan** [comment]
Note to self: fix for this exposes an issue with serialization code for built collections when `@nestedBuilders: false`. Fix that too...

**Comment by jaripekkala** [comment]
Hi @davidmorgan,

I can try help fix this issue but not sure what that note is about. Do you still recall, what it was about?

**Comment by davidmorgan** [comment]
It's probably not a good time to make changes to built_value, as it's in the middle of the migration to null safe code :) so it's pretty hard to actually build it right now. I suggest checking back in a couple of months if you're still interested :)
