### ISSUE TITLE
Correct polymorphism examples

### ISSUE THREAD

**Issue by davidmorgan** [google/built_value.dart#352]
The base class should be parameterized <V, B>. This fixes the dart2js issue.

**Comment by davidmarne-wf** [comment]
Could you explain this in a little more detail? Is this just a pattern consumers would need to implement, or would it require a change to the generator?

**Comment by davidmorgan** [comment]
I think it'll need change to the generation. The general pattern is something like this:

```
abstract class Animal<V extends Animal, B extends AnimalBuilder> implements Built<V, B> {
}

abstract class AnimalBuilder<V extends Animal, B extends AnimalBuilder> implements Builder<V, B> {
}

abstract class Cat implements Built<Cat, CatBuilder>, Animal<Cat, CatBuilder> {
}

abstract class CatBuilder implements Builder<Cat, CatBuilder>, AnimalBuilder<Cat, CatBuilder> {
}
```

**Comment by sroddy** [comment]
@davidmorgan the problem of this approach right now is that the analyzer complains about the fact that Animal and AnimalBuilder `Type parameter bound types must be instantiated`.

Defining them like that it's not a major issue:
```
abstract class Animal<V extends Animal<V, B>, B extends AnimalBuilder<V, B>> implements Built<V, B> {}

abstract class AnimalBuilder<V extends Animal<V, B>, B extends AnimalBuilder<V, B>> implements Builder<V, B> {}
```

But the problems start to arise when you actually want to use `Animal` somewhere, as you would be forced to specify the bound types on all the classes/methods/etc, and you won't be able to specify a general upper-bound for either Animal and AnimalBuilder without requiring all the classes/methods/etc to be generic on that types. This is very tedious especially because the builders introduce twice the boilerplate for that to work.

**Comment by davidmorgan** [comment]
Thanks @sroddy. Yes, that looks right.

I suspect wiring things up correctly is currently more trouble than it's worth, and people will want to use the workaround that we ended up suggesting last time for dart2js: to just drop the `Built` interfaces from the base type and builder.

This came up because in Dart 2, the restriction from dart2js will extend to DDC and the VM, too. So you'll have to choose between the workaround and the correct method, everywhere.

There was a suggestion that Dart might end up smarter about inferring generics, so you don't have to write them everywhere. But this is a long term hope rather than a plan.

**Comment by CosmicPangolin** [comment]
Hey @davidmorgan, is there any more work towards this?  My project that relies heavily on built_value is starting to reach some scale (different repos for different platforms that all rely on the same set of models), and altering the models for the dart2js libraries seems really messy and prone to failure...

I guess a dart runtime on gcp would be a kinda nice alternative...   >.<

**Comment by Lootwig** [comment]
With dart SDK version 2.4.0, the polymorphism example does not compile (type arguments are different, fixed when removing the base class `Built` interface as mentioned).
Is there a specific dart version where the example _does_ work as intended, or what is the motivation for keeping the currently non-functional example live?

**Comment by davidmorgan** [comment]
Just lack of time to clean it up--since nobody has been complaining about it, it hasn't been high priority.

**Comment by igoriuz** [comment]
Any updates on this?

**Comment by davidmorgan** [comment]
No, sorry--this hasn't been high priority.
