### ISSUE TITLE
Can't run "flutter run" and "flutter packages pub run build_runner watch" simultaneously

### ISSUE THREAD

**Issue by maksimr** [google/built_value.dart#361]
Hi,

I'm trying to use "built_value" for flutter project but it doesn't work as expected.
First of all, I could not run `flutter run` and `flutter packages pub run build_runner watch/build` simultaneously.

If run "build_runner watch" first and try run "flutter run":

> Waiting for another flutter command to release the startup lock...

If run "flutter run" first and try run "build_runner build":

> Stack dump aborted because no current Dart thread.
> pub finished with exit code -6

And my workflow now:
1. Stop flutter
2. run "flutter packages pub run build_runner build"
3. Run flutter

This is very unpleasant :(

## Additional information:
```
Flutter 0.1.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f914e701c5 (9 days ago) • 2018-02-19 21:12:17 +0000
Engine • revision 13cf22c284
Tools • Dart 2.0.0-dev.27.0-flutter-0d5cf900b0

Dart VM version: 2.0.0-dev.15.0 (Tue Jan 2 10:39:27 2018 +0100) on "macos_x64"

built_collection: '>=2.0.0 <4.0.0'
built_value: ^5.2.1
build_runner: ^0.7.9
built_value_generator: ^5.2.1
```

## STR:
- `flutter create foo`
- Add [built_value to "pubspec.yml"](https://github.com/google/built_value.dart/blob/master/example/pubspec.yaml)
- `flutter run`
- `flutter packages pub run build_runner build`

Thanks!

**Comment by maksimr** [comment]
Ok, I have found a solution/workaround.

If set `FLUTTER_ROOT` then I could run `flutter run` and `pub run build_runner watch`
but it would be nice to see this somewhere in the documentation

Thanks

**Comment by davidmorgan** [comment]
Thanks for the detailed info. I'll keep this issue open to make sure I document it / do something.

I'm not too familiar with Flutter, although I intend to be at some point :) ... I'll ask someone who is.

**Comment by davidmorgan** [comment]
I've added the command to README.md, plus an alternative: if you move your built_value classes into non-flutter packages, they can use watchers without flutter caring. This is probably the best we can do until Flutter supports a build system.
