### ISSUE TITLE
Add a flutter example

### ISSUE THREAD

**Issue by davidmorgan** [google/built_value.dart#363]
We should have an example that uses flutter.

**Comment by zoechi** [comment]
Or perhaps check if https://github.com/brianegan/flutter_architecture_samples/tree/master/example/built_redux fits your quality requirements and if not help to fix it and link to them?
I think these examples are quite popular.

**Comment by davidmorgan** [comment]
That's a handy link to have, thanks.

I'd like to write a new example, though--a large part so I actually get hands on experience using flutter with built_value myself :)

**Comment by zoechi** [comment]
👍  More examples are usually a good thing anyway

**Comment by davidmorgan** [comment]
I think the flutter example linked to is better than anything I'm likely to come up with :) I'll close this for now. Thanks.
