### ISSUE TITLE
@memoized should correctly handle nulls

### ISSUE THREAD

**Issue by dave26199** [google/built_value.dart#364]
Currently, `@memoized` getters are allowed to return null, but this value is not cached; the getter is called repeatedly.

Instead, `null` should be disallowed by default. If a getter is marked `@nullable` then nulls should be allowed, and cached.

**Comment by stevenspiel** [comment]
was this closed because it was implemented?

**Comment by davidmorgan** [comment]
Sadly not--I've been cleaning up issues that are unlikely to be implemented.

On second thoughts though this one is worth keeping around :)

It likely makes sense to have another look once `built_value` has been updated for NNBD, since that will affect null handling.

**Comment by davidmorgan** [comment]
We got this for free with NNBD :)
