### ISSUE TITLE
Adding a mixin to a Built Value doesn't properly implement its inherited interface

### ISSUE THREAD

**Issue by sroddy** [google/built_value.dart#366]
In particular, the `covariant` keyword is not properly added to the generated `replace` method

**Comment by davidmorgan** [comment]
Thanks for reporting--would you mind giving a bit more detail please? I can't follow quite which replace method you're referring to and why it needs to be `covariant`. Thanks :)

**Comment by davidmorgan** [comment]
@sroddy Any change of some detail on the issue, please? Thanks.

**Comment by davidmorgan** [comment]
I'm going to close this since I don't have enough information, please re-open with more details if it's still an issue. Thanks!
