### ISSUE TITLE
After upgrading dependencies, inherited/mixed typedef properties are no longer working  

### ISSUE THREAD

**Issue by sroddy** [google/built_value.dart#367]
I needed to rollback, so I can't give a more detailed info, but the problem was the following:

```
typedef String ATypedef(String a);

abstract class WithTypedef {
  ATypedef get aVar;
}

abstract class BuiltWithTypeDef extends Object with WithTypedef implements Built<BuiltWithTypeDef, BuiltWithTypeDefBuilder> {
}
```

The generated code after upgrading the dependencies (not built_value_generator itself) contained weird output (something with `->` symbol) instead of the `ATypedef` type).
However the type kept getting outputted correctly if the class inheriting the mixing was also redefining the variable itself.

Sorry if I was not more specific. If you are not able to understand the problem and/or need more detail I will try to reproduce it in a proper way.

**Comment by davidmorgan** [comment]
I've seen an error along those lines before, so I think I know what to look for. Thanks for reporting, I'll take a look.

**Comment by davidmorgan** [comment]
Turns out we don't need the name of the typedef. This still breaks if you try to have a serializable field with a typedef, but that never worked anyway--so my PR makes that explicitly forbidden.
