### ISSUE TITLE
Standard JSON Serializer Plugin Question

### ISSUE THREAD

**Issue by ArneSaknussemm89** [google/built_value.dart#389]
So, I've been trying to get the Firebase Database/Cloud Firestore to work with an app I'm using. I used the `StandardJsonPlugin` since it says it will serialize the classes using the standard JSON format. Only I'm not getting back `Maps` from the serializer. I'm getting `_InternalLinkedHashMap`s and I can't seem to figure out why the StandardJsonPlugin doesn't actually return `Map<String, dynamic>` values since that is actually the "default" JSON representation in Dart.

(At least to me it seems like returning `Map<String, dynamic>` values would be the "standard" JSON object you would expect to have). 

Am I just SOL and will need to write my own serializer to get the kind of JSON objects that the FlutterFire plugins seem to want? (Looks like both Cloud Firestore and Firebase Database, when setting data, expect `Map<String, dynamic>` values to get passed.

**Comment by dave26199** [comment]
This looks like an oversight, but easy to fix. I'll take a look ASAP. Thanks!

In the meantime you can take the map and convert it: just do

```
new Map<String, Object>.from(...)
```

on the map you get back from the serializer.

**Comment by zoechi** [comment]
I'd say this is working as expected.

```dart
void main() {
  print({}.runtimeType);
  print({} is Map);
}
```
```
/Users/zoechi/flutter/flutter/bin/cache/dart-sdk/bin/dart --checked --pause_isolates_on_start --enable-vm-service:51136 /Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_flutter/tool/x.dart
Observatory listening on http://127.0.0.1:51136/

_InternalLinkedHashMap
true

Process finished with exit code 0
```

**Comment by davidmorgan** [comment]
The problem is that it returns a `Map<Object, Object>` instead of a `Map<String, Object>`. Dart 2 doesn't like it :)
