### ISSUE TITLE
Intellij analyzer support for named argument constructor

### ISSUE THREAD

**Issue by joshua-i** [google/built_value.dart#394]
On our team, we generally prefer the named argument constructor to the Builder constructor. It would be great if there was an option to generate that constructor instead (and ideally later update it to reflect the current field set), even as coarsely as at the analysis_options.yaml level.

**Comment by davidmorgan** [comment]
Thanks! This a good thing to support somehow.

For the first iteration I focused on reporting errors; there are also cases, like the one you mention, where there are choices to make. For these I'd like the analyzer to offer to refactor between them, like it does for => and () {}. Options for the constructor might be a good first one to tackle.

I'm not sure about changing the default. The plugin could _maybe_ infer a good default by looking at nearby code. Configuring in the yaml file is probably something I'd like to avoid--it'll work for external projects but not well in google3.
