### ISSUE TITLE
@JsonKey(name) equivalent?

### ISSUE THREAD

**Issue by neckaros** [google/built_value.dart#396]
Hello, 
i tried to find documentation on serialization but failed to.
Is there a way to set custom key for serialization like 
```
@JsonKey(name: '_id')
String get id;
```
used by json_annotation in the flutter official doc?

**Comment by dave26199** [comment]
Yes, it's

```
@BuiltValueField(wireName: '_js')
String get id;

```

**Comment by neckaros** [comment]
Thanks @dave26199 for the reply and the great lib 😀

BTW is there a doc for those annotations and for serialization?

**Comment by davidmorgan** [comment]
You're welcome :)

The annotations are documented in the dartdoc:

https://pub.dartlang.org/documentation/built_value/5.4.3/built_value/built_value-library.html

The example code is probably the best place to see all the things you can do:

https://github.com/google/built_value.dart/blob/master/example/lib/example.dart
https://github.com/google/built_value.dart/blob/master/example/lib/values.dart

If there's anything that's not clear, please ask! :)

**Comment by neckaros** [comment]
@BuiltValueField(wireName: '_js') + dartdoc very helpful 👍
