### ISSUE TITLE
Cannot set newBuiltValueToStringHelper?

### ISSUE THREAD

**Issue by kentcb** [google/built_value.dart#397]
I was trying to find a way to have my built values format as a single line, since I'm outputting application state on every redux action, so it would be more useful that way.

I came across `FlatBuiltValueToStringHelper` and some docs on assigning `newBuiltValueToStringHelper`, but the compiler won't let me do so:

```dart
import 'package:built_value/built_value.dart';

newBuiltValueToStringHelper = (String className) => new FlatBuiltValueToStringHelper(className);
```

This gives me:

```
Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
```

Any ideas what I'm doing wrong?

**Comment by zoechi** [comment]
What's the `=` for in `newBuiltValueToStringHelper = (String ...`?
This declares a variable (with a missing `var`, `final`, `const` or type) while it looks like you want a function.

**Comment by kentcb** [comment]
@zoechi see the example [here](https://medium.com/dartlang/moving-fast-with-dart-immutable-values-1e717925fafb).

**Comment by davidmorgan** [comment]
You need to do this in a method context :)

```
void main() {
  newBuiltValueToStringHelper = (String className) => new FlatBuiltValueToStringHelper(className);
}
```

**Comment by kentcb** [comment]
omg _/facepalm_

Thanks @davidmorgan, I'm still very noob at Dart.
