### ISSUE TITLE
Exclude fields from serialization

### ISSUE THREAD

**Issue by kostaa** [google/built_value.dart#399]
It would be great to have an annotation (say @transient) that would allow field exclusion from serialization.

**Comment by dave26199** [comment]
We do :) it's

```
@BuiltValueField(serialize: false)
```

...you'll also need to either mark the field nullable or set a default for it, so that instances can be created without a value.

**Comment by kostaa** [comment]
I was looking for something like `transient` around the `nullable` in the source code ... but did not notice that it was just 10 lines below. Doh! 

Thanks!
