### ISSUE TITLE
Generate crazy efficient hashcode

### ISSUE THREAD

**Issue by kevmoo** [google/built_value.dart#40]
One-property class got

``` dart
  int get hashCode {
    return hashObjects([packageName]);
  }
```

It would be _much_ better if this just returned `packageName.hashCode` – no allocations, iteration, etc.

**Comment by davidmorgan** [comment]
Thanks. I think the right thing to do is to pull out the internals of the hashing from quiver -- that way it's never necessary to allocate a list or to iterate.

A quick benchmark of two-element hashing on the VM shows approx. three times speedup from this change. (30M hashes per second --> 100M hashes per second, if I measured correctly.)

I'll send a PR.

**Comment by davidmorgan** [comment]
https://github.com/google/built_value.dart/pull/49
