### ISSUE TITLE
Using built_value for entities with identity

### ISSUE THREAD

**Issue by ronlobo** [google/built_value.dart#401]
Hey @davidmorgan,

First a big thanks for this package, it's great!

I'm currently exploring this package in the context of domain driven design. One of the challenges that I'm facing is managing identity for entities. The identity is provided by the persistence mechanism, the auto increment id of a mysql database table. This is not the preferred identity mechanism in DDD as it should be coming from the domain (e.g. uuid4), but that's how it is and it can't change.
To solve this challenge I'm trying to implement an abstract class identifiable which should be implemented by the entities to provide an identity value object.
The problem I'm running into is that the generated classes (_$Identity) by built value override the hashCode and == operator of abstract Identity class which implements Built. I basically want to achieve that when comparing two entities, they should be treated as equal when their identity value matches.

Do you have any advise of how this problem best using this package?

**Comment by dave26199** [comment]
Glad you like it :)

You can mark all the other fields `BuiltValueField(compare: false)`. I realize this is a little annoying to do; it would make sense to add a way to flip the default for the class to false, so you only have to tag the id field `comparable: true`.

**Comment by ronlobo** [comment]
Thanks for the quick response and the tip, I'll try it out.

**Comment by ronlobo** [comment]
Ok, after checking out the polymorphism and interface examples and playing around a bit I came up with:

[Identifiable Domain Entity Example](https://gist.github.com/ronlobo/5441b6ea09dbd65feb82eced91ebd9f6)

That will do the trick for me :)

**Comment by dave26199** [comment]
Great :) thanks!

**Comment by Solido** [comment]
I'd like to reopen this case or at least discuss it. 

I'm interested in the same pattern but would like to go with the original idea of marking the id field with an annotation.

Thank you !
