### ISSUE TITLE
Question: Unhandled exception error after `flutter upgrade`

### ISSUE THREAD

**Issue by nodinosaur** [google/built_value.dart#403]
After upgrading Flutter I now get the following error when running `dart tool/build.dart` 

```
Unhandled exception:
'file:///Users/home/Flutter/myapp/tool/build.dart': malformed type: line 9 pos 9: cannot resolve class 'BuildAction' from '::'
    new BuildAction(
        ^

#0      _TypeError._throwNew (dart:core-patch/dart:core/errors_patch.dart:84)
#1      main (file:///Users/home/Flutter/myapp/tool/build.dart:9:9)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Process finished with exit code 255
```

To test:
* Created a new flutter project => `flutter create myapp`
* Add the abstract classes that you which use for json serialisation
* Add the `serializers.dart` linking the classnames you wish to generate 
* Add the `tool/build.dart`
* run => `dart tool/build.dart`

My installation is:
```
flutter --version
Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b397406561 (3 weeks ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357
```

Any idea why this is failing?

**Comment by dave26199** [comment]
You don't need a `build.dart` any more; `build_runner` knows how to run the generator without it. See `README.md`.

(Please excuse brevity, posting from phone).

**Comment by dave26199** [comment]
build_runner has a command you can give it where it outputs a dart script to run, maybe that helps?

**Comment by dave26199** [comment]
(I'm currently on vacation so I won't have access to a computer until next week. But I'm planning on writing a flutter example soon!)

**Comment by zoechi** [comment]
I have my model classes in another package that doesn't depend on Flutter and I add it to my flutter project as path dependency. In this package I can run `pub run build_runner build`.

**Comment by ArneSaknussemm89** [comment]
Maybe try running:

`flutter packages pub run build_runner build`

**Comment by nodinosaur** [comment]
Thans @ArneSaknussemm89 that works 👍

**Comment by davidmorgan** [comment]
I've added the command to README.me; closing this issue. Thanks!
