### ISSUE TITLE
Using built_value with built_collection serialize list to json

### ISSUE THREAD

**Issue by charafau** [google/built_value.dart#404]
hello, I'm using built_value with built_collection for immutable structures and json serialization for few weeks and I really like it but I've run into one problem - I want to serialize `BuiltList<MyClass>` into json but I have trouble with it (it's not json output). This is how I'm doing it:

```dart
    final todo = new Todo((b) => b..title = 'My todo');

    final BuiltList<Todo> todos = new BuiltList<Todo>([todo]);

    var jString = json.encode(serializers.serialize(todos));

    print(jString);

    //wrong output:
    // {"$":"list","":{"$":"Todo","title":"My todo"}}
```

here's my sample project (WIP but tests work) where I wanted to do something like this:

https://github.com/charafau/todo_list/blob/master/test/todo_serialize_test.dart#L29

**Comment by dave26199** [comment]
By default `serializers.serialize` can serialize any serializable type. For it to be possible to deserialize again it needs to record what the type was; that's why you see `"$":"list"` in the output.

If you want to avoid having this in the output then you'll need to tell it that you already know the type. For types that you define yourself you can use the `serislizeWith` method as in the example:

https://github.com/google/built_value.dart/blob/master/example/lib/example.dart#L119

For a `BuiltList` you'll need to instead pass a `FullType`:

https://github.com/google/built_value.dart/blob/master/built_value/test/built_list_serializer_test.dart#L40

Apologies for brevity, posting from phone :)

**Comment by charafau** [comment]
Thank you Dave, that worked!

Just for other people hitting the problem here's right solution:

```dart
final todo = new Todo((b) => b..title = 'My todo');

final BuiltList<Todo> todos = new BuiltList<Todo>([todo]);

final specifiedType = const FullType(BuiltList, const [const FullType(Todo)]);
var jString = serializers.serialize(todos, specifiedType: specifiedType);

print(jString);

//output:
// [{title: My todo}]
```

**Comment by charafau** [comment]
edit:

for my other project I needed to add this to my serializers:

```dart
final Serializers serializers = (_$serializers.toBuilder()
      ..addBuilderFactory(  // add this builder factory
          const FullType(BuiltList, const [const FullType(Todo)]),
          () => new ListBuilder<Todo>())
      ..addPlugin(new StandardJsonPlugin()))
    .build();
```
otherwise I get `Bad state: No builder for BuiltList<dynamic><Todo>.` error when trying to serialize.

This is because for first project that factory is being generated (I have other class which contains `BuiltList<Todo>` inside of it) but if you dont that factory is simply not being generated. 

Maybe there should be some variable which would say 'always generate collection factories' ?

**Comment by rogerfsgDC** [comment]
Man this library does work at all!

final specifiedType = const FullType(Built, const [const FullType(Member)]);
    var jString = serializers.serialize(member, specifiedType: specifiedType);

**Comment by athornz** [comment]
@dave26199 is there a way to opt out of this behaviour without knowing the full type?

I have an object I'm trying to serialize that has a dynamic field. I don't need to be able to deserialize this so I'm looking for a way to be able to serialize it without built_value adding the extra information in.

**Comment by davidmorgan** [comment]
If you don't need the field, you can mark it `@BuiltValueField(serialize: false)` and it won't be serialized. Does that help? Thanks.

**Comment by hasan314** [comment]
I am facing a problem while deserializing a response from a REST Api. 

Here is what I am trying to do:

I have an ApiResponse class which returns a standard response object from my Api and one of the parameters of this class is a generic result type which varies based on the endpoint I call. 

The model class code looks like this: 

`abstract class ApiResponse<T extends Object>
    implements Built<ApiResponse<T>, ApiResponseBuilder<T>> {
  static Serializer<ApiResponse> get serializer => _$apiResponseSerializer;

  T get Result;
  bool get Success;
  BuiltList<ApiError> get Errors;
  BuiltList<String> get Messages;
  ApiResultInfo get ResultInfo;

  ApiResponse._();

  factory ApiResponse([updates(ApiResponseBuilder<T> b)]) = _$ApiResponse<T>;
}

abstract class ApiError implements Built<ApiError, ApiErrorBuilder> {
  static Serializer<ApiError> get serializer => _$apiErrorSerializer;

  int get Code;
  String get Message;
  Object get ErrorData;

  ApiError._();

  factory ApiError([updates(ApiErrorBuilder b)]) = _$ApiError;
}

abstract class ApiResultInfo
    implements Built<ApiResultInfo, ApiResultInfoBuilder> {
  static Serializer<ApiResultInfo> get serializer => _$apiResultInfoSerializer;

  @nullable
  int get Page;

  @nullable
  int get PerPage;

  @nullable
  int get Count;

  @nullable
  int get TotalCount;

  ApiResultInfo._();

  factory ApiResultInfo([updates(ApiResultInfoBuilder b)]) = _$ApiResultInfo;
}
`

Here is my serializers class code:

`@SerializersFor(const [
  LoginResponse,
  ApiResultInfo,
  ApiError,
  ApiResponse
])

final Serializers serializers = (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();`


And then I am using these like this:

`http.Response res = await http.post(loginUrl, body: json.encode({
      "email": request.email,
      "password": request.password
    }), headers: {"Content-type": "application/json"});
	
	if (res.statusCode == 200) {

      final jsonBody = serializers.serialize(res.body);
      final response = serializers.deserialize(res.body);
      
      final ApiResponse<LoginResponse> response = json.decode(res.body);
	  
	  /* here I wish to process the response*/
	  
	  }`

I have been searching for the past two days but no fix so far, I have just started using flutter ( I am researching which framework to use for the Company's mobile app and I have been stuck at this point). Any help would be appreciated. 

Thanks

**Comment by hasan314** [comment]
@davidmorgan 

I am facing a problem while deserializing a response from a REST Api. 

Here is what I am trying to do:

I have an ApiResponse class which returns a standard response object from my Api and one of the parameters of this class is a generic result type which varies based on the endpoint I call. 

The model class code is below. 

` abstract class ApiResponse<T extends Object>
    implements Built<ApiResponse<T>, ApiResponseBuilder<T>> {
  static Serializer<ApiResponse> get serializer => _$apiResponseSerializer;

  T get Result;
  bool get Success;
  BuiltList<ApiError> get Errors;
  BuiltList<String> get Messages;
  ApiResultInfo get ResultInfo;

  ApiResponse._();

  factory ApiResponse([updates(ApiResponseBuilder<T> b)]) = _$ApiResponse<T>;
}

abstract class ApiError implements Built<ApiError, ApiErrorBuilder> {
  static Serializer<ApiError> get serializer => _$apiErrorSerializer;

  int get Code;
  String get Message;
  Object get ErrorData;

  ApiError._();

  factory ApiError([updates(ApiErrorBuilder b)]) = _$ApiError;
}

abstract class ApiResultInfo
    implements Built<ApiResultInfo, ApiResultInfoBuilder> {
  static Serializer<ApiResultInfo> get serializer => _$apiResultInfoSerializer;

  @nullable
  int get Page;

  @nullable
  int get PerPage;

  @nullable
  int get Count;

  @nullable
  int get TotalCount;

  ApiResultInfo._();

  factory ApiResultInfo([updates(ApiResultInfoBuilder b)]) = _$ApiResultInfo;
}
`

Here is my serializers class code:

`@SerializersFor(const [
  LoginResponse,
  ApiResultInfo,
  ApiError,
  ApiResponse
])

final Serializers serializers = (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();`


And then I am using these like this:

`http.Response res = await http.post(loginUrl, body: json.encode({
      "email": request.email,
      "password": request.password
    }), headers: {"Content-type": "application/json"});
	
	if (res.statusCode == 200) {

      final jsonBody = serializers.serialize(res.body);
      final response = serializers.deserialize(res.body);
      
      final ApiResponse<LoginResponse> response = json.decode(res.body);
	  
	  /* here I wish to process the response*/
	  
	  }`

I have been searching for the past two days but no fix so far, I have just started using flutter ( I am researching which framework to use for the Company's mobile app and I have been stuck at this point). Any help would be appreciated. 

Here is the output for flutter doctor

![image](https://user-images.githubusercontent.com/12174643/73084814-90f9f080-3ec5-11ea-9c3c-39bdccb23d4c.png)


Package versions I am using: 

![image](https://user-images.githubusercontent.com/12174643/73084912-b8e95400-3ec5-11ea-8568-6467df82be56.png)


Thanks
