### ISSUE TITLE
Question: How do you create a BuildList of dynamic types

### ISSUE THREAD

**Issue by dhillondeep** [google/built_value.dart#405]
I have a JSON that I want to deserialize but it contains a key that holds a list of `dynamic` types. So I want to create `BuildList<dynamic>` but, I am getting a compile time error.

```
Unhandled exception:
Bad state: No builder for BuiltList<dynamic>.
```

I have also tried using `BuildList<Object>` but, I am getting the same error:
```
Unhandled exception:
Bad state: No builder for BuiltList<Object>.
```
How do I set my class so that I can deserialize a list that contains values of different types?

**Comment by dave26199** [comment]
You'll need to use `Object` as `BuiltCollection` does not allow `dynamic`.

Instantiation with generics requires registering a factory for each set of generic parameters. If you had a serializable `built_value` class with a field containing a `BuiltList<Object>` then this would be done automatically in the generated code. If you don't, you'll need to add one by hand, like here:

https://github.com/google/built_value.dart/blob/master/built_value/test/built_list_serializer_test.dart#L70

This adds a builder for `int`, you need to do the same for `Object`.

Sorry for brevity--writing on my phone :)

**Comment by dhillondeep** [comment]
Thank you for your reply! I looked around and tried few things. I do have `BuiltList<Object>` in my built_value class but, it still does not generate it. I tried adding it myself: 
```dart
final Serializers serializers = (_$serializers.toBuilder()
  ..addBuilderFactory(
      const FullType(BuiltList, const [const FullType(Object)]),
          () => new ListBuilder<Object>()))
    .build();
```
This now adds `BuildList<Object>` but, it complains about the Object now:
```
Unhandled exception:
Bad state: No serializer for 'Object'.
```

Object is very broad as it could contain many types. How do I write a serializer for Object as a generic type?

Below is my code, let me know what I am doing wrong and how do I tackle this:
```dart
abstract class CoursePrerequisite implements Built<CoursePrerequisite, CoursePrerequisiteBuilder> {
  String get subject;
  @BuiltValueField(wireName: "catalog_number")
  String get catalogNumber;
  String get title;
  String get prerequisites;
  @BuiltValueField(wireName: "prerequisites_parsed")
  @nullable
  BuiltList<Object> get prerequisitesParsed;    // THIS ONE

  CoursePrerequisite._();

  static Serializer<CoursePrerequisite> get serializer => _$coursePrerequisiteSerializer;

  factory CoursePrerequisite([updates(CoursePrerequisiteBuilder b)]) = _$CoursePrerequisite;
}
```

**Comment by dave26199** [comment]
Hmm, does it contain JSON primitives? Then you want `BuiltList<JsonObject>`:

https://github.com/google/built_value.dart/blob/master/built_value/lib/json_object.dart

Which can represent all the primitive types.

**Comment by dhillondeep** [comment]
This does it for me. I did not not see `JsonObject` was available for this purpose. Thanks Dave!!

**Comment by jerryzhoujw** [comment]
To avoid copy past with error, I put the correct format here.
```dart
..addBuilderFactory(
     const FullType(BuiltList, const [const FullType(String)]),
     () => ListBuilder<String>(),
)
```
