### ISSUE TITLE
Website with docs

### ISSUE THREAD

**Issue by charafau** [google/built_value.dart#406]
Since more and more people start using dart and built_value it would be nice to create website with documentation (I saw people who considered it but because there are no docs didn't use it in the end).

I can help with creating some website, github pages might be good choice + some material design theme.

**Comment by charafau** [comment]
sorry for bothering, any news for this? Maybe it would be possible to go with newest material components from [material.io](https://material.io/collections/developer-tutorials/#web)

**Comment by charafau** [comment]
Got it, I will try to make some document then 👍

**Comment by davidmorgan** [comment]
Sounds good, thanks :)
