### ISSUE TITLE
Built value generated file fails dart checks for generics

### ISSUE THREAD

**Issue by jayantjpr** [google/built_value.dart#407]
Built value:
/// A three-way diff between the [base], the current/[yours] and [theirs] value.
abstract class Diff<T> {
  @nullable
  T get base;

  T get yours;

  @nullable
  T get theirs;

  /// Renders an instance of the type of value being diffed.
  String render(T value);
}

/// A [Diff] of list of [DateRanges]s.
abstract class DateRangesDiff
    implements
        Built<DateRangesDiff, DateRangesDiffBuilder>,
        Diff<BuiltList<DateRange>> {
  String render(BuiltList<DateRange> value) => value.toString();

  factory DateRangesDiff([updates(DateRangesDiffBuilder b)]) = _$DateRangesDiff;

  DateRangesDiff._();
}

Error:
  Undefined class 'T'. #undefined_class
  Invalid override. The type of '_$DateRangesDiff.base' ('() → dynamic') isn't a subtype of 'Diff<BuiltList<DateRange>>.base' ('() → BuiltList<DateRange>'). #strong_mode_invalid_method_override

It works if change the declaration to:
/// A [Diff] of list of [DateRanges]s.
abstract class DateRangesDiff<T extends BuiltList<DateRange>> extends Object
    with PrimitiveMergeStatusMixin<T>
    implements Built<DateRangesDiff<T>, DateRangesDiffBuilder<T>>, Diff<T> {
  String render(BuiltList<DateRange> value) => value.toString();

  factory DateRangesDiff([updates(DateRangesDiffBuilder<T> b)]) =
      _$DateRangesDiff<T>;

  DateRangesDiff._();
}

**Comment by dave26199** [comment]
I think this is the same as https://github.com/google/built_value.dart/issues/386 ... an alternative workaround should be to redeclare the getters in `DateRangesDiff`.

I'm currently on vacation, will take a look when I get back.

**Comment by kbrz** [comment]
I am facing the same issue.
@davidmorgan redeclaring getters doesn't work for me.

**Comment by dave26199** [comment]
@kbrz Could you post details of your code and the error, please? Thanks.

**Comment by kbrz** [comment]
@davidmorgan This is a sample project that reproduces this: https://github.com/kbrz/built_value_bug

There are two cases. First when I do not redeclare fields from `Machine` class, and second with those fields overridden. Dart analysis errors are respectively:

```
error: Undefined class 'I'. (undefined_class at [built_value_bug] lib/machine.g.dart:48)
error: Invalid override. The type of '_$MyMachine.input' ('() → dynamic') isn't a subtype of 'Machine<MyInput, MyOutput>.input' ('() → MyInput'). (strong_mode_invalid_method_override at [built_value_bug] lib/machine.g.dart:48)
error: Invalid override. The type of '_$MyMachine.output' ('() → dynamic') isn't a subtype of 'Machine<MyInput, MyOutput>.output' ('() → MyOutput'). (strong_mode_invalid_method_override at [built_value_bug] lib/machine.g.dart:50)
error: Undefined class 'O'. (undefined_class at [built_value_bug] lib/machine.g.dart:50)
error: Undefined class 'I'. (undefined_class at [built_value_bug] lib/machine.g.dart:105)
error: Invalid override. The type of 'MyMachineBuilder.input' ('() → dynamic') isn't a subtype of 'MachineBuilder<MyInput, MyOutput>.input' ('() → MyInput'). (strong_mode_invalid_method_override at [built_value_bug] lib/machine.g.dart:106)
error: Undefined class 'I'. (undefined_class at [built_value_bug] lib/machine.g.dart:106)
error: Undefined class 'I'. (undefined_class at [built_value_bug] lib/machine.g.dart:107)
error: Undefined class 'O'. (undefined_class at [built_value_bug] lib/machine.g.dart:109)
error: Invalid override. The type of 'MyMachineBuilder.output' ('() → dynamic') isn't a subtype of 'MachineBuilder<MyInput, MyOutput>.output' ('() → MyOutput'). (strong_mode_invalid_method_override at [built_value_bug] lib/machine.g.dart:110)
error: Undefined class 'O'. (undefined_class at [built_value_bug] lib/machine.g.dart:110)
error: Undefined class 'O'. (undefined_class at [built_value_bug] lib/machine.g.dart:111)
```

```
error: Invalid override. The type of 'MyMachineBuilder.input' ('() → MyInputBuilder') isn't a subtype of 'MachineBuilder<MyInput, MyOutput>.input' ('() → MyInput'). (strong_mode_invalid_method_override at [built_value_bug] lib/machine.g.dart:102)
error: Invalid override. The type of 'MyMachineBuilder.input=' ('(MyInputBuilder) → void') isn't a subtype of 'MachineBuilder<MyInput, MyOutput>.input=' ('(MyInput) → void'). (strong_mode_invalid_method_override at [built_value_bug] lib/machine.g.dart:103)
error: Invalid override. The type of 'MyMachineBuilder.output' ('() → MyOutputBuilder') isn't a subtype of 'MachineBuilder<MyInput, MyOutput>.output' ('() → MyOutput'). (strong_mode_invalid_method_override at [built_value_bug] lib/machine.g.dart:106)
error: Invalid override. The type of 'MyMachineBuilder.output=' ('(MyOutputBuilder) → void') isn't a subtype of 'MachineBuilder<MyInput, MyOutput>.output=' ('(MyOutput) → void'). (strong_mode_invalid_method_override at [built_value_bug] lib/machine.g.dart:107)
```

**Comment by davidmorgan** [comment]
@kbrz thanks for the example code! The first set of errors is the same issue as described here. The second is a new issue which I have opened #426 for.

You can work around it by tagging `MyMachine` with `@BuiltValue(nestedBuilders: false)`; please let me know if this does what you want. A proper fix will be harder :)
