### ISSUE TITLE
More Detailed Deserialization Error Messages

### ISSUE THREAD

**Issue by jpgilchrist** [google/built_value.dart#408]
I'm working with a legacy API that quite honestly has odd structures. I'm looking at the backend Java code and trying to determine what to make my built_value models look like... however, I don't always get the types right. When I run a test on the data I will often get an error like

"String is not of type int"

But it'd be far more helpful to get something like "String get fieldName does not match {value} of type int".

Is this possible?

**Comment by dave26199** [comment]
That's a good idea. I'll take a look. Thanks!
