### ISSUE TITLE
Remove dependency on build_config in built_value

### ISSUE THREAD

**Issue by kevmoo** [google/built_value.dart#409]
https://github.com/google/built_value.dart/blob/f3a39b87c7bd653746792ce4854cc2ea75539ff0/built_value/pubspec.yaml#L14

AFAICT, this is not depended on anywhere. It means any package that uses `build_value` brings in yaml, pkg:build (which brings in analyzer) etc.

Are we sure this is needed here?

CC @natebosch @jakemac53

**Comment by natebosch** [comment]
It's a runtime/behavior dependency. This package ships a `build.yaml` and so it needs a dependency on `build_config`.

We should even consider a warning in `pub publish` when the dependency is missing.

**Comment by natebosch** [comment]
I'm open to other suggestions too on how we can make this more obvious

**Comment by kevmoo** [comment]
> This package ships a build.yaml and so it needs a dependency on build_config.

It does? https://github.com/google/built_value.dart/tree/master/built_value

**Comment by kevmoo** [comment]
The dependency should be on `built_value_generator`

**Comment by jakemac53** [comment]
Only the builder package should need this dependency afaik
