### ISSUE TITLE
BuiltValue 'operator ==' implementation

### ISSUE THREAD

**Issue by kostaa** [google/built_value.dart#412]
In one of my classes I have flagged all properties with `@BuiltValueField(compare: false)` which effectively means that the generated implementation class should use a default `operator ==` implementation. 

The code that is generated looks like this:

``` 
    @override
    bool operator ==(dynamic other) {
      if (identical(other, this)) return true;
      if (other is! AccountGroupModel) return false;
      return true;
    }
```  
I was expecting something like this though:

``` 
    @override
    bool operator ==(dynamic other) =>identical(other, this);
```   
 Am I missing anything?

**Comment by davidmorgan** [comment]
BuiltValue provides 'value types', which means they are compared purely on value, not identity.

So the generated implementation is correct: any object of the same type compares equal.

If you want something different, that would be a new feature/setting. Maybe you could describe what you're doing so I can get an idea for how it would fit with what built_value currently offers? Thanks.

**Comment by kostaa** [comment]
I do not have any new feature requests I was just a bit surprised to see the implementation as I was expecting 'java-esque' logic. I follow your reasoning although it is a bit counter-intuitive at first.
