### ISSUE TITLE
[Question] - Protect class instance variables from being updated

### ISSUE THREAD

**Issue by ronlobo** [google/built_value.dart#414]
Looking into preventing updating class instance variables once they are set (not null).

E.g. Once an identity is set on an entity, we won't allow it to be updated again through the lifecycle of the entity.

Is there a way to do so with built_value?

**Comment by davidmorgan** [comment]
The values are already immutable ... so I guess you're asking about a kind of 'super immutable' where you can't even change the values via a builder?

i.e. this should fail:

```
void foo = new Foo((b) => b..id = 3);
void bar = foo.rebuild((b) => b..id = 4); // not allowed because id is already 3!
```

I don't think there's a way to do this right now; you can't write your own setters/getters in the builder.

Did you want it to be per field? i.e. a way to annotate the `id` field to say that it can only be set once?

**Comment by ronlobo** [comment]
Thanks for the quick follow up and putting additional mind work in clarifying the question.

Yes, the builder should not allow resetting a given value once it is set.
The builder should allow rebuilding and setting a value if it is unset.
Annotating the field might be the most convenient way to do so.

Extending your example, does it make sense if it also work for @nullable values?

```
final foo = new Foo(); // allowed id is @nullable
final bar = foo.rebuild((b) => b..id = 3); // allowed because id is null!
final bak = bar.rebuild(); // allowed, not resetting id
assert(bak.isOfId(bar.id)); // true, same entity
final baz = bar.rebuild((b) => b..id = 4); // not allowed because id is already 3!
```

Any feedback on the approach of using built_value for **entities** is more than welcome.

**Comment by ronlobo** [comment]
Closing this issue at this point. After reading further, it is recommended not to give value objects any identity and avoid the design complexities necessary to maintain entities.

**Comment by davidmorgan** [comment]
Thanks for the update.

**Comment by ronlobo** [comment]
Got this from reading Vaughn Vernon - Implementing Domain-Driven Design
