### ISSUE TITLE
Deserialize Firebase documents

### ISSUE THREAD

**Issue by BerndWessels** [google/built_value.dart#417]
Hi
It seems that the serializers cannot deserialize Firebase document data.

This
```
firestore.collection("shops").snapshots().listen((QuerySnapshot snapshot) {
      Shop shop = serializers.deserializeWith<Shop>(Shop.serializer, snapshot.documents.first.data);
      print(snapshot.documents.first.data);
}
```
fails with
```
E/flutter ( 2658): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 2658): type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<dynamic>' in type cast where
E/flutter ( 2658):   _InternalLinkedHashMap is from dart:collection
E/flutter ( 2658):   String is from dart:core
E/flutter ( 2658):   Iterable is from dart:core
```

Is there a nice way to deserialize Firebase documents and collections without manually repeating all fields over and over again?

**Comment by davidmorgan** [comment]
That sounds like a mismatch between the JSON and your class. Would you mind posting details of both please?

There is an issue open to improve error messages on failed serialization, I hope to get to this soon:

https://github.com/google/built_value.dart/issues/408

**Comment by BerndWessels** [comment]
@davidmorgan I think the clue is somewhere in here
` type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<dynamic>' in type cast `

It looks like the deserializer can only handle `Iterable<dynamic>` but firebase document data is a map.

To be honest I have no idea how `built_value` serializer / deserializer are supposed to work, the documentation that I could find didn't help a lot.

How would you deserialize documents and collections from firebase to built_value and built_collection ?

**Comment by davidmorgan** [comment]
Ah, it looks like you need `StandardJsonPlugin`. That switches to expecting a `Map`:

https://github.com/google/built_value.dart/blob/master/example/lib/example.dart#L85

But, it also looks like the data you're getting back is partially deserialized already ... what is a `GeoPoint`?

**Comment by BerndWessels** [comment]
The geopoint class comes from the firestore import and is basically latitude and longitude combined as this is a data type in firestore.

Firestore document data is a Map, I have no idea how JSON is represented in dart and how it relates to firebase.

**Comment by davidmorgan** [comment]
You'll definitely need `StandardJsonPlugin` as shown in the example:

```
final standardSerializers =
      (serializers.toBuilder()..addPlugin(new StandardJsonPlugin())).build();
```

although it refers to `json`, in fact what it does is to switch to using a `Map`. (This is 'standard JSON' because usually serialized JSON uses a map).

We will need to additionally account for classes like `GeoPoint`. Something like this should do it:

```
class GeoPointSerializer implements PrimitiveSerializer<GeoPoint> {
  final bool structured = false;
  @override
  final Iterable<Type> types = new BuiltList<Type>([GeoPoint]);
  @override
  final String wireName = 'GeoPoint';

  @override
  Object serialize(Serializers serializers, GeoPoint geoPoint,
      {FullType specifiedType: FullType.unspecified}) {
    return geoPoint;
  }

  @override
  GeoPoint deserialize(Serializers serializers, Object serialized,
      {FullType specifiedType: FullType.unspecified}) {
    return serialized as GeoPoint;
  }
}
```

And you'll need to add this serializer to `serializers`, in addition to `StandardJsonPlugin`:

```
final mySerializers =
    (serializers.toBuilder()
        ..add(new GeoPointSerializer()
        ..addPlugin(new StandardJsonPlugin())
    ).build();
```

If this works for you then I can look at supporting this use case better in `built_value` itself.

**Comment by BerndWessels** [comment]
Awesome, thank you. I will try it right away tomorrow morning (New Zealand) and post the results here.

**Comment by BerndWessels** [comment]
@davidmorgan thanks that worked, but now I realized another problem:

The serializer does not deserialize the document ID since it is not a field in the document in firestore.

So how do I keep the relation between the built_value Shop and the firestore document Shop ?

Can the serializer somehow take the document ID from and to the built_value ?

What are the implications for collections ?

**Comment by davidmorgan** [comment]
Glad it worked :)

The code you have seems like one reasonable approach. I think you could do this in a general way, rather than needing to write it for every entity type, so there won't be too much boilerplate. i.e. you can write a method which takes a document and `Shop.serializer` and returns a `Shop` with an ID.

A second approach would be to mark the ID field `@nullable`. Then you will deserialize without the ID and can add it later.

Finally a third approach would be to store the ID separately, e.g. to put the `Shop` objects in a `Map<Id, Shop>`, or you could have a generic class `Data<T>` which stores an ID and a `T`.

I think what will work best mostly depends on how you end up using them.

**Comment by BerndWessels** [comment]
Thanks, I'll already took the first approach and that works fine for now.
Let's close this until the next thing pops up 😉

**Comment by davidmorgan** [comment]
Sounds good. Thanks :)

**Comment by yehudamakarov** [comment]
> Glad it worked :)
> 
> The code you have seems like one reasonable approach. I think you could do this in a general way, rather than needing to write it for every entity type, so there won't be too much boilerplate. i.e. you can write a method which takes a document and `Shop.serializer` and returns a `Shop` with an ID.
> 
> A second approach would be to mark the ID field `@nullable`. Then you will deserialize without the ID and can add it later.
> 
> Finally a third approach would be to store the ID separately, e.g. to put the `Shop` objects in a `Map<Id, Shop>`, or you could have a generic class `Data<T>` which stores an ID and a `T`.
> 
> I think what will work best mostly depends on how you end up using them.

Hey just seeing this. I'm working with firestore for the first time and realizing that the `ConvertTo<>()` method doesn't deserialize the ID. Which is super strange to me. Is there a paradigm I'm missing where you aren't supposed to be keeping an ID property on the model in the code? What I'm doing now is getting a snapshot, and then converting it to my model, and then manually adding the snapshot's ID onto my model? seems super weird unless I'm missing something.

What are your thoughts? right now I'm asking myself "why do you need an ID property on your data model?"

**Comment by davidmorgan** [comment]
I'm not familiar with firestore ... what is the `ConvertTo` method?

Might be better to ask someone who knows firestore :)

**Comment by RaimundWege** [comment]
In case of someone is trying this for `GeoFirePoint` of the `geoflutterfire` package:
```
import 'package:built_value/serializer.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geoflutterfire/geoflutterfire.dart';

class GeoFirePointSerializer implements StructuredSerializer<GeoFirePoint> {
  final bool structured = false;
  @override
  final Iterable<Type> types = const [GeoFirePoint];
  @override
  final String wireName = 'GeoFirePoint';

  @override
  Iterable serialize(
    Serializers serializers,
    GeoFirePoint geoFirePoint, {
    FullType specifiedType = FullType.unspecified,
  }) =>
      geoFirePoint.data;

  @override
  GeoFirePoint deserialize(
    Serializers serializers,
    Iterable serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    while (serialized.iterator.moveNext()) {
      final key = serialized.iterator.current as String;
      serialized.iterator.moveNext();
      final value = serialized.iterator.current;
      switch (key) {
        case 'geopoint':
          if (value is GeoPoint) {
            return GeoFirePoint(value.latitude, value.longitude);
          }
      }
    }
    return null;
  }
}
```
