### ISSUE TITLE
[Question] Using this library with Redux and combine reducers

### ISSUE THREAD

**Issue by hillelcoren** [google/built_value.dart#424]
I'm just getting started with an app, I'm trying to use Redux with built_value. The app is working but I've needed to add .toBuilder() in all of the reducers (ie, https://github.com/invoiceninja/flutter-mobile/blob/master/lib/redux/app/app_reducer.dart#L14). 

Is a terrible mistake or the right way to do it?

Thanks for your help and the great library!

**Comment by davidmorgan** [comment]
Very good question. Yes, there is a better way to do it. Instead of assigning a builder, use the 'replace' method:

```
    ..companyState1.replace(state.selectedCompanyIndex == 1
        ? companyReducer(state.companyState1, action) : state.companyState1)
```

This is a bit less typing and a bit more efficient.

**Comment by hillelcoren** [comment]
Thank you so much! Can I ask a quick follow up question. 

Our API returns a list of objects however to follow Redux best practice we're storing the the data as a map and an array. We're currently first creating maps/lists and then creating the built values, is there a more performant approach?

https://github.com/invoiceninja/flutter-mobile/blob/master/lib/redux/product/product_reducer.dart#L66

Thanks again for your help and the libraries, they're awesome :)

**Comment by davidmorgan** [comment]
Similarly, you want `..map.addIterable` for the map, and `..list.replace` for the list.

Generally you can go via methods on the builders rather than assigning a new builder.

**Comment by hillelcoren** [comment]
Perfect, thanks!
