### ISSUE TITLE
Generate copyWith method

### ISSUE THREAD

**Issue by ordsen** [google/built_value.dart#434]
Hi,

in cases where you would like to update only certain fields of an object it makes sense to declare a copyWith method which creates a new object with the passed object's fields (if not null) or (otherwise) the original object's fields as such:

```
abstract class UserState implements Built<UserState, UserStateBuilder> {

  @nullable
  Auth get auth;

  @nullable
  String get name;

  @nullable
  BuiltMap<int, Friend> get friends;

  UserState._();

  factory UserState([updates(UserStateBuilder b)]) = _$UserState;

  UserState copyWith(UserState updates) {
    return UserState((b) => b
      ..name = updates.name ?? name
      ..friends.replace(updates.friends ?? friends)
      ..auth.replace(updates.auth ?? auth));
  }
}
```

This code is pretty much the same for each model class I have, just the field names change. Is there any possibility to make built_value generate the copyWith implementations or is there already some similar functionality? I did not find any docs or examples for this so I assume there is currently no such functionality, please point me in the right direction if I overlooked something.

If that's not the case: Is this feature in the scope of built_value? Are there any plans to implement this feature?

**Comment by davidmorgan** [comment]
Hmm. So if I understand correctly, you want to use a `UserState` with nullable fields to represent a modification of a `UserState`; when 'applying' the update, only non-null fields are modified.

This seems a little awkward; it prevents you using `null` in any meaningful way, since you can't then update to `null`.

One alternative, although I'm not sure it's a great one, is to use an `updates` function instead. You can then pass this to the 'rebuild' method:

```
var userState = <create UserState>
var myUpdates = (UserStateBuilder b) => b..name = 'name'..friends.replace(...)..auth.replace(...);
var updatedUserState = userState.rebuild(myUpdates);
```

This has the advantage that `myUpdates` can make any modification it wants to a `UserState`, but the disadvantage that it's opaque, you can't do anything else with it but apply it. Still, depending on exactly what you're doing, this might be better. What do you think?

This is essentially the same issue/request: #278 

I'm definitely open to adding something if we can figure out what the right thing to do is :) ... as mentioned in that link, protocol buffers (google data format) support merging, but they concatenate lists, which I don't think is being asked for here.

**Comment by ordsen** [comment]
Yeah that request is about what I mean.
You're right, my copyWith method would not allow to set a field to `null`, but in my case it does not need to (there is separate logic for that). 
I'm using this when I retrieve updates from a server where the returned response only contains new fields. The response is deserialized with the built_value (de)serializer and `null` just means "there is no new data for this field".

The `updates`function looks interesting, but I think despite of moving the implementation from the class to some other place the issue remains the same: Whatever the updates implementation looks like, it probably could be generated. The structure is still the same. Making it opaque of course allows you to remove these `@nullable` annotations (if you don't have a server response deserialization as mine, that is..)

For me, its just a hand full of relatively small implementations, but I thought maybe that can be automated.. I read through 278 and must admit that this request might become more complex when you want to allow specifying merging behavior.

Should I close this issue as your referenced issue is basically the same?

**Comment by davidmorgan** [comment]
Hmm, how do you deal with setting fields to `null`?

I'd definitely like to improve the situation here, but I want something that doesn't force you to use `@nullable`; there should be a way to specify which fields to update that doesn't require using `null`. For example we could have a class `Update<T>` which wraps a `Builder` for `T` and keeps track of the set of fields to change; you could then apply the update to an instance. If `Update` is serializable, I think that addresses your use case?

Might not be easy to implement, but seems like a direction worth exploring :) ... what do you think?

**Comment by ordsen** [comment]
To set a field to null I use a special reducer function (I'm using this in built_redux). Something like `overrideUserState` (which is kind of "hard override all fields") or `clearUserState`.

I like your idea of that `Update<T>` class. If I understand you right: In case of my example from above the code generation aims to reimplement the UserState as Update<UserState> class which contains all fields declared by UserState but offers functionalities like a builder? So basically you want to decorate the `UserStateBuilder` and make this class resemble `UserState` but without checking if fields are null when they are set? Then, to apply the changes there will be an `applyUpdates` function which overrides the UserState fields if their corresponding `Update` field is not null. I think this might work...

As a different approach: What is missing is a differently named class which looks like UserState but allows null fields (and has no `@nullable` annotations). So, wouldn't it make sense to create a `UserStateUpdates` class which wraps the generated `_$UserState` instead of the `Builder` for `UserState` ? My intention here is to reuse all the code already generated (e.g. == implementation, hashCode, maybe even serializers..) and just override the constructors. The new constructor of that `UserStateUpdates` class should then allow null for each field.
If the `Builder` class now provides something like `void applyUpdates(UserStateUpdates updates)` a call to update certain fields could look like this:
```
UserState original = UserState((b) => ...fully-featured-user-state...);
UserStateUpdates updates = serializer.deserialize(someServerResponse);  // user-state-like instance with some fields set to null
UserState updatedOriginal = original.rebuild((b) => b..applyUpdates(updates));
```
This reminds me a little bit of the `replace` function, but with a implementation in `UserStateBuilder` somehow like that:
```
@override
 void applyUpdates(UserState other) {
   if (other == null) throw new ArgumentError.notNull('other');
   _name = other.name ?? _$v.name;
   _friends = other.name ?? _$v.name;
   _auth = other.auth ?? _$v.auth;
 }
```  
I guess with this approach the `Builder<V extends Built<V, B>, B extends Builder<V, B>>` class would also need another generic type for `UserStateBuilder`; but maybe the existing code generation doesn't need to be modified as most parts might be reused.. 
I tried that on my code but it seems like you cannot just override the constructor, maybe you have an idea here :)

**Comment by ordsen** [comment]
Ah I see; that's probably something you have more experience with than me. The `Builder` interface idea sounds good.

**Comment by davidmorgan** [comment]
I suspect nested builders are going to be complicated, though :/

Anyway, I think I understood the issue fully. Will try to dig into it at some point. Thanks!

**Comment by numen31337** [comment]
I recently wrote to the library to deal with this issue, which is probably enough for most cases https://pub.dev/packages/copy_with_extension_gen

**Comment by nguyenxndaidev** [comment]
Hi, any news on this feature?

There are 2 situations I would like to control:
1. Reuse an existing instance if there is no changes. I think, this should be the default and the generated code is implemented this way.
2. Force to create new instance with the values from an existing instance even if they equal.

I created a test code as below:
```
abstract class Category implements Built<Category, CategoryBuilder> {
  int get id;
  String get name;

  Category._();
  factory Category([updates(CategoryBuilder b)]) = _$Category;
}
```

```
final c0 = Category((b) => b
  ..id = 0
  ..name = 'C0');
print('c0 => $c0');

final c1 = c0.rebuild((b) => b);
print('c1 => $c1');
print('c0 == c1 => ${c0 == c1}'); // true
print('identical(c0, c1) => ${identical(c0, c1)}'); // true

final c2 = c0.rebuild((b) => b..id = 2);
print('c2 => $c2');
print('c0 == c2 => ${c0 == c2}'); // false
print('identical(c0, c2) => ${identical(c0, c2)}'); // false

final c3 = c0.rebuild((b) => b..id = b.id);
print('c3 => $c3');
print('c0 == c3 => ${c0 == c3}'); // true
print('identical(c0, c3) => ${identical(c0, c3)}'); // false

final c4 = Category((b) => b.replace(c0));
print('c4 => $c4');
print('c0 == c4 => ${c0 == c4}'); // true
print('identical(c0, c4) => ${identical(c0, c4)}'); // true

final c5 = c0.rebuild(null);
print('c5 => $c5');
print('c0 == c5 => ${c0 == c5}'); // true
print('identical(c0, c5) => ${identical(c0, c5)}'); // true
```

Creation of `c3` is very interesting. I trigger one `setter` and reuse the old value to cheat the `CategoryBuilder` to set the reference to the existing instance to null and force it to build a new instance. This is a workaround to force creating new instance.

But I think, the trick above is actually a bug and the correct way should be something like the `copy()` method in [Kotlin's data class](https://kotlinlang.org/docs/reference/data-classes.html):
```
data class User(val name: String = "", val age: Int = 0)

fun main() {
    val jack = User(name = "Jack", age = 1)
    println(jack) // User(name=Jack, age=1)
    
	val olderJack = jack.copy(age = 2)
    println(olderJack) // User(name=Jack, age=2)
    println(olderJack == jack) // false
    println(olderJack === jack) // false
    
    val anotherButSameJack = jack.copy()
    println(anotherButSameJack) // User(name=Jack, age=1)
    println(anotherButSameJack == jack) // true
    println(anotherButSameJack === jack) // false
}
```

@davidmorgan:
* What is your opinion on this line `c0.rebuild((b) => b..id = b.id);`? Is it a bug?
* Will you implement the same thing as the `copy()` method in Kotlin?

**Comment by nguyenxndaidev** [comment]
Assume we want a model as below:
```
abstract class Category implements Built<Category, CategoryBuilder> {
  int get id;
  String get name;

  Category._();
  factory Category([updates(CategoryBuilder b)]) = _$Category;
}
```

Here is my change sugesstion to the library:

```
abstract class Built<V extends Built<V, B>, B extends Builder<V, B>> {
  // Allow optional parameter
  V rebuild([Function(B) updates]);

  // Allow optional parameter
  V copy([Function(B) updates]);

  // ...
}
```

```
class _$Category extends Category {
  @override
  Category copy([void Function(CategoryBuilder) updates]) =>
      (toBuilder()..update(updates)).buildCopy();

  // ...
}
```

```
class CategoryBuilder implements Builder<Category, CategoryBuilder> {
  _$Category _$v;

  int id;
  String name;

  CategoryBuilder();

  @override
  void replace(Category other) {
    if (other == null) {
      throw new ArgumentError.notNull('other');
    }
    _$v = other as _$Category;
    id = _$v?.id;
    name = _$v?.name;
  }

  @override
  void update(void Function(CategoryBuilder) updates) {
    if (updates != null) updates(this);
  }

  @override
  _$Category build() {
    if (_$v == null || _$v.id != id || _$v.name != name) {
      return buildCopy();
    }
    return _$v;
  }

  _$Category buildCopy() {
    final _$result = new _$Category._(id: id, name: name);
    replace(_$result);
    return _$result;
  }
}
```

**Comment by nguyenxndaidev** [comment]
Beside the my change sugesstion, I also like the idea of `Update<T>`.
@ngrx/entiy also uses this technique: https://ngrx.io/guide/entity/adapter

**Comment by tenninebt** [comment]
A solution could be the use of an optional class wrapping all the parameters/args of copy method. That's what I'm using in my code to be able to handle explicit _update to null value_ vs _an unchanged value_ : 
https://github.com/google/quiver-dart/blob/master/lib/src/core/optional.dart

Thoughts?

**Comment by davidmorgan** [comment]
Fun fact, I wrote `Optional` :D :D :D ... I think it's going out of fashion, with NNBD, but it's true that it works for this use case.

I wouldn't say it works _well_, though: creating an `Optional` wrapper for every field is quite some overhead :/ ... it would be cheaper to use the `Builder`, I think.

**Comment by Sunbreak** [comment]
https://getstream.io/blog/flutter-vs-react-native-the-ultimate-comparison/

**Comment by vasilich6107** [comment]
@davidmorgan could you clarify is there any `copyWith` approach for `built_value`?

**Comment by davidmorgan** [comment]
No; the `built_value` approach to `copyWith` is the `rebuild` method.
