### ISSUE TITLE
Prefer equals for default values lint - update to `=` according to Dart style guide 

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#435]
![image](https://user-images.githubusercontent.com/405837/40923076-2013d11c-6814-11e8-81b6-1009217690d4.png)

(probably also on other places)

**Comment by davidmorgan** [comment]
Yeah, I noticed recently that my fingers prefer the wrong one. I'll update. Thanks :)

**Comment by davidmorgan** [comment]
Now fixed :)
