### ISSUE TITLE
@Transient annotation that informs generator to ignore a property in ==/hash code generation.

### ISSUE THREAD

**Issue by paulgerlich-wf** [google/built_value.dart#436]
We've run into an issue where we have transient properties that should not be used to compare two classes as equal. 

Is there, or is it possible for us to get, an annotation that would tell the generator to ignore that property when overriding == and  the object hash code?

**Comment by davidmorgan** [comment]
There is :)

```
@BuiltValueField(compare: false)
```

**Comment by paulgerlich-wf** [comment]
Beautiful. Thanks David.
