### ISSUE TITLE
Parsing JSON without a discriminator

### ISSUE THREAD

**Issue by kentcb** [google/built_value.dart#437]
I'm trying to parse JSON from an API. Consequently, it does not include a discriminator and I'm getting an exception as a result:
```
Invalid argument(s): Unknown type on deserialization. Need either specifiedType or discriminator field.
```
Fair enough. The actual context is a helper method (part of a mixin) that looks like this:
```dart
  T deserialize<T>(String json) {
    final result = serializers.deserialize(convert.json.decode(json));

    ...

    return result;
  }
```
My first thought to fixing this was to pass through a `specifiedType` argument, but I don't know how to go from `T` to `Type`. In C# I'd just do `typeof(T)`, but I can't find the Dart equivalent. Moreover, I don't have an instance of `T`, nor can I create one, so I can't use the `runtimeType` instance property.

**UPDATE**: I also tried:
```dart
final result = serializers.deserialize(convert.json.decode(json), specifiedType: new FullType(T));
```
But this still gives me the above error. I don't understand :/

My first preference would be to just specify this via `specifiedType`, since that appears to be the simplest mechanism were it to work. I could also use a plugin to inject the type name, but I don't _have_ a type name to inject - only a `Type`, which doesn't appear to give me the type name.

Any tips on how I can proceed here?

**Comment by kentcb** [comment]
Ugh, solved. I did some debugging and found that the serializer for the particular DTO I chose to test with wasn't mapped. So I regenerated the code and then it worked. Not sure how that happened really, but lesson learnt.

**Comment by hasan314** [comment]
Hi I am getting a similar error, please check https://github.com/google/built_value.dart/issues/811 for details. Appreciate any help provided.
