### ISSUE TITLE
Generated code has empty constructor bodies with all nullable fields

### ISSUE THREAD

**Issue by adamlofts** [google/built_value.dart#44]
If all fields on a class are nullable built_value generates classes with empty constructor bodies. This causes an analysis lint option to show up.

INFO: Use `;` instead of `{}` for empty constructor bodies. ([yacht] lib/fp_value/value.g.dart:145)

**Comment by davidmorgan** [comment]
Thanks! Should be an easy fix, I'll take a look.

Having all nullable fields is not usually something I would recommend -- perhaps a Map would be a better fit -- but of course the generator should handle this case properly.

**Comment by davidmorgan** [comment]
This should do it -- please let me know if you want to review or if I should find someone else to take a look. Thanks!

https://github.com/google/built_value.dart/pull/45/

**Comment by adamlofts** [comment]
The change looks good to me but I am not familiar with your review process. Happy to help if you can guide me :)

**Comment by davidmorgan** [comment]
We use "Reviewable" which integrates with github. Feel free to take a look if you're interested.

https://reviewable.io/reviews/google/built_value.dart/45

Otherwise your "looks good to me" on this issue is sufficient -- thanks!

**Comment by davidmorgan** [comment]
Thanks. Will be fixed when 0.1.6 is released.
