### ISSUE TITLE
A way to merge multiple serialisers into one.

### ISSUE THREAD

**Issue by long1eu** [google/built_value.dart#446]
I have a multimodule project so merging the serialisers into one would be great.

**Comment by davidmorgan** [comment]
The expected way to do this is to use the `@SerializersFor` annotation to generate the `Serializers` instance you need once per endpoint.

The reason this is recommended is to make it clear that you don't need to include serializers for every type that happens to be in libraries you depend on. This is important if code size matters--it will give you smaller js size with dart2js, for example.

Still, it does make sense to be able to get the list of serializers from a `Serializers` instance, which would allow you to merge them--for cases when you do know that you want everything. I'll look at adding that. Thanks!

**Comment by long1eu** [comment]
the this is that those libraries are in fact modules in my project, I depend on them and I need the serialisers both in their home module and in the main one. In this case I can't gather all the serialisers in the main module and if I have them both in the main and in their own module I would just have duplicate code, witch it not good.
