### ISSUE TITLE
Skip json key but deserialize value

### ISSUE THREAD

**Issue by kadvis** [google/built_value.dart#451]
I have been trying to deserialize the below code. I don't want the deserializer to consider 'emailAddress' key but parse `name` and `address` instead. 

```
@BuiltValue(wireName: 'emailAddress')
abstract class EmailAddress implements Built<EmailAddress, EmailAddressBuilder>{
  String get name;
  String get address;
  EmailAddress._();
  factory EmailAddress([updates(EmailAddressBuilder b)]) = _$EmailAddress;
  static Serializer<EmailAddress> get serializer => _$emailAddressSerializer;
}
```

```
test("parse email address", ()async {
    String jsonStr = '''{
          "emailAddress": {
            "name": "Some Name",
            "address": "someid@hotmail.com"
          }
        }''';
    EmailAddress address = serializers.deserializeWith(EmailAddress.serializer, json.decode(jsonStr));
    print(address);
  });
```
```
@override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (specifiedType.root == EmailAddress && object is List) {
      var map = object[1] as Map;
      EmailAddress address =  serializers.deserializeWith(EmailAddress.serializer, map);
      return address;
    }
    return object;
  }
```
Tried the below code with plugin with no luck. Can you guys help?, what am I missing?
Also, I need to have the 'emailAddress' key while serializing

**Comment by davidmorgan** [comment]
Hmm, it looks to me like `Object` will be a `Map`, not a `List`? Then you would do

```
var map = object{'emailAddress'} as Map;
```

When serializing, you need to do the reverse: create a new `Map` with `emailAddress` as the key and `object` as the value.

**Comment by kadvis** [comment]
`object`  is actually a `List`. however, `object[0]` is `String` 'emailAddress' and `object[1]` is a `Map`  which contains 'name' and 'address'

**Comment by davidmorgan** [comment]
Could it be that you're also using `StandardJsonPlugin`? I think what you want is similar but different--so you may need to fork it.

An alternative would be to just throw away the built_value (de)serialization code and write your own from scratch. I don't think it's getting you a lot at this point.

**Comment by kadvis** [comment]
yes. I am using `StandardJsonPlugin` as well. I finally end up doing this in the plugin but without changing built_value (de)serialization code.

```
if(specifiedType.root == EmailAddress && object is List){
      try{
        var map = object[1] as Map;
        final result = <Object>[
          'name',
          map['name'],
          'address',
          map['address'],
        ];
        return result;
      }catch(e){
        return object;
      }
    }
```
Less code and I don't need to write the whole (de) serialization code. 
I am not sure if this is the proper way to do it. So let me know if you see anything to improve. 
thanks for the help :)

**Comment by davidmorgan** [comment]
Looks reasonable. You could maybe simplify a bit using a method to convert a map into a list, like `StandardJsonPlugin` does, with `toList`:

https://github.com/google/built_value.dart/blob/master/built_value/lib/standard_json_plugin.dart#L142 

You don't quite need all the complexity though, more like:

```
  List _toList(Map map) {
    final result = new List(map.length * 2);
    var i = 0;
    map.forEach((key, value) {
      result[i] = key;
      result[i + 1] = value;
      i += 2;
    });
    return result;
  }
```

**Comment by kadvis** [comment]
Perfect. Thanks davidmorgan.
