### ISSUE TITLE
Are alternate discriminator representations supported?

### ISSUE THREAD

**Issue by Whathecode** [google/built_value.dart#452]
The discriminator in the built_value package for Dart is stored within the object: `{ r'$': 'SomeObject, "field1": "Some value", "field2": 42 }`

However, serialization libraries on other platforms sometimes rely on a 'wrapper array' instead, in which the first element of the array denotes the Type.
```
[
    "SomeObject",
    {
        "field1": "Some value",
        "field2": 42
    }
]
```
For example, [Jackson](https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization) for Java supports this, [as well as the kotlinx.serialization library of Kotlin](https://github.com/Kotlin/kotlinx.serialization/issues/168#issuecomment-404080641).

Is this currently supported in built_value, or planned to be supported? If not, any viable approach you see to support this (at a glance, serialization plugins looked promising).

**Comment by davidmorgan** [comment]
Hmm, that sounds a whole lot like the last issue

https://github.com/google/built_value.dart/issues/451

...so the answer is, yes, a plugin seems to work. Maybe we should look at shipping something standard.
