### ISSUE TITLE
consider dropping quiver dependency

### ISSUE THREAD

**Issue by jakemac53** [google/built_value.dart#455]
It looks like it is barely used, and it is a really big dependency to pick up for consumers of this package.

The `built_collection` package should likely do the same, but I won't bother filing an issue there as well ;).

**Comment by davidmorgan** [comment]
Thanks Jake.

We do need quiver for one big thing: multimaps/multisets. 

built_collection provides versions of both, and built_value strongly depends on built_collection :)

So I don't think there's a reasonable way to break the dependency.
