### ISSUE TITLE
Need either specifiedType or discriminator field

### ISSUE THREAD

**Issue by jiangzhixiao** [google/built_value.dart#471]
hi,everyone,i'm confuse on this problem few days,any one can help me?
 when i using flutter redux,i got this problems.

> Deserializing '[data, {accounts: [], version: 5.4}, null, null]' to 'LoginResponse' failed due to: Invalid 
 argument(s): Unknown type on deserialization. Need either specifiedType or discriminator field.
  
**here is LoginResponse Deserialize method:**
``` Dart
   LoginResponse deserialize(Serializers serializers, Iterable serialized,
      {FullType specifiedType: FullType.unspecified}) {
    final result = new LoginResponseBuilder();
    final iterator = serialized.iterator;
    while (iterator.moveNext()) {
      final key = iterator.current as String;
      iterator.moveNext();
      final dynamic value = iterator.current;
      switch (key) {
        case 'data':
          result.data.replace(serializers.deserialize(value, specifiedType: const FullType(LoginResponseData)) as LoginResponseData);
          break;
        case 'error':
          result.error.replace(serializers.deserialize(value,
              specifiedType: const FullType(ErrorMessage)) as ErrorMessage);
          break;
      }
    }

    return result.build();
  }

abstract class LoginResponseData implements Built<LoginResponseData, LoginResponseDataBuilder> {

  factory LoginResponseData([void updates(LoginResponseDataBuilder b)]) = _$LoginResponseData;
  LoginResponseData._();

  BuiltList<CompanyEntity> get accounts;
  String get version;
//  StaticData get static;

  static Serializer<LoginResponseData> get serializer => _$loginResponseDataSerializer;
}
```
What really hurts me is that the debugging mode of android studio seems some problem? some variable always shows "Collecting data... it's hard to me to fix this problem cause i can't got some key variable's  
 value . just like: specifiedType.
There is some screenshot when debuging.
  
![image](https://user-images.githubusercontent.com/7273487/43695922-1b136124-996e-11e8-9ff0-5c277cc96c43.png)
![image](https://user-images.githubusercontent.com/7273487/43695925-20681b74-996e-11e8-9f13-025cd7f11188.png)
![image](https://user-images.githubusercontent.com/7273487/43695930-2367d116-996e-11e8-93b3-9bdd5ed31651.png)
![image](https://user-images.githubusercontent.com/7273487/43695935-273c341c-996e-11e8-81b8-2fe3ac3e7830.png)

i'm great appreciate if any one could give me some tips or answers!!! thanks!!!!

**Comment by davidmorgan** [comment]
I can't help you with android studio questions, sorry.

The code sample is confusing. I don't need to see the generated code--can you post just the code you wrote yourself, please?

**Comment by zoechi** [comment]
"Collecting data..." is annoying. I think it's a bug in the IntelliJ Dart plugin.
I encounter it much less frequently recently though.

**Comment by zoechi** [comment]
@jiangzhixiao that should be reported in https://youtrack.jetbrains.com/

**Comment by jiangzhixiao** [comment]
@zoechi ok,thanks zoechi
