### ISSUE TITLE
Create simple class inheritance structure with built_value

### ISSUE THREAD

**Issue by techyrajeev** [google/built_value.dart#472]
I am trying to create below structure with `Shape` being parent class and `Triangle` and `Square`

```
            Shape
             |
      ___________________
      |                  | 
Triangle                 Square
```

How can I achieve it with built_value in dart?

**Comment by dave26199** [comment]
See if there's anything that looks relevant in

https://github.com/google/built_value.dart/blob/master/example/lib/polymorphism.dart

:)

**Comment by techyrajeev** [comment]
@dave26199 thanks a lot. I wish I could have seen it in official docs :)
