### ISSUE TITLE
Deserialize with StandartJsonPlugin fail in some cases

### ISSUE THREAD

**Issue by vadimtsushko** [google/built_value.dart#474]
In some cases - and I do not fully understand specific reasons - my objects fail to deserialize with StandartJsonPlugin.
I have made stripped down example of such case in my library:
https://github.com/infovizion/enigma-dart/blob/master/enigma/example/sense/pivot_deserialization_error.dart
Input data for that example:
https://github.com/infovizion/enigma-dart/blob/master/enigma/example/sense/pivot-table-stripped.json
Last section of example tries to load data from such structure
``` json
{
    "qData": [
     [
      {
       "qText": "1.23",
       "qNum": 1.23,
       "qType": "V",
       "qAttrExps": {
        "qValues": [
         {
          "qNum": 4294638200
         }
        ]
       }
      },
      {
       "qText": "0,00",
       "qNum": 0,
       "qType": "V",
       "qAttrExps": {
        "qValues": [
         {
          "qNum": 4294638200
         }
        ]
       }
      }
     ]]
}
```

So basically that is object with one interesting property: `data`

``` Dart
abstract class NxPivotPage implements Built<NxPivotPage, NxPivotPageBuilder> {
  static Serializer<NxPivotPage> get serializer => _$nxPivotPageSerializer;

  /// Information about the left dimension values of a pivot table.
  /// Original name: qLeft
  @nullable
  @BuiltValueField(wireName: 'qLeft')
  BuiltList<NxPivotDimensionCell> get left;

  /// Information about the top dimension values of a pivot table. If there is no top dimension in the pivot table, information about the measures are given.
  /// Original name: qTop
  @nullable
  @BuiltValueField(wireName: 'qTop')
  BuiltList<NxPivotDimensionCell> get top;

  /// Array of data.
  /// Original name: qData
  @nullable
  @BuiltValueField(wireName: 'qData')
  BuiltList<BuiltList<NxPivotValuePoint>> get data;

  /// Size and offset of the data in the matrix.
  /// Original name: qArea
  @nullable
  @BuiltValueField(wireName: 'qArea')
  Rect get area;

  factory NxPivotPage([updates(NxPivotPageBuilder b)]) = _$NxPivotPage;

  factory NxPivotPage.init(
      {BuiltList<NxPivotDimensionCell> left,
      BuiltList<NxPivotDimensionCell> top,
      BuiltList<BuiltList<NxPivotValuePoint>> data,
      Rect area}) = _$NxPivotPage._;

  NxPivotPage._();
}
```

In first section of the example I successfully deserialise these `NxPivotDimensionCell` cells individually.

``` Dart
List jsonCells = jsonMap['qHyperCube']['qPivotDataPages'][0]['qData'];
  for (var row in jsonCells) {
    for (var cell in row) {
      NxPivotValuePoint value = standardJsonSerializer.deserialize(cell,
          specifiedType: FullType(NxPivotValuePoint));
      print(value);
    }
  }
```

But deserialization of object as a whole breaks with error

```
List of lists of cells inside most immediate object fail to deserialize:
Deserializing '[qData, [[{qText: 1.23, qNum: 1.23, qType: V, qAttrExps: {qValues: [{qNum: 42...' to 'NxPivotPage' failed due to: Deserializing '[[{qText: 1.23, qNum: 1.23, qType: V, qAttrExps: {qValues: [{qNum: 4294638200...' to 'BuiltList<dynamic><BuiltList<dynamic><NxPivotValuePoint>>' failed due to: Deserializing '[{qText: 1.23, qNum: 1.23, qType: V, qAttrExps: {qValues: [{qNum: 4294638200}...' to 'BuiltList<dynamic><NxPivotValuePoint>' failed due to: Bad state: No builder for BuiltList<dynamic><NxPivotValuePoint>.
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:151:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:102:18)
#2      main (file:///home/vts/project/github/enigma-dart/enigma/example/sense/pivot_deserialization_error.dart:36:49)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

I cannot attribute it just to the fact that there are nested BuiltLists in that property because similar attributes works in other objects.

Is there any workaround for such errors ?

**Comment by dave26199** [comment]
There is. Sorry for the obscure error message; I have an issue open to improve it, but didn't get around to it yet.

The key part is this:

```
Bad state: No builder for BuiltList<dynamic><NxPivotValuePoint>
```

which is itself a bit broken, it should be

```
Bad state: No builder for BuiltList<NxPivotValuePoint>
```

--so the fix is to add a builder for `BuiltList<NxPivotValuePoint>`. That's easy, just do:

```
final updatedSerializers = (serializers.toBuilder()
    ..addBuilderFactory(
        new FullType(BuiltList, [new FullType(NxPivotValuePoint)]),
        () => new ListBuilder<NxPivotValuePoint>()));
```

Sorry for any typos, I can't check this right now. There are more examples here though: https://github.com/google/built_value.dart/blob/master/built_value/test/built_list_serializer_test.dart

**Comment by vadimtsushko** [comment]
Thank you David.
I've tried and it works for me as workaround.
Should we close this issue then?
If I understand correctly it is the same problem as https://github.com/google/built_value.dart/issues/124 ?

**Comment by davidmorgan** [comment]
Great!

That's right, fixing #124 could potentially add these for you.

And #444 is the issue for improving the error message.

I'll close this now, please re-open if there's anything more to do :)

**Comment by PritishSawant** [comment]
I am getting the same issue. I tried your solution after posting a question on stackoverflow

https://stackoverflow.com/questions/54517152/failed-due-to-bad-state-no-builder-factory-for-builtlist

Can you help.

After adding your work around my serializers.dart file looks like follows

```
@SerializersFor(const [MobileLoginModel,OTPLoginModel,SignOutModel,ShortBioModel,ElectivesModels,SpecialisationModelFirstScreen])

Serializers serializers = _$serializers;

Serializers standardSerializers = (serializers.toBuilder()..addPlugin(StandardJsonPlugin())
..addBuilderFactory(FullType(BuiltList,[FullType(Category)]), () => ListBuilder<Category>())
).build();
```

But i still get the same error

**Comment by arrrrny** [comment]
@davidmorgan Can you please add a sample which includes serializing and deserializing  a Rect object? Whenever I want to add a Rect object I get below error: 
1. Make field box have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.

In this case my field is Rect get box;
