### ISSUE TITLE
Possible to pass generic type to field and deserialize?

### ISSUE THREAD

**Issue by Chozzle** [google/built_value.dart#478]
I have an api that retruns json like this:

```
{
	"data": {
		"type": "portfolios",
		"id": "1",
		"attributes": {
			"products": [{
				"description": "Everyday Options",
				},
                        ]
                 }
         }
}
```
I want to write generic deserialization code for data, type, id and attributes classes, and just be able to specify a type to deserialize the products class. Here is what I tried:

```
abstract class ResponseBody<T> implements Built<ResponseBody<T>, ResponseBodyBuilder<T>> {
  ResponseData<T> get data;

  ResponseBody._();

  factory ResponseBody([updates(ResponseBodyBuilder<T> b)]) = _$ResponseBody<T>;

  static Serializer<ResponseBody> get serializer => _$responseBodySerializer;
}
```
Then I try to deserialize with:
```
ResponseBody<Products> responseBody = serializers.deserializeWith<ResponseBody<Products>>(
      ResponseBody.serializer,
      json.decode(response.body),
    );
```
but I get the error "type '_$ResponseBodySerializer' is not a subtype of type 'Serializer<ResponseBody<Products>>'".
Am I doing this wrong or is this just not possible?

**Comment by dave26199** [comment]
I think you'll have more luck using a serializer plugin to convert. See

https://github.com/google/built_value.dart/issues/451

for some ideas. It sounds like this is a common format so it may make sense that we add built in support for it.

**Comment by Chozzle** [comment]
I actually got it to work using: 
```
ResponseBody responseBody = serializers.deserialize(
      json.decode(response.body),
      specifiedType: const FullType(ResponseBody, const [FullType(Products)])
    );
```
And also making sure I added ```..addBuilderFactory``` for each class that needs a type parameter, per [#124](https://github.com/google/built_value.dart/issues/124)
