### ISSUE TITLE
curly_braces_in_flow_control_structures

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#490]
like #456

**Comment by matanlurey** [comment]
I don't know if its reasonable to keep asking to add ignores for every possible lint rule ever written (and whatever is written in the future).

**Comment by zoechi** [comment]
I'm open for better ideas

**Comment by davidmorgan** [comment]
Bit surprised we're breaking this in the generated code--I try to keep it to style :)--I'll take a look. Thanks!

**Comment by davidmorgan** [comment]
(Will be next week or later though, pretty snowed under right now).

**Comment by zoechi** [comment]
Also `unnecessary_new`
`dartfmt --fix` removes it (this is why I missed it at first), but it still shows lots of analyser hints because the analyzer sometimes doesn't seem to recognize the change and I have to restart it to get rid of the messages.

**Comment by davidmorgan** [comment]
This is now released.
