### ISSUE TITLE
Question: how to (de)serialize Optional<T>?

### ISSUE THREAD

**Issue by kentcb** [google/built_value.dart#491]
I'm trying to send quiver's `Optional<T>` type over the wire, formatted as JSON. Without any customization, I'm getting an error saying that `Optional<MyDto>` has no serializer, which makes sense. The problem is, I can't find any examples of how to do this custom serialization. I've tried the most obvious thing I could think of as a starting point:
```dart
serializersBuilder.addBuilderFactory(const FullType(Optional,  const [const FullType(MyDto)]), () {
  throw Exception();
});
```
But this code just never seems to execute when I attempt to serialize `Optional<MyDto>`.

Any chance you could provide some pointers? Thanks.

**Comment by davidmorgan** [comment]
`Optional` is hard. My recommendation is to use `@nullable` instead.

There's some discussion of the issues here:

https://github.com/google/built_value.dart/issues/306

Basically, serialization support isn't enough--for proper `Optional` support you want:

 - `Optional` values should default to 'absent'
 - Adding an `Optional` field should be a non-breaking change for serialization
 - Builders should support setting the raw value without you having to create an `Optional` yourself

It would be possible to add this, but it's complicated. And, 1) Dart has null-aware operators, which solve part of the problem `Optional` was meant to solve; 2) Dart will hopefully at some point get 'none null by default', which should solve the rest.

So even though I like `Optional`--I actually added that class to quiver--I currently recommend against it.

If you _do_ want to use it anyway, the way to get basic serialization support is to add a `Serializer`. See e.g.

https://github.com/google/built_value.dart/blob/master/built_value/lib/src/int_serializer.dart

for an example. I can help you figure out the details if you want to try it.

**Comment by smiLLe** [comment]
I am also interested in Optional. I would rather use Optional than @nullable. But will == check still work assuming we have the same Optional<String> for example?
Can we chain serializer? Jsonserializer and optionalserializer)

**Comment by davidmorgan** [comment]
`==` works fine with `Optional`, because it implements `operator==`.

Wrapping `Json` with `Optional` won't work directly. You need a different interface that is like `Json` but returns `Optional`. What you could do is write your own `MyJson` class, and your own `MyJsonSerializer` to go with it. This `MyJson` class can return `Optional` instead of nullable.

**Comment by smiLLe** [comment]
@davidmorgan  thanks for your response :)

So i basically have to copy/paste the existing json serializer and add the possibility to handle Optionals? 
I think i am kinda stuck here, cause i am new to dart, built_value and all the code generation :) Guess i should just stick to @nullable  for now 😄

**Comment by davidmorgan** [comment]
That's right.

Sticking with `@nullable` is the fully supported path right now, so, yes, that's what I recommend :)

**Comment by mateusfccp** [comment]
It has been already more than a year, have you reconsidered this? nulls are sick.

**Comment by davidmorgan** [comment]
NNBD is landing in the language now :) ... next step here is to make `built_value` support NNBD, and see where that gets us.
