### ISSUE TITLE
Reuse underlying value where possible

### ISSUE THREAD

**Issue by davidmorgan** [google/built_value.dart#5]
For a field that uses a builder, still keep the underlying value if possible and reuse that instead of rebuilding.

**Comment by Andersmholmgren** [comment]
Do you mean check if the builder's values are the same as an underlying value and simply return that instance on build?

If so then that would be useful for what I am doing now. It will be painful to make sure that all equivalent value objects end up being the same instance

**Comment by davidmorgan** [comment]
Depending on how expensive it turns out to be. (Memory/performance). It would be simplest to keep a reference to the original value and throw away that reference when a change is made; but that wouldn't catch cases where the values are changed back to match the original value.

The main use case I have in mind is for integration with Angular, which does identity checking instead of using equality. So for trivial cases where no change is made you want to return the same instance.

Depending on exactly what you need, it might make more sense to support building with a cache, i.e. always lookup in a hashmap and reuse an existing instance when possible.

**Comment by davidmorgan** [comment]
Done in 0.4.0.

It doesn't check for equality, though -- just for assignment.
