### ISSUE TITLE
wireName with dollar $ character

### ISSUE THREAD

**Issue by wwwdata** [google/built_value.dart#504]
Hi, unfortunately I have to parse JSON from a backend that uses the `$` sign in one of the field names. This sign is a special character in dart to insert variables into strings.

So when I use an annotation like this:

```dart
@BuiltValueField(wireName: '\$date')
int get date;
```

it is getting transformed into:

```dart
      final dynamic value = iterator.current;
      switch (key) {
        case '$date':
```

and is not getting properly escaped.

**Comment by LeafarDev** [comment]
Same problem here
