### ISSUE TITLE
Nested built_collections with a custom builder not working

### ISSUE THREAD

**Issue by joe776** [google/built_value.dart#506]
Consider the following class:
```
abstract class Test implements Built<Test, TestBuilder> {
  factory Test([updates(TestBuilder b)]) = _$Test;
  Test._();
  BuiltMap<String, BuiltMap<String, double>> get test;
}
```
When I add a custom builder to that class (for this issue we can basically use the automatically generated one)
```
abstract class TestBuilder extends Builder<Test, TestBuilder> {
  MapBuilder<String, BuiltMap<String, double>> test;
  factory TestBuilder() = _$TestBuilder;
  TestBuilder._();
}
```
then the BuiltValueGenerator produces the following error:
`Make builder field test have type: BuiltMap<String, BuiltMap<String, double>> (or, if applicable, builder)`.
When I change the type to `MapBuilder<String, MapBuilder<String, double>>`the generator passes, but I get other errors like `A value of type 'MapBuilder<String, BuiltMap<String, double>>' can't be assigned to a variable of type 'MapBuilder<String, MapBuilder<String, double>>'`.

I think the problem is that the generator wrongly forbids the type `MapBuilder<String, BuiltMap<String, double>>`?

**Comment by davidmorgan** [comment]
That sounds correct. I'll take a look. Thanks!
