### ISSUE TITLE
Generation enforces default value for type arguments

### ISSUE THREAD

**Issue by har79** [google/built_value.dart#507]
For example, the given code:
```
class Node<T extends Node<T>> {}

abstract class NodeTree implements Built<NodeTree, NodeTreeBuilder> {
  Node get root;
}
```
generates
```
class _$NodeTree extends NodeTree {
  @override
  final Node<Node> root;
}
```
which explicitly specifies the generic type as the default value, preventing subclasses from being assigned.

**Comment by davidmorgan** [comment]
That's a bug. Thanks!

**Comment by har79** [comment]
Yes, that makes sense, I was misunderstanding `Node<Node>` as being different from `Node`. But, yes, they should be equivalent so it looks like an analyzer error. I've filed an issue: https://github.com/dart-lang/sdk/issues/34763
