### ISSUE TITLE
Integers <==> enums

### ISSUE THREAD

**Issue by rockingdice** [google/built_value.dart#514]
From flutter, I can use the index for each enum to do the conversion but still needs some improvements since I cannot define the enum starts from 100 or other integers like in c++:
```
enum {
    kEdgeType_Left = 1 << 0,
    kEdgeType_Right = 1 << 1,
    kEdgeType_Top = 1 << 2,
    kEdgeType_Bottom = 1 << 3,
};
```
So that I could do bit calculations and still using the power of enums.

From built value, I cannot find a way to convert enums to integers or vice versa. Since all values for them are strings.
Can you make this possible for integer values or strings that can be converted to integers?

**Comment by zoechi** [comment]
If you use old-style enums there are almost no limitations, just a bit more verbose

https://stackoverflow.com/a/13901969/217408
```dart
class Fruit {
  static const APPLE = const Fruit._(0);
  static const BANANA = const Fruit._(1);

  static get values => [APPLE, BANANA];

  final int value;

  const Fruit._(this.value);
}
```
#21966 seems related

**Comment by rockingdice** [comment]
Thanks for your reply! @zoechi 
I've written a python script to do the work for generating codes to use integer enums and built value enums. So I think currently it's not an issue for me :)
