### ISSUE TITLE
Listener in Builder.build()

### ISSUE THREAD

**Issue by Solido** [google/built_value.dart#515]
Register a listener<E> and trigger when a new _$E._() != _$v in Builder.build()
so I can catch E((b) => ...)  event.
Do you think it's easily feasible ?
Thank you !

**Comment by davidmorgan** [comment]
Overriding the `build` method is not currently supported. It should seem like a reasonable thing to support somehow.

Did I understand correctly, you want to have a listener for when a value changes--i.e. it should fire if you rebuild and change some field, but _not_ if you rebuild without changing anything?

**Comment by Solido** [comment]
Yep ! I want to capture the rebuild event and inject my code directly into your lib.

I was thinking about a convention or something where we can provide the sources to inject. 
A vague idea of the process

- run build_runner generate-templates ( templates are created with default dart code)
- modify /.build_runner/templates/MyEntity.build.dart or any available templates
- run build_runner // inject overrided templates

Think is you just don't simply use Built_value it completely change the workflow of your app so we may be able to bind to it more deeply without having you handle every too specific request :D

Else I guess the best solution for me right now would be to modify the source of your package directly or can you suggest a way to put my listener somehow.

Thanks David.

**Comment by davidmorgan** [comment]
I don't think there's a good way of doing it now.

You can add to the constructor of `Entity`, so you can catch whenever an `Entity` is created ... but you have no way to know if it changed. If `Entity` has an id that you could use to look up the old value, then you could look it up and compare.

For now a locally modified `built_value_generator` might be the way to go.

**Comment by Solido** [comment]
Will thinker will that, thanks !
