### ISSUE TITLE
Upgrade Flutter analyzer version

### ISSUE THREAD

**Issue by tudor07** [google/built_value.dart#518]
`Because every version of flutter_driver from sdk depends on analyzer 0.33.0-alpha.0 and built_value_generator >=5.5.5 depends on analyzer ^0.32.1, flutter_driver from sdk is incompatible with built_value_generator >=5.5.5.`

**Comment by davidmorgan** [comment]
Thanks! Will try to take a look this week. (I'll be on vacation next week).

**Comment by tudor07** [comment]
Thanks, and I wish you a great vacation.

**Comment by davidmorgan** [comment]
It looks like analyzer_plugin will need to be updated first, I will contact the author directly.

**Comment by guitcastro** [comment]
Any updates on this issue?

**Comment by davidmorgan** [comment]
I believe `analyzer_plugin` is now updated, I will try to release a new `built_value` this week.
