### ISSUE TITLE
Is there any way to serialize Duration?

### ISSUE THREAD

**Issue by ygpark2** [google/built_value.dart#520]
```
  @override
  Iterable serialize(Serializers serializers, AudioInfo object,
      {FullType specifiedType = FullType.unspecified}) {
    final result = <Object>[
      'duration',
      serializers.serialize(object.duration,
          specifiedType: const FullType(Duration)),
      'position',
      serializers.serialize(object.position,
          specifiedType: const FullType(Duration)),
      'playerState',
      serializers.serialize(object.playerState,
          specifiedType: const FullType(PlayerState)),
    ];

    return result;
  }
```

I excerpt this code form my .g.dart file which is generated from built_value tool.

The error message is "Bad state: No serializer for 'Duration'."

So I wonder how can I make a custom serializer for the Duration class?

**Comment by davidmorgan** [comment]
That would be a reasonable class to just support directly in `built_value`. In the meantime, you could add your own `DurationSerializer`, see `DateTimeSerializer` as an example:

https://github.com/google/built_value.dart/blob/master/built_value/lib/src/date_time_serializer.dart
