### ISSUE TITLE
How to deserialize when the value can be String or boolean?

### ISSUE THREAD

**Issue by mi5t4n** [google/built_value.dart#521]
I have a JSON key, which can have boolean or String. How do I deserialize it ?

"banner": false

or 

"banner" : "https://secure.gravatar.com/avatar/776b7c06064dad971e8d376e4e9469dd?s=96&d=retro&r=g"

**Comment by paulophp** [comment]
Hello! Wouldn't it be better if you have two fields?

**Comment by mi5t4n** [comment]
I did not write the API. The API response in that manner.

**Comment by davidmorgan** [comment]
The only way to do this currently is to write your own class to represent a value that can be a string or a boolean.

e.g. call it `StringOrBoolean`; and it would have a `bool` field and a `String` field and methods to access them.

Then you need to write a serializer for it, `StringOrBooleanSerializer`. You can base it on 

https://github.com/google/built_value.dart/blob/master/built_value/lib/src/bool_serializer.dart

and

https://github.com/google/built_value.dart/blob/master/built_value/lib/src/string_serializer.dart

...this done, add it to your `Serializers` object.

**Comment by davidmorgan** [comment]
Well--actually--an alternative way would be to write a serializer plugin that splits the field into two. You could then have a `hasBanner` field and a `banner` field. Or it could even just change `false` into an empty string, that might be simplest of all...

**Comment by mi5t4n** [comment]
@davidmorgan  How do I write my own serializer plugin? Are there any resources which I can refer to.

**Comment by davidmorgan** [comment]
`StandardJsonPlugin` is an example plugin: https://github.com/google/built_value.dart/blob/master/built_value/lib/standard_json_plugin.dart

**Comment by mi5t4n** [comment]
Thanks a lot man.
