### ISSUE TITLE
Ignoring certain fields in equality tests

### ISSUE THREAD

**Issue by kentcb** [google/built_value.dart#527]
This is more a question than issue.

Just wondering what is the most idiomatic way of ignoring certain fields when it comes to equality checks. I need to generate an ID for each new value, but then I need to be able to compare these built values whilst ignoring the ID.

The best I've been able to come up with is define my own `equalsIgnoringId` method. I'm just wondering if there's a Better Way.

**Comment by zoechi** [comment]
https://github.com/google/built_value.dart/blob/08fb968cc77f0b10dfc3ce0bd40f71e6bb85c5f5/built_value/lib/built_value.dart#L99

**Comment by davidmorgan** [comment]
Exactly :) you can tag fields

`@BuiltValueField(compare: false)`

**Comment by kentcb** [comment]
Face, meet palm 🤦‍♂️ Thanks!
