### ISSUE TITLE
Support the new mixin syntax

### ISSUE THREAD

**Issue by filiph** [google/built_value.dart#542]
With Dart 2.1, it is now possible (and preferred) to write mixins like this:

```dart
mixin Foo on Bar {
  // ...
}
```

Previously, mixins were just classes.

With 6.1.6, when I define a mixin in the aforementioned way, `built_value_generator` shows an error (something about `displayName` being called on `null`). I do not use that mixin in any of the built_value classes, but it still needs to be imported by some of the files that `built_value_generator` touches.

**Comment by filiph** [comment]
Thanks for the very quick fix! Is 6.1.7 going to land on pub soon?

**Comment by davidmorgan** [comment]
Should be today or tomorrow--just taking the opportunity to fix a bunch of other minor stuff :)
