### ISSUE TITLE
firestore timestamp to datetime serializer

### ISSUE THREAD

**Issue by neerajyadav** [google/built_value.dart#543]
I don't know if I should create it as an issue or not. Firestore is changing its behaviour for storing datetime type data. Firestore has its own type `Timestamp` to store datetime data. We usually don't want to tightly couple our entities with data type from a specific vendor and want to represent date time data with language native data type which is `DateTime` in dart. I wrote a serializer plugin to convert `Timestamp` to `DateTime`. Thought I should share it, might be helpful for someone.

``` dart
import 'package:built_value/serializer.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class TimestampSerializerPlugin implements SerializerPlugin {
  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    if (object is DateTime && specifiedType.root == DateTime)
      return object.toUtc();
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
   if (specifiedType.root == DateTime)
      return Timestamp.fromMicrosecondsSinceEpoch(object); 
   return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime) {
      return object.microsecondsSinceEpoch;
      // return object.toDate();
    } else {
      return object;
    }
  }

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    return object;
  }
}
```

and then you can add it like `StandardJsonPlugin`.
``` dart
final Serializers serializers = (_$serializers.toBuilder()
      ..add(GeoPointSerializer())
      ..addPlugin(new StandardJsonPlugin())
      ..addPlugin(new TimestampSerializerPlugin()))
    .build();
```

**Comment by davidmorgan** [comment]
Nice, thanks! A few questions have come up around this, we might want to provide this as standard. It would have to be a separate package for the `firebase` dependency, though.

**Comment by vbandrade** [comment]
I have the same use case of @neerajyadav use case: class with a DateTime property and I want it saved as Timestamp in Firestore. 

unfortunately, his serializer didn't work for me but pointed me in the direction. here's the code I ended up with:

```
class DateTimeToTimestampSerializerPlugin implements SerializerPlugin {
  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (specifiedType.root == DateTime)
      return Timestamp.fromMicrosecondsSinceEpoch(object);

    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is DateTime && specifiedType.root == DateTime)
      return object.microsecondsSinceEpoch;

    return object;
  }

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    return object;
  }
}
```

**Comment by davidmorgan** [comment]
Thanks :) this definitely seems like a promising direction.

The `StandardJsonPlugin` tests should give some pointers https://github.com/google/built_value.dart/blob/master/built_value/test/standard_json_plugin_test.dart :)

**Comment by neerajyadav** [comment]
@vbandrade glad it helped. 
I saw, you are converting object in `afterSerialize` method. That assumes the object you are receiving in `afterSerialize`  is `int` which is converted from `DateTime` in `beforeSerialize` method.

Similarly in `beforeDeserialize` you have 
``` dart
if (object is DateTime && specifiedType.root == DateTime)
``` 
I think this approach interferes the standard `DateTime` serialization.

@davidmorgan could you help us deciding which one is more efficient.

**Comment by vbandrade** [comment]
@neerajyadav, what do you mean? Interfere the standard DateTime serialization is exactly what I want.

I want to handle my data as DateTime in dart/flutter and data saved as Timestamp in Firestore. Also, my model shouldn't depend on Firestore.

here's the repo with the code in use:
https://github.com/vbandrade/porquinho

**Comment by neerajyadav** [comment]
I think when you are converting from `Timestamp` to `DateTime` then incoming object in `beforeDeserialize` should be `Timestamp` and `specifiedType` should be `DateTime`.  For me this works.
``` dart
if (object is Timestamp && specifiedType.root == DateTime)
```
Theoretically your code 
``` dart
if (object is DateTime && specifiedType.root == DateTime)
``` 
says, do the conversion when incoming data type is `DateTime` as well as outgoing is also `DateTime`. 

If both the types are `DateTime` then standard serializers can handle them itself. The plugin should participate only when `Timestamp` is converted to `DateTime`.

**Comment by vbandrade** [comment]
I see what you mean, and I agree with you. But this is what I see on that breakpoint:
![image](https://user-images.githubusercontent.com/1085485/50148328-663f7080-029f-11e9-9d26-211bc2948e1d.png)

So, here's what I gather from the code + breakpoint info:
Even tough Firestore uses Timestamp, at least in version 0.8.2+3, it comes down as DateTime. A couple weeks back there was a warning related to DateTime/Timestamp that could be related (found this issue, but its kinda old: https://github.com/flutter/flutter/issues/21487) and I admit I didn't look any further if some kind of conversion is made.

So, as built_value expects a value in microsecondsSinceEpoch to deserialize to DateTime, this conversion is made in `beforeDeserialize`

with this serializer, I'm able to read from and write to Firestore.

**Comment by neerajyadav** [comment]
@vbandrade well its strange. For me the incoming object is `Timestamp`. Are you using any other serializer which might do the conversion? I have this `firestore` setting enabled.
``` dart
await _firestore.settings(
        timestampsInSnapshotsEnabled: true,
        persistenceEnabled: true,
        sslEnabled: true);
```
I was also receiving the same "timestamp breaking" warning. After this setting enabled the warning is gone though.

**Comment by neerajyadav** [comment]
Also @davidmorgan one limitation I found in my above implementation is, it converts all the `DateTime` to `UTC`. Is there a way I can serialize dates to local datetime? This way I won't need to convert dates to local datetime everywhere. It can be a central point to convert dates to local timezone.

**Comment by vbandrade** [comment]
I wasn't using any settings because I didn't know how to set them (guess this is one more thing you taught me on this thread, tks 🙇 )

Just ran my app with paying attention to the debug console and seems like you're right. Running on default settings I got the message: 
```
W/Firestore(25854): (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
W/Firestore(25854): To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
W/Firestore(25854):
W/Firestore(25854): FirebaseFirestore firestore = FirebaseFirestore.getInstance();
W/Firestore(25854): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
W/Firestore(25854):     .setTimestampsInSnapshotsEnabled(true)
W/Firestore(25854):     .build();
W/Firestore(25854): firestore.setFirestoreSettings(settings);
W/Firestore(25854):
W/Firestore(25854): With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
W/Firestore(25854):
W/Firestore(25854): // Old:
W/Firestore(25854): java.util.Date date = snapshot.getDate("created_at");
W/Firestore(25854): // New:
W/Firestore(25854): Timestamp timestamp = snapshot.getTimestamp("created_at");
W/Firestore(25854): java.util.Date date = timestamp.toDate();
W/Firestore(25854):
W/Firestore(25854): Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
```

but from what I remember, the message wasn't as detailed and complete like this one. I'll update my settings. Thanks again. :)

**Comment by neerajyadav** [comment]
I think there is an issue with my serializer also. I edited the description for the fix. Earlier I was doing conversion in `beforeSerialize` method. When serilization occurs it converts it to `int` microseconds. I moved the conversion to `afterSerialize` method and it is working fine. Updated the code also.

**Comment by neerajyadav** [comment]
Another edit: If you pass local non-utc date for `serialization` it will throw an error. To handle this, I made another change. In `beforeSerialize` method, converting date to `utc`. Updated the code.

**Comment by neerajyadav** [comment]
After fixing all the bugs in debug mode I now stcuk with issues in release mode. I don't know what's the root cause but if is working in `debug` mode it should work in `release` mode. I think it is something with `firestore`. I'm able to receive data, serialize it and deserialize it when connected to `vscode` and run the `flutter` project.

When I make `apk` with `flutter build apk` and run `apk` on my android device, deserialization breaks. Here is the error I'm getting.
``` log
'UserEntity' failed due to: Deserializing '01/03/1988' to 'DateTime' failed due to: 
type '_OneByteString' is not a subtype of type 'int' in type cast
``` 
What is `_OneByteString` type? The same serializer is working absolutely fine in debug mode.

@davidmorgan please jump in. I seriously need your help here.

**Comment by davidmorgan** [comment]
@vbandrade There's no support for serializing with non-local datetime--as that's very likely to cause problems. You could instead add a getter that converts to local time; or do it when you render...

@neerajyadav I guess `_OneByteString` is just some implementation of `String`; probably accurate just to pretend the error message says `String`. 

Which code is trying to turn `01/03/1988` into a `DateTime`? If it's in your serializer code, then you need to account for the fact that you might have a `String`. Right now it looks like you're getting expecting an integer here:

```
    if (specifiedType.root == DateTime)
      return Timestamp.fromMicrosecondsSinceEpoch(object);
```

--so maybe check if the type is a `String`, and if so, maybe use something to parse it ... `DateTime.parse`?

**Comment by davidmorgan** [comment]
(BTW I've been watching this discussion with interest, but don't have a lot of time to get into it now, sorry about that!)

**Comment by neerajyadav** [comment]
@davidmorgan  no problem. Though my error is resolved itself without any code change. I don't know the exact cause. I will try to dig down and recreate the issue again. If find something, will try to update/optimize the `serializer`.

**Comment by vbandrade** [comment]
hey all,

I´ve added the setup to my firestore and now my serializer is almost identical to @neerajyadav's

```dart
class DateTimeToTimestampSerializerPlugin implements SerializerPlugin {
  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (object is int && specifiedType.root == DateTime)
      return Timestamp.fromMicrosecondsSinceEpoch(object);

    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime)
      return object.microsecondsSinceEpoch;

    return object;
  }

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    return object;
  }
}
```
 I've decided to not change the value of the object being serialized (in `beforeSerialize`). imo is not the serializer responsibility to guarantee DateTime in UTC.

I ran in debug and release mode in the emulator and in my device and all worked out fine. could not reproduce the _OneByteString error @neerajyadav had.

**Comment by neerajyadav** [comment]
@vbandrade try to send local datetime to `firestore` document. 
During deserialization `built_value` automatically converts `DateTime` coming from server to UTC.
But when it comes to serializing `built_value` require UTC `DateTime` only.  Create your object with local `DateTime` and try to serialize and save it to `firestore`. You will get the error.
Regarding `_OneByteString`, I also received once. Don't know why that came but it was working fine after that.

**Comment by jimmyff** [comment]
> Nice, thanks! A few questions have come up around this, we might want to provide this as standard. It would have to be a separate package for the `firebase` dependency, though.

How would you get around the requirement of including the dependency? At the moment I've got a temporary dummy serializer in my platform agnostic 'core' package and I'm using a conditional imports for platform specific serializers.  Like this:

```dart
import 'serializers/date_time_serializer.dart'
    if (dart.library.io) 'package:mobile/serializers/date_time_serializer.dart'
    if (dart.library.js) 'package:web/serializers/date_time_serializer.dart';
```

**Comment by dinbtechit** [comment]
> I don't know if I should create it as an issue or not. Firestore is changing its behaviour for storing datetime type data. Firestore has its own type `Timestamp` to store datetime data. We usually don't want to tightly couple our entities with data type from a specific vendor and want to represent date time data with language native data type which is `DateTime` in dart. I wrote a serializer plugin to convert `Timestamp` to `DateTime`. Thought I should share it, might be helpful for someone.
> 
> ```dart
> import 'package:built_value/serializer.dart';
> import 'package:cloud_firestore/cloud_firestore.dart';
> 
> class TimestampSerializerPlugin implements SerializerPlugin {
>   @override
>   Object beforeSerialize(Object object, FullType specifiedType) {
>     if (object is DateTime && specifiedType.root == DateTime)
>       return object.toUtc();
>     return object;
>   }
> 
>   @override
>   Object afterSerialize(Object object, FullType specifiedType) {
>    if (specifiedType.root == DateTime)
>       return Timestamp.fromMicrosecondsSinceEpoch(object); 
>    return object;
>   }
> 
>   @override
>   Object beforeDeserialize(Object object, FullType specifiedType) {
>     if (object is Timestamp && specifiedType.root == DateTime) {
>       return object.microsecondsSinceEpoch;
>       // return object.toDate();
>     } else {
>       return object;
>     }
>   }
> 
>   @override
>   Object afterDeserialize(Object object, FullType specifiedType) {
>     return object;
>   }
> }
> ```
> 
> and then you can add it like `StandardJsonPlugin`.
> 
> ```dart
> final Serializers serializers = (_$serializers.toBuilder()
>       ..add(GeoPointSerializer())
>       ..addPlugin(new StandardJsonPlugin())
>       ..addPlugin(new TimestampSerializerPlugin()))
>     .build();
> ```

This is not working.  I'm getting the following error. Have you seen this error before?

```
W/instapie.speed( 6707): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
E/flutter ( 6707): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Deserializing '[lastName, AAAA, gender, male, displayName, Dinesh, hasChildren, false...' to 'ProfileData' failed due to: Deserializing 'Timestamp(seconds=1563802759, nanoseconds=272000000)' to 'String' failed due to: type 'Timestamp' is not a subtype of type 'String' in type cast
E/flutter ( 6707): #0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:153:11)
E/flutter ( 6707): #1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:104:18)
E/flutter ( 6707): #2      BuiltJsonSerializers.deserializeWith (package:built_value/src/built_json_serializers.dart:35:12)
E/flutter ( 6707): #3      new ProfileBloc.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:speedy/bloc/profile/profile_bloc.dart:26:51)
E/flutter ( 6707): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 6707): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 6707): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 6707): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 6707): #8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 6707): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter ( 6707): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter ( 6707): #11     _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 6707): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6707): #13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6707): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 6707): #15     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6707): #16     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6707): #17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6707): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 6707): #19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 6707): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```

**Comment by kwintAl** [comment]
Before built_value I did serialization by hand.
Firebase SDK gives you a local DateTime object, so I would say, to do not break my code, deserialization with built_value methods should do it same way.

> You could instead add a getter that converts to local time; or do it when you render...

is a litte bit overhead doing it this way (my opinion).

I think the conversion **UTC <--> local** should be done in plugin.
here is @vbandrade code I modified for my use case.

@vbandrade & @neerajyadav thank you for sharing your code.


```dart
import 'package:built_value/serializer.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class DateTimeToTimestampSerializerPlugin implements SerializerPlugin {
  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (object is int && specifiedType.root == DateTime) {
      return Timestamp.fromMicrosecondsSinceEpoch(object - _getOffsetInMicroseconds());
    }

    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime)
      return object.toDate().microsecondsSinceEpoch + _getOffsetInMicroseconds();
    
    return object;
  }

  int _getOffsetInMicroseconds() => DateTime.now().timeZoneOffset.inMicroseconds;

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    return object;
  }
}
```

I do not write timestamps to Firestore, so **the serialize method is not tested**

**Comment by mahdizakizadeh** [comment]
@neerajyadav I've never used serializes in dart. Can you explain more so I can use this in my code?

**Comment by neerajyadav** [comment]
@mahdizakizadeh Author provided two very good blogs to get started. You can use them.
- [built_value for Immutable Object Models](https://medium.com/@davidmorgan_14314/darts-built-value-for-immutable-object-models-83e2497922d4#.48dyezxcl)
- [built_value for Serialization](https://medium.com/@davidmorgan_14314/darts-built-value-for-serialization-f5db9d0f4159#.h12y94wu7)

**Comment by flutterapptesting** [comment]
Can someone suggest how to convert DateTime into Timestamp so it can be stored into firestore.

          Timestamp _dueDate = onValue as Timestamp; // this line is giving an error with or without cast.

E/flutter ( 9348): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'DateTime' is not a subtype of type 'Timestamp' in type cast


Here's the code:
//.......................................................
  Widget inputDueDate() {
    return Padding(padding: new EdgeInsets.only(left: 10.0, right: 10.0),
      child: TextField(
        onTap: ()=> ShowDateCalenddar(context, ).then((onValue){
          Timestamp _dueDate = onValue as Timestamp; // Convert DateTime into timestamp so it can be stored into firebase document
          printText('ShowDateCalenddar:', '${_dueDate.toString()} , $onValue');
        }),

        style: Theme.of(context).textTheme.body2,
        controller: _dueDateController,
        decoration: InputDecoration(labelText: homeworkConfig.dueDateLabel,
          enabled: (widget.CRUDFlag == 'READ' ? false: true),
        ),
        maxLines: 1,
      ),
    );
  }


  Future<DateTime> ShowDateCalenddar(BuildContext context, ) async {
    final DateTime picked = await showDatePicker(
        context: context,
        initialDate: DateTime.now(),
        firstDate: DateTime(2019, 1),
        lastDate: DateTime(2101));
    if (picked != null) {
      setState(() {
        _dueDateController = TextEditingController(text: picked.toString());
      });
    }
    return picked;
  }

**Comment by neerajyadav** [comment]
@flutterapptesting In case it is related to `built_value` serialization, you can use below code for conversion.
``` dart
Timestamp.fromMicrosecondsSinceEpoch(object); // here object int MicrosecondsSinceEpoch. 
``` 

otherwise I think there is a direct method in `Timestamp` for converting from `datetime`.  Something like `Timestamp.fromDatetime(datetime)`

**Comment by feinstein** [comment]
The plugin posted by @neerajyadav doesn't work for me, I just want to desserialize a Firestore Map into a value object, but `beforeDeserialize` `if (object is Timestamp && specifiedType.root == DateTime) {` is never true, as the `specifiedType` is always `Timestamp` and not `DateTime`.

**Comment by VictorUvarov** [comment]
I've updated the plugin to convert UTC Datetimes back into local date times in the app. I also fixed some TimeStamp error when serializing a DateTime into a TimeStamp. This has worked perfectly for me so far.
```dart
import 'package:built_value/serializer.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class TimestampSerializerPlugin implements SerializerPlugin {
  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    if (object is DateTime && specifiedType.root == DateTime) {
      return object.toUtc();
    }
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (specifiedType.root == DateTime) {
      if (object.runtimeType == int) {
        return Timestamp.fromMicrosecondsSinceEpoch(object);
      } else if (object.runtimeType == DateTime) {
        return Timestamp.fromDate(object);
      }
    }
    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime) {
      return object.toDate().toLocal().toString();
    }
    return object;
  }

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime) {
      return object.toDate().toLocal();
    } else if (object is DateTime && specifiedType.root == DateTime) {
      return object.toLocal();
    }
    return object;
  }
}

```

**Comment by VictorUvarov** [comment]
For me I wanted to server to hold the TimeStamp as UTC and the client would receive a local DateTime. 
```dart
class TimestampSerializerPlugin implements SerializerPlugin {
  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    if (object is DateTime && specifiedType.root == DateTime) {
      return object.toUtc();
    }
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (object is int && specifiedType.root == DateTime) {
      return Timestamp.fromMicrosecondsSinceEpoch(object);
    }
    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime) {
      return object.microsecondsSinceEpoch;
    }

    return object;
  }

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    if (object is DateTime && specifiedType.root == DateTime) {
      return object.toLocal();
    }
    return object;
  }
}
```

**Comment by flutterapptesting** [comment]
Thank You @neerajyadav  and everyone for the response.

**Comment by minikin** [comment]
I'm wondering, does this solution works for anyone?

**Comment by dinbtechit** [comment]
> I'm wondering, does this solution works for anyone?

Yes it did for me.

**Comment by minikin** [comment]
@dinbtechit I super keen to learn how?

**Comment by minikin** [comment]
What I'm doing wrong?

**Comment by dinbtechit** [comment]
ah! Try getting rid of the `toDate()`

Change from:
```
 @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime) {
      return object.toDate().microsecondsSinceEpoch;
    }

    return object;
  }

```
to

```
 @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime) {
      return object.microsecondsSinceEpoch;
    }

    return object;
  }

```

**Comment by minikin** [comment]
@dinbtechit thanks you!

What about serialization? It's crashing here:
```dart
  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (object is int && specifiedType.root == DateTime) {
      return Timestamp.fromMicrosecondsSinceEpoch(object);
    }
    return object;
  }
```

**Comment by dinbtechit** [comment]
Here is the code that I use:

```dart
library serializers;

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:speedy/model/profile_data.dart';
import 'package:built_value/standard_json_plugin.dart';

part 'serializers.g.dart';

@SerializersFor(const [
  ProfileData
])
final Serializers serializers =  (
    _$serializers.toBuilder()
      ..addPlugin(StandardJsonPlugin())
      ..addPlugin(DateTimeToTimestampSerializerPlugin())
).build();


class DateTimeToTimestampSerializerPlugin implements SerializerPlugin {
  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (object is int && specifiedType.root == DateTime)
      return Timestamp.fromMicrosecondsSinceEpoch(object);

    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime)
      return object.microsecondsSinceEpoch;

    return object;
  }

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    return object;
  }
}
```

**Comment by minikin** [comment]
@dinbtechit Thank you for sharing! 
I still have `Exception has occurred.
JsonUnsupportedObjectError (Converting object to an encodable object failed: Instance of 'Timestamp')` 

Can I have a quick look into `ProfileData`, please?

**Comment by dinbtechit** [comment]
It has to be the field datatype should be `DateTime` not `Timestamp`

```dart
library profile_data;

import 'dart:convert';

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import 'serializers.dart';

part 'profile_data.g.dart';

abstract class ProfileData implements Built<ProfileData, ProfileDataBuilder> {

  static Serializer<ProfileData> get serializer => _$profileDataSerializer;

  String get uid;
  @nullable
  String get photoURL;
  @nullable
  String get firstName;
  @nullable
  String get lastName;
  @nullable
  String get email;
  @nullable
  String get profileDisplayName;
  @nullable
  BuiltList<String> get picturesUrls;
  @nullable
  DateTime get lastLogin;
  @nullable
  String get aboutYou;
  @nullable
  String get displayName;
  @nullable
  String get jobTitle;
  @nullable
  DateTime get dateOfBirth;
  @nullable
  bool get hasChildren;
  @nullable
  String get gender;
  @nullable
  BuiltList<String> get sexualOrientation;


  ProfileData._();

  factory ProfileData([void Function(ProfileDataBuilder) updates]) = _$ProfileData;

   String toJson() {
    return json
        .encode(serializers.serializeWith(ProfileData.serializer, this));
  }


  static ProfileData fromJson(String jsonString) {
    return serializers.deserializeWith(
        ProfileData.serializer, json.decode(jsonString));
  }

  static ProfileData fromMap(Map<String, dynamic> data) {
    return serializers.deserializeWith(
        ProfileData.serializer, data);
  }

}
```

**Comment by minikin** [comment]
@dinbtechit Thank you again for sharing!
Your class looks exactly like mine...

>  think the field datatype should be DateTime not Timestamp
What do you mean?

**Comment by dinbtechit** [comment]
can you add some break points and identify exactly which attributes blows up during the serialization? You want to inspect the data that's being passed in.

**Comment by minikin** [comment]
End up storing Timestamp as a string.

**Comment by larssn** [comment]
There are a lot of versions of `TimestampSerializerPlugin` in this thread, which can be confusing. Here's what I would consider the absolute final version of this plugin:

```dart
import 'package:built_value/serializer.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

/// Converts a Firestore [Timestamp] to a [DateTime] and vise versa.
///
/// Implementation note: It technically does not convert to a DateTime, since this is already handled by the existing plugin: 'package:built_value/src/date_time_serializer.dart'
/// which is loaded by default.
class TimestampSerializerPlugin implements SerializerPlugin {
  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    if (object is DateTime && !object.isUtc && specifiedType.root == DateTime) {
      return object.toUtc();
    }

    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (object is int && specifiedType.root == DateTime) {
      return Timestamp.fromMicrosecondsSinceEpoch(object);
    }

    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime) {
      return object.microsecondsSinceEpoch;
    }

    return object;
  }

  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    return object;
  }
}
```

The only optimization is the `!object.isUtc` check in `beforeSerialize`.

It works.

**Comment by jaredanderton** [comment]
Thank you for providing this! 

I actually had to adjust the overrides, to handle nullable returns are param `Object`s:

```dart
import 'package:built_value/serializer.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

/// Converts a Firestore [Timestamp] to a [DateTime] and vise versa.
///
/// Implementation note: It technically does not convert to a DateTime, since this is already handled by the existing plugin: 'package:built_value/src/date_time_serializer.dart'
/// which is loaded by default.
class TimestampSerializerPlugin implements SerializerPlugin {
  @override
  Object? beforeSerialize(Object? object, FullType specifiedType) {
    if (object is DateTime && !object.isUtc && specifiedType.root == DateTime) {
      return object.toUtc();
    }

    return object;
  }

  @override
  Object? afterSerialize(Object? object, FullType specifiedType) {
    if (object is int && specifiedType.root == DateTime) {
      return Timestamp.fromMicrosecondsSinceEpoch(object);
    }

    return object;
  }

  @override
  Object? beforeDeserialize(Object? object, FullType specifiedType) {
    if (object is Timestamp && specifiedType.root == DateTime) {
      return object.microsecondsSinceEpoch;
    }

    return object;
  }

  @override
  Object? afterDeserialize(Object? object, FullType specifiedType) {
    return object;
  }
}
```
