### ISSUE TITLE
`BuiltValueField(compare: false)` as a default for an entity

### ISSUE THREAD

**Issue by matanlurey** [google/built_value.dart#557]
For example, for domain objects that have an `id` or identity field and are not user-creatable (i.e. every instance of this object is created by the system, a sort of enum-like with fields that are serialized by not domain mutable):

```dart
@BuiltValue(identity: true)
abstract class Role implements Built<Role, RoleBuilder> {
  factory Role._build(void Function(RoleBuilder) b) = _$Role;
  Role._();

  @BuiltValueField(compare: true)
  String get id;

  int get salary;
}

final employee = Role._build((b) => b..id = 'employee'..salary = 10000);
final supervisor = Role._build((b) => b..id = 'supervisor'..salary = 20000);
final manager = Role._build((b) => b..id = 'manager'..salary = 40000);
```

The alternative, as listed in https://github.com/google/built_value.dart/issues/401, is to add `@BuiltValueField(compare: false)` to every field _but_ `id`, which is what I'm currently doing.

**Comment by davidmorgan** [comment]
That makes sense, thanks. I'll take a look.

**Comment by davidmorgan** [comment]
Got a second request for this, bumping the priority.
