### ISSUE TITLE
No documentation for memoized

### ISSUE THREAD

**Issue by Will-W** [google/built_value.dart#561]
There is no documentation in the README, the API Reference from the package page, or the code about `@memoized`. This doesn't help discovery and doesn't help correct usage.

In my case, it wasn't clear that the annotation would only be honoured on getters, rather than methods that take arguments, and there is no message in the generator telling you that, so I was silently not getting memoization when I thought I was.

[An aside: is there a particular reason why arbitrary methods can't be memoized, avoiding the need for a separate library like reselect? And if not, is an error in the generator possible - I can file a separate issue]

**Comment by davidmorgan** [comment]
Thanks for filing! Yes, this should be better documented. I'll take a look.

Do you mean memoizing zero argument methods, or all methods? Memoizing methods with arguments is quite a bit more complicated as a feature since you'll have to keep a map of values. Is that something people want?

**Comment by Will-W** [comment]
> Memoizing methods with arguments is quite a bit more complicated as a feature since you'll have to keep a map of values

Ah yes, of course you'd need a more complicated cache - I hadn't thought the implementation through.

It would be convenient for me, but I'm not 100% convinced that my architecture is right. I need to extract stuff from my model (I'm using flutter_built_redux) with arguments, but it may not be appropriate for that code to live in the model class.  It may be more appropriate to have a separate layer between the model and my presentation code that does the extraction. This is particularly true if the extraction needs to visit multiple parts of my model, as then the top level class in the model would end up with lots of stuff in it, and memoization would be negatively affected by unrelated parts of the tree changing.
