### ISSUE TITLE
Private classes are not entirely supported

### ISSUE THREAD

**Issue by matanlurey** [google/built_value.dart#564]
For example, the following:

```dart
part 'private.g.dart';

class _PrivateData implements Built<_PrivateData, _PrivateDataBuilder> {
  factory _PrivateData(void Function(_PrivateDataBuilder) b) = _$PrivateDataBuilder;
  _PrivateData._();
}
```

... works fine. If I try to add a `Serializer`, though:

```dart
part 'private.g.dart';

class _PrivateData implements Built<_PrivateData, _PrivateDataBuilder> {
  static Serializer<_PrivateData> get serializer => _$_PrivateDataSerializer;

  factory _PrivateData(void Function(_PrivateDataBuilder) b) = _$PrivateDataBuilder;
  _PrivateData._();
}
```

... the name `_$_PrivateDataSerializer` seems to have a conflict - it is actually the `class` (making the above code illegal, trying to return a `Type` as a `Serializer). I can't use the actual field, `_$privateDataSerializer`, because then the builder fails saying my code is wrong.

Workaround so far is using a public class instead.

**Comment by davidmorgan** [comment]
I'll take a look; private classes ought to be mostly serialization, but I think there will be problems with generics, where we have to be able to inject factories for builders for each generic type that's used. (e.g. `() => FooBuilder<Bar>()` if you use `Foo<Bar>` in a field).

Still, supporting as far as we can seems plausible.
