### ISSUE TITLE
Deserializing an EnumClass object should provide a Map but it is List<dynamic> type

### ISSUE THREAD

**Issue by sunkistmehta** [google/built_value.dart#574]
`SurveyMedium` can be of two types: `Web` and `Mobile`, hence, `EnumClass`. However, the only key value pair of interest within that sub-json is `InternalIdentifier`.  The `surveyMedium` member of the `Survey` class should be deserialized to `WEB` and not the entire sub-json.

``` json
{
    "Survey": {
        "SurveyMedium": {
          "Id": "1234-abcd-xyz-7890",
          "InternalIdentifier": "WEB",
          "Value": "Web"
        }
    }
}

```

``` dart
class SurveyMedium extends EnumClass {
  static Serializer<SurveyMedium> get serializer => _$surveyMediumSerializer;

  @BuiltValueEnumConst(wireName: 'WEB')
  static const SurveyMedium web = _$web;
  @BuiltValueEnumConst(wireName: 'MOBILE')
  static const SurveyMedium mobile = _$mobile;

  const SurveyMedium._(String name) : super(name);

  static BuiltSet<SurveyMedium> get values => _$surveyMediumValues;
  static SurveyMedium valueOf(String name) => _$surveyMediumValueOf(name);
}
```

```dart
abstract class Survey implements Built<Survey, SurveyBuilder> {

  SurveyMedium get surveyMedium;

  Survey._();
  factory Survey([updates(SurveyBuilder b)]) = _$Survey;
  static Serializer<Survey> get serializer => _$surveySerializer;
}
```

To accomplish this, I am trying to write a Serializer plugin `InternalIdSerializerPlugin`.

``` dart
class InternalIdSerializerPlugin implements SerializerPlugin {

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    
    if (specifiedType.root == SurveyMedium) {
      final mapObj = object as Map<String, dynamic>; // this fails
      final internalId = mapObj['InternalIdentifier'] as String;
      return internalId;
    }
    return object;
  }

}
```

It fails trying to cast the `object` as a `Map`. Exact error is: 
`type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast`

Upon debugging I found out that the `object` is of type `List<dynamic>` with odd indices representing the keys and even indices representing the values of the map/json i.e.

```
obj[0]: 'id'
obj[1]: '1234-abcd-xyz-7890'
obj[2]: 'InternalIdentifier'
obj[3]: 'WEB'
obj[2]: 'Value'
obj[3]: 'Web'
```

The object is a `map` if I implement `SurveyMedium` as a `built_value` type and not extend an `EnumClass`. However, I want the features of an enum class for my business logic. 

~~How can I solve this issue?~~

**EDIT**
For now, I have a solution which creates a map out of that list. But I am interested in knowing why is it returning a list and not a map?

**Comment by BrennanGambling** [comment]
You could do something like this:
```dart
//List for the MapEntry's
final List<MapEntry<String, dynamic>> entries = List();
//make sure the length of object is even, if not subtract 1 to make it even.
//this is done as the for loop increments by 2 and a odd value would result 
//in an out of bounds error.
final int numEntries =
    object.length.isEven ? object.length : object.length - 1;
//for each pair of keys and values
for (int i = 0; i < numEntries; i += 2) {
  //add a MapEntry to the entries List.
  entries.add(MapEntry(object[i], object[i + 1]));
}
//create the Map from an Iterable of MapEntry's
final mapObj = Map.fromEntries(entries);
```

**Comment by sunkistmehta** [comment]
Thanks for that response, @BrennanGambling. I have done something similar for now but through this issue, I meant to ask why is it returning a list and not a map.
