### ISSUE TITLE
Getter not found: 'BuiltList'

### ISSUE THREAD

**Issue by PauloKeller** [google/built_value.dart#581]
It's more a doubt than a bug
I'm trying to build this json structure

```
{
  "balance": 0,
  "results": [
    {
      "id": 0,
      "type": "coin",
      "subType": "string",
      "balance": 0,
      "fail": true
    }
  ],
  "links": {
    "ref": "string",
    "href": "string",
    "method": "GET"
  }
}
```
but I want to change the wired class for 'results' key: 
``` 
@BuiltValueField(wireName: 'results')
  BuiltList<Finance> get finances;
```

In my serializers I add something like this:
```
..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Finance)]),
          () => new ListBuilder<Finance>()))
```

So I got this error:

```
serializers.g.dart:17:26: Error: Getter not found: 'BuiltList'.
          const FullType(BuiltList, const [const FullType(Finance)]),

serializers.g.dart:18:21: Error: Method not found: 'ListBuilder'.
          () => new ListBuilder<Finance>()))
```

So I forgot something!? 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!

**built_collection: 4.1.0
built_value: 6.3.0**

**Comment by iamaravindh** [comment]
y this got closed?

**Comment by jordychetty** [comment]
Ensure you've imported `built_collection` in `serializers.dart`:
```dart
import 'package:built_collection/built_collection.dart';
```

**Comment by sh1l0n** [comment]
> Ensure you've imported `built_collection` in `serializers.dart`:
> 
> ```dart
> import 'package:built_collection/built_collection.dart';
> ```

lol thx :)
