### ISSUE TITLE
Best way to run builder in development?

### ISSUE THREAD

**Issue by maxlapides** [google/built_value.dart#583]
Hey I'm loving `built_value`. Right now, I'm using VSCode, and I have my `launch.json` set up like this:

```
{
  [
    {
      "name": "My App",
      "request": "launch",
      "type": "dart",
      "program": "lib/main.dart",
      "preLaunchTask": "flutter: build_runner watch",
    }
  ]
}
```

That way, when I start the VSCode debugger, it runs the build runner in a Terminal tab. But, the IDE isn't updated immediately when code is generated. Is this how you would recommend setting up the project for development, or should I be using `build.yaml` somehow?

Thanks so much!

**Comment by davidmorgan** [comment]
I don't know anything about VSCode, I'm afraid; that looks reasonable.

Recognizing that the generated code changed should be some combination of VSCode and the dart analyzer; it may make sense to file an issue there: https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server

**Comment by maxlapides** [comment]
Okay cool. Do you typically use Android Studio? I'm just curious whether you intend for there to essentially be a watcher alive in a Terminal window during development, or if there's some more elegant way of watching for file changes?

**Comment by davidmorgan** [comment]
Having a watcher alive in a terminal window is how I do it :)

**Comment by maxlapides** [comment]
Gotcha thanks!
