### ISSUE TITLE
Suggestion - Adding an Article about Custom Serializers

### ISSUE THREAD

**Issue by Vanethos** [google/built_value.dart#586]
First, I have to deeply apologize for the shameless plug here, but I will try to explain my reasoning behind it:

In your latest version you added `@BuiltValueSerializer`, a feature that I have been looking forward to for some time now. However, I did not find any documentation about it and had to go into the Unit Tests (by going to the changelog of the commit) to see how it worked.

For that reason, and since some might have to use it in the future, I have decided to write a small article to explain how can we build a custom serializer in a pratical case.

If you do not feel that this is a good addition, if you want, I can try to create a small piece of documentation for this project.

The article in question: https://medium.com/@solid.goncalo/creating-custom-built-value-serializers-with-builtvalueserializer-46a52c75d4c5

Thank you.

**Comment by davidmorgan** [comment]
Nice article :)

Sorry for the slow response, I've been on vacation.

Were you thinking of linking to it from the `Articles` section in the `README.md`? Or maybe the `Tutorials` section? Either sounds good to me.

**Comment by Vanethos** [comment]
Hey David!

First: thanks! 😄 

I think it's more a `Tutorial`, what do you think?

**Comment by davidmorgan** [comment]
Added. Thanks :)
