### ISSUE TITLE
generic deserialize

### ISSUE THREAD

**Issue by cnzhuzi** [google/built_value.dart#588]
Hi David!

I try to build a sample to deserialize json string to generic model, like **`User<Address<Geo>>`**  (https://github.com/cnzhuzi/Flutter-Json-Generic-with-built_value-Sample)

Is this the right way to deal with generic deserialize?
Is there any convenient method at present, or update plan in the future?

Thank you very much! 🤝 @davidmorgan

**Comment by dave26199** [comment]
That looks correct--only comment is you don't need `@BuiltValueField` everywhere, the wire name defaults to the field name.

If you can be more specific about what you would like to see, I'm open to feature requests :)

Thanks!

**Comment by cnzhuzi** [comment]
> That looks correct--only comment is you don't need `@BuiltValueField` everywhere, the wire name defaults to the field name.
> 
> If you can be more specific about what you would like to see, I'm open to feature requests :)
> 
> Thanks!

Thank you!  I know that @BuiltValueField  is not essential, it's generate by  json2builtvalue converter 😜

I expect  the 'Serializers' class, the registration of builderFactory and generic deserialize code can be easier to use, such as registering them with some annotations.
