### ISSUE TITLE
How to parse nested JSON in built_value library

### ISSUE THREAD

**Issue by TahaMalas** [google/built_value.dart#592]
I'm trying to parse this JSON object using built_value library, I managed to get the base response

```
{
    "status": true,
    "message": "",
    "data": {
        "current_page": 1,
        "data": [
            {
                "id": 30,
                "id_f": "D01"
            },
            {
                "id": 31,
                "id_f": "D02"
            },
        ],
        "first_page_url": "http://192.168.1.120:8000/api/requests/driver?page=1",
        "from": 1,
        "last_page": 2,
        "last_page_url": "http://192.168.1.120:8000/api/requests/driver?page=2",
        "next_page_url": "http://192.168.1.120:8000/api/requests/driver?page=2",
        "path": "http://192.168.1.120:8000/api/requests/driver",
        "per_page": 20,
        "prev_page_url": null,
        "to": 20,
        "total": 34
    }
}


```

I managed to parse the BaseResponse which I found out from this helpful [anwer](https://stackoverflow.com/questions/51575371/flutter-how-to-parsed-nested-json-to-a-class-with-generics/51890211#51890211)

Put I got stuck because I want to finally get an object like this

`BaseResponse<PaginateResponse<BuiltList<Deliveries>>>
`
Is there any solution to do that with the awesome built_value library?

**Comment by davidmorgan** [comment]
This might help, you can give it JSON and it will generate the Dart code for you:

**Comment by TahaMalas** [comment]
> This might help, you can give it JSON and it will generate the Dart code for you:
> 
> https://charafau.github.io/json2builtvalue/

I tried it but it's not giving me generics, So if I want to use BaseResponse or PaginateResponse with another data I can't do that, I managed to implement something like this BaseResposne<PaginatedResposne<Deliveries>> But the data in paginated response is not BuiltList, So basically I can't parse the JSON I want, when add BuiltList to it it breaks miserably, any ideas

**Comment by davidmorgan** [comment]
I can't really follow what you're trying--maybe you could post the object code, and the JSON you want it to map to? Thanks.

**Comment by TahaMalas** [comment]
That's the JSON I want to parse 

```
{
    "status": true,
    "message": "",
    "data": {
        "current_page": 1,
        "data": [
            {
                "id": 30,
                "id_f": "D01"
            },
            {
                "id": 31,
                "id_f": "D02"
            },
        ],
        "first_page_url": "http://192.168.1.120:8000/api/requests/driver?page=1",
        "from": 1,
        "last_page": 2,
        "last_page_url": "http://192.168.1.120:8000/api/requests/driver?page=2",
        "next_page_url": "http://192.168.1.120:8000/api/requests/driver?page=2",
        "path": "http://192.168.1.120:8000/api/requests/driver",
        "per_page": 20,
        "prev_page_url": null,
        "to": 20,
        "total": 34
    }
}

```

That's my BaseResponse class 

```
abstract class BaseResponse<T>
    implements Built<BaseResponse<T>, BaseResponseBuilder<T>> {
    bool get status;

    String get message;

    @nullable
    T get data;

    BaseResponse._();

    factory BaseResponse([updates(BaseResponseBuilder<T> b)]) = _$BaseResponse<T>;

    static Serializer<BaseResponse> get serializer => _$baseResponseSerializer;
}

```

And that's my PaginateResponse 

```
abstract class PaginateResponse<T>
    implements Built<PaginateResponse<T>, PaginateResponseBuilder<T>> {

  @BuiltValueField(wireName: 'current_page')
  @nullable
  int get currentPage;

  @BuiltValueField(wireName: 'first_page_url')
  @nullable
  String get firstPageURL;

  @BuiltValueField(wireName: 'from')
  @nullable
  int get from;

  @BuiltValueField(wireName: 'last_page')
  @nullable
  int get lastPage;

  @BuiltValueField(wireName: 'last_page_url')
  @nullable
  String get lastPageURL;

  @BuiltValueField(wireName: 'next_page_url')
  @nullable
  String get nextPageURL;

  @BuiltValueField(wireName: 'path')
  @nullable
  String get path;

  @BuiltValueField(wireName: 'per_page')
  @nullable
  int get perPage;

  @BuiltValueField(wireName: 'prev_page_url')
  @nullable
  String get prevPageURL;

  @BuiltValueField(wireName: 'to')
  @nullable
  int get to;

  @BuiltValueField(wireName: 'total')
  @nullable
  int get total;

  @BuiltValueField(wireName: 'data')
  @nullable
  BuiltList<T> get data;

  PaginateResponse._();

  factory PaginateResponse([updates(PaginateResponseBuilder<T> b)]) =
      _$PaginateResponse<T>;

  static Serializer<PaginateResponse> get serializer =>
      _$paginateResponseSerializer;
}

```

Finally this is the class I want to parse:

```
abstract class Deliveries implements Built<Deliveries, DeliveriesBuilder> {
  @BuiltValueField(wireName: 'id')
  int get id;

 @BuiltValueField(wireName: 'id_f')
  @nullable
  String get orderName;

  Deliveries._();

  factory Deliveries([updates(DeliveriesBuilder b)]) = _$Deliveries;

  String toJson() {
    return json.encode(serializers.serializeWith(Deliveries.serializer, this));
  }

  static Deliveries fromJson(String jsonString) {
    return serializers.deserializeWith(
        Deliveries.serializer, json.decode(jsonString));
  }

  static Serializer<Deliveries> get serializer => _$deliveriesSerializer;
}

```

I want to be able to do something like this : final BaseResponse<PaginateResponse<Deliveries>> response = _repo.getDeliveries();

How can I parse this complex JSON?

**Comment by larssn** [comment]
Maybe this can help: https://www.youtube.com/watch?v=hNbOSSgpneI

**Comment by davidmorgan** [comment]
So I notice that the JSON does not at any point specify which class the `data` represents.

Generic deserialization requires that there is a field in the data saying which type it is. Otherwise, the deserializer does not know what to instantiate.

That means it's hard; you'll need to write a serializer plugin that examines the data and figures out which type to deserialize to, then adds that type into the data to pretend that it's specified as needed.

**Comment by stuz5000** [comment]
@davidmorgan Its not always true that a type-specifier JSON attribute is needed to load generics (at least, its not true for other languages with generics, such as scala) ...  Its possible to write something like:
```
PaginateResponse<Users>  addresses = PaginateResponse<Address>.fromJson(json);
                                                                                                      ^^^^
```
.... and so provide the missing type information (Address) to deserialize a generic. It doesn't solve all cases of polymorphism, but for generic, providing the fully-initiated template type information is sufficient .

Does value_builder support anything like this:
```
   standardSerializers.deserializeWith(PaginateResponse<Address>.serializer, json);
   standardSerializers.deserializeWith<PaginateResponse<Address>>.serializer(json);
```
or,
```
   standardSerializers.deserializeWith(PaginateResponse.serializer, json, T=Address);
```
? ... (the latter is assuming Dart's reflection inherited generic type erasure) from Java.

**Comment by davidmorgan** [comment]
Dart does _not_ do generic type erasure--it's all there at runtime. But not necessarily in the most convenient/usable form :)

If you created a `built_value` class with a field of type `PaginateResponse<Address>` then that would supply the generic information in a way that `built_value` can use: by registering a way to create `PaginateResponse<Address>` instances.

Without that, you need to supply that yourself by adding a builder factory for the exact type: https://pub.dev/documentation/built_value/latest/serializer/SerializersBuilder/addBuilderFactory.html

Then, you need to call `serializers.deserialize`, pass a `specifiedType` to give the full type you want, and cast the result using `as`. The `specifiedType` will be used as a key to look up the builder factory that you registered.

We could potentially add some syntactic sugar on top of that, similar to `deserializeWith` but for generics, but it would do the same thing underneath. Possibly we could create a class like `FullType` that is able to directly supply the generics so you don't need to write them twice.
