### ISSUE TITLE
Support latest analyzer version

### ISSUE THREAD

**Issue by chip2n** [google/built_value.dart#598]
Version 0.35.3 is out. Probably blocked by `analyzer_plugin` again?

**Comment by davidmorgan** [comment]
That's right.

@stereotype441 :)

**Comment by twistedinferno** [comment]
Hi David, many thanks for the tool, it is very handy.  I just wondered if you have had any indication on when `analyzer_plugin` might get updated...I'm at a crossroads on whether to roll back some stuff or not!

**Comment by davidmorgan** [comment]
Didn't hear back from the analyzer team yet--will ping them.

From my side I'm busy the next few days, so it will be Friday at the earliest that I can release a new `built_value`.

**Comment by twistedinferno** [comment]
ah thanks for getting back, I'll look out for an update :-)

**Comment by twistedinferno** [comment]
Looks like there is a new version of the analyzer_plugin with the updated analyzer package (just in case you hadn't noticed already, no rush from my side :-)  
https://pub.dartlang.org/packages/analyzer_plugin#-versions-tab-
