### ISSUE TITLE
Plugin for protobuf support

### ISSUE THREAD

**Issue by listepo** [google/built_value.dart#599]
It would be nice to have this for [protobuf](https://github.com/dart-lang/protobuf)

**Comment by davidmorgan** [comment]
What kind of integration were you thinking?

**Comment by listepo** [comment]
Please see https://github.com/dart-lang/protobuf/issues/214

**Comment by davidmorgan** [comment]
We can serialize to protocol buffers, but it's not possible to do a 1:1 mapping, because `built_value` supports polymorphism and protos don't. So if you map directly to protocol buffers then you lose features.

Did you have a particular use case in mind for the integration?

**Comment by listepo** [comment]
I'm looking for a way to drop proto and use the [POCO](https://en.wikipedia.org/wiki/Plain_old_CLR_object) approach

**Comment by listepo** [comment]
Thank you, most likely it will be a stand-alone solution.

**Comment by truongsinh** [comment]
I'm interested in this as well. For now, I have to manually define `fromProto` and `toProto`. @listepo are you working on a solution?

**Comment by listepo** [comment]
@truongsinh not yet, but in plans.
