### ISSUE TITLE
This provides an easy way to write deeply immutable classes for Dart that behave in a consistent, predicatable way.

### ISSUE THREAD

**Issue by mezoni** [google/built_value.dart#6]
Author of this software really believes that deeply immutable classes should means value types?

>> In computer science, the term value type is commonly used to refer to one of two kinds of data types: Types of values or Types of objects with deep copy semantics.

>> In object-oriented programming, object copying is creating a copy of an existing object, a unit of data in object-oriented programming. The resulting object is called an object copy or simply copy of the original object.

Immutability does not means a data of value types.

No problem but why this nonsences on the [Google Github](https://github.com/google)?
Is Google's programmers no longer have another job?

What usefull (as value types) means this monstruous code?

```dart

  String toString() {
    return 'Value {'
        'anInt=${anInt.toString()}\n'
        'aString=${aString.toString()}\n'
        'anObject=${anObject.toString()}\n'
        'aDefaultInt=${aDefaultInt.toString()}\n'
        'listOfInt=${listOfInt.toString()}\n'
        '}';
  }
```

A value (data of value types) is a `sequence of bits`.  How it can contains String or even Object?

Sorry, but I cannot undestand the conclusions of the author.
It should read wikipedia before make such conclusions.

[Value type](https://en.wikipedia.org/wiki/Value_type)

I am sorry again but my brain can not perceive such conclusions:

# Built Values for Dart
Built values are value types for Dart.

**Comment by davidmorgan** [comment]
In languages that don't have value types, immutability is a way to get the same semantics.

Here's a document about @AutoValue for Java which describes why this works:

https://github.com/google/auto/tree/master/value

**Comment by mezoni** [comment]
They have explanation:

```
We will refer to these classes as value types in this document.
```

Everyone can specify - We will refer to `white` as `black` in this document.
And and this will explains everything.

Here is a full explanation from your link.

>> Classes with value semantics are extremely common in Java. These are classes for which object identity is irrelevant, and instances are considered interchangeable based only on the equality of their field values. We will refer to these classes as value types in this document.

Here is explanation from your main page.

>> Built values are value types for Dart. 

This explains nothing.

**Comment by davidmorgan** [comment]
Yes, the documentation here needs work.

In languages without value types, immutable classes with compare-by-value are the closest you can get. They work very well, we use them extensively. Unfortunately you need code generation to produce them, which is what @AutoValue and now built_value are for.

So, they take a little bit of getting used to.

**Comment by mezoni** [comment]
>> Yes, the documentation here needs work.

From @AutoValue presentation:

@AutoValue
... what, why and how?

What's a `value type`?
By this we mean a `type with value semantics.`
It's class without identity: two instances are considered interchangeable as long as they have equal field values.

Examples:
DateTime, Money, Uri... but you also tend to create a great many of these yourself.
You know the kind: they're the ones where you have to implement equals and hashCode, and usually toString.

Note: `value type` can mean different things in different contexts.

So they're structs?
A common misconception is that value types never have behavior, only state—they're structs.

This is like assuming an enum is only an int. Java's enums are much richer than that!

In value types, as with enums, behavior is welcome! (This behavior should be limited to pure functions that depend only on their inputs and instance state).

etc.

**Comment by davidmorgan** [comment]
Lots of writing to do, I know.

Once I have support for JSON serialization I'd like to write a full example Angular app.

Until there's JSON serialization the use cases for web apps are comparatively limited, so currently I see this as a work in progress, mostly for people who want to dig into it / contribute. That said, if you're writing server side Dart (such as tools), and you don't care about serialization, this should already be useful.

**Comment by mezoni** [comment]
You concept I cannot understand (and accept).

This is more predictable and understandable.
[Data Classes](https://kotlinlang.org/docs/reference/data-classes.html)

```kotlin
data class User(val name: String, val age: Int)

data class User(val name: String = "", val age: Int = 0)

fun copy(name: String = this.name, age: Int = this.age) = User(name, age)

val jack = User(name = "Jack", age = 1)
val olderJack = jack.copy(age = 2)
```

**Comment by davidmorgan** [comment]
It's exactly the same idea. Here's what your example looks like with built_value. The difference is, built_value actually exists for Dart ;)

class User implements Built<User, UserBuilder> {
  String get name;
  int get age;
}

class UserBuilder implements Builder<User, UserBuilder> {
  String name = '';
  int age = 0;
}

val jack = new User((b) => b..name = 'Jack'..age = 1);
val olderJack = jack.rebuild((b) => b.age = 2);

**Comment by mezoni** [comment]
- The primary constructor needs to have at least one parameter;
- All primary constructor parameters need to be marked this (final);
- Data classes cannot be abstract or open
- Data classes may not extend other classes (but may implement interfaces).

For implementing the generator enough only a special annotations.

Eg. (this is self enough)

```dart
@DataClass("UserData") abstract class User {
  @DefaultValue(1) int get age;
  String get name;
}
```
`
And generator can generate:

```dart
class UserData implements User {
  final int age;
  final String name;
  UserData({this.age = 1, this.name});
  User copy(User other) => new User(age: other.age, name: other.name);
  bool operator ==(other) { /**/ }
  int get hashCode { /**/ }
}
```

**Comment by davidmorgan** [comment]
The reason for the builder is because it's sometimes useful to be able to pass around a partially complete instance.

var builder = new UserBuilder();
builder.age = 3;
// later
builder.name = 'Jack';
return builder.build();

This is particularly useful when you have nested data or nested collections.

So, yes, it's a little extra boilerplate compared to the simplest possible value type implementation, in exchange for a bit of extra power.

@AutoValue gives you the choice as to whether you need a builder; if you don't, it's pretty much exactly what you describe. built_value currently requires a builder, I think that for most cases it's a better way to go. Of course if enough people want it I could add a builderless version.

**Comment by davidmorgan** [comment]
Thanks for the thoughts. If you have any specific suggestions, please open separate issues for them. Otherwise, I think the misc mailing list might be a better place for general discussion :)
