### ISSUE TITLE
null values are stripped when serializing

### ISSUE THREAD

**Issue by larssn** [google/built_value.dart#604]
Hello, thanks for a wonderful plugin. It's making our boilerplate related headacres go away.

However we're running into a minor issue serializing data into a Firestore compatible Map. The generated serializers are stripping out nulls (which makes sense in a JSON context).

The offending code is the `if` that is generated in the `.g.dart` files, for example:
```
if (object.color != null) {
      result
        ..add('color')
        ..add(serializers.serialize(object.color,
            specifiedType: const FullType(String)));
}
```

If we comment it out, our resulting Map has keys with nulls, as desired.

Any way to make built_value not generate that `if` check?

**Comment by davidmorgan** [comment]
Not currently.

We could potentially add it as a configuration setting on the serializer field.

```
@BuiltValueSerializer(includeNulls: true)
```

From your side, you could post-process the data to add in the nulls, but that's a bit awkward unless you have the list of keys / field names handy.

**Comment by larssn** [comment]
Well it's a bit of a pain point currently. We're probably gonna lean on post-processing, since it's cleaner than setting a string to `''`, an array to `[]`, a number to 0 (iffy), etc.

Your suggested solution seems like a good, clean idea though.

**Comment by larssn** [comment]
@davidmorgan This feature was stripped from v8 correct? If so, how to handle it? Our requirements remain the same: It is useful to serialize nulls when working with Firestore.

**Comment by davidmorgan** [comment]
Yes--but it looks like I could actually add it back--will aim to do so.

**Comment by kuhnroyal** [comment]
With a global option and a per-field override? https://github.com/google/built_value.dart/issues/912 
I would love to not have to write custom serializers for that :)

**Comment by larssn** [comment]
Any workaround until this gets implemented? We have a ton of code that relies on this, from the old version. There's currently a lot of glitches related to saving data, which is to be expected, but not optimal. 😅

**Comment by kuhnroyal** [comment]
The serializer class can handle `null` now but all the default serializers don't serialize `null`.
I am currently writing the serializer manually where this is needed but that is not ideal.

**Comment by larssn** [comment]
@davidmorgan Will you accept a PR that re-implements this? I assume the solution is similar to the last one?

**Comment by larssn** [comment]
@kuhnroyal Thanks for the suggestion but we have more than 100 built value entities, so writing a custom serializer for most of them is probably gonna take longer than a PR. 😊

**Comment by kuhnroyal** [comment]
@larssn I agree. I implemented this in the OpenAPI generator by generating it from a mustache template: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/class.mustache#L58

I would also love to have something like `@BuiltValueField(serializeNull: true)` so I can set this per field and not only global.
See https://github.com/google/built_value.dart/issues/912

**Comment by larssn** [comment]
@kuhnroyal My first priority is just to get it back to how it was. A `BuiltValueField` has to come later. We have a deadline next monday, and this is a blocker.

**Comment by davidmorgan** [comment]
https://github.com/google/built_value.dart/issues/1049
