### ISSUE TITLE
Docs should say if generated files should be added to git or not

### ISSUE THREAD

**Issue by feinstein** [google/built_value.dart#607]
Should we add generated `.g.dart` files to our git repositories, or not? It would be nice to have this on the docs.

**Comment by pschiffmann** [comment]
The build package docs do give a recommendation on this:

https://pub.dartlang.org/packages/build_runner#source-control:

> When it comes to _generated_ files it is generally best to not submit them to source control, but a specific `Builder` may provide a recommendation otherwise.

https://pub.dartlang.org/packages/build_runner#publishing-packages:

> In general generated files **should** be published with your package, but this may not always be the case. Some `Builder`s may provide a recommendation for this as well.

https://github.com/dart-lang/build/blob/master/docs/faq.md:

> When a Builder specifies `build_to: source` you will see them next to your other files but should not edit them by hand, and they are generally meant to be published with your package.

I have seen this question a couple of times already, but the answer is not really in the scope of this package. Maybe it would be a good idea to write a blog post or something that gives a general overview how to use the Dart build system, and place a link in the built_value README?

**Comment by feinstein** [comment]
Well, a blog post will be very welcome, but I think the main issue is that this information is on the `build_runner` package and not in the `built_value` package, which is the one that most people read.

**Comment by davidmorgan** [comment]
Thanks for the issue! Sorry for the slow response. I've added an 'FAQ' section which refers to the build_runner docs.

I imagine there will be plenty more things to add to the FAQ later :)
