### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: No serializer for 'SignIn'

### ISSUE THREAD

**Issue by SantyTaco** [google/built_value.dart#611]
Good Morning,
I was trying to serialize a Json response using built_value. I can get the response:
  `{
     "status": 200,
      "user_id": "c285677c-9c",
      "id_token": "eyJraWQiOiJ0eT",
      "refresh_token": "eyJjdHkiOiJKV1QiLCJlbmM",
      "expires_in": 3600
    }`

I have created this files: 
1.-Abstract class Signin
   `abstract class SignIn implements Built<SignIn, SignInBuilder>{
      static Serializer<SignIn> get serializer => _$signInSerializer;
      @nullable
       int get status;

      @BuiltValueField(wireName: 'user_id')
       String get userId;

      @BuiltValueField(wireName: 'id_token')
      String get idToken;

      @BuiltValueField(wireName: 'refresh_token')
      String get refreshToken;

      SignIn._();

      factory SignIn([updates(SignInBuilder b)]) = _$SignIn;

      static SignIn fromJson(String jsonString) {
      return serializers.deserializeWith(SignIn.serializer, json.decode(jsonString));
     }
    }`
 2.- A serializer class
  `@SerializersFor(const [
    SignIn,
   ])

   final Serializers serializers = (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();`

3- Data source class

   `class SigninDataSource {
      SigninDataSource();

      Future<Signin> signIn ({
        String email = '***',
        String apiKey = '****',
        String password = '**',
     }) async {
        var url = "https://api-dev/signin";
        var body = json.decode('{"email": "$email", "password": "$password"}');
        http.post(url, body: json.encode(body),
        headers: {
          "x-api-key": apiKey,
          "content-type" : "application/json",})
        .then((response) {
        print("Response status: ${response.statusCode}");
        print("Response body: ${response.body}");
        return SignIn.fromJson(response.body));
        }
      );
     }
   }`

When I tried to serialize the response I get this result:

E/flutter (19028): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: No serializer for 'SignIn'.

**Comment by davidmorgan** [comment]
Does your `SignIn` class have a `serializer` declaration like this?

```dart
static Serializer<SignIn> get serializer => _$signInSerializer;
```

If not--it needs one :)

**Comment by MaxZubko** [comment]
### I'm going to add documents from one collection to another Firestore Flutter
**file 1**
```
addDataToCart(data) async{
    DocumentReference ref = await db.collection('cart').add(data);
    print(ref.documentID);
    return ref.documentID;
  }
```
**file 2 (bloc)**
```
 addDataToCart(
    data,
    )  {
    String id = db.addDataToCart(data);
    this.id = id;
    _inId.add(this.id);
  }
```
**file 3**
```
onTap: () {
              blocCart.addDataToCart(blocTickets.readData());
            },
```

![image](https://user-images.githubusercontent.com/45923184/56440244-86d11300-62f1-11e9-984e-62add703770e.png)
