### ISSUE TITLE
Forward-compatible enums

### ISSUE THREAD

**Issue by maxlapides** [google/built_value.dart#617]
As an example, I have an enum class like:

```dart
class Fruits extends EnumClass {
  const Fruits._(String name) : super(name);
  static Serializer<Fruits> get serializer => _$fruitsSerializer;

  @BuiltValueEnumConst(wireName: 'APPLE')
  static const Fruits apple = _$apple;

  @BuiltValueEnumConst(wireName: 'ORANGE')
  static const Fruits orange = _$orange;

  @BuiltValueEnumConst(wireName: 'BANANA')
  static const Fruits banana = _$banana;

  static BuiltSet<Fruits> get values => _$values;
  static Fruits valueOf(String name) => _$valueOf(name);
}
```

I'm using this enum to deserialize a string that's coming from an API. Now, someone else on the API team updates things, and now the API is returning another fruit, `kiwi`. Immediately my app crashes because this enum cannot deserialize `kiwi`. Ideally, I would like to deserialize any "other" value into an `other` enum value. Or simply deserializing to `null` would also work. Is there any way to handle this kind of thing?

**Comment by davidmorgan** [comment]
Makes a lot of sense.

How about I add

```
@BuiltValueEnumConst(fallback: true)
```

which lets you mark a single value as the "fallback" value to use when deserialization fails?

**Comment by maxlapides** [comment]
@davidmorgan that would be PERFECT! Thanks a ton!

**Comment by davidmorgan** [comment]
SG. I'll try to get to it in the next batch of changes.
