### ISSUE TITLE
Expose BuilderFactories within Serializers class

### ISSUE THREAD

**Issue by ekupershlak** [google/built_value.dart#621]
We'd like to combine multiple Serializers instances together into one to serialize different values across our project. The Serializers interface gives us a way to collect all built_value serializers, but the builderFactories are not exposed. This prevents us from doing a merge of Serializers instances.

**Comment by davidmorgan** [comment]
Sounds good. I was already planning on doing a batch of minor improvements/features in the next few days, so I'll include this one.
