### ISSUE TITLE
How to dynamically update single field in Built_value class?

### ISSUE THREAD

**Issue by jans-y** [google/built_value.dart#640]
Hi,

I am using AngularDart where I switched from mutable classes to built classes. My app has a lot of forms which are responsible for creating / updating my Entities which are all built classes.

Before, I was able to use the two-way data-binding [(ngModel)]. Now with built classes I have to manually rebuild the class on every change since built classes have no setters.

Therefore I created a method like this:
```
void changeCustomer(String field, dynamic value) {
    Map<String, dynamic> map = serializers.serializeWith(Customer.serializer, customer);
    map[field] = value;
    Customer data = serializers.deserializeWith(Customer.serializer, map);
    store.dispatch(SetUpdatedCustomerDataAction(customerId, data));
}
```

which I call from template: `<input (change)="changeCustomer('name', $event)">`

I thought this would be a nightmare in terms of performance but it is actually ok.

However, I am sure there must be a better way. I have read your [>> comment <<](https://github.com/google/built_collection.dart/issues/144#issuecomment-379583843) but that syntax doesn't work for me.

I have tried:
`customer.rebuild((b) => b[field] = value);`
but always got this error from IDE:
`The operator []= isn't defined for the class 'CustomerBuilder'.`

What would be the best approach?
**Thank you.**

**Comment by jadengis** [comment]
What I think you should be doing is embedding a builder object into the form component and treat it was the view model for your form. For example:

``` dart
class FormComponent implement OnInit {
  FormModelBuilder formModel;

  void ngOnInit() {
    formModel = FormModelBuilder();
  }

  void onSubmit() {
    final formData = formModel.build();
    // do something with the form data...
  }
}
```

with template
``` html
<input [(ngModel)]="formModel.data">
```

This allows you to use two-way binding (`[(ngModel)]`) on the mutable builder fields like you were doing before, but when the user is finished with the form, you create an immutable copy of that data (by building the builder) and you can then pass that immutable object into your business logic and do what you need with it (save to database etc).

**Comment by davidmorgan** [comment]
The suggestion about binding to the builder makes sense; there are definitely projects using angular with built value this way.

Otherwise, there isn't currently a way to access fields by name other than serialization, as you're doing. I can see adding a feature that makes it possible, but that's quite a big feature since it will effect the serializer generation.

**Comment by jans-y** [comment]
@jadengis : Thank you for your response. That sounds as a good practice. However, requirement of my app is to save form state after every input change. I am using redux.dart with middleware that stores form state change into the Local Storage, that's why I need to be able to dynamically update properties of my classes.

I was making research for this but my Dart skills are just not there yet. I would be grateful for such feature.

Thank you.

**Comment by dougmill** [comment]
@jans-y Have you looked into the [`BuiltValue.generateBuilderOnSetField`](https://pub.dev/documentation/built_value/latest/built_value/BuiltValue/generateBuilderOnSetField.html) feature added in version 6.4.0? Use it like this:
```
@BuiltValue(generateBuilderOnSetField: true)
abstract class Customer implements Built<Customer, CustomerBuilder> {
  String get name;
  // Define all your other fields...
}
```
```
class FormComponent {
  CustomerBuilder customer;

  FormComponent() {
    customer = CustomerBuilder()..onSet = storeUpdate;
  }

  void storeUpdate() {
    var builtCustomer = customer.build();
    // store the state change using builtCustomer
  }
}
```
```
<input [(ngModel)]="customer.name">
```
