### ISSUE TITLE
Should Mixin fields serialize?

### ISSUE THREAD

**Issue by CosmicPangolin** [google/built_value.dart#642]
Since extending isn't allowed, I'm trying to figure out how to use an interface and mixin to provide serializable fields with default values for all implementing classes.  Something like this: 

```
abstract class ValueInterface {
  String get id;
  DateTime get createdTime;
}

abstract class ValueInterfaceDefaults {
  String id = Uuid().v4();
  DateTime createdTime = DateTime.now().toUtc();
}

abstract class Value with ValueInterfaceDefaults
     implements ValueInterface, Built<Value, ValueBuilder> {
...
}

```

Thus I can call value.id, but the object doesn't expose id for serialization - even with a local field override, the generated _$Value output omits id if it exists in a mixin.  Should this be possible, or am I thinking of mixins incorrectly (new to the concept)? I probably misunderstood, but I figured https://github.com/google/built_value.dart/issues/214 would handle this.

I've also been following https://github.com/google/built_value.dart/issues/212, but I'm afraid the recently proposed solution won't help with my interface defaults case.  Is it just better form to define all defaults in respective value classes, even if they're broadly shared through an interface? 

Thanks much for any help.

**Comment by davidmorgan** [comment]
The generator can't tell the difference between getters from the mixin that are supposed to be fields, and getters from the mixin that are doing computation. Currently it assumes they are doing computation and does not serialize them.

With the proposal in #212 we would need to mark getters-that-are-actually-field-defaults with an annotation. So I think, actually, this will work for you. Let's say we use `@BuiltValueField()` to mark such getters; then:

```
abstract class ValueInterfaceDefaults {
  @BuiltValueField()
  String get id => Uuid().v4();
  @BuiltValueField()
  DateTime get createdTime => DateTime.now().toUtc();
}
```
