### ISSUE TITLE
Is there a way to programatically define updates on rebuild?

### ISSUE THREAD

**Issue by CosmicPangolin** [google/built_value.dart#643]
Separately... :)

If I want to do something like timestamp rebuilds without manually updating the field, is there a way to do that currently?

If not, the thing that seems to make sense to me would be to define a rebuild function in the value class, and then have the something like the following in the generated _$Value to call the super: 

```
  Value rebuild(void Function(User2Builder) updates) =>
      (super.rebuild()..toBuilder()..update(updates)).build();
```

This would allow default rebuild logic that could be overwritten with explicit updates (I think?)

**Comment by davidmorgan** [comment]
There isn't currently a nice way to do this. I agree, it makes sense to have one.

**Comment by CosmicPangolin** [comment]
Awesome!  With custom rebuild functions and the interface stuff, I'm pretty convinced built_value unlocks some shockingly powerful data modeling...I'm thinking along the lines of Active Records in Ruby on Rails, but with some fluttery composition.   Thanks so much :)

**Comment by davidmorgan** [comment]
Hi everyone,

I have a PR out to support setting defaults by adding a `finalizeBuilder` method to your value type. It can do arbitrary postprocessing on fields. It works for value types and serialization.

https://github.com/google/built_value.dart/pull/731/files#diff-0495adf5d2e9dbde8ab38eae465d6ad1

The only caveat is that the generated ._ constructor taking named params doesn't use it. If you write a custom factory constructor that uses this generated constructor, you have to deal with postprocessing yourself.

The same PR adds a hook for initializing builders so you can set defaults.

Thoughts, opinions? Does it look like this fills the gap in current functionality?

Thanks!
