### ISSUE TITLE
Provide a way to check switch statements cover all EnumClass values

### ISSUE THREAD

**Issue by davidmorgan** [google/built_value.dart#644]
Dart native enums support this; it would be nice to somehow check for EnumClass.

**Comment by maks** [comment]
This would be great! Theres alot of discussion and prior art over on the Bobs issue in the Dart repo, [this comment](https://github.com/dart-lang/language/issues/546#issuecomment-554597830) perhaps being useful to code that built_value could generate?

**Comment by maks** [comment]
Actually this may be a dumb idea, but what if the generated code for EnumClass created a "backing" Enum and then each EnumClass had a property, say `enumType` that returned a matching Enum value that could then be used in switch statements and so benefit from Darts already existing support for reporting when a switch on a Enum is not exhaustive of all cases?

**Comment by micimize** [comment]
@maks [I don't think it's dumb](https://gist.github.com/micimize/39f6d59492b3c6792e607a476fb131a6)

**Comment by maks** [comment]
@micimize sorry only had a chance to have a look at your code now but that looks like a nice straightforward way of doing what I had in mind when I made my suggestion. Hopefully @davidmorgan will get a chance to look at implementing something like this for built_value in the future.

**Comment by zoechi** [comment]
These linter rules work with built_value enums
- exhaustive_cases
- no_default_cases

**Comment by danielgomezrico** [comment]
@zoechi what do you mean by work? I just tested one and I dont see any linter when I miss a case.

**Comment by zoechi** [comment]
@danielgomezrico  I got linter warnings
Have you tried dev channel? Not sure when it got introduced.

**Comment by danielgomezrico** [comment]
@zoechi do you mean the flutter dev channel? I was checkig with 1.22.0 but I will give it a try

**Comment by davidmorgan** [comment]
Use 'pub get' or the flutter equivalent(?) to check your `linter` version; `exhaustive_cases` was added in `0.1.117`.

You'll also need to enable `exhaustive_cases` in your `analysis_options.yaml` file :)

**Comment by maks** [comment]
According to [this](https://dart-lang.github.io/linter/lints/exhaustive_cases.html) it's for `Dart SDK: >= 2.9.0-12.0.dev` which should mean it's now available in Flutter stable channel which is `1.22.1` atm and has a Dart version of `2.10.0`

**Comment by danielgomezrico** [comment]
After adding this option `exhaustive_cases` to `analysis_options.yaml` it worked! awesome, thanks to all 👍

**Comment by maks** [comment]
Given the new linter rule is available and working @davidmorgan I guess this can now be closed?

**Comment by davidmorgan** [comment]
Yes, thanks! We should mention it in the docs, filed https://github.com/google/built_value.dart/issues/929 for that.
