### ISSUE TITLE
Custom BuiltList type factory using custom field

### ISSUE THREAD

**Issue by vitor-gyant** [google/built_value.dart#651]
Hi,

One of my models has one field which is a BuiltList of a given interface. During deserialisation and depending on the nested list 'type' field I want to factory the correct implementation. After reading all the docs, blogs and source code this was the only way I found it to work. However, with this approach I have to specify raw deserialisation for all the fields and not only the BuiltList field. Is there a better approach for doing this ? 

```
abstract class CardModelInterface {
  CardTypeEnum get type;
  BuiltList<QuickResponseModel> get responses;
}
```

```
abstract class CarouselModel extends Object
    with MessageInterface
    implements Built<CarouselModel, CarouselModelBuilder> {
  factory CarouselModel([void updates(CarouselModelBuilder b)]) =
      _$CarouselModel;

  factory CarouselModel.fromJson(String data) =>
      serializers.deserializeWith(CarouselModel.serializer, json.decode(data));

  CarouselModel._();

  @BuiltValueSerializer(custom: true)
  static Serializer<CarouselModel> get serializer => CarouselSerializer();
//
  @override
  MessageTypeEnum get type;

  @nullable
  bool get incoming;

  @nullable
  bool get isUndoable;

  @nullable
  DoctorInfoModel get doctorInfo;

  @nullable
  String get doctorId;

  @BuiltValueField(wireName: 'talkingtodoctor')
  @nullable
  bool get talkingToDoctor;

  **BuiltList<CardModelInterface> get cards**;
}
```

And this is the custom builder implementation:

```
class CarouselSerializer implements StructuredSerializer<CarouselModel> {
  @override
  Iterable<Type> get types => [
        CarouselModel, // variable type
        _$CarouselModel, // internal built_value type
      ];

  // name of the variable we are going to Serialize
  @override
  final String wireName = 'carousel';

  @override
  CarouselModel deserialize(
    Serializers serializers,
    Iterable serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    // Initialize an empty builder
    final result = CarouselModelBuilder();

    // Create an `Iterator` from the serialized data received
    final iterator = serialized.iterator;
    // Loop the iterator for each key
    while (iterator.moveNext()) {
      final key = iterator.current as String;
      iterator.moveNext();
      final value = iterator.current;
      // for each key, assign the correct value to the builder
      switch (key) {
        case 'type':
          result.type = serializers.deserialize(value,
              specifiedType: const FullType(MessageTypeEnum));
          break;
        case 'incoming':
          result.incoming = serializers.deserialize(value,
              specifiedType: const FullType(bool));
          break;
        case 'isUndoable':
          result.isUndoable = serializers.deserialize(value,
              specifiedType: const FullType(bool));
          break;
        case 'doctorInfo':
          result.doctorId = serializers.deserialize(value,
              specifiedType: const FullType(DoctorInfoModel));
          break;
        case 'doctorId':
          result.doctorId = serializers.deserialize(value,
              specifiedType: const FullType(String));
          break;
        case 'talkingToDoctor':
          result.doctorId = serializers.deserialize(value,
              specifiedType: const FullType(bool));
          break;
        case 'cards':
          print(value);
          if (value is List<dynamic>) {
            result.cards.replace(value.map<CardModelInterface>((cardJson) {
              final cardType = serializers.deserializeWith(
                  CardTypeEnum.serializer, cardJson['type']);
              switch (cardType) {
                case CardTypeEnum.card:
                  return serializers.deserializeWith(
                      CardModel.serializer, cardJson);
                case CardTypeEnum.clinic:
                  return serializers.deserializeWith(
                      ClinicCardModel.serializer, cardJson);
              }
            })) as BuiltList;
          } else {
            throw DeserializationError(value, specifiedType, Error());
          }

          break;
        default:
          break;
      }
    }

    return result.build();
  }

  @override
  Iterable serialize(Serializers serializers, CarouselModel object,
      {FullType specifiedType = FullType.unspecified}) {
    throw UnimplementedError();
  }
}
```

Does anyone have a good suggestion here ? @davidmorgan ?

Thanks in advance,

**Comment by davidmorgan** [comment]
`built_value` automatically supports deserializing to the right type, based on including the type name in the JSON.

Exactly how you can make use of this depends on what constraints you have on your code.

Do you have control over the JSON format, or do you have to use a format specified by something else (e.g. an API)? Are you using `StandardJsonPlugin`?

**Comment by vitor-gyant** [comment]
Thanks David,

I don’t have a way to change the API format. I’m using StandardJsonPlugin.

—

Vitor Magalhães
Senior iOS Developer

GYANT EU
Rua das Moutadas nº 61,
4405-665, Gulpilhares
VNG, Portugal

m: +351 926 113 063
 e: vitor@gyant.com

iOS App Store: GYANT - Digital Doctor
Messenger: m.me/theGYANT

GYANT - Healthcare Amplified

**Comment by davidmorgan** [comment]
I see.

`StandardJsonPlugin` lets you specify the `discriminator` when it's initialized; it defaults to `$`, it looks like you want it to be `type`.

Then it's a matter of getting those `type` values to match with your class wire names. Try using the `@BuiltValue` annotation for this; e.g.

```
@BuiltValue(wireName = 'card')
abstract class CardModel ... 
```

I'm not 100% sure this works, but if it doesn't, that seems fixable :)

**Comment by vitor-gyant** [comment]
@davidmorgan I'm trying to understand your suggestion. So, I have multiple card model classes, for example, CardModelX and CardModelY. The root json object has a field called cards which could be of any of these two types. To understand which type the card has I have to inspect the field 'type' in the card json dictionary. 

I don't understand how the suggested approach would work here. Could you provide some more information please ?

Thanks,

**Comment by davidmorgan** [comment]
When you initialize `StandardJsonPlugin`, set `discriminator` to `type`. `built_value` will then look at the `type` field.

Then all you need to do is make your class names match what is written in the `type` field. If it's already literally `CardModelX` then there's nothing more to do. If the wire format uses e.g. `card-model-x` then you would need to write `@BuiltValue(wireName = 'card-model-x')` on the class `CardModelX`.
