### ISSUE TITLE
In StandardJsonPlugin, deserialization fails when the value in a Map is NULL

### ISSUE THREAD

**Issue by tamcy** [google/built_value.dart#653]
Consider the following model class:

```dart

abstract class Announcement implements Built<Announcement, AnnouncementBuilder> {
  static Serializer<Announcement> get serializer => _$announcementSerializer;

  BuiltMap<String, String> get remarks;

  Announcement._();

  factory Announcement([updates(AnnouncementBuilder b)]) = _$Announcement;
}
```

Here `remarks` is a `Map` that stores localized values. When deserializing with `StandardJsonPlugin`, the following data works fine:
```json
    {
        "remarks": {
            "en_US": "Remarks EN",
            "zh_HK": "Remarks ZH"
        }
    }
```

But this example will fail:
```json
    {
        "remarks": {
            "en_US": null,
            "zh_HK": null
        }
    }
```

And the error is as below:
```
I/flutter (29052): Deserializing '[remarks, {en_US: null, zh_HK: null}]' to 'Announcement' failed due to: Deserializing
I/flutter (29052): '[null, null, null, null]' to 'BuiltMap<String, String>' failed due to: Invalid argument(s): null
I/flutter (29052): key
```

Looks like this is caused by the function `StandardJsonPlugin`'s `_toListUsingDiscriminator`, which converts the `Map` to a `List`:
https://github.com/google/built_value.dart/blob/2480cb4a4688bc4fbd7473ceb8128369a258edc5/built_value/lib/standard_json_plugin.dart#L159-L202

In this function, keys with `NULL` value are simply skipped (line 195). I don't know the rationale behind this, but since the length of the list is fixed to the sum of keys and values of the Map (line 187), this causes two NULL values at the end of the list whenever a NULL value in the Map is encountered and skipped. Which is why the second JSON sample data results in a List with four NULLs, and the code fails when attempting to use the NULL as the key in `_toMap()`:

https://github.com/google/built_value.dart/blob/2480cb4a4688bc4fbd7473ceb8128369a258edc5/built_value/lib/standard_json_plugin.dart#L80-L88

Seems the "lightest" fix would be to break the loop in `_toMap()` when `key` is `NULL` (this may affect other plugins though). What do you think?

**Comment by tamcy** [comment]
I am now working around the issue using the following plugin:

```dart

class RemoveNullInMapConvertedListPlugin implements SerializerPlugin {
  Object beforeSerialize(Object object, FullType specifiedType) => object;

  Object afterSerialize(Object object, FullType specifiedType) => object;

  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (specifiedType.root == BuiltMap && object is List) {
      return object.where((v) => v != null).toList();
    }

    return object;
  }

  Object afterDeserialize(Object object, FullType specifiedType) => object;
}
```

But I'd prefer those keys with NULL values are preserved in the final BuiltMap, and still don't understand why it was decided that `StandardJsonPlugin` doesn't work this way.

**Comment by davidmorgan** [comment]
Thanks for the detailed report!

That code was written with objects in mind; when a field is null, `built_value` just omits the value, so nulls are not needed when deserializing. The intent was just to ignore them, but as you describe, it doesn't actually work.

`BuiltMap` can't contain `null` keys, so there's no way to actually keep the `null`. Given that, I think the correct fix is to make it actually ignore the nulls as originally intended.

**Comment by jffiorillo** [comment]
Thank you @tamcy  for the workaround...  @davidmorgan  do you have plan to solve this issue anytime soon?  In the meanwhile, @tamcy  workaround should be used? 

Thank you @davidmorgan

**Comment by davidmorgan** [comment]
No ETA I'm afraid; I'll try to include it with the next batch of fixes/improvements.

Yes, the workaround given above is the right way to go for now.

**Comment by davidmorgan** [comment]
https://github.com/google/built_value.dart/issues/1049
