### ISSUE TITLE
Use with jaguar_orm

### ISSUE THREAD

**Issue by elnurvl** [google/built_value.dart#656]
Hi. I am using jaguar_orm on my application. I want to use built value for the same POJOs which the ORM uses. But it seems, there is a problem regarding the immutability of the fields from the side of jaguar_orm, so I cannot use two libraries together. Is there any workaround to get this work?

Thanks.

**Comment by davidmorgan** [comment]
If `jaguar_orm` requires mutable fields then I don't see any way for them to work together right now--built_value classes are required to be immutable.

I guess the requirement from the `jaguar_orm` side comes when it's creating instances. We'd need a way to teach it to use builder classes instead. This sounds like a feature request for `jaguar_orm` :)

**Comment by elnurvl** [comment]
Yeah, I figured it out after examining the generated codes thoroughly. There are only two issues which need to be solved from the jaguar_orm_gen side.
1. The library should use `Builder` classes in order to make a model from a map.
2. Unfortunately, jaguar_orm_gen is unable to relate getter annotations in an abstract class(for example, `@PrimaryKey()`) to a field of the concrete class. I cannot put annotations in the generated code either because any change to that code will be overwritten by source_gen.

**Comment by davidmorgan** [comment]
Makes sense.

Reading annotations from superclasses sounds like a reasonable thing to do--`built_value` has an issue open for the same thing

https://github.com/google/built_value.dart/issues/387

**Comment by elnurvl** [comment]
@davidmorgan , I have been digging the source code of jaguar_orm for the last 3 days in order to solve the second problem. I afraid, it is far more difficult and cumbersome to tweak the code of jaguar_orm for this purpose. However, in my opinion, it would be more reasonable to tweak built_value to copy all getter annotations and paste them above the generated fields as they are? Does it sound clean for you?

**Comment by davidmorgan** [comment]
I see a problem with that: we can't be sure that all annotations make sense on the builder. It might make sense for the `jaguar_orm` annotations ... but other annotations can mean arbitrary things.

One option that might already work is that you can write the builder class outline yourself, and let `built_value` generate the implementation rather than the whole thing. Then you can add whatever annotations you like to it.

See for example `ValueWithDefaultsBuilder` here

https://github.com/google/built_value.dart/blob/master/example/lib/values.dart

**Comment by elnurvl** [comment]
@davidmorgan , it is not about the `Builder` class. You need to give the data class itself to the `jaguar_orm`, which in this case is the implemented `_$Value` class. I think it would be reasonable to copy whatever annotations are written on top of the properties to the overridden fields. An arbitrary annotation would not be resolved in the abstract class anyway, besides, it seems natural to have exact annotations on the fields of the generated classes.

**Comment by davidmorgan** [comment]
Ah, yes, copying just when we override something makes more sense.

I'm a bit confused, though--how could `jaguar_orm` work with the data classes--doesn't it need the fields to be mutable so it can set them?

**Comment by elnurvl** [comment]
Yes, it needs to use the builder class. But because there is a factory constructor in abstract classes which include builders, it is enough to tweak the code of the `jaguar_orm` to use `factory `constructors. Actually, I already worked on the generator of the `jaguar_orm`, so it can read annotations from direct superclasses and use factory constructors. The generator works pretty well, but the changes need to be generalized. I am not sure, which library should we prefer to change for this purpose, as if we make the above-mentioned change on the `built_value` package too, there will be a serious conflict in `jaguar_orm`, because of annotation doubling as seen below.

```
  List<ElementAnnotation> getAnnotationsOf(FieldElement f) {
    List<ElementAnnotation> annotations = f.metadata;
    if (f.hasOverride) {
      f.enclosingElement.supertype?.element
          ?.getGetter(f.name)
          ?.metadata
          ?.forEach((f) => annotations.add(f));
    }
    // annotations = list of jaguar_orm ColumnBase annotations of the field
    if (annotations.length > 1) {
      throw Exception('Only one Column annotation is allowed on a Field!');
    }
    return annotations;
  }
```

**Comment by davidmorgan** [comment]
I see. Unfortunately there's no standard for reading annotations from supertypes, so we can't just support the standard behaviour and be done.

What I would suggest for `jaguar_orm_gen` is that it uses the first annotation encountered, i.e. if there is an annotation available immediately then do not check the supertype. Then this will work whatever we do with `built_value`.

**Comment by elnurvl** [comment]
@davidmorgan , I meant, I am not sure if the `built_value` should copy property annotations to implemented classes, or `jaguar_orm` should read annotations from superclasses instead.

But your suggestion is sensible. I will apply it on the code. Thanks. I am closing the issue, as I found a way to integrate two packages for myself. If you feel, the `built_value` should apply the change I suggested, you can reopen the issue again.

**Comment by davidmorgan** [comment]
Thanks! I think the path you're following is the better/correct fix.

I'd be interested to hear when it's working--that seems like a pretty nice integration to have :)

**Comment by elnurvl** [comment]
@davidmorgan, it finally works. However the code has became highly opinionated and does not work for other classes not conform to `built_value` and `built_list` requirements. It needs to be generalized before being published as an update to the `jaguar_orm`.
