### ISSUE TITLE
Support numbers in @BuiltValueEnumConst

### ISSUE THREAD

**Issue by larssn** [google/built_value.dart#657]
A small feature request.

In TypeScript it is extremely useful that you can give your enums either a string or number value. For example, we use Firestore, and when creating security rules, a number based value for figuring out what permissions are, is a given. In our old system this came from a `Role` enum, with numbers as values (Staff = 10, Admin = 20, Owner = 30. The gaps allow for expansion).

Example enum:
```
part 'role.g.dart';

class Role extends EnumClass {
  @BuiltValueEnumConst(wireName: 30)
  static const Role OWNER = _$owner;

  @BuiltValueEnumConst(wireName: 20)  
  static const Role ADMIN = _$admin;

  @BuiltValueEnumConst(wireName: 10)
  static const Role STAFF = _$staff;

  const Role._(String name) : super(name);

  static Serializer<Role> get serializer => _$roleSerializer;
  static BuiltSet<Role> get values => _$values;
  static Role valueOf(String name) => _$valueOf(name);
}
```

**Comment by davidmorgan** [comment]
Makes sense.

We can't just allow `wireName: 10` because `wireName` takes a `String`. We could add a new `wireNumber` that cannot be used together with `wireName`, how does that sound?

**Comment by larssn** [comment]
Up to you. 😄 

But couldn't wireName just take a `dynamic` and then your code could do a simple:
```
if (wireName is num) {
   // ...
} else if (wireName is String) {
   // ...
} else {
   throw new Exception('`wireName` must be either a num or String');
}
```

**Comment by davidmorgan** [comment]
We could. But weakly typed APIs went out of fashion with Dart 1 ;)

**Comment by larssn** [comment]
Alright, well `wireNumber` would be perfectly acceptable. 👍

**Comment by votruk** [comment]
@davidmorgan hi! Do you plan to add this feature any time soon? I feel very frustrated without the ability to create enums with values especially after having a more functional version (sealed classes) in Kotlin.

**Comment by davidmorgan** [comment]
Sorry, I missed this in the last round of improvements. Bumped the priority as it seems useful + easy to do, I'll try to take a look at it next time.

**Comment by BreSmit521** [comment]
Was there any ETA on this issue?

**Comment by kuhnroyal** [comment]
This is a welcome change but we somehow need access to the generated `wireNumber` in the generated class. Either as static method or directly on each enum.
Maybe something like a static `numberOf` function.
Ideally we get a separate base class `IntEnumClass` that additionally to `name` also has a `value` field.

Most folks that use this feature most likely use the int value extensively, like for putting it into the database but now they have no access to it.

**Comment by kuhnroyal** [comment]
I managed to workaround this problem but it is ugly.
```
  int get value {
    return _$FooSerializer._toWire[name] as int;
  }

  static Foo valueOfInt(int value) {
    return valueOf(_$FooSerializer._fromWire[value]);
  }
```

**Comment by davidmorgan** [comment]
Yeah, we need to figure out a nice way to expose that information; that's pretty much the same as https://github.com/google/built_value.dart/issues/663
