### ISSUE TITLE
Firebase standard Serializers fail

### ISSUE THREAD

**Issue by Chimbi** [google/built_value.dart#658]
I have this issue trying to put a standard json file to Firebase. I tried to follow all your recommendations but still does not work here is my code:
`Serializers serializers = _$serializers;

Serializers standardSerializers =
(serializers.toBuilder()..addPlugin(new StandardJsonPlugin())).build();`

with this I command I create this json file:

`flutter: Json file: {$: PolizaBuilt, poliza: 0, sede: Bogota norte, fechaEmision: 2019-05-29 08:40:28.545064, periodo: 1, numero: 0, temporario: 0, estado: 40, comision: 10.0, cupo_operativo: 0, afianzado: 1, tipoPoliza: Particular, clausulado: Observación, periodoEmision: 1, retroactividad: 21, fechaHoraInicial: 2019-05-29 08:40:28.545567, fechaHoraFinal: 2019-05-29 08:40:28.545599, contratante: 1, objeto: 10100, numeroContrato: 0AZXXX999, valorContrato: 2000000.0, fechaInicial: 2019-05-29 08:40:28.545685, fechaFinal: 2019-05-29 08:40:28.545718, sincronizar: 0}`

and then I try to post it to Firebase

`var prueba = jsonDecode(polizaJson(ctv1));
                    print("Json file: $prueba");
                    polizaRef.child(ctv.poliza.toString()).set(prueba);`

The error makes me get lost my device connection, I already tried to add the Google.plist with xCode but does not work.

`*** First throw call stack:
(
	0   CoreFoundation                      0x00000001146a21bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001137c4735 objc_exception_throw + 48
	2   Runner                              0x000000010feab494 +[FValidation validateFrom:validDictionaryKey:withPath:] + 644
	3   Runner                              0x000000010fe7dc01 +[FSnapshotUtilities internalNodeFrom:priority:withValidationFrom:atDepth:path:] + 2593
	4   Runner                              0x000000010fe7d167 +[FSnapshotUtilities nodeFrom:priority:withValidationFrom:atDepth:path:] + 231
	5   Runner                              0x000000010fe7d008 +[FSnapshotUtilities nodeFrom:priority:withValidationFrom:] + 248
	6   Runner                              0x0000000<…>
Lost connection to device.`

**Comment by davidmorgan** [comment]
Sorry I missed this! I don't know quite how that error could be related to `built_value`. Since this issue is so old I'm going to assume you found a fix by now, if not, please reopen!
