### ISSUE TITLE
Configurable mechanism for determining types for serialized data

### ISSUE THREAD

**Issue by Sitiritis** [google/built_value.dart#666]
Hello. Now I have the following situation:

A service provides a library in Java (almost the same situation is with iOS and Swift), which has quite big number of model classes, which are used to communicate with the service through the library. I am trying to port this library for Flutter, and for that I am using Flutter platform channels. I have all these models duplicated in Dart and I want to use built_value to pass these models from Flutter to a platform as a JSON serialized string.

The library I am porting is designed in such a way that all models are inherited from a general abstract model, which would look in Dart as follows:
```dart
abstract class GeneralModel
{
  int get typeID;
}
```
And all models that are instantiable are descendants of the `GeneralModel`, that is each such model _overrides_ `typeID` getter and assigns it a unique value that determines the type of the model, i. e.:
```dart
abstract class Answer implements Built<Answer, AnswerBuilder>, GeneralModel
{
  ... // Answer class fields

  static int _typeID = 42; // 42 is unique amoung all other models and determines the type Answer

  @override
  int get typeID;

  factory Answer([void updates(AnswerBuilder b)]) =>
    _$Answer((b) => b..typeID = _typeID..update(updates));
  ... // other built_value boilerplate
}
```
Model classes can also have polymorphic types as their fields.

Investigating the behavior of built_value I have found out that to determine type of object being deserialized, either:
1) a serializer for a particular type has to be passed to `serializers.deserializeWith()`
2) `FullType` object has to be passed to `serializers.deserialize()`
3) a special field in JSON **"$"**, which has a type's name as its value, is used to infer the serializer for the specified type

# Question & proposition
## Question
Is it possible to introduce a configurable mechanism for determining types during the serialization and deserialization process?
## Simple example of the mechanism design and its usage
I have not read the code of built_value, so I do not know the best way to implement such mechanism and integrate it with already existing code. From my subjective point of view as a user of built_value it would be convenient to annotate the field that is used to determine a type:
```dart
abstract class Answer implements Built<Answer, AnswerBuilder>, GeneralModel
{
  ... // Answer class fields

  @BuiltValueTypeIdentifier(wireName: "type", value: 42) // means that this field identifies the type of object being serialized and deserialized and value 42 associates with Answer type
  @override
  int get typeID;

  factory Answer([void updates(AnswerBuilder b)]) = _$Answer;
  ... // other built_value boilerplate
}
```
So calling `String answerSerialized = json.encode(serializers.serialize(new Answer((b) => /*initialized fields, except typeID, which is assigned automatically when constructing the Answer object with the provided value from annotation*/)))` results in:
```jsonc
{
  "type": 42,
  // other fields
}
```
And the call to `serializers.deserialize(answerSerialized)`, would construct a new instance of `Answer` without throwing an exception, because the type is known.

P. S. Even though I have not read the code of built_value, yet, I am willing to help with the design and implementation of such mechanism.

**Comment by davidmorgan** [comment]
When you instantiate `StandardJsonPlugin` you can se the `discriminator` to what you want; does that do what you need?

`https://github.com/google/built_value.dart/blob/master/built_value/lib/standard_json_plugin.dart

**Comment by Sitiritis** [comment]
I guess yes, `discriminator` is what I need, but:
1) it does not work with integers being values for `discriminator`, because [`BuiltJsonSerializers._deserialize()` tries to convert it to `String`](https://github.com/google/built_value.dart/blob/master/built_value/lib/src/built_json_serializers.dart#L114)
2) if I make `typeID` a `String`, it does not find serializer. Is there a way to map `typeID` with types?

**Comment by davidmorgan** [comment]
Currently the type needs to be the class name.

But, you _can_ override the wire name of the class, like this:

```dart
@BuiltValueClass(wireName: '42')
class Answer implements Built<...
```

I'm not 100% sure that works, but it's worth a try.

**Comment by Sitiritis** [comment]
Yes, it indeed helps with finding serializers (actually annotation should be `@BuiltValue`), but now during the deserialization it complains that typeID is not initialized for the reason [built_value cuts the list of fields, where the typeID resides](https://github.com/google/built_value.dart/blob/51e6524c4caebead2830d6e5ed67d9163d344b56/built_value/lib/src/built_json_serializers.dart#L123), so generated deserializer does not get the field.

**Comment by dave26199** [comment]
You don't need a typeID field in the class any more for serialisation; it
will be set/used automatically.

If you need that value for your other code you can just have a getter that
returns a fixed value. But that would be not related to serialization.

int get typeID => 43;

**Comment by Sitiritis** [comment]
Yes, was just thinking about the same. Thank you, it works perfectly! The issue can be closed.
