### ISSUE TITLE
Document all possible annotations

### ISSUE THREAD

**Issue by wemped** [google/built_value.dart#670]
Maybe this already exists and I'm just yet to find it, but there should be a doc that describes all the annotations available in built_value (preferably w/ examples!)

examples of some annotations I've found while poking around 
`@BuiltValue`, `@BuiltValueEnumConst`, `@BuiltValueField`

**Comment by davidmorgan** [comment]
Well, they are documented in the API docs :)

https://pub.dev/documentation/built_value/latest/built_value/built_value-library.html

Maybe I should link that from the README?

**Comment by wemped** [comment]
I think a link in the README is a great solution, thanks! 👍 

Feel free to leave this open as a reminder, or close whenever!

**Comment by davidmorgan** [comment]
Added a line/link 'see the API docs' to the introduction section of the README. Sorry this took so long to get to :) thanks for filing!
