### ISSUE TITLE
Access nested JSON field without creating multiple almost-empty classes

### ISSUE THREAD

**Issue by wemped** [google/built_value.dart#671]
Suppose I'm serializing some JSON for one of my models, and I have a deeply nested field that I'd like to have as a "first level" field on my model. In this case, the `name` field.
```
{  
   "id":1234,
   "metadata":{  
      "names":{  
         "name":"The title of the thing"
      }
   },
   "created_at":"DATE"
}
```

Is there a way to serialize that field, without having to write multiple the almost-empty classes for `metadata` and `names`? 

Something along the lines of 
```
abstract class ThingModel implements Built<ThingModel, ThingModelBuilder> {
  String get id;
  @BuiltValueField(wireName: 'metadata.names.name')
  String get name;

  factory ThingModel([Function(ThingModelBuilder b) updates]) = _$ThingModel;
  ThingModel._();
  static Serializer<ThingModel> get serializer => _$thingModelSerializer;
}
```

**Comment by davidmorgan** [comment]
Right now the only thing you can do is write a custom serializer for ThingModel.

**Comment by matthewfx** [comment]
I agree with @wemped that it would be great to have a dot notation to get into nested fields i.e `@BuiltValueField(wireName: 'level1.level2.level3')`
