### ISSUE TITLE
Serialization not working

### ISSUE THREAD

**Issue by arabbani** [google/built_value.dart#674]
The generated file has an error after adding serialization.
Following is the code:
`
import 'dart:convert';

import 'package:built_value/built_value.dart';
import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';

import 'serializers.dart';

part 'test_r.g.dart';

abstract class TestR implements Built<TestR, TestRBuilder> {
  String get name;
  String get title;
  @nullable
  TypeR get type;
  BuiltList<String> get cols;

  TestR._();

  factory TestR([updates(TestRBuilder b)]) = _$TestR;

  static Serializer<TestR> get serializer => _$testRSerializer;

  String toJson() {
    return json.encode(serializers.serialize(this));
  }

  TestR fromJson(String jsonString) {
    return serializers.deserialize(json.decode(jsonString));
  }
}

class TypeR extends EnumClass {
  static const TypeR one = _$one;
  static const TypeR two = _$two;
  const TypeR._(String name) : super(name);

  static BuiltSet<TypeR> get values => _$values;
  static TypeR valueOf(String name) => _$valueOf(name);

  static Serializer<TypeR> get serializer => _$typeRSerializer;
}

`
Serializer: 
`
import 'package:built_value/serializer.dart';

import 'test_r.dart';

part 'serializers.g.dart';

@SerializersFor(const [
  TypeR,
  TestR,
])
final Serializers serializers = _$serializers;
`

The generated code:
`
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'test_r.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

const TypeR _$one = const TypeR._('one');
const TypeR _$two = const TypeR._('two');

TypeR _$valueOf(String name) {
  switch (name) {
    case 'one':
      return _$one;
    case 'two':
      return _$two;
    default:
      throw new ArgumentError(name);
  }
}

final BuiltSet<TypeR> _$values = new BuiltSet<TypeR>(const <TypeR>[
  _$one,
  _$two,
]);

Serializer<TestR> _$testRSerializer = new _$TestRSerializer();
Serializer<TypeR> _$typeRSerializer = new _$TypeRSerializer();

class _$TestRSerializer implements StructuredSerializer<TestR> {
  @override
  final Iterable<Type> types = const [TestR, _$TestR];
  @override
  final String wireName = 'TestR';

  @override
  Iterable serialize(Serializers serializers, TestR object,
      {FullType specifiedType = FullType.unspecified}) {
    final result = <Object>[
      'name',
      serializers.serialize(object.name, specifiedType: const FullType(String)),
      'title',
      serializers.serialize(object.title,
          specifiedType: const FullType(String)),
      'cols',
      serializers.serialize(object.cols,
          specifiedType:
              const FullType(BuiltList, const [const FullType(String)])),
    ];
    if (object.type != null) {
      result
        ..add('type')
        ..add(serializers.serialize(object.type,
            specifiedType: const FullType(TypeR)));
    }
    return result;
  }

  @override
  TestR deserialize(Serializers serializers, Iterable serialized,
      {FullType specifiedType = FullType.unspecified}) {
    final result = new TestRBuilder();

    final iterator = serialized.iterator;
    while (iterator.moveNext()) {
      final key = iterator.current as String;
      iterator.moveNext();
      final dynamic value = iterator.current;
      switch (key) {
        case 'name':
          result.name = serializers.deserialize(value,
              specifiedType: const FullType(String)) as String;
          break;
        case 'title':
          result.title = serializers.deserialize(value,
              specifiedType: const FullType(String)) as String;
          break;
        case 'type':
          result.type = serializers.deserialize(value,
              specifiedType: const FullType(TypeR)) as TypeR;
          break;
        case 'cols':
          result.cols.replace(serializers.deserialize(value,
                  specifiedType:
                      const FullType(BuiltList, const [const FullType(String)]))
              as BuiltList);
          break;
      }
    }

    return result.build();
  }
}

class _$TypeRSerializer implements PrimitiveSerializer<TypeR> {
  @override
  final Iterable<Type> types = const <Type>[TypeR];
  @override
  final String wireName = 'TypeR';

  @override
  Object serialize(Serializers serializers, TypeR object,
          {FullType specifiedType = FullType.unspecified}) =>
      object.name;

  @override
  TypeR deserialize(Serializers serializers, Object serialized,
          {FullType specifiedType = FullType.unspecified}) =>
      TypeR.valueOf(serialized as String);
}

class _$TestR extends TestR {
  @override
  final String name;
  @override
  final String title;
  @override
  final TypeR type;
  @override
  final BuiltList<String> cols;

  factory _$TestR([void Function(TestRBuilder) updates]) =>
      (new TestRBuilder()..update(updates)).build();

  _$TestR._({this.name, this.title, this.type, this.cols}) : super._() {
    if (name == null) {
      throw new BuiltValueNullFieldError('TestR', 'name');
    }
    if (title == null) {
      throw new BuiltValueNullFieldError('TestR', 'title');
    }
    if (cols == null) {
      throw new BuiltValueNullFieldError('TestR', 'cols');
    }
  }

  @override
  TestR rebuild(void Function(TestRBuilder) updates) =>
      (toBuilder()..update(updates)).build();

  @override
  TestRBuilder toBuilder() => new TestRBuilder()..replace(this);

  @override
  bool operator ==(Object other) {
    if (identical(other, this)) return true;
    return other is TestR &&
        name == other.name &&
        title == other.title &&
        type == other.type &&
        cols == other.cols;
  }

  @override
  int get hashCode {
    return $jf($jc(
        $jc($jc($jc(0, name.hashCode), title.hashCode), type.hashCode),
        cols.hashCode));
  }

  @override
  String toString() {
    return (newBuiltValueToStringHelper('TestR')
          ..add('name', name)
          ..add('title', title)
          ..add('type', type)
          ..add('cols', cols))
        .toString();
  }
}

class TestRBuilder implements Builder<TestR, TestRBuilder> {
  _$TestR _$v;

  String _name;
  String get name => _$this._name;
  set name(String name) => _$this._name = name;

  String _title;
  String get title => _$this._title;
  set title(String title) => _$this._title = title;

  TypeR _type;
  TypeR get type => _$this._type;
  set type(TypeR type) => _$this._type = type;

  ListBuilder<String> _cols;
  ListBuilder<String> get cols => _$this._cols ??= new ListBuilder<String>();
  set cols(ListBuilder<String> cols) => _$this._cols = cols;

  TestRBuilder();

  TestRBuilder get _$this {
    if (_$v != null) {
      _name = _$v.name;
      _title = _$v.title;
      _type = _$v.type;
      _cols = _$v.cols?.toBuilder();
      _$v = null;
    }
    return this;
  }

  @override
  void replace(TestR other) {
    if (other == null) {
      throw new ArgumentError.notNull('other');
    }
    _$v = other as _$TestR;
  }

  @override
  void update(void Function(TestRBuilder) updates) {
    if (updates != null) updates(this);
  }

  @override
  _$TestR build() {
    _$TestR _$result;
    try {
      _$result = _$v ??
          new _$TestR._(
              name: name, title: title, type: type, cols: cols.build());
    } catch (_) {
      String _$failedField;
      try {
        _$failedField = 'cols';
        cols.build();
      } catch (e) {
        throw new BuiltValueNestedFieldError(
            'TestR', _$failedField, e.toString());
      }
      rethrow;
    }
    replace(_$result);
    return _$result;
  }
}

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new

`

// serializers.g.dart

`
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'serializers.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(TestR.serializer)
      ..add(TypeR.serializer)
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>()))
    .build();

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new

`

The error is in serializers.g.dart file.
In the `
 ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>()))`
It says 

> Undefined name 'BuiltList'.
Try correcting the name to one that is defined, or defining the name.

> Arguments of a constant creation must be constant expressions.

Try making the argument a valid constant, or use 'new' to call the constructor.

> Undefined class 'ListBuilder'.
Try changing the name to the name of an existing class, or creating a class with the name 'ListBuilder'.

**Comment by davidmorgan** [comment]
That means you need to import 'package:built_collection/built_collection.dart' :)

**Comment by arabbani** [comment]
But it's in the generated file

**Comment by arabbani** [comment]
Ok. now it's working.

**Comment by arabbani** [comment]
Ok. now it's working.

**Comment by arabbani** [comment]
I have imported built_collection in the serializers file. Thankxx. Bdw, great library. keep up the good work.

**Comment by davidmorgan** [comment]
Yeah, generated "part" files can't import things, so you have to add it in the manually maintained file.

You're welcome :)
