### ISSUE TITLE
Generated Builder is unexpected when nested BuiltMap.

### ISSUE THREAD

**Issue by okadan** [google/built_value.dart#677]
### Built class

```dart
abstract class Value implements Built<Value, ValueBuilder> {
  BuiltMap<String, BuiltMap<String, int>> get collection;

  // other code...
}
```

### Builder class that is generated

```dart
class ValueBuilder implements Builder<Value, ValueBuilder> {
  MapBuilder<String, BuiltMap<String, int>> _collection;

  // other generated code...
}
```

In the above case, Why is generating `MapBuilder<String, BuiltMap<String, int>>` instead of `MapBuilder<String, MapBuilder<String, int>>`?

Is there a way to generate `MapBuilder<String, MapBuilder<String, int>>` ?

**Comment by davidmorgan** [comment]
Currently, no; this is really hard to implement generally/correctly.

The best you can do today is to write your own `Builder` class--`built_value` will still generate the implementation for you--with helper methods to make the kind of update you want easier.
