### ISSUE TITLE
num serializer

### ISSUE THREAD

**Issue by larssn** [google/built_value.dart#682]
So it seems this should be supported #132 but I'm seeing an integer stored in Firestore, get serialized into a double, using the JSON serializer.

The model basically has a:
`num get percentage;`

And the incoming map from firestore has:
`{'percentage' -> 5}`

After running it through `serializers.deserializeWith(serializer, map);` the resulting percentage field's runtimeType is a double. So 5 turns into 5.0.

**Comment by davidmorgan** [comment]
Which platform is that on? i.e. web or flutter?

**Comment by larssn** [comment]
Flutter! :-) Sorry, didn't think it relevant.

**Comment by davidmorgan** [comment]
Hrm. Looking at the num serializer, we actually explicitly call `toDouble`:

https://github.com/google/built_value.dart/blob/master/built_value/lib/src/num_serializer.dart

I think this was accidentally added in this PR:

https://github.com/google/built_value.dart/commit/a55664824347aec6ac2a7408779ca9de6c5bb7d6#diff-0edb42ee87b83b55257981717229a6aa

And the correct thing to do will be to just return `serialized as num` without calling `toDouble`.

**Comment by larssn** [comment]
Sounds about right. Perfect!

**Comment by davidmorgan** [comment]
I'll aim to do that in the next batch of updates/fixes--might be a little while though, I'm going on vacation soon.

In the meantime you could copy out + fix + install the fixed version to work around this :)

**Comment by larssn** [comment]
Nah it's fine. We have a workaround in place already. If we really need it, I'll just fork the project.

Anyway, have a good vacation!
