### ISSUE TITLE
Is necessary add library keyword at top of file?

### ISSUE THREAD

**Issue by basketball-ico** [google/built_value.dart#683]

**Comment by dave26199** [comment]
No :)

**Comment by basketball-ico** [comment]
Thanks, but it is a good practice? I see some people said that, but i don't know why :(

**Comment by dave26199** [comment]
No; library statements are legacy from dart 1. You rarely need then in dart 2, and if you do, you'll know.

**Comment by basketball-ico** [comment]
Thank you 🤗
