### ISSUE TITLE
Built value getters work with all classes or only with dart built-in types?

### ISSUE THREAD

**Issue by basketball-ico** [google/built_value.dart#684]

**Comment by dave26199** [comment]
They're supposed to be immutable types. This includes any built value types you create.

In practice we don't enforce this so it can be any type.

**Comment by basketball-ico** [comment]
Thanks, I am reading the docs.
So if you want to use serialization
* you can't use `enum` of dart, you need to use `Enum Classes`,  
* All classes that are properties of the built value, need be also a built values classes,
* If you want to use collections this need to be `BuildCollection`

Is this correct, or have I missed something?

* What of [dart cores classes](https://api.dartlang.org/stable/2.4.0/dart-core/dart-core-library.html) can be used? For example I see you can use `String` `int` `bool` , but `Duration` need a custom serializer, 

Thanks

**Comment by dave26199** [comment]
That's correct.

Supported built in types are an arbitrary list :) any type that is immutable, we could add support for. I don't think the list is documented, you can find it if you dig into the `Serializers` initialization code.
