### ISSUE TITLE
How can I remove "discriminator" field when do serialization?

### ISSUE THREAD

**Issue by basketball-ico** [google/built_value.dart#685]
When use `StandardJsonPlugin`

I want my out put be like that

```json
 {
  "name": "Jhon Doe"
}
```
and not like this

```json
 {
   "s": "Person",
   "name": "Jhon Doe"
}
```

**Comment by dave26199** [comment]
You need to specify explicitly what you're serializing/deserializing. Then the discriminator is not needed and is omitted.

Search for serializeWith in the example:

https://github.com/google/built_value.dart/blob/master/example/lib/example.dart

**Comment by basketball-ico** [comment]
Thanks, this is awesome! 🤗.

Do you think add `toJson` & `fromJson` with type `Map<String, dynamic>` is a good idea?

```dart
abstract class Person implements Built<Person, PersonBuilder> {
  @nullable
  String get name;

  Person._();
  factory Person([void Function(PersonBuilder) updates]) = _$Person;

  static Serializer<Person> get serializer => _$personSerializer;

  static Person fromJson(Map<String, dynamic> json) =>
      serializers.deserializeWith(Person.serializer, json);

  Map<String, dynamic> toJson() =>
      serializers.serializeWith(Person.serializer, this);
}
```

**Comment by dave26199** [comment]
Yes that makes sense, if you search for flutter examples I think you'll find people using much that pattern.

**Comment by basketball-ico** [comment]
Thank you 🤗

**Comment by basketball-ico** [comment]
@dave26199 hello again 😁
For example with an `EnumClass` that you use directly for serialization in a key-value database what is the recommend name for the shortcut methods for serialization, in built values classes as you can see is `toJson` and `fromJson` or `toMap` or `fromMap`, but this name not have sense with an `EnumClass`.

I am thinking in `fromString` and `toString`. what do you think?

```dart
class TestEnum extends EnumClass {
  static Serializer<TestEnum> get serializer => _$testEnumSerializer;

  static const TestEnum yes = _$yes;
  static const TestEnum no = _$no;
  static const TestEnum maybe = _$maybe;

  const TestEnum._(String name) : super(name);

  static BuiltSet<TestEnum> get values => _$values;
  static TestEnum valueOf(String name) => _$valueOf(name);

  String toString() {
    return serializers.serializeWith(TestEnum.serializer, this);
  }

  static TestEnum fromString(String value) {
    return serializers.deserializeWith(TestEnum.serializer, value);
  }
}
```
