### ISSUE TITLE
When use .toBuilder()?

### ISSUE THREAD

**Issue by basketball-ico** [google/built_value.dart#686]
Hello, I can't understand  when use `.toBuilder()`, can you explain me please.

**Comment by dave26199** [comment]
You can usually just use `rebuild`.

`toBuilder` is for rare cases when you need the builder to stick around for longer than one update, for example when passing between methods or when doing lots of updates on one go.

**Comment by basketball-ico** [comment]
@dave26199
Thanks, sorry, can you show me a little code example, I can't understand :(

**Comment by davidmorgan** [comment]
You mostly don't need it :)
