### ISSUE TITLE
Where and how many serializers.dart files can I create?

### ISSUE THREAD

**Issue by basketball-ico** [google/built_value.dart#689]
Hello

What is your recommendation for create `serializers.dart` file.

For example I have a models folder with all models in my app and there I have the `serializers.dart`

But I use BLoC pattern and some states(outputs) are defined in each "blocs" folder and have also some built values that need serialization.

Is a good idea have `serialzers.dart` file in models folder, and other `serializers.dart` in  blocs folder?
Or is better only 1 `serializers.dart` at the root of the app?

Thanks

**Comment by dave26199** [comment]
The only time you'll really benefit from more than one is if you need different sets of serializers in different parts of your codebase.

For example you might have a server that speaks two different APIs. They should have different serializers to avoid unneeded dependencies when a type is not used.
