### ISSUE TITLE
Have an annotation for make all fields @nullable without write the annotation on each field?

### ISSUE THREAD

**Issue by basketball-ico** [google/built_value.dart#690]

**Comment by davidmorgan** [comment]
https://github.com/google/built_value.dart/issues/557

**Comment by basketball-ico** [comment]
@davidmorgan I see you close this and refer to this https://github.com/google/built_value.dart/issues/557
but I don't see how this make all fields nullables :(

**Comment by davidmorgan** [comment]
Use `@BuiltValue(

**Comment by davidmorgan** [comment]
Whoops. Looks like I forgot to include `@BuiltValue(defaultNullable: true)` when I made that change :/ reopening ... thanks for pinging.

**Comment by davidmorgan** [comment]
On further thought, this should wait until after `built_value` is adapted for NNBD. The `@nullable` annotation will likely go away, so I'm hesitant about adding more code related to it.

**Comment by davidmorgan** [comment]
Yes--it goes away.
