### ISSUE TITLE
What's better choice for use built_value with a db lib.

### ISSUE THREAD

**Issue by jerryzhoujw** [google/built_value.dart#691]
What's better choice for use `built_value` with a db(sqlite) lib ?

Create `SerializerPlugin` ?

I see there's a issue in [moor](https://github.com/simolus3/moor/issues/89) which prefer to merge `*.g.dart`

**Comment by davidmorgan** [comment]
No ideas, sorry! I haven't used dart with SQL. But I'll leave this open in case someone wants to comment :)

**Comment by jerryzhoujw** [comment]
Currently I use `ModelA` for `built_value` to handle request, and create `DBModelA` for SQL operation,  and create map function between `ModelA` and `DBModelA`.

**Comment by jerryzhoujw** [comment]
updated in https://github.com/simolus3/moor/issues/89.

seems [fixed](https://github.com/simolus3/moor/issues/89#issuecomment-796973563)

I didn't try with that yet.
