### ISSUE TITLE
Using value type as Mocks for testing

### ISSUE THREAD

**Issue by ZeekHuge** [google/built_value.dart#692]
I am using value types in my core code, but for testing purposes, I am mocking them - `MockValueTypeClass extends Mock implements ValueTypeClass {}`. With this in the test code, when I am trying to auto-generate the code, it shows error in the test code, which is obvious as the `MockValueTypeClass` is not following standards in which a value type class should be implemented and yet implementing (indirectly) the builder pattern. Is their a way to stop built-value generator from looking into the test code and just go through the `lib` directory ?

**Comment by davidmorgan** [comment]
FWIW, it's often recommended that you do not mock value types, e.g. https://stackoverflow.com/questions/47304193/don-t-mock-value-objects-too-generic-rule-without-explanation

There isn't currently a way to stop generation from triggering. This seems like a bug: we should probably only do generation if you directly implement `Built`, not if you transitively implement it.

It's likely to be a while before I can get to fixing this, unfortunately.

**Comment by ZeekHuge** [comment]
I would like to work on this bug with some guidance. From what it looks like, a test should go into the [values.dart](https://github.com/google/built_value.dart/blob/master/end_to_end_test/lib/values.dart) and [values_test.dart](https://github.com/google/built_value.dart/blob/master/end_to_end_test/test/values_test.dart). Once we have a failing test, then it would require fixing the built_value_generator ? Would that be the correct approach ?

**Comment by davidmorgan** [comment]
Sounds good. That's correct.

You need to run `tools/use_local_deps` first, to update the repo so that the end_to_end test package depends on the local `built_value_generator` instead of the one from pub.

**Comment by dfdgsdfg** [comment]
Can I workaround with `build.yaml`'s `excludes` option?

```yaml
builders:
  my_builder:
    import: 'what should I do?'
    builder_factories: 'what should I do?'
    build_extensions: 'what should I do?'
    defaults: 
      generate_for:
        exclude: ['./test']
```

**Comment by dfdgsdfg** [comment]
Seems work with below config.

```dart
targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: true

builders:
  built_value:
    target: ":built_value_generator"
    import: "package:built_value_generator/builder.dart"
    builder_factories: ["builtValue"]
    build_extensions: {".dart": [".built_value.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    defaults: 
      generate_for:
        exclude: ['./test']
```
Default `build.yaml` comes from here.
https://github.com/google/built_value.dart/blob/master/built_value_generator/build.yaml
