### ISSUE TITLE
Extend EnumClass?

### ISSUE THREAD

**Issue by cpboyd** [google/built_value.dart#694]
Potentially related to #57 and #58.

My specific use case is that I'm using a EnumClasses to specify navigation paths within a Flutter application.

There is, however, replicated code across classes that I could alleviate if I could have an intermediate `abstract class EnumRoute extends EnumClass {}`

Would it be possible to have the `isEnumClass` check use `name.startsWith('Enum')` (similar to `isBuiltValue`)?
https://github.com/google/built_value.dart/blob/master/built_value_generator/lib/src/serializer_source_class.dart#L118-L127

**Comment by dave26199** [comment]
Could you make `EnumRoute` a mixin? Then the change would be to allow you to write `Foo extends EnumClass with EnumRoute` ... not sure if that's allowed today.

**Comment by cpboyd** [comment]
@dave26199 I tried that, but since I define field getters, e.g.:
```dart
String get title;
```
I'm then unable to use a `const` constructor.

Perhaps that's an issue worth raising over at dart-lang since I don't actually have any fields... Just getters (which I suppose I could just turn into functions).

**Comment by davidmorgan** [comment]
Looks like you found an SDK bug :)

**Comment by cpboyd** [comment]
I'll close this then, since a `mixin` would work fine for my use case.
