### ISSUE TITLE
Facilitate a cleaner vertical architecture

### ISSUE THREAD

**Issue by kentcb** [google/built_value.dart#695]
This is kinda three things all related to wanting to implement a clean vertical architecture. That is, every feature in my app lives in its own folder, including serializers. Here are the three related things:

1. Similar to #621, would it be possible to expose the plugins that have been added to a `Serializers` instance?
2. Ideally, a method on `SerializersBuilder` to take a `Serializers` instance and add _everything_ from it
3. The existing `Serializers` API feels a little wrong now. I suspect this is a result of its evolutionary history.

If I had these things, each of my features could live in almost complete isolation, with only a single new line being added to the top-level composition logic whenever a new feature is added to my app.

## 1. Expose plugins

This is so that any of my features can add a plugin they require and then the composition logic higher in my application can automatically add that plugin into the top-level serializers.

## 2. New method on `SerializersBuilder`

This is a small thing really, but it would save me having to jump through some hoops to achieve my goals. My current code looks like this:

```dart
/// The serializers for all built values across the entire application.
final Serializers serializers = _createSerializers();

Serializers _createSerializers() {
  final serializersBuilder = SerializersBuilder();

  // Add some standard serializers.
  serializersBuilder.add(Iso8601DateTimeSerializer());

  // Compose in serialization support for each feature.
  _compose(serializersBuilder, feature1Serializers);
  _compose(serializersBuilder, feature2Serializers);
  _compose(serializersBuilder, feature3Serializers);

  // JSON serialization support.
  serializersBuilder.addPlugin(StandardJsonPlugin());

  return serializersBuilder.build();
}

/// Takes all the serializers and builder factories from [serializers] and adds them to [serializersBuilder].
void _compose(SerializersBuilder serializersBuilder, Serializers serializers) {
  assert(serializersBuilder != null);
  assert(serializers != null);
  serializersBuilder.addAll(serializers.serializers);

  for (final builderFactoryKey in serializers.builderFactories.keys) {
    serializersBuilder.addBuilderFactory(builderFactoryKey, serializers.builderFactories[builderFactoryKey]);
  }
}
```

If a new method were added, it could look like this:

```dart
final Serializers serializers = (SerializersBuilder()
  ..add(Iso8601DateTimeSerializer())
  ..compose(feature1Serializers)
  ..compose(feature2Serializers)
  ..compose(feature3Serializers)
  ..addPlugin(StandardJsonPlugin())).build();
```

Which is a lot cleaner.

## 3. API Naming

Above, I used `compose` when I felt like I should be writing `add`, but `add` is of course already taken to mean adding a serializer. I feel like a better API would look something like this:

```dart
void add(Serializers);

void addSerializer(Serializer);
void addAllSerializers(Iterable<Serializer>);

void addBuilderFactory(...);

void addPlugin(SerializerPlugin);
void addPlugins(Iterable<SerializerPlugin>);
```

But maybe this is a bridge too far and not worth a breaking change 🤷‍♂

**Comment by davidmorgan** [comment]
Sure, it makes sense to add methods as you describe. It may be a little while until I get to it, `built_value` typically waits until my other work is unusually quiet.

Renaming, though, would be far too hard at this point, sorry :D

**Comment by davidmorgan** [comment]
This is addressed in https://github.com/google/built_value.dart/issues/711 :)

**Comment by kentcb** [comment]
This is great - thanks @davidmorgan.

Just so I know, what is the plan regarding another release? I thought maybe the release would happen automatically after merge, but that doesn't appear to be the case.
