### ISSUE TITLE
DeserializationError should be an Exception

### ISSUE THREAD

**Issue by jamesderlin** [google/built_value.dart#696]
I'm skeptical that anything could or would be done about this, but I think that `DeserializationError` should be an `Exception` (a possible runtime error) instead of an `Error` (a logical error) since the input being deserialized can come from unknown sources.  Attempting to detect and reject malformed data by catching the `DeserializationError` runs afoul of the [`avoid_catching_errors` lint](http://dart-lang.github.io/linter/lints/avoid_catching_errors.html).

**Comment by davidmorgan** [comment]
Hmm, you are correct, it should be an `Exception`. Probably too late to change it now.

I have to say though that I don't like the lint; I like my lints to have no false positives, but there definitely _are_ cases where you should catch errors; in fact it's essential to do so at some point, unless you want your users to see stack traces!

We don't currently have a good model in the analyzer for 'lint that is expected to have false positives'. Something to look at at some point :)

**Comment by simolus3** [comment]
Apart from the analyzer lint, dart2js also treats subclasses or errors differently when `-O3` or higher is enabled (from the [docs](https://dart.dev/tools/dart2js)):
> Before using -O3, test using -O2 to ensure that your app never throws a subtype of Error (such as TypeError).

Could this be a problem here?

**Comment by davidmorgan** [comment]
That's a good point, thanks.

I wonder if we could make it implement both `Error` and `Exception`, and what dart2js would do with it then. I'll ask...

**Comment by davidmorgan** [comment]
Checked with the dart2js team, here was the response:

"The concern with -O3 is that type checks are left out and assumed to pass (e.g. the argument to List.add is not checked). This should not affect control flow between a throw expression and a catch."

--so I think that's fine.

**Comment by jamesderlin** [comment]
Hm.  Back in April I asked for "Clarification on how Errors affect optimizations" on the dart-discuss list:

> If code does throw Error, does that mean that -O3 will do nothing or that using -O3 will cause UB?

and I was told:

> Undefined behavior. If, for example, you have:
> 
> ```dart
>    if (!isAdmin) {
>     throw SecurityError('Only Admins may access the dashboard');
>   }
>   navigateToDashboard();
> ```
> 
> Dart2JS may choose to compile this to:
> 
> ```dart
>   navigateToDashboard();
> ```

Am I misunderstanding?

**Comment by davidmorgan** [comment]
Hmmmmm. Those two statements do seem contradictory. If you have the thread handy for the "undefined behaviour comment", maybe re-ask there?

**Comment by rakudrama** [comment]
dart2js will _not_ compile
```dart
  if (!isAdmin) {
    throw SecurityError('Only Admins may access the dashboard');
  }
  navigateToDashboard();
```
to
```dart
  navigateToDashboard();
```
_unless_ it can prove `isAdmin` is always `true`.

**Comment by davidmorgan** [comment]
Got it. Thanks!

**Comment by jamesderlin** [comment]
> dart2js will _not_ compile
> 
> ```dart
>   if (!isAdmin) {
>     throw SecurityError('Only Admins may access the dashboard');
>   }
>   navigateToDashboard();
> ```
> 
> to
> 
> ```dart
>   navigateToDashboard();
> ```
> 
> _unless_ it can prove `isAdmin` is always `true`.

If it can prove `isAdmin` is always `true`, then it doesn't matter what's in `if`'s then-clause.  Are you saying that a `throw TypeThatDerivesFromError` statement will *never* be optimized out?

This is all very confusing (so confusing that I've now apparently heard conflicting explanations from different people whom I consider to experts on dart2js.

**Comment by davidmorgan** [comment]
:)

Stephen works on dart2js, so what he says is more or less definitive.
