### ISSUE TITLE
class runtime type is not same as Class name, it start with _$ prefix

### ISSUE THREAD

**Issue by hustlemickey** [google/built_value.dart#697]
```
abstract class Login implements Built<Login, LoginBuilder> {
  static Serializer<Login> get serializer => _$loginSerializer;

  Login._();

  factory Login([void Function(LoginBuilder) updates]) = _$Login;

 }
```
And I have a serializers file contain standardSerializers which can serialize a json  object
```
Login  login = standardSerializers.deserializeWith(Login.serializer, map);
print(login.runtimeType);
```
expect: "Login"
but: "_$Login"
Did I made a mistake? if not how do I get the right result which is "Login"

**Comment by davidmorgan** [comment]
`Login` is an abstract class; there is no way to get an instance of it.

The class that actually implements `Login` is generated for you in the `.g.dart` file, and it's called `_$Login`. You'll find that any way you instantiate `Login`, the result is a `_$Login`.

If you absolutely need to get the string `Login`, you can use `Serializers`. It has a method `serializerForType`. And: `standardSerializers.serializerForType(login.runtimeType).wireName` will give you `Login` :)

**Comment by hustlemickey** [comment]
Got it, thanks a lot
