### ISSUE TITLE
Is it possible to make all field default to nullable without @nullable annotation

### ISSUE THREAD

**Issue by hustlemickey** [google/built_value.dart#700]
I have a Model made with built_value, 
named  "Message"
and I have an API , when success it return 
`{"success": true, "code":"000","data":{"foo":"bar"}}`
I call  `message.data.foo`, it's ok.
but when it fail,
`{"success": false, "code":"001","data":{}}`
I call  `message.data.foo`,   throw an exception  foo should be nullable,

assuming there are lots of models, and nested objects inside models, I have to annotate every filed to be nullable to avoid exception, that not a good way, is there any other faster or elegant way todo it?

**Comment by MahdiPishguy** [comment]
@hustlemickey i think this is duplicate issue. please search before create new issue

https://github.com/google/built_value.dart/issues/690

**Comment by davidmorgan** [comment]
Thanks--this is not supported yet but it's at the top of my TODO list

https://github.com/google/built_value.dart/issues/557
