### ISSUE TITLE
How can I Deserializing double or int to String value

### ISSUE THREAD

**Issue by hustlemickey** [google/built_value.dart#707]
Here is a wire example, but it really happened.
when has value return json will be 
`{prize:34.9}`
but some time api returns 
`{prize:""}` for not set prize,
but how can I make a statement ?
```
String get prize;
num get prize;
```
I need it at same time. or failed due to: Deserializing '34.9' to 'String' failed due to: type 'double' is not a subtype of type 'String' in type cast , vice versa， any help would be thanks

**Comment by davidmorgan** [comment]
Unfortunately you'll need to do something custom here; e.g. modify the JSON before you try to deserialize it, to fix the empty strings.

You can either do that completely outside `built_value`, or you could do it more integrate with `built_value` using a serializer plugin or a fully custom serializer for the particular type.

**Comment by hustlemickey** [comment]
Thanks, currently I trying to modify the JSON before deserialize.
