### ISSUE TITLE
escape some fileds which are dart keyword

### ISSUE THREAD

**Issue by MahdiPishguy** [google/built_value.dart#708]
in my application which i connected to server, that return this output:

```dart
"usertags": {
    "in": [
        {
           
        }
    ]
},
```

in thst `in` is dart keyword and i don't how can i escape that to get data from that and i get this error:

> error: Expected a class member.

```dart
abstract class BuiltUserTags implements Built<BuiltUserTags, BuiltUserTagsBuilder> {

  BuiltList<BuiltIn>    get   in;

  BuiltUserTags._();

  factory BuiltUserTags([updates(BuiltUserTagsBuilder b)]) = _$BuiltUserTags;

  static Serializer<BuiltUserTags> get serializer => _$builtUserTagsSerializer;
}
```

**Comment by davidmorgan** [comment]
You'll need to call the field something different, then use `BuiltValueField(wirename: 'in')` to serialize as `in`.

**Comment by MahdiPishguy** [comment]
@davidmorgan 

is this correct? i don't think

`BuiltList<BuiltIn>    get   BuiltValueField(wirename: 'in');`

**Comment by davidmorgan** [comment]
```
@BuiltValueField(wirename: 'in')
BuiltList<BuiltIn> get ins;
```

:)

**Comment by MahdiPishguy** [comment]
@davidmorgan 

`wirename` should be had `wireName`

:+1:
