### ISSUE TITLE
Serializers should provide a convenience method to merge in other Serializers

### ISSUE THREAD

**Issue by jsmarr** [google/built_value.dart#711]
[Serializers](https://github.com/google/built_value.dart/blob/master/built_value/lib/serializer.dart#L51) is essentially a collection of individual Serializer and builder factory objects, but there's no way to add/merge in one or more Serializers into an existing Serializers. Logically, this should be as straightforward as `serializers.merge(otherSerializers)` but absent such a utility method, there's a fair amount of boilerplate callers have to write to achieve this (copying over all of the individual Serializer items inside the otherSerializers and also copying across all of the builder factories). It would be easier for developers and presumably more robustly tested if Serializers itself provided such a standard merge method.

**Comment by davidmorgan** [comment]
SGTM, thanks.
