### ISSUE TITLE
Sorting fields in map after/during Deserialization

### ISSUE THREAD

**Issue by timxschroeder** [google/built_value.dart#715]
I want to deserialize product information that I get from Firestore. As this in JSON, the BuiltMap<String, String> that is a field in the product, is not ordered. 
Is there any way to define an order/sorting for the BuiltMap during or after deserialization? 

I tried writing a custom Serializer but could not really get it to work as most of the code expects this to be just a BuiltMap and not a custom type. I also don't really want to interfere with any of the serialization or deserialization, as they work just fine right now. 

Is there any way to define something like a post-deserialization-hook in which I could just simply sort that map?

**Comment by davidmorgan** [comment]
Yes, you could write a `SerializerPlugin` that changes the ordering. See `StandardJsonPlugin` for an example of a plugin and how to install it.
