### ISSUE TITLE
Serializing dynamic/Object fields

### ISSUE THREAD

**Issue by josh-burton** [google/built_value.dart#716]
I have class that includes a field with type of Object:

```
abstract class JsonPatchOperation1 implements Built<JsonPatchOperation1, JsonPatchOperation1Builder> {

  @BuiltValueField(wireName: 'op')
  String get op;

  @BuiltValueField(wireName: 'path')
  String get path;

  @BuiltValueField(wireName: 'value')
  Object get value;

  JsonPatchOperation1._();
}
```

By default built_value with StandardJsonPlugin serializes this field with a descriminator. The backend doesn't understand this and my API call fails.

As a fix, I've created a custom serializer that serializes this field:

```
Serializer valueSerializer = serializers.serializerForType(object.value.runtimeType as Type);
result..add('value')..add(serializers.serializeWith<dynamic>(valueSerializer, object.value));
```

The only difference between this and the generated serializer is checking if there is a serializer for the field runtime type:

`Serializer valueSerializer = serializers.serializerForType(object.value.runtimeType as Type);`

Is there a reason the generated serializer couldn't do this by default for fields that are dynamic/generic/Object?

**Comment by davidmorgan** [comment]
built_value wouldn't be able to deserialize the result, so it does not seem like a great default :) ... being able to deserialize is usually a pretty important property of serialization ;)

Maybe we could add `@BuiltValueField(discriminator: false)` for cases like this?
