### ISSUE TITLE
Doubt with the builder class generated

### ISSUE THREAD

**Issue by basketball-ico** [google/built_value.dart#719]
I see that each builder class create a variable `_$v`, like [this](https://github.com/google/built_value.dart/blob/9355b7ca57db728ff39d8ee8dad952f9bbdc4368/example/lib/values.g.dart#L433), I know this is used for return a reference of the current built value in case you want to create a copy but you don't update any field.

But I can't think in a case when you want to create a copy without update any field, maybe this is used by the buit collections, but I am not sure, please can you said a case when this is useful,
 Thank you

**Comment by dave26199** [comment]
It happens behind the scenes when there are nested builders. It means you can cheaply update complex data structures--parts you don't modify are reused rather than copied.

In your own code it's probably rare but it might happen if you pass around a builder.

**Comment by basketball-ico** [comment]
Thank you, I understood, excellent work :)

**Comment by basketball-ico** [comment]
@dave26199  hello, I wonder why in the getters you call `_$this`, because this set  `_$v` to `null`, and this force to create a new instance when call again `build`

```dart
 int _value;
  int get value => _$this._value;
  set value(int value) => _$this._value = value;

  VerySimpleValueBuilder get _$this {
    if (_$v != null) {
      _value = _$v.value;
      _$v = null;
    }
    return this;
  }

  @override
  void replace(VerySimpleValue other) {
    if (other == null) {
      throw new ArgumentError.notNull('other');
    }
    _$v = other as _$VerySimpleValue;
  }

```
I think is better something like this:

```dart
...
  int _value;
  int get value => _$v != null ? _$v.value : _value;
  set value(int value) => _$this._value = value;

  VerySimpleValueBuilder get _$this {
    if (_$v != null) {
      _value = _$v.value;
      _$v = null;
    }
    return this;
  }

  @override
  void replace(VerySimpleValue other) {
    if (other == null) {
      throw new ArgumentError.notNull('other');
    }
    _$v = other as _$VerySimpleValue;
  }
...
```

but maybe I'm missing something, thanks

**Comment by davidmorgan** [comment]
Eagerly copying fields from `other` would mean we copy the whole data structure even if we only update part of it. That would make the cost of updating proportional to the size of the entire data structure, when we want it to be proportional to the size of the change. (Well, the size of the change plus the path from the change to the root, which is the best we can do with an immutable data structure).

**Comment by basketball-ico** [comment]
@davidmorgan And what about this? and now don't need to copy `other`.
```dart
...
  int _value;
  int get value => _$v != null ? _$v.value ? _value;
  set value(int value) => _$this._value = value;

  VerySimpleValueBuilder get _$this {
    if (_$v != null) _$v = null;
    return this;
  }

  @override
  void replace(VerySimpleValue other) {
    if (other == null) {
      throw new ArgumentError.notNull('other');
    }
    _$v = other as _$VerySimpleValue;
  }
...

```

**Comment by davidmorgan** [comment]
That doesn't work, `_value` needs initializing when `_$v` is cleared.

**Comment by basketball-ico** [comment]
@davidmorgan sorry I fix that, so id this work this have any improve?

```dart
  int _value;
  int get value => _$v != null ? _$v.value : _value;
  set value(int value) => _$this._value = value;

  VerySimpleValueBuilder get _$this {
    if (_$v != null) {
      _value = _$v.value;
      _$v = null;
    }
    return this;
  }

  @override
  void replace(VerySimpleValue other) {
    if (other == null) {
      throw new ArgumentError.notNull('other');
    }
    _$v = other as _$VerySimpleValue;
  }
```

**Comment by davidmorgan** [comment]
I think you're suggesting only copying on the first 'set' instead of the first 'set' or 'get'?

That would be a performance improvement in situations where you use the builder getter without actually making changes. I'm not aware that that's an important use case. The tradeoff is that the code is a little more complicated.

If it does turn out to be an important use case for someone then we should dig deeper :)

Thanks.

**Comment by basketball-ico** [comment]
> I think you're suggesting only copying on the first 'set' instead of the first 'set' or 'get'?

Yes, that is exactly what I wanted to say.

Well, I also not see this case,  but I wanted to make sure I understand what the builder do :) , so for now it's fine like this :D

Thank you for your time.
