### ISSUE TITLE
Question: Dealing with recursive models

### ISSUE THREAD

**Issue by VictorUvarov** [google/built_value.dart#720]
What is the best approach when deserializing a model (1) that contains another model (2), which contains model(1)? For example: 

Model 1
```dart
abstract class Post implements Built<Post, PostBuilder> {
  String get title;
  String get description;
  User get user;
  Comment get comment;
  ...
}
```

Model 2
```dart
abstract class Comment implements Built<Comment, CommentBuilder> {
  String get message;
  User get user;
  Post get post;
  ...
}
```

Model 3
```dart
abstract class User implements Built<User, UserBuilder> {
  String get name;
  ...
}
```

I want to deserialize a post, but I need to deserialize the user and comment, which leads to recursion. Setting the fields to null seems like a hack. Any advice would be really appreciated.

**Comment by dave26199** [comment]
One approach would be to break the loops by storing IDs instead of the full object for some fields. Then look up in a map when you need to.

**Comment by VictorUvarov** [comment]
Yeah, maybe I should just store the ids. Thanks for the advice.
