### ISSUE TITLE
Can I use any version of build_runner?

### ISSUE THREAD

**Issue by basketball-ico** [google/built_value.dart#729]
I see all examples and packages and all of them use `build_runner: ^1.0.0`, can I have a problem if I use the latest resolved `build_runner: ^1.7.1` ?

Thank you.

**Comment by davidmorgan** [comment]
`^1.0.0` means '`1.0.0` or any compatible version'. Changes to the second and third numbers count as compatible, so, yes, it includes `1.7.1`.

**Comment by basketball-ico** [comment]
Amazing, I had no idea about this.
Thank you
