### ISSUE TITLE
Documentation and examples for _initializeBuilder and _finalizeBuilder

### ISSUE THREAD

**Issue by davidmorgan** [google/built_value.dart#736]

**Comment by davidmorgan** [comment]
It might be better to use annotations than magic method names; that also makes it easier to document.

**Comment by felixwortmann** [comment]
@davidmorgan is there a way to do this with annotations by now? Or do you still have to change the factory method?

**Comment by davidmorgan** [comment]
No change I'm afraid.

**Comment by davidmorgan** [comment]
Example here: https://github.com/google/built_value.dart/issues/212#issuecomment-632702910

**Comment by davidmorgan** [comment]
Closing in favour of https://github.com/google/built_value.dart/issues/1051
