### ISSUE TITLE
Question: differentiating built values with the same name, different package

### ISSUE THREAD

**Issue by kentcb** [google/built_value.dart#742]
Hi,

I am using `built_value` in the context of Redux, and I lean on it heavily for logging purposes. Each Redux action is a built value and I want to be able to infer from a log of such actions what has led to a crash/problem.

The issue I have is that it is not uncommon for the same action name to be used by separate features. An obvious example is `Load` or `Populate`, since many features need to be able to do this. What I end up with in my log is something like:

```
Load {}
```

This does not differentiate which feature/package the `Load` action belongs to.

I'm aware I can overload `toString` and take ownership of the output, but doing that on every action would be quite laborious and easy to forget. I'd prefer being able to provide my own `BuiltValueToStringHelperProvider` that can automatically supplement the output with package/feature names, but it only receives a class name.

I'm also considering adding some kind of `Feature` interface with a single member that provides a feature name. Then my logging infrastructure could check if the action implements that interface and include the feature name if it does. But again, this would be very laborious.

I kind of feel like `BuiltValueToStringHelperProvider` should receive both a class name _and_ a package name, but I just wanted to put the question out there.

**Comment by davidmorgan** [comment]
Package wouldn't be sufficient; you'd need the full URI. Source URI has never seemed to be a particularly good/first class concept in Dart; at least, I haven't really seen it used for anything. If you did use it, it would stop you moving files around inside the package.

I wonder if you'd be better off with that `Feature` interface. Then you can include whatever string is actually meaningful.

There might be something we can do with codegen to help, open to suggestions. I guess, I'm looking for something slightly more generally applicable/useful, if possible :)

**Comment by kentcb** [comment]
What about being able to specify an arbitrary value/nonce against a BV that is then passed into the `BuiltValueToStringHelperProvider`?

```dart
@BuiltValue(nonce: 'foo')
class MyBuiltValue { ... }
```

**Comment by kentcb** [comment]
I just tried solving this by defining a base class for all actions in a given feature:

```dart
/// An interface that actions can implement to provide further qualification to their name in log output.
///
/// See https://github.com/google/built_value.dart/issues/742 for more context.
abstract class QualifiedName {
  /// Gets a qualifying prefix for the action.
  ///
  /// This prefix will be prepended to log output and will automatically be suffixed with a period to separate the prefix from the remainder
  /// of the action identifier.
  String get qualifyingPrefix;
}

...

abstract class BaseAction implements QualifiedName {
  @override
  String get qualifyingPrefix => 'app';
}

abstract class TearDown extends BaseAction implements Built<TearDown, TearDownBuilder> {
  factory TearDown() => _$TearDown();

  TearDown._();
}
```

But `built_value` does not support `extends`:

```
1. Stop class extending other classes. Only "implements" and "extends Object with" are allowed.
```

So I instead have to take this route:

```dart
// QualifiedName exists as before

mixin ActionMixin implements QualifiedName {
  @override
  String get qualifyingPrefix => 'app';
}

abstract class TearDown with ActionMixin implements Built<TearDown, TearDownBuilder> {
  factory TearDown() => _$TearDown();

  TearDown._();
}
```

**Comment by davidmorgan** [comment]
That looks reasonable.
