### ISSUE TITLE
Question: Can another generator be used to generate the required abstract class definitions?

### ISSUE THREAD

**Issue by srikrsna** [google/built_value.dart#748]
Is it possible to generate types using another generator built using source_gen which built_value would pickup and generate files for? If so does it need to be a LibraryBuilder/PartBuilder or just a SharedPartBuilder with dependency order in build_config suffice?

**Comment by davidmorgan** [comment]
I guess it should be, but I'm not too knowledgeable about `package:build` configuration. Maybe ask over at `package:build` or `package:source_gen`?
