### ISSUE TITLE
Incremental builds not working

### ISSUE THREAD

**Issue by maxlapides** [google/built_value.dart#751]
Hi there, recently I noticed that the incremental builds don't seem to be working at all. As soon as I save any file in my project, it runs the entire code generation process which can take over 1 minute for our large project. I'm totally stumped on any way to debug this or find a workaround. I'm simply running:

```
flutter packages pub run build_runner watch
```

and on every single file save, it will rebuild everything.

We love built_value, and appreciate any help you can offer! Thanks!

**Comment by davidmorgan** [comment]
It's possible this relates to a circular dependency that was added in `v6.8.1`. You could try downgrading to `v6.7.1`.  The newest version `v7.0.0` should also fix it, but I don't know if enough core packages have updated yet that it's actually possible to use it.

**Comment by maxlapides** [comment]
I just tried downgrading to `v6.7.1` and unfortunately the issue is still occurring. If this is an issue that is just related to our project, do you have any recommendations on how to track it down? Thanks again :)

**Comment by davidmorgan** [comment]
Is this still a problem? I just released a version of v7 that should let you use the most recent versions of everything. Hopefully it now works :)

Thanks.

**Comment by maxlapides** [comment]
Hey I just tried out the latest and unfortunately the issue persists, but I think this may be an issue with the way we've structured our project. We have a big file called `internals.dart` that exports all of our reusable stuff, this includes reusable components and well as `built_value` models. The problem is that we have a bunch of circular dependencies within `internals.dart`, so every time a file that is exported by `internals.dart` is modified, the entire project is rebuilt.

I think we may be able to get rid of the circular dependencies by breaking up `internals.dart` into smaller files. The problem, I think, is that some files in `exports1.dart` would import `exports2.dart` and then some files in `exports2.dart` would import `exports1.dart`, creating a circular dependency that would result in a full rebuild of `exports1.dart`, `exports2.dart` and any other files that import those files.

Unfortunately due to the size of the project, it is very expensive for me to try to reorganize the project to try to avoid these issues. I have already spent many days trying to reconfigure the imports. I have managed to isolate the circular dependencies to within `internals.dart`, but I have been having trouble getting past this.

Do you have any recommendations for best practices on how to structure projects? Or do you have any recommendations on how I can identify circular dependencies? Does any such tooling exist?

Thanks so much for your help!

**Comment by davidmorgan** [comment]
I don't know enough about `package:build` to know how this should work, sorry. I suggest asking over at `package:build` :)

**Comment by maxlapides** [comment]
Okay, will do! Thanks!
