### ISSUE TITLE
Broken @SerializersFor annotation. Are all the types imported?

### ISSUE THREAD

**Issue by metaltigerfish** [google/built_value.dart#752]
Hi I am getting the following issue every time I add a particular model to /blzr_development/lib/models/serializers.dart.

Error in BuiltValueGenerator for /blzr_development/lib/models/serializers.dart.
Broken @SerializersFor annotation. Are all the types imported?

I have ensured that all types are imported. I have even changed the order of the imports

It all relates to one model which is complex called 'Match'. Everytime I remove it from the @SerializersFor it works. The moment I add it back I get the error.

**Comment by metaltigerfish** [comment]
For completeness the solution was as simple as renaming the model from 'Match' to 'Matchx' - not sure why the name was causing problems.

**Comment by davidmorgan** [comment]
That likely relates to a class called `Match` being part of `dart:core`, so it's always imported.

You could try

```dart
import 'dart:core' hide Match;
```

Or using an explicit `show` on the import where you import your version of `Match`.
