### ISSUE TITLE
Unwanted value "$" when serializing a BuiltList

### ISSUE THREAD

**Issue by marcos930807** [google/built_value.dart#753]
I have been working with BuiltValue without problems until today that I need to send in the body of a post, an array of an Object, the problem is that when serializing the array, a property (unwanted by me) appears "$" with value "name of the Objet "
Example:
I have to send this in the body of a post to an endpoint:
[
   {
     "topic": string,
     "subject": string,
     "id": string,
     "eventType": string,
     "eventTime": string,
     "data":{
       object-unique-to-each-publisher
     },
     "dataVersion": string,
     "metadataVersion": string
   }
]
I have the BuiltValue class: ===========>

abstract class EventSchema implements Built<EventSchema, EventSchemaBuilder> {
  // fields go here
  @BuiltValueField(wireName: 'id')
  String get id;

  @nullable
  @BuiltValueField(wireName: 'topic')
  String get topic;

  @nullable
  @BuiltValueField(wireName: 'subject')
  String get subject;

  @nullable
  @BuiltValueField(wireName: 'eventType')
  String get eventType;

  @nullable
  @BuiltValueField(wireName: 'eventTime')
  String get eventTime;

  @nullable
  @BuiltValueField(wireName: 'dataVersion')
  String get dataVersion;

  @nullable
  @BuiltValueField(wireName: 'metadataVersion')
  String get metadataVersion;

  @nullable
  @BuiltValueField(wireName: 'data')
  SystemAudit get systemAudit;

  EventSchema._();

  factory EventSchema([updates(EventSchemaBuilder b)]) = _$EventSchema;

  String toJson() {
    return json.encode(serializers.serializeWith(EventSchema.serializer, this));
  }

  static EventSchema fromJson(String jsonString) {
    return serializers.deserializeWith(EventSchema.serializer, json.decode(jsonString));
  }

  static Serializer<EventSchema> get serializer => _$eventSchemaSerializer;
}
SystemAudit is anohter BuiltValue class i dont put it here.
Serializer===========>
library serializers;

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';

port 'eventgrid/event.dart';
import 'eventgrid/system_audit.dart';

part 'serializers.g.dart';

@SerializersFor(const [
 
  EventSchema,
  SystemAudit

])
final Serializers serializers =
    (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();

If i call toJson metod on EventShema the result is OK
this is the result
 {
     "topic": string,
     "subject": string,
     "id": string,
     "eventType": string,
     "eventTime": string,
     "data":{
       object-unique-to-each-publisher
     },
     "dataVersion": string,
     "metadataVersion": string
   }
but when i use my serilizer on BuiltList<EventSchema> whit only 1 event this is my unwanted result
[
{     
     "$": "EventSchema",  //How remove this 
     "topic": string,
     "subject": string,
     "id": string,
     "eventType": string,
     "eventTime": string,
     "data":{
       object-unique-to-each-publisher
     },
     "dataVersion": string,
     "metadataVersion": string
   }
]
PD: I use Chopper with BuiltValue Converter and this is the code for converting request body
body: serializers.serializeWith(
          // Since convertRequest doesn't have a type parameter, Serializer's type will be determined at runtime
          serializers.serializerForType(request.body.runtimeType),
          request.body,
        ),
      ),
runtimeType for BuiltList<EventSchema> is  _BuiltList<EventSchema>
Sorry for my bad English, any help is appreciated.

**Comment by marcos930807** [comment]
I discovered that when the serializer is use without a type, it add the unwanted "$", in my case the type that is use when converting is "list", but I don't know how to specify list inner content type and therefore put the "$" sign, if anyone knows how to convert BuiltList<EventSquema> into this
[
   {
     "topic": string,
     "subject": string,
     "id": string,
     "eventType": string,
     "eventTime": string,
     "data":{
       object-unique-to-each-publisher
     },
     "dataVersion": string,
     "metadataVersion": string
   }
] please please help me!!

**Comment by davidmorgan** [comment]
When you deserialize/deserialize, you can pass a `FullType`. 

```dart
serializers.deserialize(json, specifiedType: FullType(BuiltList, [FullType(EventSchema)]))
```

when you specify the type yourself in this way it's not written on the wire.

Hope that helps :)

**Comment by marcos930807** [comment]
Thanks very much for the quick answer, this solve my problem i have to create also a new builder factory on serializer and specify the type inside my Chopper Converter like this
if(request.body is BuiltList<EventSchema>){
      return super.convertRequest(request.replace(
        body: serializers.serialize(request.body,specifiedType: FullType(BuiltList, [FullType(EventSchema)]))
      ));
    }
You save my day Thanks again!!
Closing now.
