### ISSUE TITLE
The part file is not been generated by Built_value

### ISSUE THREAD

**Issue by Chimbi** [google/built_value.dart#755]
I'm trying to follow the Hacker_news example on the boring show. I am not getting any errors but the part file is not been generated by Built Value;

Here is my flutter doctor text:

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.5-pre.45, on Mac OS X 10.14.6 18G95, locale en-CO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
Macs-Mac-mini:hackernews andres$ flutter doctor -v
[✓] Flutter (Channel master, v1.12.5-pre.45, on Mac OS X 10.14.6 18G95, locale en-CO)
    • Flutter version 1.12.5-pre.45 at /Users/andres/Documents/Development/flutter
    • Framework revision 73c32545b7 (2 days ago), 2019-11-20 11:02:35 +0000
    • Engine revision 176f563296
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andres/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 3149EC0C-B326-4BB3-84C6-F2724B1344C8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!
`
Built value says that everything is fine and that the actions were executed correctly.
I know that is a strange error, thanks for your help.

Here is my pubspec.yaml:

`name: hackernews
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.2.5
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.8.2
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
 `

**Comment by davidmorgan** [comment]
I'm not particularly familiar with flutter. How do you run the `built_value` generator?

**Comment by Chimbi** [comment]
"If using Flutter, the equivalent command is flutter packages pub run build_runner build."

**Comment by Chimbi** [comment]
part 'filename.g.dart'

**Comment by Chimbi** [comment]
I found this issue on a similar subject apparently is a version problem but is not fixed yet: https://github.com/dart-lang/sdk/issues/36616

**Comment by Chimbi** [comment]
Solved is a version problem. Updating flutter, dart and Android Studio should solve the problem

**Comment by dlsagayaraj** [comment]
> dart-lang/sdk#36616

What version did you upgrade to?
