### ISSUE TITLE
Serialization with generic types

### ISSUE THREAD

**Issue by zhangzhenxi** [google/built_value.dart#757]
### Case
I came up with this when I tried with serialization at generic built value classes

```dart
var data = GenericValue<int>((b) => b..value = 1);
var serialized = [
  'GenericValue',
  'value',
  ['int', 1],
];
var sMap = {
  'value': 1,
};
var serializersWithPlugin =
    (serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();

test('can be serialized', (){
  expect(serializersWithPlugin.serialize(data), sMap);
});

test('can be serialized', () {
  expect(serializers.serialize(data), serialized);
});
```

The result of this test :

```
Expected: {'value': 1}
  Actual: {'$': 'GenericValue', 'value': {'$': 'int', '': 1}}
   Which: has different length and has extra map key '$'

package:test_api                         expect
test/generics_serializer_test.dart 84:7  main.<fn>.<fn>
```

Original code could be found at [here](https://github.com/google/built_value.dart/blob/71742e9ae5abb12cf10c1601c7d1f92998aff213/end_to_end_test/test/generics_serializer_test.dart#L68)

I just want to serialize `data` with `StandardJsonPlugin`, and the result may like to `sMap` kind of style. Are there any solutions right now?

**Comment by mdobosh** [comment]
@zhangzhenxi could you please tell me how did you fix it? I have same issue now )
