### ISSUE TITLE
eliminate need to explicitly list serializable Built types in SerializersFor

### ISSUE THREAD

**Issue by dave-doty** [google/built_value.dart#758]
If possible, it would be great to find a way to eliminate the need to explicitly list a type in the `SerializersFor` annotation. This runs against the DRY principle, since the intention to make the class serializable is already implied by the `static Serializer<...` statement in the class.

It is a very common bug for me to forget to do add this. The rest of the boilerplate that is part of the class declaration can be put in a code snippet (e.g., `static Serializer<MyAction> get serializer => _$myActionSerializer;`). But the list given to `SerializersFor` cannot be put in this code snippet.

**Comment by davidmorgan** [comment]
We used to try to find classes to serialize using the analyzer, but that was more trouble than it's worth. It's complex, slow, and counter-intuitive.

You could add a presubmit script that uses find/grep to build a list of classes and checks they all show up in SerializersFor?

**Comment by dave-doty** [comment]
@davidmorgan Speaking of DRY, I've been bit in the other direction as well. In other words, I've put the type into the `@SerializersFor` list, but forgot to put the line `static Serializer<MyType> get serializer => _$myTypeSerializer;` in the class declaration. Everything compiles fine, but I get a `Bad state: No serializer for ...` error at run time.

If it is not straightforward to automatically generate the list, it would be helpful to have a compile-time warning when one of those declarations is present but not the other. Though perhaps this is as difficult as producing the list of serializable types?

Or, would it cause problems simply to provide a default serializer in all cases? Then there's no problem to solve with determining the list of serializable types. It's simply assumed to be every instance of `Built` in the whole project.

It seems like overriding the default is already possible using custom serializers, and it would not cause any run time overhead if the serializer is never called. (Just like `==` and `hashCode` are provided but possibly never used.)

**Comment by davidmorgan** [comment]
Here's the issue for it not checking if the built_value type is actually serializable: 

https://github.com/google/built_value.dart/issues/635

It's doable, I just need to implement it :)
