### ISSUE TITLE
Question: How to convert from object to Map<String, dynamic>?

### ISSUE THREAD

**Issue by dfdgsdfg** [google/built_value.dart#759]
What is proper way to convert from object to map for firestore update and set?

Some ways come to mind, but I'm not sure it's good.

```dart
// 1 toJson then decode to map again
json.decode(object.toJson)

// 2 create toMap method inside the model
abstract class A implements Built<A, ABuilder> { 
...
  Map<String, dynamic> toMap() =>
    {
      'name': name,
      'email': email,
    };
...
}
```

I think 2 is better but maybe more mature way like toJson example.
```dart
String toJson() {
    return json.encode(serializers.serializeWith(HomeTeam.serializer, this));
  }
```

Any suggestion?

**Comment by davidmorgan** [comment]
`serializers.serializeWith` already returns a `Map<String, dynamic>` if you're using `StandardJsonPlugin`.

**Comment by bdoubleu86** [comment]
Seems linke I am having an issue with serializeWith. It is telling me:
> A value of type 'Object?' can't be returned from the function 'json' because it has a return type of 'Map<String, dynamic>?'.

I am having this code:
`Map<String, dynamic>? get json => serializers.serializeWith(serializer, this);`

Any idea? Or do I need to cast from Object to Map?

**Comment by davidmorgan** [comment]
Yes, just cast it to the right type :)

**Comment by bdoubleu86** [comment]
This should do the trick as well:
`Map<String, dynamic> get json => jsonDecode(serializers.toJson(serializer, this));`
