### ISSUE TITLE
To have symmetric serialize/deserialize logic in a custom serializer

### ISSUE THREAD

**Issue by reedom** [google/built_value.dart#764]
I wrote a custom serializer for `IconData` to be worked with `StandardJsonPlugin`.
In its `serialize()`, it returns `Map<String, dynamic>`, however, `deserialize()` receives `serialized` as `List<dynamic>`.
That's because `StandardJsonPlugin.beforeSeralize()` tends to convert a map to a list.
Is there any way to have `serialized` as a `Map`?

----
Resources:

```dart
class StandardJsonPlugin implements SerializerPlugin {
  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Map && specifiedType.root != JsonObject) {
      if (specifiedType.isUnspecified) {
        return _toListUsingDiscriminator(object);
      } else {
        return _toList(object, _needsEncodedKeys(specifiedType));
      }
    } else {
      return object;
    }
  }
```

```dart
// A value class
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:flutter/widgets.dart' hide Builder;

abstract class CustomAction
    implements Built<CustomAction, CustomActionBuilder> {
  IconData get icon;

  CustomAction._();

  factory CustomAction([void Function(CustomActionBuilder) updates]) =
      _$CustomAction;

  static Serializer<CustomAction> get serializer => _$customActionSerializer;
}
```

```dart
// A custom serializer
class IconDataSerializer implements PrimitiveSerializer<IconData> {
  final bool structured = false;

  @override
  Object serialize(Serializers serializers, IconData icon,
      {FullType specifiedType = FullType.unspecified}) {
    return <String, dynamic>{
      'codePoint': icon.codePoint,
      'fontFamily': icon.fontFamily,
      'fontPackage': icon.fontPackage,
      'matchTextDirection': icon.matchTextDirection,
    };
  }

  @override
  IconData deserialize(Serializers serializers, Object serialized,
    {FullType specifiedType = FullType.unspecified}) {
    final data = serialized as List<dynamic>;  // {_List} size = 8
    // deserialize...
    return ...
  }

  @override
  Iterable<Type> get types => BuiltList<Type>([IconData]);

  @override
  String get wireName => 'IconData';
}
```

```dart
@SerializersFor(const [CustomAction])
final Serializers serializers = (_$serializers.toBuilder()
      ..addPlugin(StandardJsonPlugin())
      ..add(IconDataSerializer()))
    .build();
```

Note:
For a return value of `serialize()`:
```dart
object = {_InternalLinkedHashMap} size = 4
 0 = {map entry} "codePoint" -> 59477
 1 = {map entry} "fontFamily" -> "MaterialIcons"
 2 = {map entry} "fontPackage" -> null
 3 = {map entry} "matchTextDirection" -> false
```

`deserialze()` will receive the following. It even lacks `fontPackage` entry since it was a `null` field in `serialize()` and then `StandardJsonPlugin._toList()` drops any `null` entries. This makes it harder the deserialize logic more.

```dart
serialized = {_List} size = 8
 0 = "codePoint"
 1 = 59477
 2 = "fontFamily"
 3 = "MaterialIcons"
 4 = "matchTextDirection"
 5 = false
 6 = null
 7 = null
```

```dart
class StandardJsonPlugin implements SerializerPlugin {
  List _toList(Map map, bool hasEncodedKeys) {
    var result = List(map.length * 2);
    var i = 0;
    map.forEach((key, value) {
      // Drop null values, they are represented by missing keys.
      if (value == null) return;

      result[i] = hasEncodedKeys ? _decodeKey(key as String) : key;
      result[i + 1] = value;
      i += 2;
    });
    return result;
  }
```

**Comment by davidmorgan** [comment]
Your serializer should use `List`, and rely on `StandardJsonPlugin` to convert it to/from a `Map`.

Instead of

```
{
      'codePoint': icon.codePoint,
      'fontFamily': icon.fontFamily,
      'fontPackage': icon.fontPackage,
      'matchTextDirection': icon.matchTextDirection,
    }
```

you need

```
[
      'codePoint', icon.codePoint,
      'fontFamily', icon.fontFamily,
      'fontPackage', icon.fontPackage,
      'matchTextDirection', icon.matchTextDirection,
]
```

And then to deserialize you need to loop and split out keys/values; see any of the generated serializers for an example, e.g.

https://github.com/google/built_value.dart/blob/master/example/lib/values.g.dart#L93

**Comment by reedom** [comment]
@davidmorgan,  thanks for the reply.

Yet I don't see enough reason why we need to take that looks-redundant way.
Why custom serializers should use `List` over `Map`?

On serialization, it's less optimal to return `List`. 
The internal logic might be changed in the future, but right now returning `List` and `Map` will get the same value on the way.

```dart
  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    if (object is List &&
        specifiedType.root != BuiltList &&
        specifiedType.root != BuiltSet &&
        specifiedType.root != JsonObject) {
      if (specifiedType.isUnspecified) {
        return _toMapWithDiscriminator(object);
      } else {
        return _toMap(object, _needsEncodedKeys(specifiedType)); // for List, it takes this path
      }
    } else {
      return object; // for Map, it goes through here
    }
  }

  // [needsEncodedKeys] is [false] this time while the keys are [String].
  Map _toMap(List list, bool needsEncodedKeys) {
    var result = <String, Object>{};
    for (int i = 0; i != list.length ~/ 2; ++i) {
      final key = list[i * 2];
      final value = list[i * 2 + 1];
      result[needsEncodedKeys ? _encodeKey(key) : key as String] = value;
    }
    return result;
  }
```
Anyway, the result serializer applied your suggestion is this:
```dart
class IconDataSerializer implements PrimitiveSerializer<IconData> {
  final bool structured = false;

  @override
  IconData deserialize(Serializers serializers, Object serialized,
      {FullType specifiedType = FullType.unspecified}) {
    final args = <String, dynamic>{
      'codePoint': null,
      'fontFamily': null,
      'fontPackage': null,
      'matchTextDirection': null,
    };
    final iterator = (serialized as Iterable).iterator;
    while (iterator.moveNext()) {
      final key = iterator.current as String;
      iterator.moveNext();
      if (key != null) {
        args[key] = iterator.current;
      }
    }
    return IconData(
      args['codePoint'],
      fontFamily: args['fontFamily'],
      fontPackage: args['fontPackage'],
      matchTextDirection: args['matchTextDirection'],
    );
  }

  @override
  Object serialize(Serializers serializers, IconData icon,
      {FullType specifiedType = FullType.unspecified}) {
    return [
      'codePoint',
      icon.codePoint,
      'fontFamily',
      icon.fontFamily,
      'fontPackage',
      icon.fontPackage,
      'matchTextDirection',
      icon.matchTextDirection,
    ];
  }

  @override
  Iterable<Type> get types => BuiltList<Type>([IconData]);

  @override
  String get wireName => 'IconData';
}
```

Not sexy.😭
Again, why do we need this complexity?

**Comment by davidmorgan** [comment]
Lists are the default format instead of maps because 1) lists are better for performance, and 2) they're more flexible; JSON maps can only contain strings as keys, if you instead put the keys in a list then you don't have that limitation.

To support people who want maps, there is `StandardJsonPlugin`. But the core is based on lists.

By the way, why do you need to write your own serializer? They are usually generated for you :)

**Comment by reedom** [comment]
> To support people who want maps, there is StandardJsonPlugin. But the core is based on lists.

Uh, it might be `MapJsonObject`?
My code got better now 😃 
```dart
class IconDataSerializer implements PrimitiveSerializer<IconData> {
  final bool structured = false;

  @override
  IconData deserialize(Serializers serializers, Object serialized,
    {FullType specifiedType = FullType.unspecified}) {
    final MapJsonObject data = serialized;
    return IconData(
      data.value['codePoint'],
      fontFamily: data.value['fontFamily'],
      fontPackage: data.value['fontPackage'],
      matchTextDirection: data.value['matchTextDirection'],
    );
  }

  @override
  Object serialize(Serializers serializers, IconData icon,
    {FullType specifiedType = FullType.unspecified}) {
    return MapJsonObject(<String, dynamic>{
      'codePoint': icon.codePoint,
      'fontFamily': icon.fontFamily,
      'fontPackage': icon.fontPackage,
      'matchTextDirection': icon.matchTextDirection,
    });
```

> By the way, why do you need to write your own serializer? They are usually generated for you :)

Oh, yes?
I'm afraid not, i.e. `IconData` comes from `package:flutter/widgets.dart`, so I had given up to get the one generated. :crying_cat_face:
(My journey began when I got an error: `Bad state: No serializer for 'IconData'.`)

**Comment by davidmorgan** [comment]
Hmm. I don't really understand how `MapJsonObject` works; if it does then I guess it is accidental and will only work with `StandardJsonPlugin`. There's a risk that it might break with a future release.

But I guess it solves your immediate problem :)

Re: the class being in flutter, that makes sense. It'd be nice to have a `built_value_flutter` package that adds serializers for all the built in types. I don't think that's something I'm likely to get to any time soon, though :)

**Comment by reedom** [comment]
> Hmm. I don't really understand how MapJsonObject works; 
`StandardJsonPlugin .afterSerialize` and `StandardJsonPlugin.beforeDeserialize` won't touch `MapJsonObject` since it's a decendant of `JsonObject`.

> There's a risk that it might break with a future release.
Hmm, I just hope that converters other than `StandardJsonPlugin` take care of `JsonObject` family as well. :)
Or my code is kept as a workaround.

> Re: the class being in flutter, that makes sense. It'd be nice to have a built_value_flutter package that adds serializers for all the built in types. I don't think that's something I'm likely to get to any time soon, though :)

It'd be lovely but... it should be very tough to prepare those serializers and too hard to maintain them.
Rather I wish to have a nice mechanism(syntax) that helps generators to generate a serializer of a specific build in type.

Anyway, thank you for your help. I've learned a lot through this discussion and research.
