### ISSUE TITLE
Question: how to override == in generated classes

### ISSUE THREAD

**Issue by AlexBacich** [google/built_value.dart#765]
Hello,

Is there a way to change ==, hashCode, toString in generated classes? By default they are relying to all fields in my base class. I want to limit that to smaller amount of fields.

Thanks in advance, Alex

**Comment by davidmorgan** [comment]
Yes, you can add an annotation to fields to stop them being compared. See

https://pub.dev/documentation/built_value/latest/built_value/BuiltValueField-class.html

:)

**Comment by AlexBacich** [comment]
Lazy me! Should have searched better. Thanks!

**Comment by davidmorgan** [comment]
No problem, it's nice to get a question I can answer ;)
