### ISSUE TITLE
auto-generate named argument constructor so arguments don't need to be listed explicitly

### ISSUE THREAD

**Issue by dave-doty** [google/built_value.dart#767]
The [recommended way](https://medium.com/dartlang/moving-fast-with-dart-immutable-values-1e717925fafb) to create a named argument constructor requires one to type out the fields in the argument list, and to make the names exactly the same as the getter field names, e.g., 

```dart
abstract class Value implements Built<Value, ValueBuilder> {
  int get x;
  int get y;
  factory Value({int x, int y}) = _$Value._;
  Value._();
}
```

I wonder if there is a way to specify this more succinctly (and DRY-ly) as a class-level annotation (and of course it would be great not to have to specify the private `_` constructor as boilerplate either, although I understand this may be a Dart issue), e.g.,

```dart
@namedArgConstructor
abstract class Value implements Built<Value, ValueBuilder> {
  int get x;
  int get y;
}
```

**Comment by davidmorgan** [comment]
The Dart language does not currently have a way for us to generate the factory for you; you have to write it.

**Comment by noinskit** [comment]
What about auto-generating a pseudo-constructor, a function e.g. `Value createValue({@required int x, @required int y})`? From my point of view, it's a minor syntactic hassle and the current built_value constructors are already custom due to the use of builders, and having compile-time checks for supplying required values is critical!

**Comment by davidmorgan** [comment]
It doesn't help. Static functions (and constructors are basically static functions) have to be written in the manually maintained class, the language doesn't give us a way to supply them in generated code.

i.e. we can generate something but you still have to write the type signature then delegate to it for it to appear on your class. Which is exactly what you can do today :)

**Comment by noinskit** [comment]
Sorry for being unclear - I meant a globally scoped function, not a static function within the autogenerated (or source) class. (Hence it would have to have the name of the class to create in its name, like `createValue` to continue the example from this issue's requester.)

**Comment by davidmorgan** [comment]
Ah, I see, thanks.

I'm not a fan of that idea, though; a top level function that only appears in generated code is hard to import/use/discover.

Also, we can't use `@required` without forcing you to always import `package:meta` by hand :/

**Comment by noinskit** [comment]
I know, it's not *perfect*.

But honestly, from my point of view, the benefits far outweight the costs, which are
(1) remembering about one more import, which is only done once per each file with autogenerated classes, and
(2) syntactical weirdness, which is arguably less weird than with "real" constructor, but with this builder argument.

Well, I agree with the point about discoverability, too (not sure about "import" - it's "part" of the same file/"library").

As an extra benefit, I'd be able to pass such pseudo-constructor as a parameter (c.f. https://github.com/dart-lang/language/issues/216 "Proposal: allow passing constructors as functions") :)

**Comment by noinskit** [comment]
I keep thinking about this, lack of compile-time checks for using all required fields is what makes me hesitate to switch to this library, even though I understand your concern about discoverability of autogenerated methods.
What about making this an optional feature, off by default?

**Comment by davidmorgan** [comment]
I understand your concern.

I haven't found it to be a problem in practice, though: most commonly, the set of fields you assign to is fixed, i.e. something like

```
var foo = Foo((b) => b..foo = 1..bar =2);
```

which means that to be sure it's correct you just have to run it once. It's true that you could have a mistake if you never either test or run the code, but that should be rare :D

My preferred approach for checking required fields is via a lint. This should have the advantage that it can _also_ work when using the builder syntax. Just need to get around to writing it :)

**Comment by noinskit** [comment]
Of course you're right about the usual case, but it does happen in my case that I'm adding new required fields to POJOs that are not parts of an external interface, and having immediate feedback from the linter (in the form of "missing required parameter" linter rule) helps, even if I do want to have tests (i.e. runtime detection of the problem) as well.

Explicit linter rule for built_value argument builders would work for me as well - checking @required annotations is just a linter rule, after all. Is there an issue and/or ETA for this feature? All I know about dart analyzer plugin support is that it's advertised as "not currently available for general use".

**Comment by davidmorgan** [comment]
Actually I think we could probably add it to the core lint set--they already have some lints that relate to specific libraries.

So it would go under `package:lint`.

No issue/ETA yet I'm afraid.

**Comment by micimize** [comment]
what if we instead wrote
```dart
abstract class Value implements Built<Value, ValueBuilder> {
  factory Value({int x, int y}) = _$Value._;
  Value._();
}
```
and generated
```dart
extension on Value {
  int get x => _$Value.x;
  int get y => _$Value.y;
}
```
