### ISSUE TITLE
default values for named argument constructor

### ISSUE THREAD

**Issue by dave-doty** [google/built_value.dart#768]
Is there a way to use default values with the named argument constructor?

Suppose I use the [recommended method](https://github.com/google/built_value.dart/issues/643#issuecomment-546370425) for default values using `_initializeBuilder`: 

```dart
abstract class ValueWithBuilderInitializer implements
        Built<ValueWithBuilderInitializer, ValueWithBuilderInitializerBuilder> {
  int get anInt;
  static void _initializeBuilder(ValueWithBuilderInitializerBuilder b) => 
      b..anInt = 7;
  factory ValueWithBuilderInitializer([void Function(ValueWithBuilderInitializerBuilder) updates]) = 
      _$ValueWithBuilderInitializer;
  ValueWithBuilderInitializer._();
}
```

If I instead switch to the named argument constructor:
```dart
abstract class ValueWithBuilderInitializer implements
        Built<ValueWithBuilderInitializer, ValueWithBuilderInitializerBuilder> {
  int get anInt;
  static void _initializeBuilder(ValueWithBuilderInitializerBuilder b) => 
      b..anInt = 7;
  factory ValueWithBuilderInitializer({int anInt}) = 
      _$ValueWithBuilderInitializer._;
  ValueWithBuilderInitializer._();
}
```
Then attempting to use it:
```dart
var v = ValueWithBuilderInitializer();
```

I get this error message:

*Error: Tried to construct class "ValueWithBuilderInitializer" with null field "anInt". This is forbidden; to allow it, mark "anInt" with @nullable.*

For this specific instance, I can put the default value directly in the constructor:

```dart
  factory ValueWithBuilderInitializer({int anInt = 7}) = 
      _$ValueWithBuilderInitializer._;
```

But in general, the field might be a `BuiltList`, for instance, or some other type with non-const defaults:

```dart
  factory ValueWithBuilderInitializer({BuiltList<int> ints = BuiltList<int>()}) =
      _$ValueWithBuilderInitializer._;
```

which generates the error *Error: Cannot invoke a non-'const' factory where a const expression is expected.* among others.

**Comment by dave26199** [comment]
Unfortunately not.

With named arguments there is no way to know whether you explicitly passed `null` or didn't pass anything.

So it's impossible to correctly apply defaults, and the generated named arguments constructor doesn't try. If you use it then you need to handle defaults yourself.
