### ISSUE TITLE
SerializerPlugin functionality per single serializer

### ISSUE THREAD

**Issue by snird** [google/built_value.dart#770]
Hello,
So I haven't found an easy way to do this:
I want to user `SerializerPlugin` hooks, e.g the `beforeDeserialize` to enrich JSON object received from an API, before they go into the default serializer generated.

Currently, the only easy place to do it is within the serializers set defined to a package of built value classes, that live together as they are nested so they need to have their serializers defined together.
```
@SerializersFor([
  One,
  DependsOnOne,
  DependsOnTheAbove,
])
```

then ofcourse `addPlugin` on these serializers builder alongside `StandardJsonPlugin`.

But my enrichment plugin should be used only by `One` for example.
Is there an easy way to do it?

**Comment by davidmorgan** [comment]
Plugins always apply to all serializers.

But you can check the type being serialized inside the plugin, and just decide to do nothing for types that the plugin does not care about.
