### ISSUE TITLE
DDC debugging gives inconsistent values for equality

### ISSUE THREAD

**Issue by UnHumbleBen** [google/built_value.dart#772]
I have a simple test for `Grid Position`, which is a BuiltValue:
```
  test('BuiltValue GridPositon', () {
    GridPosition a = GridPosition(0, 2, 1);
    GridPosition b = GridPosition(0, 2, 1);
    expect(a, b);
  });
```
This test passes, but when I debug on DDC:
![ddc_built_value](https://user-images.githubusercontent.com/31255679/71398677-0bd5a000-25d6-11ea-821a-acdafc1ac78e.png)

The test still passes when I use DDC, but the console outputs the opposite result. For a simple example like this, it is not a big deal, but when I have a large object with many fields, these false negatives are frustrating to examine. Any idea how to fix this bug?

**Comment by davidmorgan** [comment]
`===` isn't a Dart operator; so you're comparing using javascript. I believe `===` in javascript is equivalent to `identical` in Dart. Indeed, the two objects are not identical, they are different instances. So returning `false` is right.

I suggest asking over at the DDC project for input on how best to debug with DDC.

**Comment by UnHumbleBen** [comment]
`==` also returns `false`. Is this expected?

**Comment by davidmorgan** [comment]
I don't know, sorry. I'm not particularly familiar with debugging with DDC.
