### ISSUE TITLE
Unable to update the object using toBuilder() and build()

### ISSUE THREAD

**Issue by yakubpashask** [google/built_value.dart#773]
Hey, I have all the data models that are built on built value and was facing an issue while updating the data using the toBuilder().

Here is my object structure: 
`{
  "trainData": {
    "trainBtwnStnsList": [
      {
        "avlFareData": {
          "12704-1A-T": {
            "color": "ff0000",
            "baseFare": "",
            },
          "12704-2A": {
            "color": "ff0000",
            "baseFare": "",
          }
        }
      }
    ]
  }
}`

and I want to update the same object with a new **baseFare** value which is inside "**12704-1A-T**" without a new object.
and here is what I am doing but don't see the data gets updated.
`trainData.trainBtwnStnsList[i].toBuilder()
      ..update((obj)=> obj.avlFareData[key].toBuilder()..update((d)=> avlFareDataUpdated)..build())
      ..build();`

**avlFareDataUpdated** this has the new value ==> {"baseFare":"1200","color": "ff0000"}

My end goal is to update the complete **trainData** Object with the new value.

**Comment by yakubpashask** [comment]
not sure if this is a proper way of doing it but just tried this way of nesting.
 ```
trainData.toBuilder()
      ..update((td)=>
        td.trainBtwnStnsList
          ..update((data)=>
            data[i].toBuilder()
              ..update((obj)=> 
                  obj.avlFareData[key].toBuilder()
                    ..update((d)=> avlFareDataUpdated)
                    ..build())
              ..build())
        ..build())
      ..build();
```

**Comment by dave26199** [comment]
`trainData` is immutable; you can't modify it. What you need to do is to create a new one and assign it. This goes for nested fields, too. So what you need is something more like:

```dart
trainData = trainData.rebuild((td)=>
    td.trainBtwnStnsList.data[i] =
  
       td.trainBtwnStnsList.data[i].rebuild((obj)=> 
                 obj.avlFareData[key] = obj.avlFareData[key] = avlFareDataUpdated))));
```

Typing on phone so this is a little tricky to get exactly right, but hopefully that gives you the idea :)

**Comment by yakubpashask** [comment]
Awesome. thank you so much. I was able to update the complete object now.
