### ISSUE TITLE
Question: exposing protected field class setters

### ISSUE THREAD

**Issue by micimize** [google/built_value.dart#785]
Is it possible for `built_value` to recognize the setter `appearsIn = []` for the field getter `List<Episode> get appearsIn => fields.appearsIn`? `fields` would also be a built value.

Context: For my use-case (modeling graphql's inheritance scheme) I define all fields as [a protected field on the base class](https://github.com/micimize/graphql-to-dart/blob/3c0f79491ad9a5ae22c6ee5daefac3738ed1bc5a/example/lib/graphql/schema.dart#L992), then [expose them with getters](https://github.com/micimize/graphql-to-dart/blob/3c0f79491ad9a5ae22c6ee5daefac3738ed1bc5a/example/lib/graphql/hero_for_episode.gql.dart#L39) in child classes

**Comment by micimize** [comment]
I guess I could generate a [builder with setters per-class](https://github.com/google/built_value.dart/blob/33b8f773be50a19ada301c01f46fc10bcaf4b9b1/end_to_end_test/lib/values.dart#L225), I would rather not though.

**Comment by davidmorgan** [comment]
I'm not sure I follow. Recognize how? `built_value` classes do not have setters, as they are immutable :)

**Comment by micimize** [comment]
@davidmorgan Right, I'm referring to the setters in the builder. So with the value classes:
```dart
abstract class Fields implements Built<Fields, FieldsBuilder> {
  int get id;
  //...
}

abstract class Container implements Built<Container, ContainerBuilder> {
  @protected
  Fields fields;

  int get id => fields.id;

  //...
}

// Could I then do
Container((c) => c.id = 1);

// or would it have to be
Container((c) => c.fields.id = 1);
```

```

**Comment by davidmorgan** [comment]
I don't think there's a way we could work out automatically that you want to expose all the getters of one field as top level getters. So, yes, it'd have to be `c.fields.id = 1`.

I guess we could give you an annotation that causes the getters to nested fields to be generated. I'm not sure there's a lot of demand for that. Note that you can use the cascade operator to access multiple fields:

```
Container((c) => c.fields..id = 1..otherNestedField = 2)
```

so you don't have to repeat `fields` a lot.

**Comment by micimize** [comment]
Yeah, I think it's adequately covered by writing a custom builder. It does seems to me that exposing `@protected` fields in `rebuild` is a bit inconsistent in itself, but that's a different issue
