### ISSUE TITLE
Default value example only shows the Custom Builder method

### ISSUE THREAD

**Issue by feinstein** [google/built_value.dart#787]
The example [here](https://github.com/google/built_value.dart/blob/2f72546a144a146fb12f78ae0512404f3e8423cb/example/lib/values.dart#L117) shows how to make default field values through a custom builder, but this [article](https://medium.com/dartlang/moving-fast-with-dart-immutable-values-1e717925fafb) shows another way:

>where you want to set defaults for fields, you can now do this in the factory, instead of having to write your own builder class

```dart
abstract class Value implements Built<Value, ValueBuilder> {
  int get x;
  int get y;
  bool get awesome;  factory Value([updates(ValueBuilder b)]) =>
      new _$Value((b) => b
          ..awesome = True
          ..update(updates));
}void main() {
  var value = new Value((b) => b
      ..x = 10
      ..y = 20);
}
```

The examples should reflect this.

**Comment by davidmorgan** [comment]
Indeed it should, thanks. There's also a third way, using a 'builder initializer' method.

**Comment by davidmorgan** [comment]
https://github.com/google/built_value.dart/issues/1042
