### ISSUE TITLE
watch not detecting when @SerializersFor changed to another file

### ISSUE THREAD

**Issue by feinstein** [google/built_value.dart#789]
I added the whole `@SerializersFor` [initialization](https://github.com/google/built_value.dart/blob/master/example/lib/serializers.dart) on `main.dart`, killed the `watch` command and restarted it and it created the `main.g.dart` successfully. 

Later I decided to change `@SerializersFor` for another location and created `serialization.dart` and placed it there instead, but `watch` didn't update my files with a new one, it just removed `main.g.dart`. I had to restart `watch` again to get a `serialization.g.dart`.

Is this expected behavior?

**Comment by davidmorgan** [comment]
I don't think so; this is likely an issue for `package:build`.
