### ISSUE TITLE
Serializers should accept Converters

### ISSUE THREAD

**Issue by feinstein** [google/built_value.dart#790]
In my use case I have a `Map<String, dynamic>` and I wanted to just pass this to a `Serializer` and create my class. The `StandardJsonPlugin` looked promising, but things didn't work out that well.

My class has a `DateTime` field, but the `Map<String, dynamic>` has a `Timestamp` instead (provided by the Firebase Firestore Flutter package). So the desserialization fails, as `StandardJsonPlugin` can't create a `DateTime` from a `Timestamp`. 

In other languages this is as simple as providing a `Converter`, that knows how to create a `DateTime` from a `Timestamp` and vice-versa, but I can't find any documentation on how to achieve this in `built_value`.

**Comment by davidmorgan** [comment]
I agreed we could do better here.

Recommendation over at #791 for how to achieve this with `built_value`'s current support.

**Comment by feinstein** [comment]
Sorry, but did you forget to link something at #791? 😬

**Comment by davidmorgan** [comment]
Odd, I'm sure I wrote a response, I don't know where it ended up. Re-posted (approximately) :)
