### ISSUE TITLE
SerializerPlugin don't allow for changing the Object's Type

### ISSUE THREAD

**Issue by feinstein** [google/built_value.dart#791]
I want to convert a Firebase `Timestamp` to a `DateTime` so I tried the following:

```dart
class TimestampToDateTimeConverter implements SerializerPlugin {
  @override
  Object afterDeserialize(Object object, FullType specifiedType) {
    return object;
  }

  @override
  Object afterSerialize(Object object, FullType specifiedType) {
    return object;
  }

  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Timestamp) {
      return object.toDate();
    } else {
      return object;
    }
  }

  @override
  Object beforeSerialize(Object object, FullType specifiedType) {
    return object;
  }
}
```

But as far as I understand the `specifiedType`, passed to the `beforeDeserialize()`, won't change, so the serialization engine don't know that a `Timestamp` became a `DateTime` and it keeps complaining there isn't a serializer for a `Timestamp` even though I can see it's converted properly.

Maybe this plugin API should return a tuple with a new `Object` and a new `FullType`?

**Comment by davidmorgan** [comment]
I think the right way to do this is to implement your own `DateTimeSerializer` class, i.e. a fork of:

https://github.com/google/built_value.dart/blob/master/built_value/lib/src/date_time_serializer.dart

The `specifiedType` should always be the deserialized type, so it can just be `DateTime`.

**Comment by feinstein** [comment]
And how will the framework know which serializer to call? Mine or the original one?

**Comment by feinstein** [comment]
Further discussion/code about this in #543

**Comment by feinstein** [comment]
I tried to add my own `DateTimeSerializer` with `(_$serializers.toBuilder()..add(DateTimeSerializer())..addPlugin(StandardJsonPlugin())).build();` but it isn't even being called.

**Comment by feinstein** [comment]
@davidmorgan sorry to bother you with this, but I am a bit lost and can't find any docs on this, I tried this as well, but it doesn't even gets called:

```dart
@SerializersFor([
  MyType,
  Timestamp,
])
final Serializers serializers =
    (_$serializers.toBuilder()..add(TimestampSerializer())..addPlugin(StandardJsonPlugin())).build();

class TimestampSerializer implements PrimitiveSerializer<Timestamp> {
  final bool structured = false;
  @override
  final Iterable<Type> types = BuiltList<Type>([Timestamp]);
  @override
  final String wireName = 'Timestamp';

  @override
  Object serialize(Serializers serializers, Timestamp timestamp,
      {FullType specifiedType = FullType.unspecified}) {
    return timestamp.microsecondsSinceEpoch;
  }

  @override
  Timestamp deserialize(Serializers serializers, Object serialized,
      {FullType specifiedType = FullType.unspecified}) {
    var microsecondsSinceEpoch = serialized as int;
    return Timestamp.fromMicrosecondsSinceEpoch(microsecondsSinceEpoch);
  }
}
```

**Comment by davidmorgan** [comment]
You need to call `serializers.add` to register your serializer. It will replace the one that's already registered for `DateTime`.

**Comment by davidmorgan** [comment]
(It looks like github is losing some posts! I saw a reply of yours in email but don't see it here).

Your `TimestampSerializer` is a serializer of `DateTime`, not a serializer of `TimeStamp`. It's always the _deserialized_ type that is referred to, just like with `specifiedType`.

So

```
final Iterable<Type> types = BuiltList<Type>([Timestamp]);
```

should be

```
final Iterable<Type> types = BuiltList<Type>([DateTime]);
```

:)

**Comment by feinstein** [comment]
This time it's not github's fault, I deleted it myself as I made it work. The problem was me at the end... I changed the code a lot to test some hypothesis and forgot enterely, so the serializers weren't being called because I changed the types and forgot to replace them back. Thanks David!
