### ISSUE TITLE
Use built_value with model which implements(extends) entity

### ISSUE THREAD

**Issue by don-prog** [google/built_value.dart#792]
I'm trying to use `built_value` in [this template app](https://github.com/ResoCoder/flutter-tdd-clean-architecture-course). Now I want to use `built_value` with my model class(e.g. `BuiltNumberTriviaModel`) which I use as the `Chopper` response class. My model should extend my entity (e.g. `NumberTrivia`) which extends `Equatable`, and this is the problem. You know that I can neither extend my model `BuiltNumberTriviaModel`, nor implement if superclass extends `Equatable`.
So, what will be the best architectural solution here? Change hierarchy? Remove `Equatable` or `built_value`?
I'm really new to `Flutter` and `Dart`, so sorry for the possibly stupid question.

**Comment by davidmorgan** [comment]
Hmm, what is it you want `built_value` to do for you? :)

**Comment by don-prog** [comment]
@davidmorgan I think the main advantages ara that I can conveniently use serialization and deserialization for `Chopper` and also value equality.

**Comment by davidmorgan** [comment]
It looks like there is a tutorial here on how to combine built_value and chopper :)

https://resocoder.com/2019/07/14/chopper-retrofit-for-flutter-3-converters-built-value-integration/

**Comment by don-prog** [comment]
Thanks, I already saw this tutorial, but unfortunately the model in it does not implement the entity class.

**Comment by davidmorgan** [comment]
I'm not directly familiar with Chopper, but I suspect the approach they're describing is the right one; I don't think it will work to extend the entity class, I think you'll need to convert between built_value and the entity class like they do.

**Comment by don-prog** [comment]
@davidmorgan 
> I think you'll need to convert between built_value and the entity class like they do.

But in this tutorial he didn't use the model and entity, but only the model(`BuiltPost`) which he also uses in the UI. So, what do you mean?

**Comment by davidmorgan** [comment]
I think the idea is that you hide the entity class and only use the model class for everything. Doesn't that work for you?

I really don't know anything about chopper, so I'm guessing here :)

**Comment by don-prog** [comment]
Ok, thanks, I will use this idea
