### ISSUE TITLE
Non-nullable fields are null in rebuild() closure

### ISSUE THREAD

**Issue by filiph** [google/built_value.dart#80]
[I may be doing something wrong, and it's too late for me to try and build a reduced test case, so take this with a grain of salt.]

I have a class like this:

```
abstract class Situation implements Built<Situation, SituationBuilder> {
  int get id;
  SituationState get state;
  // ...
}
```

And an associated builder like this:

```
abstract class SituationBuilder
    implements Builder<Situation, SituationBuilder> {
  @virtual
  int id = _random.nextInt(_largeInteger);
  @virtual
  SituationState state;

  SituationBuilder._();
  factory SituationBuilder() = _$SituationBuilder;
}
```

Note that `state` is not nullable. But when I run `rebuild` on the situation, the provided SituationBuilder instance's `state` field is set to `null`.

I'm on Dart 1.21.0. Problem happens both on Dart VM and in dart2js. The previous version didn't seem to have this issue (although I did recently refactor so I can't be sure).

Here's some debugging flow when `rebuild` is called on a Situation instance.

---

<img width="480" alt="screen shot 2016-12-08 at 00 28 38" src="https://cloud.githubusercontent.com/assets/919717/21003032/e90ad568-bcdd-11e6-9101-52295842f209.png">

---

<img width="334" alt="screen shot 2016-12-08 at 00 29 15" src="https://cloud.githubusercontent.com/assets/919717/21003047/04b41e3c-bcde-11e6-83ed-9153e1c20900.png">

---

<img width="419" alt="screen shot 2016-12-08 at 00 29 57" src="https://cloud.githubusercontent.com/assets/919717/21003055/0f5f0b12-bcde-11e6-96c0-8d56fa06892f.png">

---

<img width="242" alt="screen shot 2016-12-08 at 00 30 10" src="https://cloud.githubusercontent.com/assets/919717/21003059/18430648-bcde-11e6-9ba9-bd3ddb754954.png">

---

The last one is the state of the SituationBuilder when it's being passed to the provided `updates()` closure.

**Comment by davidmorgan** [comment]
Thanks! You're quite right. The problem is that the builder fields remain null until any setter is used. They should rather remain null until any setter _or_ getter is used. I'll send a fix.

**Comment by davidmorgan** [comment]
PTAL https://github.com/google/built_value.dart/pull/81
