### ISSUE TITLE
API/docs/examples for _finalizeBuilder?

### ISSUE THREAD

**Issue by dave-doty** [google/built_value.dart#805]
I'm a bit confused how to use `_finalizeBuilder` (or maybe more generally how to use Builder objects).

In my example case, I want to enforce a more complex logic for nullability: to ad-hoc simulate a [Union type](https://en.wikipedia.org/wiki/Union_type), I have two fields `position` and `grid_position`, both Built objects, and I want to enforce that exactly one of them is `null`.

Here's how I ended up doing it, which feels awkward:

```dart
@nullable
GridPosition get grid_position;

@nullable
Position3D get position;

static void _finalizeBuilder(HelixBuilder b) {
    if (b._$this._grid_position == null && b._$this._position == null) {
      throw ArgumentError('exactly one of Helix.grid_position and Helix.position should be null, '
          'but both are null.');
    }
    if (b._$this._grid_position != null && b._$this._position != null) {
      throw ArgumentError('exactly one of Helix.grid_position and Helix.position should be null, '
          'but both are non-null.');
    }
  }
```

Most other checks I tried didn't work. Suppose I actually set one of them to `null` and the other not in the constructor, nevertheless `builder.position` and `builder.grid_position` are both non-`null` (i.e., a non-`null` builder is used to represent a `null` built value)

On the other hand (though I can't seem to reproduce it now), I thought there was a condition under which both `builder._position` and `builder._grid_position` could both be `null`, even though one was set to non-`null` in the constructor.

Is there a recommended way to access field values (particularly nested builders) in `_finalizeBuilder`?

**Comment by davidmorgan** [comment]
As you've discovered, nested builders are auto created when accessed via getters. This is mostly convenient but sometimes rather confusing :)

You don't need `_finalizeBuilder` for validation; you can just put it in the constructor called `_`. See `ValidatedValue` here:

https://github.com/google/built_value.dart/blob/master/example/lib/values.dart

**Comment by dave-doty** [comment]
Ah, thanks!

What cases is `_finalBuilder` useful for?

**Comment by davidmorgan** [comment]
No problem.

`_finalizeBuilder` is primarily for when you want to _modify_ values before they're immutable. For example, if you have a `path` field, you could canonicalize the path in `_finalizeBuilder`.

A special case is that you might want to use it for wrapping values that can are mutable until frozen, to ensure everything gets frozen.

**Comment by davidmorgan** [comment]
https://github.com/google/built_value.dart/issues/1051
