### ISSUE TITLE
@nullable nested collections act non-intuitively

### ISSUE THREAD

**Issue by bmcbarron** [google/built_value.dart#809]
A nested built collection in a built value's builder is initialized to an empty collection whenever it is read, to allow this pattern:
`(b) => b.map.replace({...});`

While consistent from a syntax perspective, it is surprising that merely reading a @nullable member can cause it to become non-null. Disallowing @nullable on such fields would avoid this surprise. Given that this API is in heavy use, changing the behavior might be difficult, so maybe a lint warning would be sufficient to avoid this trap.

I considered commenting on #754 instead, but the issues seemed subtly different to me.

**Comment by davidmorgan** [comment]
Yes, it's surprising. This is a tradeoff, as you say, against usability.

I kind of think that declaring a collection nullable to start with is a weird thing to do :) ... at the very least, it needs a comment to explain what's going on.

There's definitely some improvement left for nullable nested builders as mentioned in #754. I'm open to other suggestions. Adding a lint would be one option, but personally I prefer that a lint has no false positives, i.e. that it's always possible to make the lint not fire. I wonder if we should have a softer form of lint which is just advisory; that would then need to be supported through all the tools/UI so it's surfaced in a non-annoying way...

**Comment by laurensdewaele** [comment]
Hi, not sure where to place this but this seems best here:

I have following nested collections: 
`Hold` that has a field `Grip rightGrip` that is nullable.
`Grip` in turn, also a field `Fingers fingers` that is not nullable.

I explicitly set rightGrip = null, but then built_value tries to set all the underlying values, also to null, which definitely should not be nullable. I don't understand why it does this, or why this is intended?

If this is intended behaviour, how do I specify that rightGrip can be null, without actually setting it to null. I'm at a loss here :D

`The following BuiltValueNestedFieldError was thrown while handling a gesture:
Tried to build class "Hold" but nested builder for field "rightGrip" threw: Tried to build class
 "Grip" but nested builder for field "fingers" threw: Tried to construct class "Fingers" with null
field "pinky". This is forbidden; to allow it, mark "pinky" with @nullable.`

**Comment by davidmorgan** [comment]
@laurensdewaele There must have been a problem with setting `rightGrip` to `null`. Once it's null, there is no 'nested builder for field "rightGrp"' as complained about in the error message.

Note that as per this issue, it's easy to accidentally get a builder again--this happens if you use the 'rightGrip' getter in any way.
