### ISSUE TITLE
Deep match runtimeType in equalsBuilt

### ISSUE THREAD

**Issue by jellzilla** [google/built_value.dart#810]
IIUC, the current implementation of `equalsBuilt` does two things:
1. Checks the runtimeType of the expected and actual values.
2. Does a deep comparison of a struct-like Map representation of the expected and actual values.

I would like to see the runtimeType checked at each level of the deep comparison as well. This is particularly important for generic fields of the top-level Built.

For example:

```
class Root implements Built<Root, RootBuilder> {
  BuiltList<Generic<Object>> get children;
  ...
}

class Generic<T> extends Built<Generic<T>, GenericBuilder<T>> {
  ...
}
```

Because neither `Generic.operator==()` nor `equalsBuilt()` on `Root` will check the type arguments of `Root.children`, there is no way to easily test this.

I can see deep runtimeType checking potentially having the drawback where the expected value intends to use less-specific types that happen to match the actual value. I'm not sure how important this is to maintain.

**Comment by davidmorgan** [comment]
Makes sense. Here's a thought: why not add that as a different matcher? `equalsBuiltExactTypes`?
