### ISSUE TITLE
using built_value to serialize/deserialize a class involving generic parameters.

### ISSUE THREAD

**Issue by hasan314** [google/built_value.dart#811]
I am facing a problem while deserializing a response from a REST Api. 

Here is what I am trying to do:

I have an ApiResponse class which returns a standard response object from my Api and one of the parameters of this class is a generic result type which varies based on the endpoint I call. 

The model class code looks like this: 

`abstract class ApiResponse<T extends Object>
    implements Built<ApiResponse<T>, ApiResponseBuilder<T>> {
  static Serializer<ApiResponse> get serializer => _$apiResponseSerializer;

  T get Result;
  bool get Success;
  BuiltList<ApiError> get Errors; // This is a built list of type ApiError. 
  BuiltList<String> get Messages;  // This is a built list of type String.
  ApiResultInfo get ResultInfo;

  ApiResponse._();

  factory ApiResponse([updates(ApiResponseBuilder<T> b)]) = _$ApiResponse<T>;
}

abstract class ApiError implements Built<ApiError, ApiErrorBuilder> {
  static Serializer<ApiError> get serializer => _$apiErrorSerializer;

  int get Code;
  String get Message;
  Object get ErrorData;

  ApiError._();

  factory ApiError([updates(ApiErrorBuilder b)]) = _$ApiError;
}

abstract class ApiResultInfo
    implements Built<ApiResultInfo, ApiResultInfoBuilder> {
  static Serializer<ApiResultInfo> get serializer => _$apiResultInfoSerializer;

  @nullable
  int get Page;

  @nullable
  int get PerPage;

  @nullable
  int get Count;

  @nullable
  int get TotalCount;

  ApiResultInfo._();

  factory ApiResultInfo([updates(ApiResultInfoBuilder b)]) = _$ApiResultInfo;
}
`

Here is my serializers class code:

`@SerializersFor(const [
  LoginResponse,
  ApiResultInfo,
  ApiError,
  ApiResponse
])

final Serializers serializers = (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();`

And then I am using these like this:

` http.Response res = await http.post(loginUrl, body: json.encode({
      "email": request.email,
      "password": request.password
    }), headers: {"Content-type": "application/json"});
	
	if (res.statusCode == 200) {

      final jsonBody = serializers.serialize(res.body);
      final response = serializers.deserialize(res.body);
      
      final ApiResponse<LoginResponse> response = json.decode(res.body);
	  
	  /* here I wish to process the response*/
	  
	  } `

Here is the output for flutter doctor:

![image](https://user-images.githubusercontent.com/12174643/73085816-3eb9cf00-3ec7-11ea-953a-c7ddb6cb5d68.png)

Here are the package versions I am using: 

![image](https://user-images.githubusercontent.com/12174643/73085838-4e391800-3ec7-11ea-856b-ff60454b3369.png)

Here is the error I get:

![image](https://user-images.githubusercontent.com/12174643/73085881-601abb00-3ec7-11ea-92da-e35d6f1d3f69.png)

I have been searching for the past week but haven't found a solution so far and so I am posting this issue here. I have just started using flutter ( I am researching which framework to use for the Company's mobile app and I have been stuck at this point). Any help would be appreciated. 

Thanks

**Comment by davidmorgan** [comment]
I think this code is the problem

```
  final jsonBody = serializers.serialize(res.body);
  final response = serializers.deserialize(res.body);
  
  final ApiResponse<LoginResponse> response = json.decode(res.body);
```

you need to call `json.code` then `serializers.serialize`, e.g.

```
  final ApiResponse<LoginResponse> response = serializers.deserialize(json.decode(res.body));
```

Good luck :)
