### ISSUE TITLE
constant values for built_value class fields

### ISSUE THREAD

**Issue by dustin-graham** [google/built_value.dart#812]
Hello,
I'm using built_value in conjunction with Cloud Firestore. It's working great but there is something I'd like to be able to do with built_value which would help our workflow. The Firestore SDK's query mechanism requires the string name of the field which I want to filter on. for example:

given this built_value class:
```dart
abstract class InspectionTemplate
    implements
        Built<InspectionTemplate, InspectionTemplateBuilder>,
        FirestoreDocument {
  InspectionTemplate._();

  String get name;

  /// Field I am filtering with
  BuiltList<String> get vehicleIds;

  bool get requireMeterUpdate;

  bool get requireSignature;

  BuiltList<InspectionTemplateSection> get sections;

  static Serializer<InspectionTemplate> get serializer =>
      _$inspectionTemplateSerializer;

  factory InspectionTemplate(
          [void Function(InspectionTemplateBuilder) updates]) =
      _$InspectionTemplate;
}
```

Firestore requires my filter query to provide the name of the field used in the query
```dart
collectionRef.where(
      "vehicleIds",
      arrayContains: userId,
    )
```

I'd prefer to not have the string literal "vehicleIds" in my codebase as this is a maintenance burden. I'd like to ask if there is a way to get a collection of constants generated for my built_value classes. Looking at the generated serializers, the builder definitely has access to the names of the fields, there just needs to be a place to put these values as constants so that they can be access in other parts of the program. I imagine a built_enum might be useful for this purpose, we'd have to have a built_enum generated as a companion to the built_value file. Perhaps you have another idea of how I might be able to get the field names generated for me.

Thank you!

**Comment by davidmorgan** [comment]
We could do something like

```
abstract class InspectionTemplate ... {
  static BuiltValueMetadata<InspectionTemplate> get metadata => _$metadata;
}
```

And `BuiltValueMetadata` has an EnumClass called `fields`. The tricky thing is that this would be of a new type, e.g. `InspectionTemplateFields`, that doesn't exist outside the generated code. Usually we try to minimize how much API gets generated.

I can't think of any nice way of doing this :/

**Comment by dustin-graham** [comment]
@davidmorgan thanks for getting back to me!

I can now see the trouble with getting this to work with an EnumClass. However, instead could we do something similar to how the Builder classes are generated?

```dart
// inspection_template.dart

abstract class InspectionTemplate ... {

  String get templateName;

  /// required pattern {ClassName}Metadata get metadata => _$metadata;
  static InspectionTemplateMetadata get metadata => _$metadata;
}
```

```dart
// inspection_template.g.dart

class InspectionTemplateMetadata {
  static const templateName = 'templateName'
}
```

Then from other places in my app I could do this:

```dart
final fieldName = inspectionTemplate.metadata.templateName;
```

The other thing that occurs to me that could be done with this pattern is to use the generated Metadata class to store other useful information about fields that can be gathered from annotations during code generation processing. 

for example, I really like having the `_initializeBuilder` feature for... initializing builders. It's invaluable for setting default values. However, I think that if we had  a `defaultValue` field in `BuiltValueField`, we could store that default value in something like a `BuildValueFieldMetadata<T>` within the generated Metadata class. Maybe it could look like this:

```dart
// somewhere in the built_value library... built_value_field_metadata.dart

class BuiltValueFieldMetadata<T> {
  final String fieldName;

  // nullable
  final T defaultValue;

  const BuiltValueFieldMetadata(this.fieldName, this.defaultValue);
}
```

```dart
// inspection_template.dart

abstract class InspectionTemplate ... {

  @BuiltValueField(defaultValue = 'Inspection Template')
  String get templateName;

  /// required pattern {ClassName}Metadata get metadata => _$metadata;
  static InspectionTemplateMetadata get metadata => _$metadata;
}
```

```dart
// inspection_template.g.dart

class InspectionTemplateMetadata {
  static const templateName = BuiltValueFieldMetadata<String>('templateName','Inspection Template');
}
```

```dart
final fieldName = inspectionTemplate.metadata.templateName.fieldName;
```

Then in the `inspection_template.g.dart`, where it creates the InspectionTemplateBuilder, it could use my the metadata to initialize the builder with any default values that were set in the annotations.

I know that setting default values isn't exactly on topic for this issue, but this solution seems to be at least one way of getting useful information about our classes since we don't reflection available to us.

**Comment by dustin-graham** [comment]
@davidmorgan also, if we can decide on a direction for this feature to be done. I'd love to contribute the feature to the project.
