### ISSUE TITLE
Multiple type field [question]

### ISSUE THREAD

**Issue by jans-y** [google/built_value.dart#818]
**Hi,**

I wasn't able to find out on my own if it's possible to create BuiltValue class where one field can have multiple types (in my case it is either Double or String).

```
class CustomBuiltValueClass {
    // I have a JSON that has field named **value** which is in 90% of situations String
    String get value;
    // in 10% of situations it could also be a double
    double get value;
}
```
Is this possible to do this or is the only way to create two separate classes and determine in my code the actual runtimeType of that field and use the corresponding Serializer class?

**Thank you!**

**Comment by davidmorgan** [comment]
Sorry for slow response.

There isn't a great way of dealing with this now, unfortunately. You could have two `@nullable` fields, one of type `String` and one of type `double`, and only set one of them. Or you could have one `Object` field, and add methods to access it that do casts to the type you want. Either way you'll need custom deserialization to manage that.
