### ISSUE TITLE
"Builder" conflicts with Flutter

### ISSUE THREAD

**Issue by jrwang** [google/built_value.dart#825]
I get this conflict when using built_value and Flutter:
```
The name 'Builder' is defined in the libraries 'package:built_value/built_value.dart' and 'package:flutter/src/widgets/basic.dart'. #ambiguous_import
  Classes and mixins can only implement other classes and mixins. #implements_non_class
```
However, using qualified imports for `built_value.dart` presents this issue:

`Stop using "as" when importing "package:built_value/built_value.dart". It prevents the generated code from finding helper methods.
`

The alternative of using qualified imports for Flutter core libraries seems onerous.

**Comment by dave26199** [comment]
Do you need `Builder` from `built_value`? If not, you can `hide` it. Maybe that solves your problem?

**Comment by micimize** [comment]
Workarounds to this:
1. `import 'package:flutter/material.dart' as flutter`
2. `import 'package:flutter/material.dart' hide Builder`
3. break your built values into a separate file
