### ISSUE TITLE
VSCode extension and IntelliJ plugin with built value snippets

### ISSUE THREAD

**Issue by GiancarloCode** [google/built_value.dart#826]
I love this library. 😁

I have created an extension for VSCode and plugin for IntelliJ with different snippets that help save a lot of time, It has helped me a lot and I hope someone else will find it useful.
* [VSCode extension](https://marketplace.visualstudio.com/items?itemName=GiancarloCode.built-value-snippets)
* [IntelliJ plugin](https://plugins.jetbrains.com/plugin/13786-built-value-snippets)
* [Repository](https://github.com/GiancarloCode/vscode-built-value-snippets)

If you have any suggestions I would appreciate it.

**Comment by davidmorgan** [comment]
Very nice, thanks :) added links to the "tools" section of the README.

The only nitpick/suggestion from my side is that the `toMap` and `fromMap` methods generated for e.g. `btvs` are only needed if you're using serialization in a particular way; so maybe they should be optional. That said, it's easy enough to delete them if you don't want them, so maybe also not :)

Thanks.

**Comment by GiancarloCode** [comment]
Great, thanks for reviewing and adding it in the README. :)

What you say is true, it could be optional, but I have reviewed several projects and they mostly use serialization in conjunction with `StandardJsonPlugin`, and they usually add these methods, (usually from/to Json/Map) so have more snippets It could be more annoying than having to remove them manually.

PD I have hardly seen any project that doesn't use `StandardJsonPlugin` when use serialization. :)

**Comment by davidmorgan** [comment]
Makes sense, thanks.

The two ways I use `built_value` serialization are 1) server and client both in Dart, and 2) command line tools in Dart. The default works really well for this. I realize neither of these is at all a common use case, though ;)
