### ISSUE TITLE
[question] Deserialize  primitive field as custom class

### ISSUE THREAD

**Issue by AlexBacich** [google/built_value.dart#827]
Hey, I have another question on library usage. 

I have built_value class with some primitive fields which can be serialized\deserialized with no problem.

```
@BuiltValueField(wireName: 'currency')
  String get currency;
```

What I want to do though is to create custom class for primitive type.  In my case is something like this:

```
@BuiltValueField(wireName: 'currency')
 Currency get currency;
```

Currency only has one stored field name.

I tried my Currency class implement PrimitiveSerializer<Currency> and StructuredSerializer<Currency>, tried adding class into Serializers. 

However I get error "Bad state: No serializer for 'Currency' all the time during deserialization of parent class containing Currency field

I can probably provide custom serializer for all build_value classes containing my Currency field, but that's a lot of classes.

What is the right way to do this? 

Thanks @davidmorgan  for this amazing library.

**Comment by AlexBacich** [comment]
Ah, found missing part! 
In Serializers I should've put line:
`..add(CurrencySerializer())`

**Comment by AlexBacich** [comment]
To summarize things to do what I wanted you need two steps: 
1. Create YourClassSerializer implementing PrimitiveSerializer<YourClass>
2 Add this line into serializers.dart:
..add(YourClassSerializer())

**Comment by kaparray** [comment]
How write my custom CurrencySerializer?

**Comment by AlexBacich** [comment]
My example:

```
class CurrencySerializer implements PrimitiveSerializer<Currency> {
  @override
  final Iterable<Type> types = BuiltList<Type>([Currency]);
  @override
  final String wireName = 'Currency';

  @override
  Object serialize(Serializers serializers, Currency object, {FullType specifiedType = FullType.unspecified}) =>
      object.name;

  @override
  Currency deserialize(Serializers serializers, Object serialized, {FullType specifiedType = FullType.unspecified}) =>
      Currency._(serialized as String);
}

```

**Comment by kaparray** [comment]
Thx
