### ISSUE TITLE
How parse BuiltMap<int, BuiltMap<int, BuiltMap<int, BuiltMap<int, int>>>>

### ISSUE THREAD

**Issue by kaparray** [google/built_value.dart#828]
I faced such a problem and don't know how to solve it. I get this JSON from the server:

{
"123": {
       "32": {
            "4324": { "29": "4"}
         }
   },
"312": {
       "4324": {
            "63": { "3": "9"}
         },
  "53": {
            "823": { "24": "65"}
         }
   }
}

In the log I see this:
failed due to: Bad state: No builder factory for Bitmap<int, Bitmap<int, Bitmap<int, int>>>. Fix by adding one, see Serializers Builder.add a Builder Factory.

Please help me fix it :)

**Comment by davidmorgan** [comment]
Description is here: https://pub.dev/documentation/built_value/latest/serializer/SerializersBuilder/addBuilderFactory.html

For your specific case, it's something like

```
serializers = (serializers.toBuilder()
      ..addBuilderFactory(
        const FullType(Bitmap, [FullType(int), FullType(Bitmap, [FullType(int), FullType(Bitmap, [int, int])])]),
        () => BitmapBuilder<int, Bitmap<int, Bitmap<int, int>>>(),
      ))
    .build();
```

Bit tricky to get all the brackets right, I might have missed one :)

**Comment by kaparray** [comment]
In my case I add this:

```dart
final Serializers serializers = (_$serializers.toBuilder()
      ..addPlugin(
        StandardJsonPlugin(),
      )
      ..addBuilderFactory(
        const FullType(BuiltMap, [
          FullType(int),
          FullType(BuiltMap, [
            FullType(int),
            FullType(BuiltMap, [
              FullType(int),
              FullType(BuiltMap, [FullType(int), FullType(int)])
            ]),
          ]),
        ]),
        () => BuiltMap<int, BuiltMap<int, BuiltMap<int, BuiltMap<int, int>>>>()
            .toBuilder(),
      )
      ..addBuilderFactory(
        const FullType(BuiltMap, [
          FullType(int),
          FullType(BuiltMap, [
            FullType(int),
            FullType(BuiltMap, [FullType(int), FullType(int)])
          ]),
        ]),
        () => BuiltMap<int, BuiltMap<int, BuiltMap<int, int>>>().toBuilder(),
      )
      ..addBuilderFactory(
        const FullType(BuiltMap, [
          FullType(int),
          FullType(BuiltMap, [FullType(int), FullType(int)])
        ]),
        () => BuiltMap<int, BuiltMap<int, int>>().toBuilder(),
      )
      ..addBuilderFactory(
        const FullType(BuiltMap, [FullType(int), FullType(int)]),
        () => BuiltMap<int, int>().toBuilder(),
      ))
    .build();
```

**Comment by jans-y** [comment]
This bug still exists.

I mean that deeper BuiltMap structures don't get all the factories generated.

Is this going to be fixed?

I am fixing it manually every time I run codegen right now but I am using CI/CD where it's not possible.

Other solution would be to commit *.g.dart to my Git => Is there any argument why it shouldn't be done?

Thank you.

**Comment by davidmorgan** [comment]
You don't need to add the builder factories in the generated code, you can add it in your own checked in code.

Checking in `*.g.dart` works too.
