### ISSUE TITLE
Is it possible to decode an object with json string  property ?

### ISSUE THREAD

**Issue by jerryzhoujw** [google/built_value.dart#833]
Here's a example json: 

Is that possible use built_value to decode the config to a json object ?

```json
{
  "data": {
    "me": {
      "id": "5",
      "username": "JJ",
      "config": "{\"school\":\"high_school\",\"class\":\"[\\\"math\\\",\\\"physics\\\",\\\"sports\\\"]\"}"
    }
  }
}
```

**Comment by jerryzhoujw** [comment]
I think my problem can be, is it possible to specify a property need to do extra `jsonDecode()` before normal deserialize.

**Comment by davidmorgan** [comment]
There's no built in way to do that, you'd have to write either a custom serializer for the class or a serializer plugin.

**Comment by jerryzhoujw** [comment]
Thank you @davidmorgan , I just do extra decode in the property again when I read this value, with simply set the property as String.
