### ISSUE TITLE
Incorrect factory validation on _Builders

### ISSUE THREAD

**Issue by micimize** [google/built_value.dart#835]
A custom builder `_Builder` will fail validation with `factory _Builder() = _$Builder`, asking instead for `_$_Builder`. However, it is the former that is generated.
```
Error in BuiltValueGenerator for

  abstract class _HomeSelectionSet with Home
    implements Built<_HomeSelectionSet, _HomeSelectionSetBuilder>.

Please make the following changes to use BuiltValue:
  1. Make builder class have exactly one factory:
    factory _HomeSelectionSetBuilder() = _$_HomeSelectionSetBuilder
```

(Not much of) a workaround is to use the `_$_Builder` statement for generation, then `s/_\$_/_$/g` in the source file, or simply don't use protected builders.

**Comment by davidmorgan** [comment]
Thanks for taking a look at this.

Unfortunately there is a more complex/subtle issue with allowing classes to be library private.

For serialization we need to be able to generate references to the serializer field in the central `serializers.g.dart`, and, if a class appears in a generic type, we need to be able to generate 'builder factories'. Both of these will break if the type is private:

```
Serializers _$serializers = (new Serializers().toBuilder()
      ..add(_HomeSelectionSet.serializer
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(_HomeSelectionSet)]),
          () => new ListBuilder<_HomeSelectionSet>())
```

I don't see a nice workaround for this, and I'm hesitant to allow private classes when they won't be fully supported. It's also kind of nice to ban private classes in case any _future_ generated code needs to access them.

An alternative pattern would be to put the classes that you want to be private under a `/src/` path so it's clear they're not meant to be used from outside the package. The codegen will still work :)

Happy for any better suggestions, of course :)

**Comment by micimize** [comment]
Ahh, I see. But regardless, we might as well correct the generated names, and then add a check that instructs user to unhide their serializables, so that it reads as "disallowed" rather than "broken"

I think one option would be to conditionally generate
```dart
_$serializers = Map<Serializer, Built>;
```
if `final serializers = _$serializers;` exists in the source file, and then conditionally use that for aggregating the serializers. The same approach could be generalized to other centralization mechanisms in the future. Or `built_value.Serializer` could have a singleton collector instance that is used to collect serializers in the generated code. I like that even more.

**Comment by micimize** [comment]
In https://github.com/micimize/built-graphql I'm just generating `Serializers` on a per-file basis. There are also plenty of other ways a user can export privatized classes, like `const serializables = <Type>[_MySerializable];`

One nice thing about private classes is that even if they are somehow completely broken in the future, they can't (or shouldn't) really involve a breaking change on the user's part

**Comment by davidmorgan** [comment]
Unfortunately singleton collectors don't work in Dart; there's no way to have static initialization code that runs on startup, so there's no way for generated code in each library to add itself into the singleton. Here's the language issue / discussion: https://github.com/dart-lang/language/issues/369

So, we have to be able to generate something that can find the generated serializers. It's true that we could export the types somehow, but that seems broken: changes to private classes, should be okay, but we'd be making that not true. (e.g. using the name in serialization).

I think the right solution here is as you said: allow private classes, but don't allow them to have serializers. Private serialized classes are a weird corner--we would be writing the name on the wire, their fields end up public in the wire protocol and so can't be changed, and people can cause them to be instantiated by passing particular data to your app. Seems like just forbidding it with a nice error message is reasonable.

What do you think?

Thanks.

**Comment by micimize** [comment]
Ahh yes I think that's the ideal approach

**Comment by micimize** [comment]
Alright, added a `name.startsWith('_')` error check to the serializers generator to #836, along with tests for that and to ensure `_Value` generates 
`allOf(isNot(contains(r'_$_')), isNot(contains(r'1.')));`
