### ISSUE TITLE
Dynamic field updates using data from a Map<String, dynamic>

### ISSUE THREAD

**Issue by oliverfunk** [google/built_value.dart#839]
Say I have a complex hierarchical state model with many fields, some of which can be nullable and some can't.
I want to apply validations to fields that require it when they are updated (and only when they are updated), so I can guarantee that the state will never be invalid.

I also want to express some of these validated fields as types (i.e. ValidatedTypes) so I can parameterise my business logic method using them (so I know I can trust the data while using it in business logic calls).
I am new to dart and can't really figure out the best way of making the ValidatedType, but that's not really in the scope of this question.

This what I've got so far (excuse the length):

```dart

typedef Validator<T> = void Function(T);

abstract class ValidatedType<T> {
  final T _value;

  T get value => _value;

  ValidatedType(this._value, Validator validator) {
    validator(_value);
  }
}

class IDVal extends ValidatedType<int> {
  static Validator validator = (n) {
    if (n % 10 != 0) throw Exception('id should be divisible by 10!');
  };

  IDVal(int id) : super(id, validator);
}


abstract class Root implements Built<Root, RootBuilder> {
  String get name;
  int get id;

  @nullable
  Inner get inner;

  Root._();

  factory Root([updates(RootBuilder b)]) = _$Root;

  static Serializer<Root> get serializer => _$rootSerializer;

  static Root fromMap(Map<String, dynamic> modelData) =>
      serializers.deserializeWith(Root.serializer, modelData);

  Map<String, dynamic> toMap() => serializers.serializeWith(Root.serializer, this);

  Root rebuildWith(Map<String, dynamic> fieldUpdates)=> this.rebuild((b) => b..replace(Root.fromMap(fieldUpdates)));
}

abstract class RootBuilder implements Builder<Root, RootBuilder> {
  String name;

  int _id;
  int get id => _id;
  set id(int i) {
    IDVal.validator(i);
    _id = i;
  }

  Inner inner;

  factory RootBuilder() = _$RootBuilder;

  RootBuilder._();
}

abstract class Inner implements Built<Inner, InnerBuilder> {
  BuiltList<Inners> get inners;

  Inner._();

  factory Inner([updates(InnerBuilder b)]) = _$Inner;

  static Serializer<Inner> get serializer => _$innerSerializer;
}

abstract class Inners implements Built<Inners, InnersBuilder> {
  int get num;
  // could be more complex...

  Inners._();

  factory Inners([updates(InnersBuilder b)]) = _$Inners;

  static Serializer<Inners> get serializer => _$innersSerializer;
}

abstract class InnersBuilder implements Builder<Inners, InnersBuilder> {
  int _num;
  int get num => _num;
  set num(int n) {
    if (n<0){
      throw Exception('num must be < 0');
    }
  }

  factory InnersBuilder() = _$InnersBuilder;

  InnersBuilder._();
}
```

Then you can call rebuildWith with the data in the correct Map<String, dynamic> format (so it can be deserialized to a Root object).

The serializer is using the standard JSON plugin.

2 problems with this:

1. I have to make every field @nullable to make this work, which I don't want. For example, name and id shouldn't be null for a valid state.
2. rebuildWith creates an intermediate, unnecessary instance of Root (using fromMap)

Any suggestions on how to do this better? I'm trying to stick to something simple so as much of the work can be generated for me, given that the Root model could be very long and complex.

This is similar to #434

**Comment by davidmorgan** [comment]
The supported way of checking the final class is to put all the checks in the constructor of the class. Then the builder should be used for partial/invalid instances, and when you build, everything is checked.

Does that not work for your use case?

Thanks.
