### ISSUE TITLE
The method 'MultiHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.

### ISSUE THREAD

**Issue by sidlatau** [google/built_value.dart#841]
I am switched to flutter dev channel (v1.15.20) and code generation stopped to work.
I am using these versions:
```
built_value: ^7.0.9
build_runner: ^1.8.0
built_value_generator: ^7.0.9
```

Error:
```
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../flutter/.pub-cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:129:8: Error: The method 'MultiHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.  void set(String name, Object value) {       ^org-dartlang-sdk:///sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').  void set(String name, Object value,       ^../../flutter/.pub-cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:97:8: Error: The method 'MultiHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.  void add(String name, Object value) {       ^org-dartlang-sdk:///sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').  void add(String name, Object value,       ^
```

**Comment by davidmorgan** [comment]
I don't think this relates to `built_value`; it's a problem with your dependencies.

Looks like you need `http_multi_server` version `2.2.0`.

I suggest trying `pub upgrade`, and see if it will upgrade to that version. If not, try specifying it in  your `pubspec.yaml` and you'll find out which package is preventing the upgrade--then you can file an issue for that.

**Comment by sidlatau** [comment]
Thanks, `flutter pub upgrade` solved the problem!

**Comment by davicg** [comment]
> I don't think this relates to `built_value`; it's a problem with your dependencies.
> 
> Looks like you need `http_multi_server` version `2.2.0`.
> 
> I suggest trying `pub upgrade`, and see if it will upgrade to that version. If not, try specifying it in your `pubspec.yaml` and you'll find out which package is preventing the upgrade--then you can file an issue for that.

Had the same issue! Running flutter pub ugrade solved! Thanks!!

**Comment by lukepighetti** [comment]
Fixed it for me too. What's going on behind the scenes to make this fix the issue?

**Comment by natebosch** [comment]
> I always assumed pub was pulling the highest version for each package that meets constraints without me having to remind it to.

`flutter packages get` or `pub get` will generally try to fetch the _same_ versions of packages you already have (though I think if you change your pubspec there might be cases where it ends up upgrading packages it doesn't need to...)

`flutter packages upgrade` or `pub upgrade` will always try to fetch the latest version of packages.

**Comment by daniloapr** [comment]
I had the same issue and `flutter pub upgrade` worked for me.
