### ISSUE TITLE
resolve analysis error

### ISSUE THREAD

**Issue by MahdiPishguy** [google/built_value.dart#844]
i'm using latest version of this library and this below code is for older version of the library,

**Error:** `(serializers.serializerForType(SingleItemType))`

> error: The argument type 'Serializer<dynamic>' can't be assigned to the parameter type 'Serializer<SingleItemType>'. (argument_type_not_assignable at [xxxx] lib\service\built_value_converter.dart:41)

**code:**
```dart
  SingleItemType _deserialize<SingleItemType>(Map<String, dynamic> value) {
    return serializers.deserializeWith(serializers.serializerForType(SingleItemType), value);
  }
```

**Error:** 

> // built_value_converter.dart:22
> _convertToCustomObject<SingleItemType>(dynamicResponse.body)
> 
> // built_value_converter.dart:37
> (element)

> error: The argument type 'dynamic' can't be assigned to the parameter type 'Map<String, dynamic>'. (argument_type_not_assignable at [xxxxx] lib\service\built_value_converter.dart:37)

and 

> error: The argument type 'dynamic' can't be assigned to the parameter type 'Map<String, dynamic>'. (argument_type_not_assignable at [xxxxx] lib\service\built_value_converter.dart:22)

code:
```dart
  @override
  Response<BodyType> convertResponse<BodyType, SingleItemType>(Response response) {
    final Response dynamicResponse = super.convertResponse(response);
    final BodyType customBody = _convertToCustomObject<SingleItemType>(dynamicResponse.body);
    return dynamicResponse.copyWith(body: customBody);
  }

  BuiltList<SingleItemType> _deserializerListOf<SingleItemType>(List dynamicList) {
    return BuiltList<SingleItemType>(dynamicList.map((element) => _deserialize<SingleItemType>(element)));
  }
```

**Comment by davidmorgan** [comment]
From the error message I'm guessing you have a class called `Serializer` defined yourself somewhere (or in another library you depend on besides `built_vlaue`) and it's clashing with the one in `built_value`. Could that be the problem?

**Comment by MahdiPishguy** [comment]
@davidmorgan i get error in AndroidStudio and dart analysis, my serializer class is very basic

```
part 'serializers.g.dart';
@SerializersFor([
    BuiltInstagramAccountData,BuiltUserInfo,BuiltPageInfo,
    BuiltUserInAccountData,BuiltBiographyWithEntities,BuiltEntities,
    BuiltHashtag,BuiltPeopleData,BuiltFeeds,BuiltFacepileTopLikers,BuiltCaption,
    BuiltImageVersions2,BuiltCandidates,BuiltHighlights,BuiltStories,BuiltUserInStories,
    BuiltFollowings,BuiltUsersInFollowings,BuiltFollowers,BuiltUsersInFollowers
  ]
)
//@formatter:on
final Serializers serializers = (_$serializers.toBuilder()
  ..addPlugin(StandardJsonPlugin())).build();
```

**Comment by davidmorgan** [comment]
Likely you have some `import` that is providing a different implementation of `Serializers`.
