### ISSUE TITLE
Error while handling 204 status code

### ISSUE THREAD

**Issue by MangeshKadam** [google/built_value.dart#854]
API which I am using returns 200 in some cases and 204 for other cases. Json deserialization works perfectly fine for 200 as response string is json. But in case of 204, response is empty string. In this case it throws below error
FormatException: Unexpected end of input

How to handle empty string here?

**Comment by davidmorgan** [comment]
Just check if the string is empty before you try to deserialize it, and do something else :)

Or, catch the FormatException and do something else.
