### ISSUE TITLE
Deserialize a DateTime from two sources in different formats

### ISSUE THREAD

**Issue by elvis-gbmme** [google/built_value.dart#857]
Hi,
I have a built_value class that gets data from two sources (firestore and elasticsearch). The two formats are Firestore in DateTime and elastic in DateTime as String.

I'm already using the following serializers StandardJsonPlugin, TimestampSerializerPlugin (#541) and GeopointSerializerPlugin

The firesstore data is working fine after using the TimestampSerializer, but the elasticsearch sends the DateTime in a string format which causes the following exception
`failed due to: Deserializing '2019-07-22T09:43:01.000Z' to 'DateTime' failed due to: type 'String' is not a subtype of type 'int' in type cast`

I found #454 to be close to my issue and tried using it, but it breaks even my firestore serialization with the error `Unhandled Exception: type '_TypeError' is not a subtype of type 'Exception'`.

Kindly help.

Thanks.

**Comment by Rahuvich** [comment]
I am currently dealing with this exact issue.
`Deserializing '1998-04-02T05:35:55.000Z' to 'DateTime' failed due to: type 'String' is not a subtype of type 'int' in type cast)`

If you find any solution I would appreciate you letting me know. Same way, if I find something :)

**Comment by davidmorgan** [comment]
This requires https://github.com/google/built_value.dart/issues/1046
