### ISSUE TITLE
Cannot serialize generic values if type parameter isn't explicitly used.

### ISSUE THREAD

**Issue by brandondiamond** [google/built_value.dart#861]
I have a built value that uses a generic type solely for type safety (to "brand" the value):

```
abstract class Id<T> implements Built<Id<T>, IdBuilder<T>> {
  static Serializer<Id> get serializer => _$idSerializer;

  String get name;

  factory Id.of(String name) => Id<T>((b) => b..name = name);
  factory Id([void Function(IdBuilder<T>) updates]) = _$Id<T>;
  Id._();
}

```

When the type "T" isn't actually used, the generated serializer elides the BuilderFactory lookup; as a result, the type parameter isn't correctly bound. This results in an error.

Is there a way to work around this limitation?

Thank you!

**Comment by brandondiamond** [comment]
Looks like this is where the decision is made:
https://github.com/google/built_value.dart/blob/master/built_value_generator/lib/src/serializer_source_class.dart#L416

I realize this is a bit of a fringe case. Would this be something worth supporting with an annotation? Or is the best solution to include a nullable dummy field?

**Comment by davidmorgan** [comment]
I can't think of a reason why it won't work :)

I'll aim to give it a try the next time I work on a `built_value` release.

If you want to experiment with it yourself before then I'd be interested to hear how it goes :)
