### ISSUE TITLE
Issue when an inherited getter is overrided with an implementation

### ISSUE THREAD

**Issue by nnaskov** [google/built_value.dart#863]
Hey @davidmorgan  I think I am seeing an issue related to #328 , where the generated class does not compile. 

Here is how I reproduce it:

```dart
@BuiltValue(instantiable: false)
abstract class BaseGeneric extends Object {
  String get name;

  BaseGeneric rebuild(void Function(BaseGenericBuilder) updates);
  BaseGenericBuilder toBuilder();
}

abstract class Child extends Object
    implements BaseGeneric, Built<Child, ChildBuilder> {
  @override
  String get name => "myname";

  Child._();
  factory Child([void Function(ChildBuilder) updates]) = _$Child;
}
```
And this is the error for the generated ChildClass
```
Error: The non-abstract class 'ChildBuilder' is missing implementations for these members:
 - BaseGenericBuilder.name
 - BaseGenericBuilder.name=
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
```

The problem comes from `@BuiltValue(instantiable: false)`. If I remove this line then the  generated class compiles, but then obviously, I cannot have the `.rebuild()` and `.toBuilder()` methods on the `BaseGeneric` class.

Am I doing something stupid or is this a bug?

**Comment by davidmorgan** [comment]
Correct, that relates to the linked issue. The only way to do what you want right now is to split `BaseGeneric` into two classes. One has `@BuiltValue(instantiable: false)` and contains getters for things that you want to be _fields_, i.e. to have a settable value. The other does not have a `BuiltValue` annotation, it is a normal interface, and can have getters for things that are allowed to be hardcoded.

I think it would be possible to add a way to mark fields in `BaseGeneric` so a builder field is not generated so them, `@BuiltValueField(isAField: false)`, but that would be a new feature for `built_value`.
