### ISSUE TITLE
[Question] Using multiple mixins that can `rebuild`

### ISSUE THREAD

**Issue by andreavaccari** [google/built_value.dart#864]
Hi @davidmorgan, thank you for your work on this excellent package.

I need help in understanding how to define small classes or mixins that represent "units" of state and behavior, and how to compose these units in different ways to define more complex built values. The code below illustrates this idea and is self explanatory.

```dart
abstract class Identity {
  Identifier get id;
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

@BuiltValue(instantiable: false)
abstract class Selectable {
  Selectable rebuild(void Function(SelectableBuilder) updates);
  SelectableBuilder toBuilder();

  bool get selected;

  Selectable toggleSelected({bool value}) {
    return rebuild((b) => b..selected = value ?? !b.selected);
  }
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

@BuiltValue(instantiable: false)
abstract class Starrable {
  Starrable rebuild(void Function(StarrableBuilder) updates);
  StarrableBuilder toBuilder();

  bool get starred;

  Starrable toggleStarred({bool value}) {
    return rebuild((b) => b..starred = value ?? !b.starred);
  }
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

@BuiltValue(instantiable: false)
abstract class BaseNode implements Identity, Selectable, Starrable {
  BaseNode rebuild(void Function(BaseNodeBuilder) updates);
  BaseNodeBuilder toBuilder();

  Identifier get parent;
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

abstract class TextNode implements BaseNode, Built<TextNode, TextNodeBuilder> {
  TextNode._();

  factory TextNode([void Function(TextNodeBuilder) updates]) = _$TextNode;

  String get text;
}

```

The above obviously doesn't work because the definition of `_$TextNode` in the generated file is missing concrete implementations of `Selectable.toggleSelected` and `Starrable.toggleStarred`.

If I attempt to fix the issue with:

```dart
@BuiltValue(instantiable: false)
abstract class BaseNode with Identity, Selectable, Starrable {
  BaseNode rebuild(void Function(BaseNodeBuilder) updates);

  BaseNodeBuilder toBuilder();

  Identifier get parent;
}
```

The above gives me error because of conflicts between `BaseNode.rebuild`, `Selectable.rebuild`, and `Starrable.rebuild`, and similarly for `*.toBuilder`

I tried different variations of the above setup but I always get one or more errors in `BaseNode`, `TextNode`, or in the generated file. I'm having a hard time understanding if this is a limitation of `built_value` or if I need to tweak my code.

Please note that I'd like to keep `Identity`, `Selectable`, and `Starrable` separate, as I have other domain entities that need only some subset of the above, e.g. only `Identity` and `Selectable`, or only `Identity` and `Starrable`.

Thank you in advance for your help!

**Comment by andreavaccari** [comment]
Hi @davidmorgan, I investigated this more and found a solution that works after some tweaks to the generated code. I figured I should check with you before trying to touch `built_value_generator`. Below are my code and  the tweaks to the generated code.

Incidentally, I'm convinced the answer to this issue must be related to #862 and maybe also #863. However, I'm having a hard time concisely explaining how these different ideas come together.

```dart
abstract class Identity {
  String get id;
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

abstract class Mergeable<E extends Mergeable<E>> {
  E merge(E prev, E next);
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

@BuiltValue(instantiable: false)
abstract class BaseEntity {
  BaseEntity rebuild(void Function(BaseEntityBuilder) updates);
  BaseEntityBuilder toBuilder();

  String get id;
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

@BuiltValue(instantiable: false)
abstract class Starrable<V extends Starrable<V, B>,
    B extends StarrableBuilder<V, B>> {
  V rebuild(void Function(B) updates);
  B toBuilder();

  bool get starred;

  V toggleStar({bool value}) {
    return rebuild((b) => b.starred = value ?? !b.starred);
  }
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

@BuiltValue(instantiable: false)
abstract class Selectable<V extends Selectable<V, B>,
    B extends SelectableBuilder<V, B>> {
  V rebuild(void Function(B) updates);
  B toBuilder();

  bool get selected;

  V toggleSelect({bool value}) {
    return rebuild((b) => b.selected = value ?? !b.selected);
  }
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

@BuiltValue(instantiable: false)
abstract class BaseNode
    implements
        Identity,
        Mergeable<BaseNode>,
        Starrable<BaseNode, BaseNodeBuilder>,
        Selectable<BaseNode, BaseNodeBuilder> {
  @override
  BaseNode rebuild(void Function(BaseNodeBuilder) updates);
  @override
  BaseNodeBuilder toBuilder();
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

abstract class TextNode
    with
        Starrable<BaseNode, BaseNodeBuilder>,
        Selectable<BaseNode, BaseNodeBuilder>
    implements BaseNode, Built<TextNode, TextNodeBuilder> {
  TextNode._();

  factory TextNode([void Function(TextNodeBuilder) updates]) = _$TextNode;

  String get text;

  @override
  TextNode merge(BaseNode prev, BaseNode next) {
    return null;
  }
}
```

The generated code needs 3 tweaks:

```dart
abstract class StarrableBuilder<V extends Starrable<V, B>,
    B extends dynamic> {
// to
abstract class StarrableBuilder<V extends Starrable<V, B>,
    B extends StarrableBuilder<V, B>> {
```

```dart
abstract class SelectableBuilder<V extends Selectable<V, B>,
    B extends dynamic> {
// to
abstract class SelectableBuilder<V extends Selectable<V, B>,
    B extends SelectableBuilder<V, B>> {
```

```dart
abstract class BaseNodeBuilder
    implements
        StarrableBuilder<BaseNode, dynamic>,
        SelectableBuilder<BaseNode, dynamic> {
// to
abstract class BaseNodeBuilder
    implements
        StarrableBuilder<BaseNode, BaseNodeBuilder>,
        SelectableBuilder<BaseNode, BaseNodeBuilder> {
```

There are two more issues with the above code that are worth mentioning.

Firstly, I ideally would like to mixin `Starrable` and `Selectable` in `BaseNode` rather than in `TextNode`. If I do so, I get a compile-time error that `_$TextNode` is missing implementations for `TextNode.Selectable.toggleSelect%Selectable.toggleSelect` and for `TextNode.Starrable.toggleStar%Starrable.toggleStar`.

Secondly, I noticed that if I define a non-instantiable Built Value `A` and a Built Value `B` that implements `A`, `BBuilder` will correctly implement `ABuilder`. However, if I define the Built Value `B` to mixin `A`, `BBuilder` will not implement or mixin `ABuilder`. Is there a reason for this? I would prefer to mixin than implement so I can inherit methods implementation. (I'm aware I can do both, but I'm not a fan of the unnecessary repetition).

Hope this is clear. Thank you for your help!

**Comment by davidmorgan** [comment]
Thanks for all the detail :)

This is a more complex case than I've considered so far. I've been thinking of at most a single `instantiable: false` base class (or, singly-rooted hierarchy) which you get 'common fields' from, i.e. fields that are represented on the base builder as well. Then, polymorphic use of further fields would rely on normal interfaces, meaning they are only present on the value, with no shared builder interface.

If there's a way to make it work in a more composable way then that sounds great. You're welcome to play with generator. I suggest running `tool/use_local_deps` to get everything to use local deps then adding to `end_to_end_test` to experiment.

Two notes of caution: 1) I don't get a lot of time for non-urgent work on `built_value`, so it might take ~months to land something, unless it turns out to be very easy to land; and 2) the transition to NNBD is coming soon, I might reject changes before that since fixing up the generator to generate null safe code is already a fairly daunting project.

Those warnings aside, this is a very interesting area and I'd definitely like to improve `built_value` here.

Thanks :)

**Comment by andreavaccari** [comment]
Hi @davidmorgan, I hope you are well. I'm going to close this issue as it's become clear I won't be able to work on it anytime soon. Thank you for your help in understanding this issue and for your work on the library!
