### ISSUE TITLE
Allow Setting default case for wireName

### ISSUE THREAD

**Issue by ibrahim-mubarak** [google/built_value.dart#866]
It would be incredibly useful to set a default "case" for `wireName`. Some APIs dominantly use Camel Case but in my opinion most use Snake Case.

However on the Dart Side, the norm is to use camel case for non constant Identifiers. Using snake case can trigger Dart Analyser to throw warnings.

We should be able to Set the default case at a global level and class level.

**Comment by davidmorgan** [comment]
That's a good idea. Options we could offer: lower_snake_case, UPPER_SNAKE_CASE; any others?

**Comment by ibrahim-mubarak** [comment]
Most common cases for Strings would be 

- snake_case
- camelCase
- PascalCase or UpperCamelCase
- CONSTANT_CASE or UPPER_SNAKE_CASE
- param-case or kebab-case
- Header-Case
- Title Case
- Sentence case

Implementing most of these might not make sense with regards to JSON APIs though.

**Comment by RiteshChandnani** [comment]
Isn't this same as #743?

**Comment by davidmorgan** [comment]
You are correct, thanks! I will increase the priority of that issue and close this one :)
