### ISSUE TITLE
StandardJsonPlugin: serialize as list.

### ISSUE THREAD

**Issue by GiacomoRandazzo** [google/built_value.dart#868]
Hi, thanks for this great package!

I ran into a problem and am looking for a clean solution.

I have a `Delta` and `DeltaOperations` built values.
```dart
abstract class Delta implements Built<Delta, DeltaBuilder> {
    BuiltList<DeltaOperation> get operations;

    // other fields that I don't want to serialize
   
    // other methods
}
```

I want to serialize the `Delta` built value, the only field that needs to be serialized is a `BuiltList`. Therefore I'd like the output of the serialization to be a list like `[{...delta op 1..., ...delta op2..., ...]`.

I've tried creating a custom serializer but with no success.
The problem is that, whatever I do in the custom serializer, `StandardJsonPlugin`'s `afterSerialize` will try to convert the `List` into a `Map`, since `specifiedType.root == Delta`. https://github.com/google/built_value.dart/blob/c639efb991bad52cb903ade6fd5619a2679c02ef/built_value/lib/standard_json_plugin.dart#L39-L52

The only way out seems to be overriding `afterSerialize` in a new plugin, but it seems like an overkill to me.
Is there any other way to solve this problem?

Another option would be to serialize `operation` in `Delta`'s `toJson` method, instead of `this`. But my guess is that it would not work if I serialize another built value with a `Delta` as field.

I appreciate any help you can provide.

**Comment by davidmorgan** [comment]
The only thing I can think of is that you could store the values as a `BuiltList<DeltaOperation>` in the class that currently contains a `Delta`. Then, to provide a `Delta`, you could provide a getter (or maybe a memoized getter) which converts that list into a `Delta`.

**Comment by RAN3000** [comment]
I wish there was a less convoluted way, thank you though!
