### ISSUE TITLE
memoized `hashCode` throws error message: "1. Stop implementing hashCode; it will be generated for you."

### ISSUE THREAD

**Issue by UnHumbleBen** [google/built_value.dart#870]
I tried adding memozied `hashCode` as specified [here](https://github.com/google/built_value.dart/blob/master/CHANGELOG.md#710):
```
 @memoized
  int get hashCode
```

But I get the error message:

```
1. Stop implementing hashCode; it will be generated for you.
```

Am I doing something wrong?

**Comment by davidmorgan** [comment]
Are you on version `7.1.0`? Maybe `pub upgrade`?

**Comment by UnHumbleBen** [comment]
My mistake. You are right. Thank you.

**Comment by davidmorgan** [comment]
Glad I could help, enjoy your memoized hashCodes ;)
