### ISSUE TITLE
Specify field serialization and deserialization separately 

### ISSUE THREAD

**Issue by AirborneEagle** [google/built_value.dart#872]
This is a question.
I am hoping that I have just overlooked the answer, as I have been unable to find it in documentation etc.

I have a field `id` which I want populated when creating the object from a data response.

But I do not want to have the field in the object that is sent back.

so what I would hope I could do is something like:
```
  @BuiltValueField(serialize: false, deserialize: true)
  @nullable
  String get id;
```
does that make sense what I am trying to do?

**Comment by davidmorgan** [comment]
There isn't a direct way to do that. I think the best way is to have the field be `@nullable` then clear it before serializing.

We _could_ support it as an annotation, but I'm not sure there's enough call for it for it to be worth adding. I'll leave this issue around so people can add their +1s if they want it too :)

Thanks.

**Comment by AirborneEagle** [comment]
So when a field value is null, it does not get serialized?

**Comment by davidmorgan** [comment]
That's correct, nothing is written for nulls, unless you write `@BuiltValue(serializeNulls: true)`.

**Comment by mrverdant13** [comment]
@davidmorgan did you mean `@BuiltValueSerializer(serializeNulls: true)`?
I can't find the `serializeNulls` argument on `BuiltValue`.

**Comment by dave26199** [comment]
Yes :)
