### ISSUE TITLE
StandardJsonPlugin deserialize to ListJsonObject instead of MapJsonObject?

### ISSUE THREAD

**Issue by okadan** [google/built_value.dart#874]
Without StandardJsonPlugin, the value is converted to MapJsonObject as expected,
but with StandardJsonPlugin, the value is converted to ListJsonObject as unexpectedly.

**Environment**

- dart: 2.8.2
- built_value: 7.1.0

**Minimum Reproduce**

``` dart
final serializers = (_$serializers.toBuilder()
  ..addPlugin(StandardJsonPlugin())
).build()

final object = serializers.deserialize({'key': 'value'}, specifiedType: FullType(MapJsonObject));
print(object.runtimeType); // => ListJsonObject
```

**Comment by davidmorgan** [comment]
Does it work if you use `specifiedType: FullType(JsonObject)` instead?

If so that should be a workaround; and the fix will be a few more special cases in `standard_json_plugin.dart`.

Thanks.

**Comment by okadan** [comment]
> Does it work if you use specifiedType: FullType(JsonObject) instead?

This workaround seems to work.
