### ISSUE TITLE
Has support for nullable types been added for Dart 2.9.0?

### ISSUE THREAD

**Issue by long1eu** [google/built_value.dart#877]

**Comment by davidmorgan** [comment]
No, but looking forward to doing it :)

**Comment by long1eu** [comment]
Awesome. Can't wait :D

**Comment by hillelcoren** [comment]
@davidmorgan you rock, thanks again for all of your efforts with this project!

**Comment by pspgt** [comment]
Are there some updates on this?

**Comment by davidmorgan** [comment]
The code is updated for null safety, but not published.

Since null safety is still experimental, there isn't currently a nice way to publish it that works, e.g. you'll find it hard to make `pub build` work.

Once there is an SDK release where null safety is no longer experimental, that should be fixed, and I can publish :)

**Comment by idootop** [comment]
> The code is updated for null safety, but not published.
> 
> Since null safety is still experimental, there isn't currently a nice way to publish it that works, e.g. you'll find it hard to make `pub run build_runner build` work.
> 
> Once there is an SDK release where null safety is no longer experimental, that should be fixed, and I can publish :)

How to use it?
![图片](https://user-images.githubusercontent.com/35302658/97411706-9516db00-193b-11eb-9369-57aec8ce5d53.png)

**Comment by davidmorgan** [comment]
I don't think there's a good way right now.

The SDK release mentioned above is coming soon--easiest is to wait a week or two :)

**Comment by idootop** [comment]
> I don't think there's a good way right now.
> 
> The SDK release mentioned above is coming soon--easiest is to wait a week or two :)

ok, thx.
