### ISSUE TITLE
[Question] [Bug] Builder with extension

### ISSUE THREAD

**Issue by kaparray** [google/built_value.dart#878]
I have a model with two string type fields. This error is output during generation:

Error in BuiltValueGenerator for abstract class CredentialsSubState implements Built<CredentialsSubState, dynamic>.
Please make the following changes to use BuiltValue:

1. Make field accessToken have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
2. Make field refreshToken have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.

I connect my extension, which looks like this:

extension StringExample on String {
  bool get isBlank => this == null || isEmpty;
  bool get isNotBlank => this != null && isNotEmpty;
}

How fix it?

**Comment by davidmorgan** [comment]
I'm not sure how the error relates to the extension. 

What does the model class look like? In particular, what is the type of `accessToken` and `refreshToken`?

**Comment by kaparray** [comment]
@nullable
  String get accessToken;

  @nullable
  String get refreshToken;

**Comment by kaparray** [comment]
Maybe I create demo project to show this problem?

**Comment by dave26199** [comment]
Maybe you have an old analyzer version. Could you please try `pub upgrade`? Or the Flutter equivalent if you're using Flutter.
