### ISSUE TITLE
Firestore write failed when using built_value models

### ISSUE THREAD

**Issue by souryanair** [google/built_value.dart#879]
Hi David,

Would appreciate your help on the below query. 

pubspec.yaml status
dependencies:
  built_value: ^7.1.0
  built_collection: ^4.3.2

dev_dependencies:
  build_runner: ^1.10.0
  source_gen: ^0.9.5
  built_value_generator: ^7.1.0

Please find the below Built Classes 
abstract class Address implements Built<Address, AddressBuilder> {
  @nullable
  String get addressLines;
  @nullable
  String get city;
  @nullable
  String get state;
  @nullable
  String get country;
  Address._();

  factory Address([void Function(AddressBuilder) updates]) = _$Address;

  String toJson() {
    return
        json.encode(serializers.serializeWith(Address.serializer, this))
        ;
  }

  static Address fromJson(String jsonString) {
    return serializers.deserializeWith(
        Address.serializer, json.decode(jsonString));
  }

  static Serializer<Address> get serializer => _$addressSerializer;
}

When the build is being written as below, its reflecting an error 
    final address2 = AddressBuilder()
      ..addressLines = address.addressLines
      ..city = address.city
      ..state = address.state
      ..country = address.country
      ..postalCode = address.postalCode;

    Firestore.instance.runTransaction((Transaction transactionHandler) async {
      CollectionReference reference = Firestore.instance.collection("address");

      await reference
          .add(serializers.serializeWith(Address.serializer, address2.build()));
    });

Error details -
E/CloudFirestorePlugin( 6665): java.lang.Exception: DoTransaction failed: type 'List<Object>' is not a subtype of type 'Map<String, dynamic>'
E/CloudFirestorePlugin( 6665): java.util.concurrent.ExecutionException: java.lang.Exception: DoTransaction failed: type 'List<Object>' is not a subtype of type 'Map<String, dynamic>'
E/CloudFirestorePlugin( 6665): 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.0.2:69)
E/CloudFirestorePlugin( 6665): 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.0.2:33)
E/CloudFirestorePlugin( 6665): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:571)
E/CloudFirestorePlugin( 6665): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:523)
E/CloudFirestorePlugin( 6665): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$0(com.google.firebase:firebase-firestore@@21.3.0:301)
E/CloudFirestorePlugin( 6665): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$5.call(Unknown Source:6)
E/CloudFirestorePlugin( 6665): 	at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@17.0.2:2)
E/CloudFirestorePlugin( 6665): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin( 6665): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin( 6665): 	at java.lang.Thread.run(Thread.java:919)
E/CloudFirestorePlugin( 6665): Caused by: java.lang.Exception: DoTransaction failed: type 'List<Object>' is not a subtype of type 'Map<String, dynamic>'
E/CloudFirestorePlugin( 6665): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4$1$1.error(CloudFirestorePlugin.java:553)
E/CloudFirestorePlugin( 6665): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:205)
E/CloudFirestorePlugin( 6665): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:103)
E/CloudFirestorePlugin( 6665): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:642)
E/CloudFirestorePlugin( 6665): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CloudFirestorePlugin( 6665): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/CloudFirestorePlugin( 6665): 	at android.os.Looper.loop(Looper.java:174)
E/CloudFirestorePlugin( 6665): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/CloudFirestorePlugin( 6665): 	at java.lang.reflect.Method.invoke(Native Method)
E/CloudFirestorePlugin( 6665): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/CloudFirestorePlugin( 6665): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 6665): [ERROR:flutter/shell/common/shell.cc(213)] Dart Error: Unhandled exception:
E/flutter ( 6665): PlatformException(Error performing transaction, java.lang.Exception: DoTransaction failed: type 'List<Object>' is not a subtype of type 'Map<String, dynamic>', null)
E/flutter ( 6665): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 6665): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 6665): <asynchronous suspension>
E/flutter ( 6665): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 6665): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:48)
E/flutter ( 6665): #4      MethodChannelFirestore.runTransaction (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:123:10)
E/flutter ( 6665): #5      Firestore.runTransaction (package:cloud_firestore/src/firestore.dart:85:22)
E/flutter ( 6665): #6      ABCState.build (package:myapp/pages/page1.dart:1675:24)
E/flutter ( 6665): #7      StatefulElement.build (package:flutter/src/widgets/framework.dart:4623:28)
E/flutter ( 6665): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
E/flutter ( 6665): #9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter ( 6665): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 6665): #11     StatefulElement.update (package:flutter/src/widgets/framework.dart:4711:5)
E/flutter ( 6665): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5841:14)
E/flutter ( 6665): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 6665): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 6665): #17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4587:5)
E/flutter ( 6665): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5841:14)
E/flutter ( 6665): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5841:14)
E/flutter ( 6665): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 6665): #24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter ( 6665): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 6665): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:4711:5)
E/flutter ( 6665): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5841:14)
E/flutter ( 6665): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5841:14)
E/flutter ( 6665): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 6665): #33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter ( 6665): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 6665): #35     StatefulElement.update (package:flutter/src/widgets/framework.dart:4711:5)
E/flutter ( 6665): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 6665): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 6665): #39     StatelessElement.update (package:flutter/src/widgets/framework.dart:4587:5)
E/flutter ( 6665): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
E/flutter ( 6665): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 6665): #42     StatefulElement.performRebuild (package:flutter/src/widgets/frame

This is the first issue i'm raising on github ! Request your understanding in case I missed anything !

**Comment by davidmorgan** [comment]
Are you using `StandardJsonPlugin`? If not, you should be :) examples here

https://github.com/google/built_value.dart/issues/171

**Comment by souryanair** [comment]
Yes, I'm using it 👍

Serializers serializers = _$serializers;

Serializers standardSerializers =
    (serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();

**Comment by davidmorgan** [comment]
Hmmmm but in your code you call `serializers.serializerWith`, to use it you need to call `standardSerializers.serializerWith`, I think ;)

**Comment by souryanair** [comment]
> Hmmmm but in your code you call `serializers.serializerWith`, to use it you need to call `standardSerializers.serializerWith`, I think ;)

Thank you for pointing that out! 
I’ll do the changes and get back on this!!

**Comment by souryanair** [comment]
Thank you @davidmorgan for the help. This is now sorted and it’s working fine!!

**Comment by souryanair** [comment]
Thanks again!
