### ISSUE TITLE
Q: How to write Primitive Wrapper Classes?

### ISSUE THREAD

**Issue by justinfargnoli** [google/built_value.dart#882]
My team and I are having trouble trying to parse a web servers json response into wrapper classes of dart's primitive datatypes. 

We've been using this simple [example of fetching the information of an album](https://flutter.dev/docs/cookbook/networking/fetch-data) to try and find a solution. 

The example will correctly parse into the following class.

    abstract class Album implements Built<Album, AlbumBuilder> {
      int get userId;
      int get id;
      String get title;
    
      Album._();
      factory Album([void Function(AlbumBuilder) updates]) = _$Album;

      Map<String, dynamic> toJson() {
        return serializers.serializeWith(Album.serializer, this);
      }

      static Album fromJson(Map<String, dynamic> json) {
        return serializers.deserializeWith(Album.serializer, json);
      }

      static Serializer<Album> get serializer => _$albumSerializer;
    }

However, when we modify it to use a wrapper, namely 'UserID', of the dart primitive type 'int' (as shown below), built_value is no longer able to parse the response. 

    abstract class UserId implements Built<UserId, UserIdBuilder> {
      int get userId;
    
      UserId._();
      factory UserId([void Function(UserIdBuilder) updates]) = _$UserId;
    
      Map<String, dynamic> toJson() {
        return serializers.serializeWith(UserId.serializer, this);
      }
    
      static UserId fromJson(Map<String, dynamic> json) {
        return serializers.deserializeWith(UserId.serializer, json);
      }
    
      static Serializer<UserId> get serializer => _$userIdSerializer;
    }
    
    abstract class Album implements Built<Album, AlbumBuilder> {
      UserId get userId;
      int get id;
      String get title;
    
      Album._();
      factory Album([void Function(AlbumBuilder) updates]) = _$Album;
    
      Map<String, dynamic> toJson() {
        return serializers.serializeWith(Album.serializer, this);
      }
    
      static Album fromJson(Map<String, dynamic> json) {
        return serializers.deserializeWith(Album.serializer, json);
      }
    
      static Serializer<Album> get serializer => _$albumSerializer;
    }

We have been struggling to find an ergonomic way to address this with built_value. (We have also tried using json_serializable with little success.) Is there a simple solution to this or a nice workaround? 

Thank you for your help in advance :)

**Comment by justinfargnoli** [comment]
In case you'd like to see our code, here it is:
[learn_built_value.zip](https://github.com/google/built_value.dart/files/4784160/learn_built_value.zip)

**Comment by davidmorgan** [comment]
One way would be to supply your own serializer for `UserId` instead of it using the generated one.

The serializer can basically be a copy of https://github.com/google/built_value.dart/blob/master/built_value/lib/src/int_serializer.dart

**Comment by justinfargnoli** [comment]
Thanks for the response! We just figured it out and the link you gave was really helpful :)

For others looking at this issue we found these other two links helpful.
- [This link](https://github.com/google/built_value.dart/blob/master/end_to_end_test/lib/values.dart#L455) is test for built_value which implements a primitive wrapper class with serialization.
- [This link](https://medium.com/flutter-community/creating-custom-built-value-serializers-with-builtvalueserializer-46a52c75d4c5) is a tutorial for implementing a custom serializer.
