### ISSUE TITLE
serialization for BuiltMap<String, Object> fails

### ISSUE THREAD

**Issue by MohiuddinM** [google/built_value.dart#883]
I get the following error:
`Deserializing '[description, 1]' to 'BuiltMap<String, Object>' failed due to: Bad state: No serializer for 'Object'`

Serializers file:
```
const specifiedType = const FullType(BuiltMap, [FullType(String), FullType.object]);

final Serializers serializers = (_$serializers.toBuilder()
      ..addBuilderFactory(specifiedType, () => MapBuilder<String, Object>())
      ..addPlugin(StandardJsonPlugin()))
    .build();
```

**Comment by jans-y** [comment]
AFAIK, you have specify more specific Type than Object (e.g. String, double, int...) or provide custom serializer for the Object type.

**Comment by MohiuddinM** [comment]
It does allow Object type, but I think either its broken or it doesn't work with JSON

https://github.com/google/built_value.dart/blob/6894ba4dd12551dae002caaa33e84b1888d5e2e4/built_value/test/built_map_serializer_test.dart#L178

**Comment by davidmorgan** [comment]
`Object` only works when the JSON encodes the type of each value, as it does in that test.

**Comment by MohiuddinM** [comment]
@davidmorgan I just did some testing and print the output from serializer, it does automatically annotate the types:
`"bool":{"$":"bool","":true},"int":{"$":"int","":12}`. So, probably this is the reason its not compatible with standard json from web apis (what I intend to do). 
Anyway, I ended up using JsonObject instead of BuiltMap (the only downside being it doesn't work with DateTime)
