### ISSUE TITLE
generated serializer is not a subtype of Serializer<...>

### ISSUE THREAD

**Issue by krevedkokun** [google/built_value.dart#885]
I have following model
```dart
abstract class Pagination<T>
    implements Built<Pagination<T>, PaginationBuilder<T>> {
  static Serializer<Pagination> get serializer => _$paginationSerializer;

  factory Pagination([void Function(PaginationBuilder<T>) updates]) =
      _$Pagination<T>;

  Pagination._();

  int get count;
  String get next;
  String get previous;
  BuiltList<T> get result;

  String toJson() {
    return json.encode(serializers.serializeWith(Pagination.serializer, this));
  }

  static Pagination fromJson(String jsonString) {
    return serializers.deserializeWith(
      Pagination.serializer,
      json.decode(jsonString),
    );
  }
}

```
when I try to deserialize json with it I get following error
```
Unhandled Exception: type '_$PaginationSerializer' is not a subtype of type Serializer<Pagination<Product>>'
```
not really sure why this is happening

built_collection 4.3.2
built_value 7.1.0
built_value_generator 7.1.0
any hints is appreciated

**Comment by davidmorgan** [comment]
Do you have any custom analysis options enabled in `analysis_options.yaml`?

**Comment by davidmorgan** [comment]
Could you see if it works when you drop either `implicit-casts: false` or `implicit-dynamic: false`?

**Comment by krevedkokun** [comment]
> Could you see if it works when you drop either `implicit-casts: false` or `implicit-dynamic: false`?

no, problem still persist

**Comment by davidmorgan** [comment]
Could you please give the full stack trace from the exception? Thanks.

**Comment by minikin** [comment]
@krevedkokun Can you post your import, please? I believe that this issue might be related to conflicting imports.

**Comment by zl910627** [comment]
Same problem.
Of course, `addBuilderFactory` for `BuiltList` with `T`(detail type) has been done first time.

**Comment by minikin** [comment]
@zl910627 Can you post a code with imports, pls? I might help.

**Comment by zl910627** [comment]
Same with above.
```dart
..addBuilderFactory(
  const FullType(BuiltList, [FullType(Video)]),
  () => ListBuilder<Video>(),
)
..addBuilderFactory(
  const FullType(PageResp, [FullType(Video)]),
  () => PageRespBuilder<Video>(),
)
```
this is what I have registered in factory.
`Video` class is simple `Built_Value` class, and `PageRepo` is same structure with `Pagination`
Thank you

> I have following model
> 
> ```dart
> abstract class Pagination<T>
>     implements Built<Pagination<T>, PaginationBuilder<T>> {
>   static Serializer<Pagination> get serializer => _$paginationSerializer;
> 
>   factory Pagination([void Function(PaginationBuilder<T>) updates]) =
>       _$Pagination<T>;
> 
>   Pagination._();
> 
>   int get count;
>   String get next;
>   String get previous;
>   BuiltList<T> get result;
> 
>   String toJson() {
>     return json.encode(serializers.serializeWith(Pagination.serializer, this));
>   }
> 
>   static Pagination fromJson(String jsonString) {
>     return serializers.deserializeWith(
>       Pagination.serializer,
>       json.decode(jsonString),
>     );
>   }
> }
> ```
> 
> when I try to deserialize json with it I get following error
> 
> ```
> Unhandled Exception: type '_$PaginationSerializer' is not a subtype of type Serializer<Pagination<Product>>'
> ```
> 
> not really sure why this is happening
> 
> built_collection 4.3.2
> built_value 7.1.0
> built_value_generator 7.1.0
> any hints is appreciated

**Comment by zl910627** [comment]
Hi @minikin , @davidmorgan 👆

**Comment by zl910627** [comment]
hi @davidmorgan 
why don't you publish `beta` for `built_value_generator` (8.0)?
https://github.com/google/built_value.dart/blob/be0feaf544ef576d459e1949bfd51dec1199bd7d/end_to_end_test/lib/generics.dart#L39 ~ https://github.com/google/built_value.dart/blob/71742e9ae5abb12cf10c1601c7d1f92998aff213/end_to_end_test/test/generics_serializer_test.dart#L222
are very same with my concept and this issue.
But it does not work with above mentioned versions.
```
built_collection 4.3.2
built_value 7.1.0
built_value_generator 7.1.0
```

**Comment by davidmorgan** [comment]
Unfortunately `package:build_runner` has a dependency on `built_value`; that makes a circular dependency which makes it hard to publish major version bumps.

It should be possible to use the unpublished version with a dependency override.

**Comment by zl910627** [comment]
ok, thank you

**Comment by zl910627** [comment]
hello @davidmorgan 
how about below case?
```dart
abstract class BoundGenericValue<T extends num>
    implements Built<BoundGenericValue<T>, BoundGenericValueBuilder<T>> {
  static Serializer<BoundGenericValue> get serializer =>
      _$boundGenericValueSerializer;

  T get value;

  factory BoundGenericValue([updates(BoundGenericValueBuilder<T> b)]) =
      _$BoundGenericValue<T>;
  BoundGenericValue._();
}
```

And `T` would be `Pagination` with other generic type.
I just tried, but it does not work.

**Comment by avechuche** [comment]
Hi, did you find a solution for this? I have the same problem. Thanks!

**Comment by davidmorgan** [comment]
I added test coverage around generic serialization here

https://github.com/google/built_value.dart/pull/998/commits/b2dc887b5de235cf97078966ef0216f8d57f5363

but was unable to repro that error. I did hit one thing that needed fixing, not sure if it helps.

If you are still having this problem could you please provide a full example for how to repro the error? Thanks.

**Comment by aliyazdi75** [comment]
Try this: https://github.com/aliyazdi75/gallery/blob/main/services/http_service/lib/src/models/src/pagination.dart

**Comment by davidmorgan** [comment]
I need a full example with both the model class and how to call it so it fails, please :)

**Comment by aliyazdi75** [comment]
> Try this: https://github.com/aliyazdi75/gallery/blob/main/services/http_service/lib/src/models/src/pagination.dart

This one doesn't fail:
```dart
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

import 'serializers.dart';

part 'pagination.g.dart';

abstract class Pagination<T>
    implements Built<Pagination<T>, PaginationBuilder<T>> {
  int? get count;

  String? get next;

  String? get previous;

  BuiltList<T>? get results;

  Pagination._();

  factory Pagination([Function(PaginationBuilder<T>) updates]) =
      _$Pagination<T>;

  static Pagination<T> fromJson<T>(Map<String, dynamic> json) {
    final specifiedType = FullType(Pagination, [FullType(T)]);
    final serializersWithBuilder = (serializers.toBuilder()
          ..addBuilderFactory(specifiedType, () => PaginationBuilder<T>())
          ..addBuilderFactory(
              FullType(BuiltList, [FullType(T)]), () => ListBuilder<T>()))
        .build();
    return serializersWithBuilder.deserialize(json,
        specifiedType: specifiedType) as Pagination<T>;
  }

  static Serializer<Pagination<Object?>> get serializer =>
      _$paginationSerializer;
}
```
and call like this for example:
```dart
Pagination.fromJson<Recommendation>(response);
```

**Comment by davidmorgan** [comment]
Oh, I see what you mean. Thanks :)

**Comment by zizo95** [comment]
I'm still getting this error even by cloning `built_value` repo and run the example test.

# Reproduce:

```dart
void example() {
  final data = {
    'value': [
      {
        'anInt': 818,
      },
    ]
  };

  print(serializers.deserializeWith<GenericValue<BuiltList<SimpleValue>>>(GenericValue.serializer, data));

  // See chat_example and end_to_end_test for more complex usage!
}

```
# Output

`Unhandled exception:
type '_$GenericValueSerializer' is not a subtype of type 'Serializer<GenericValue<BuiltList<SimpleValue>>>'`

# Stacktrace
```
Unhandled exception:
type '_$GenericValueSerializer' is not a subtype of type 'Serializer<GenericValue<BuiltList<SimpleValue>>>'
#0      example
package:example/example.dart:21
#1      main
bin/example.dart:8
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```

**Comment by davidmorgan** [comment]
`deserializeWith` is not intended to be used with an explicit generic type argument; it will infer the right one from the `serializer`.

You will end up with a `GenericValue<Object>` via this route. To get a `GenericValue<BuiltList<SimpleValue>>` you need to 1) use `serializers.deserialize` method, passing in the correct `FullType` object to indicate `<BuiltList<SimplerValue>>`; 2) add a `builderFactory` for this case to `serializers`; and 3) if you need that to be the static type, cast it.

Note that simply having a field of type `GenericValue<BuiltList<SimpleValue>>` does most of this for you as part of the enclosing class generated serializer--but you'll need to register the `BuilderFactory` by hand.
