### ISSUE TITLE
how to set default values for missing built_collection fields when calling deserialize

### ISSUE THREAD

**Issue by dave-doty** [google/built_value.dart#886]
I gathered from comments on #212 that the appropriate way to specify default values for non-nullable fields is using `_finalizeBuilder`.

I assumed that if any non-nullable fields are missing, then they would be `null` in the builder, and checking them for `null` in `_finalizeBuilder` is the appropriate way to assign them a default value. For example:

```dart
var storable_json_map = json.decode(json_str);
AppUIStateStorable storables = standard_serializers.deserialize(storable_json_map);

// ...

abstract class AppUIStateStorable implements Built<AppUIStateStorable, AppUIStateStorableBuilder> {
  // ...
  BuiltSet<EditModeChoice> get edit_modes;
  // ..
  static void _finalizeBuilder(AppUIStateStorableBuilder b) {
    if (b.edit_modes == null) {
      b.edit_modes = DEFAULT_AppUIStateStorableBuilder.edit_modes;
    }
    // ...
  }
}
```

However, it appears that when the edit_modes field is missing from the serialized JSON stored in the variable `json_str` above, when `standard_serializers.deserialize(storable_json_map);` is called, which in turn calls `_finalizeBuilder`, within the method `_finalizeBuilder`, `b.edit_modes` is the empty `BuiltSet`, rather than `null`.

Is this expected behavior? Is this documented somewhere?

Also, is this the recommended way to assign default values to fields that were missing from a serialized instance? I want this because I use JSON serialization to store app settings in localStorage, but I want a smooth way to update. When I add a new field to be stored, then for any user running the app for the first time after that update, that field will not be in localStorage, and I want to autopopulate any missing fields with their default values.

In my particular case, the empty set is not a valid value for `edit_modes`. So, I can simply check whether it is the empty set, and replace with the default set.

But in general, I would not know how to tell the difference between that being the intended stored value, versus being the empty set because the field was missing from the serialized JSON.

**Comment by davidmorgan** [comment]
Nested builders, for collections or for nested value types, are auto initialized when accessed. This is to make it convenient to update deeply nested fields.

In the generated builder implementation there is a field which starts off as `null` and is populated on access, but there is no public way to access this state directly. You could do it by switching to writing out the builder explicitly, then directly accessing the private field. This might break if the generation details change.

Would `_initializeBuilder` do what you want? Then you don't need to conditionally set the default, you can just always set it?

**Comment by dave-doty** [comment]
I'm not sure how `_initializeBuilder` works with `deserialize`. Would `deserialize` first read the serialized JSON, populate the Builder with fields it finds in the serialized JSON, but leave other fields of the Builder (those missing from the serialized JSON) equal to `null`, and then call `_initializeBuilder`? If so I could check for `null` in `_initializeBuilder`.

More generally, I'm wondering if you have a recommended way of populating with default values specifically for this case: deserializing from an old instance that is possibly missing some fields that were not defined at the time it was serialized.

**Comment by davidmorgan** [comment]
`initializeBuilder` is the _first_ thing called on the builder, before the serializer does anything.

The serializer does nothing at all when fields are missing, i.e. it does not modify the builder at all.

So, it will leave whatever default you set in `initializeBuilder`.

**Comment by davidmorgan** [comment]
Covered by https://github.com/google/built_value.dart/issues/1051
