### ISSUE TITLE
Question: Serialization/Deserializaton with Map<String, dynamic>

### ISSUE THREAD

**Issue by JRamos29** [google/built_value.dart#887]
Hi,
i'm trying to use built_value, but i can't figure it out how to make the methods toJson() and fromJson() transforms and receives a Map<String, dynamic> instead of String. I used a snippet to create my classes, and don't know what changes i need to make to achieve the serialization with Map<String, dynamic>.  I need to use with Firestore and the method setData only accepts map. This is my current serializer: 

```
final Serializers serializers =
    (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();
```

And here are the methods:

```
 String toJson() {
    return json.encode(serializers.serializeWith(Comment.serializer, this));
  }

  static Comment fromJson(String jsonString) {
    return serializers.deserializeWith(
        Comment.serializer, json.decode(jsonString));
  }
```

**Comment by PalakSDarji** [comment]
Hey I am facing the same situation. Firebase APIs returns Map with list of key and value. BuiltValue cant parse it. The error returned is : Unhandled Exception: type 'BuiltMapSerializer' is not a subtype of type 'Serializer<BuiltMap<String, BuiltProduct>>'. Any solution you got?

**Comment by JRamos29** [comment]
> Hey I am facing the same situation. Firebase APIs returns Map with list of key and value. BuiltValue cant parse it. The error returned is : Unhandled Exception: type 'BuiltMapSerializer' is not a subtype of type 'Serializer<BuiltMap<String, BuiltProduct>>'. Any solution you got?

I asked at stackoverflow and received this [answer](https://stackoverflow.com/questions/62650956/how-to-serialize-with-mapstring-dynamic-using-the-package-built-value/63092401#63092401). Hope it helps.

**Comment by binajmen** [comment]
Hi @JRamos29,

Did you succeed to implement the solution ?

I tried the following without success:
```dart
  Map<String, dynamic> toFirestore() {
    return serializers.serializeWith(Place.serializer, this);
  }

  static Place fromFirestore(Map<String, dynamic> json) {
    return serializers.deserializeWith(Place.serializer, json);
  }
```

`A value of type 'Object?' can't be returned from the method 'toFirestore' because it has a return type of 'Map<String, dynamic>'.dartreturn_of_invalid_type`

**Comment by JRamos29** [comment]
Hi @binajmen. 

The only possible solution I have is the one linked above.
And I stopped working on the project far ago, so I can't tell how was solved it either. Sorry.
