### ISSUE TITLE
Failure deserializing [{a_b.c: 1}] to BuiltList<Map>

### ISSUE THREAD

**Issue by flipch** [google/built_value.dart#894]
The error is 

`Deserializing '[{sales.total_units: 1}]' to 'BuiltList<Map>' failed due to: Invalid argument(s): Unknown type on deserialization. Need either specifiedType or discriminator field.`

I'll say that this project was generated by [openapi-generator](https://github.com/OpenAPITools/openapi-generator) and I have opened a bug [here](https://github.com/OpenAPITools/openapi-generator/issues/6951).

I believe that perhaps their [templating file ](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart-dio/serializers.mustache)for serializers is wrong. 

**However I am trying to fix it ** and seem unable to, even after I've manually added the missing builderFactory.

I have added the, previously missing, BuilderFactory

```dart
Serializers serializers = (_$serializers.toBuilder()
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Map)]),
          () => new ListBuilder<Map<String, String>>())
      ..add(Iso8601DateTimeSerializer()))
    .build();
```

It seems it's trying to retrieve the type descriminator from the actual json object as a last resort instead of doing a Map<string, string> deserialization.
![image](https://user-images.githubusercontent.com/10780503/87828657-42089480-c832-11ea-9b70-fe7af95fc849.png)

Looking at the call stack, starting on the first deserialize being called (bottom to top)
![image](https://user-images.githubusercontent.com/10780503/87828719-63698080-c832-11ea-83cb-14093e23a4ee.png)

I can see the library first deserializing the List and then for each item, deserialize with the specifiedType of Map
![image](https://user-images.githubusercontent.com/10780503/87828914-d8d55100-c832-11ea-8b4b-787d05ffdb24.png)

Can I get some help understanding why is it going to the fallback method and not just deserializing the Map<String,String> ?

**Comment by davidmorgan** [comment]
Adding the `builderFactory` is part of the problem--but the other part is that if you know you want a `BuiltMap<String, String>`, you need to say so when you deserialize.

i.e. pass the same `fullType` to the `deserialize` method :)

**Comment by flipch** [comment]
The code that is calling the deserialize method at the top of this. The JSON object is a list of dictionaries of string,string

```dart
 final FullType type = const FullType(BuiltList, const [const FullType(Map)]);
 BuiltList<Map> dataList = _serializers.deserialize(response.data is String ? jsonDecode(response.data) : response.data, specifiedType: type);
 var data = dataList.toList();
```

So if I were to, in addition to adding the builder Factory, also specify the type on the deserialize method like so
```dart
final FullType type = const FullType(BuiltList, const [
  const FullType(
      Map, const [const FullType(String), const FullType(String)])
]);
BuiltList<Map> dataList = _serializers.deserialize(
    response.data is String ? jsonDecode(response.data) : response.data,
    specifiedType: type);
var data = dataList.toList();
```
I would expect it to start working except I still get the same error

**Comment by davidmorgan** [comment]
I think I see the issue :) ... it should be `BuiltMap`, not `Map`.
