### ISSUE TITLE
Add serialization interceptor(transform)

### ISSUE THREAD

**Issue by dagba** [google/built_value.dart#898]
Ability to create custom mapper(serializer) for specific field, for example: DateTime -> int (timestamp), DateTime <- int (timestamp)
As example right down below is the way of mapping timestamp to Date in ObjectMapper(Swift) library:
```
    class TimestampDateTransform: TransformType {
        public typealias Object = Date
        public typealias JSON = Int
        
        public init() {}
        
        public func transformFromJSON(_ value: Any?) -> Object? {
            if let interval = value as? Int {
                return Date(timeIntervalSince1970: Double(interval))
            }
            return nil
        }
        
        public func transformToJSON(_ value: Object?) -> JSON? {
            if let date = value {
                return Int(date.timeIntervalSince1970)
            }
            return nil
        }
    }
```

**Comment by davidmorgan** [comment]
I'm not sure I understand the request; you can already add custom serializers for your own types, or to override the built in serializers for types, e.g.

https://medium.com/flutter-community/creating-custom-built-value-serializers-with-builtvalueserializer-46a52c75d4c5

**Comment by dagba** [comment]
@davidmorgan sorry for incomplete description of the proposal, updated the issue

**Comment by dave26199** [comment]
Ah, I understood now, thanks.

Currently the only way to do this is to provide a custom serializer for the parent type, so you can handle each field as you like.

A way to specify a serializer per field would be nice. It's likely a big change, though, so I'm afraid it's unlikely to happen soon.

**Comment by dagba** [comment]
Got it, thanks.

**Comment by davidmorgan** [comment]
Same issue as https://github.com/google/built_value.dart/issues/1046
