### ISSUE TITLE
Empty dynamic literal maps break JsonObject

### ISSUE THREAD

**Issue by micimize** [google/built_value.dart#902]
An untyped empty literal map `{}` has a `Map<dynamic, dynamic>` `runtimeType`, resulting in a deserialization error:
https://github.com/google/built_value.dart/blob/b1023fe0713f6af8f2316c74edc14fd23ee16aae/built_value/lib/json_object.dart#L67-L72

I'm not sure if `built_value` should check for this itself, but one way would be:
```dart
 } else if (value is Map && value.isEmpty) { 
   return MapJsonObject(<String, Object>{}); 
 } else { 
```
I haven't been able to figure out where my empty json object is getting its type from, which is the main reason I think it'd be worth handling in `built_value` (avoiding unexpected and tedious troubleshooting). I can see the argument either way though, just thought it's worth considering.

<details>
<summary> dartpad example code for `{}` typing</summary>

```dart
void main() {
  print(
    [
      {},
      {'a': [], 'b': 'b'}
    ].map(
      (o) => [o, o.runtimeType, o is Map<String, Object>],
    ),
  );
}
// => ([{}, JsLinkedHashMap<dynamic, dynamic>, false], [{a: [], b: b}, JsLinkedHashMap<String, Object>, true])
```

</details>

```dart

For now I'm working around this with a custom json plugin that casts `JsonObject` bound `Map`s:
```dart
  @override
  Object beforeDeserialize(Object object, FullType specifiedType) {
    if (object is Map) {
      if (specifiedType.root != JsonObject) {
        if (specifiedType.isUnspecified) {
          return _toListUsingDiscriminator(object);
        } else {
          return _toList(object, _needsEncodedKeys(specifiedType));
        }
      }
      return object.cast<String, Object>();
    } else {
      return object;
    }
  }
```

**Comment by davidmorgan** [comment]
Thanks.

I think the workaround you're using is reasonable--if this turns out to be a common problem we could add something to `built_value`.

**Comment by davidmorgan** [comment]
I think it should be `Map<String, Object?>`. Will address as part of https://github.com/google/built_value.dart/issues/1052
