### ISSUE TITLE
Unhandled Exception: Bad state: No element, when deserialized Json is an empty list

### ISSUE THREAD

**Issue by smac89** [google/built_value.dart#904]
This is related to https://github.com/google/built_value.dart/issues/881, but I'm not sure why it was closed.

Calling `List.first` in dart, on an empty list always results in the above exception, which makes this issue a bug

The offending line of code is:
https://github.com/google/built_value.dart/blob/b1023fe0713f6af8f2316c74edc14fd23ee16aae/built_value/lib/src/built_json_serializers.dart#L141

Also:
https://github.com/google/built_value.dart/blob/b1023fe0713f6af8f2316c74edc14fd23ee16aae/built_value/lib/src/built_json_serializers.dart#L114

There might be others, but I'm just looking in the one file where this exception occurred

**Comment by davidmorgan** [comment]
We only hit this point in the code if we can't find a serializer, which means either the serializer type must be written in the JSON--so there is an element--or the JSON is wrong.

But, we could provide a better error message, it should say e.g. `No serializer for '${specifiedType.root}' and no type specified in JSON`.

**Comment by davidmorgan** [comment]
https://github.com/google/built_value.dart/issues/1042
