### ISSUE TITLE
Enum wireNumber don't work together with fallback 

### ISSUE THREAD

**Issue by AlexBacich** [google/built_value.dart#907]
Here's example of enum constants. If response is 0 or -1 - works perfectly. However if something unexpected is coming (like 42) - error is dropped during serialization. Fallback is supposed to catch. 

```
@BuiltValueEnumConst(wireNumber: 0)
  static const ResponseCode ok = _$ok;

  @BuiltValueEnumConst(wireNumber: -1, fallback: true)
  static const ResponseCode failure = _$failure;
```

And error itself: 
Caught error: Deserializing '[returnCode, 8, returnCodeDescr, The entitlement key provided does not match ...' to 'ActivationResponse' failed due to: Deserializing '8' to 'ResponseCode' failed due to: type 'int' is not a subtype of type 'String' in type cast

**Comment by davidmorgan** [comment]
That's a bug--thanks.

Will be while before I can land a fix as the package is currently migrated to null safety, sorry about that.

**Comment by AlexBacich** [comment]
Not big deal, will simply not use for that case for now
P.s. great package - use it a lot in day to day work.
