### ISSUE TITLE
Help reduce boilerplate (best practices or further optional source_gen)

### ISSUE THREAD

**Issue by filiph** [google/built_value.dart#91]
I find myself writing a lot of boilerplate code with custom built_values and I always wonder if it's possible to cut most of it. Looking at a typical class:

    abstract class FightSituation extends Situation
        implements Built<FightSituation, FightSituationBuilder> {
      factory FightSituation.initialized(
              Iterable<int> playerTeamIds, Iterable<int> enemyTeamIds) =>
          new FightSituation((b) => b
            ..playerTeamIds = new BuiltList<int>(playerTeamIds)
            ..enemyTeamIds = new BuiltList<int>(enemyTeamIds));
      factory FightSituation([updates(FightSituationBuilder b)]) = _$FightSituation;
      FightSituation._();

      // ... actual logic of the class
    }

And here's the builder:

    abstract class FightSituationBuilder extends SituationBuilder
        implements Builder<FightSituation, FightSituationBuilder> {
      @virtual
      int id = getRandomId();
      @virtual
      int time = 0;
      @virtual
      BuiltList<int> playerTeamIds;
      @virtual
      BuiltList<int> enemyTeamIds;
      @virtual
      MapBuilder<int, TimedEventCallback> events =
          new MapBuilder<int, TimedEventCallback>();
    
      factory FightSituationBuilder() = _$FightSituationBuilder;
      FightSituationBuilder._();
    }

Looking at these two:

* Do you feel like some of this could be done better on my (the user's) part? Is some of it a downright anti-pattern? If so, how do we help people not to fall in that hole?
* Could any of this be automated away by further source generation? Something like what AngularDart does with annotations? Or maybe half-way between current built_value and there?

**Comment by davidmorgan** [comment]
Hi Filip,

Good questions.

The main thing you can do to reduce the boilerplate is to stop writing the builder yourself. If you do that, a default/empty one is generated for you. I notice you're initializing some values to defaults -- but you could do that in your "initialized" constructor instead. Would that work?

The other thing I notice in your code is that your builder holds a "BuiltList<int>". You could instead have it be "ListBuilder<int>"; this is what it will default to if you don't define your own builder. This will save you a bit of typing:

`
factory FightSituation.initialized(
          Iterable<int> playerTeamIds, Iterable<int> enemyTeamIds) =>
      new FightSituation((b) => b
        ..playerTeamIds.replace(playerTeamIds)
        ..enemyTeamIds.replace(enemyTeamIds));
`

The idea of built_value is absolutely to minimize the amount of boilerplate you end up writing, so we can dig into this until we hit something that looks optimal :)

**Comment by filiph** [comment]
Thanks, this is extremely helpful!

In the end, it's easier for me to `implement` situation instead of extending it. It doesn't let me share some code but at least it works.

A feature request would be to have a section in the readme (or an example in `examples/`) with a concrete tutorial on how to solve inheritance. I think that even if most of this tutorial would be copy-pasted from your reply above, it would be helpful. 

Unless I'm mistaken, the idea of having many classes that inherit from A, which itself is a BuiltValue, will be quite a common use case.

Btw, I'm not sure if that's unsupported or a bug, but if I have:

    abstract class Situation<V extends Built<V, B>, B extends Builder<V, B>>
        implements Built<V, B> {
      // ... common interace ...
    }

and then I want a built value like this:

    abstract class FightSituation
        implements Situation<FightSituation, FightSituationBuilder> {
      // ... concrete implementation ...
    }

then the source generation fails with this:

    // **************************************************************************
    // Generator: BuiltValueGenerator
    // Target: abstract class FightSituation
    // **************************************************************************
    
    // Error: Invalid argument(s) (builtParameters): Must not be null

I have to explicitly implement BuiltValue for this to work:

    abstract class FightSituation
        implements
            Situation<FightSituation, FightSituationBuilder>,
            Built<FightSituation, FightSituationBuilder> {
      // ...
    }

Should I file this as a bug?

I'm closing this one because my issue has been solved 👍

**Comment by filiph** [comment]
I spoke too soon. In the end I dropped the requirement that the `Situation` class must implement BuiltValue, and I go by convention. It was just too much hassle.

**Comment by dave26199** [comment]
FYI with the latest version relaxing what you can do with the factory, you can now set defaults in the default factory, e.g.

```
  factory Dialog([updates(DialogBuilder b)]) =>
      new _$Dialog((b) => b
        ..inProgress = false
        ..update(updates));
```

**Comment by filiph** [comment]
Is the "relaxing what you can do with the factory" documented? I _think_ I can grasp the constraints from your example but it would be better to be sure.

I still use the three constructor everywhere (`factory FightSituation.initialized(...)`, `factory FightSituation([...]) = _$FightSituation` and `FightSituation._();`) and that sucks.

**Comment by davidmorgan** [comment]
The constraint is that you have to mention the generated type. i.e. anything with _$FightSituation in it is allowed.

This is pretty arbitrary -- if that's too tight we can loosen it further.
