### ISSUE TITLE
Cannot import 'package:flutter/widgets.dart' in Built Value class

### ISSUE THREAD

**Issue by mh-achesarone** [google/built_value.dart#910]
This may just be a misunderstanding of the use of the library on my part, so apologies if that is the case.

We are using built_value in our project, with one use case being creating View Models. We would like to be able to use BuildContext in our View Models in some instances (as a parameter to functions, not directly as a field), and thus we must import 'package:flutter/widgets.dart'. However, when we do this, we get the following error:

`error: 'LoginScreenViewModelBuilder' doesn't extend 'Builder<LoginScreenViewModel, LoginScreenViewModelBuilder>'. (type_argument_not_matching_bounds at ../login_screen_view_model.dart:10)`

Is this an error on our end, that we shouldn't use flutter imports in any value classes, or is there something else going on?

Thank you very much.

**Comment by davidmorgan** [comment]
I think this is because `widgets.dart` has a class called `Builder` :) you will need to hide it or import with a prefix.

```
import 'package:flutter/widgets.dart' hide Builder;
```

or

```
import 'package:flutter/widgets.dart` as widgets;
```

**Comment by mh-achesarone** [comment]
Yes! That solved it. Thank you very much for the advice and great library.
