### ISSUE TITLE
Swagger / OpenAPI support

### ISSUE THREAD

**Issue by wstrange** [google/built_value.dart#92]
It would be nice if swagger codegen could generate built_value models and client stubs

**Comment by davidmorgan** [comment]
Sounds reasonable. Would you mind expanding a bit on what'd be needed exactly please -- I guess the JSON serialization needs to be compatible with OpenAPI?

**Comment by wstrange** [comment]
This is more of a nice to have (low priority), but yea, OpenAPI support is what I was thinking.

Today they have a generator that uses dartson for serialization - which I gather is quite slow.  I was thinking the generator might be able to generate built_value code instead.

This RFE might not belong here..(could be part of the openapi project?) but I thought it would be good to capture the concept somewhere.

**Comment by davidmorgan** [comment]
Sounds good to me. I'll take a look at some point.

**Comment by davidmorgan** [comment]
In #296 I add support for a discriminator field to `StandardJsonPlugin`.

I realize this isn't full Swagger compatibility, but it should be enough that someone interested can take it further. I doubt I'll get to adding more support. If anyone is interested in helping out, please open another issue :)
