### ISSUE TITLE
Add meta-comment to generated files to exclude from coverage

### ISSUE THREAD

**Issue by shouichi** [google/built_value.dart#921]
By adding `// coverage:ignore-file` to generated files, the coverage tool ignores the whole file. See https://github.com/dart-lang/coverage/pull/302.

**Comment by davidmorgan** [comment]
Thanks.

I'm not sure it makes sense for a generator to decide whether coverage is computed on the output ... wouldn't it make more sense for the coverage tool to skip all generated files if that's what is wanted?

**Comment by shouichi** [comment]
Yeah, that makes more sense. I'll file an issue to the coverage tool repo. Thanks!

I'm OK to close this. Should I close?

**Comment by davidmorgan** [comment]
Sounds good, thanks.
