### ISSUE TITLE
[question] Copying object 

### ISSUE THREAD

**Issue by AlexBacich** [google/built_value.dart#922]
Probably not related to built_value itself, but what if.. 

I have one parent class. Let's say Figure, with field 'id'.
In addition two child classes: 
- Circle (with field radius)
- Square (with field side)

What I'm curious about is how to create Square object from Circle object. During creation the parent "id" field should be left, the rest cleared. 

The only thing coming into my mind is to write factory constructor like Square.fromCircle(Circle circle). And use builder to copy ID + fill other fields. But maybe there is easier way to copy parent class fields? 

p.s. thanks for awesome library, can't stop using it :)

**Comment by davidmorgan** [comment]
If you have a shared interface for the shared fields, e.g. `implements HasId`, then you can create constructors that take a `HasId` and extract the ID from it, and will work for Circle, Square, and anything else in an ID :)

**Comment by AlexBacich** [comment]
Right, thanks! Better than my thoughts :) In my real example I have ID and other base class fields done as mixin. And child classes are created with mixin. 
So solution would be create (instantiable: false) base class with mixin and let other classes extend it. As this link suggests: https://github.com/google/built_value.dart/blob/master/example/lib/polymorphism.dart

**Comment by AlexBacich** [comment]
I have thought about another way. Not the most elegant though.  Since all objects have serialize methods - it's also possible to serialize one class object, deserialize to another and fill with other fields.

**Comment by AlexBacich** [comment]
I have one other comment about polymorphism.dart
From that example - it's not possible to rebuild base class. 

```
test('Polymorphism', (){
      final Animal cat = Cat((b) => b..legs = 4..tail = true);
      expect(cat.legs, 4);
      cat.rebuild((b) => b..legs = 3);
      expect(cat.legs, 3);    // This will fail, cat will still have 4 legs. Maybe it's caring about cats having all 4 legs too much :-/
    });
```

**Comment by davidmorgan** [comment]
`cat` is immutable, you need to do `cat = cat.rebuild(...)` :)

**Comment by AlexBacich** [comment]
such a silly mistake. Thanks!
