### ISSUE TITLE
Add method: static ContentType valueOf(String name) => _$valueOf(name)

### ISSUE THREAD

**Issue by grappetite-ali** [google/built_value.dart#924]
Its giving me below error even i have added `valueOf` function inside my EnumClass.
_`Add method: static ContentType valueOf(String name) => _$valueOf(name)`_

This is how my code looks.

```
class ContentType extends EnumClass {
  static Serializer<ContentType> get serializer => _$contentTypeSerializer;

  static BuiltSet<ContentType> get values => _$values;

  static ContentType valueOf(String name) {
    try {
      return _$valueOf(name);
    } catch (e) {
      return _$unknown;
    }
  }

  static const ContentType paragraph = _$paragraph;
  static const ContentType header = _$header;
  static const ContentType unknown = _$unknown;

  const ContentType._(String name) : super(name);
}
```

I have used try catch in valueOf block because i want to return `_$unknown` as a default value if `_$valueOf(name)` throws Argument Exception.

**Comment by dave26199** [comment]
The generator doesn't let you provide a different implementation. If you want something different, it will have to be an additional method, e.g. valueOfOrDefault.

**Comment by grappetite-ali** [comment]
@dave26199 ! I could have used valueOfOrDefault but the issue is that `valueOf` is being called by serializer. How could i make it not to throw `ArgumentError` ?

**Comment by dave26199** [comment]
Ah, that's directly supported via

https://pub.dev/documentation/built_value/latest/built_value/BuiltValueEnumConst-class.html

Annotate the field you want to be the default, and write "fallback: true" :)

**Comment by grappetite-ali** [comment]
Thanks @dave26199 . fallback: true solved my issue. I am closing this ticket.
