### ISSUE TITLE
Generic Type in built value Model Class

### ISSUE THREAD

**Issue by irangareddy** [google/built_value.dart#925]
I am working a JSON, where one value return two different types of datatype `bool` and `String` based on data availability

**If CoverImage doesn't exist**
```JSON
{
"cover_image": false,
}
```

**If CoverImage exist**
```JSON
{
"cover_image": "https://images.pexels.com/photos/1998435/pexels-photo-1998435.jpeg"
}
```

**Current Model Class Declaration**
```dart
@BuiltValueField(wireName: 'cover_image')
  String get coverImage;
```

**Usage in View**
```dart
NetworkImage((user.coverUrl as bool != false) ? '${user.coverImage}' : KCoverImage)
```

**Issue**
```text
failed due to: Deserializing 'false' to 'String' 
failed due to: type 'bool' is not a subtype of type 'String' in typecast
```

I want to implement a `dynamic` data type in the model class thus, I able to downcast accordingly.
I found similar issues in `stackoverflow.com` with no answers. Kindly make it clear

Detail Explanation is Appreciated

**Comment by davidmorgan** [comment]
One option is to make the field a `JsonObject`

https://github.com/google/built_value.dart/blob/master/built_value/lib/json_object.dart

which is allowed to be any JSON type, which includes strings or booleans.

The other option would be to create your own class, e.g. `StringOrBool`, write a custom serializer and handle both `bool` and `String` in the serializer.

**Comment by irangareddy** [comment]
**`JsonObject` Worked**
```dart
@BuiltValueField(wireName: 'cover_image')
  JsonObject get coverImage;
```
**Usage in View**
```dart
NetworkImage((user.coverImage.isBool) ? KCoverImage : '${user.coverImage}'),
```

As of now, it worked great 🥳

I really appreciate the effort you put into solving issues and you inspire @davidmorgan

Thank you ❤️
