### ISSUE TITLE
Making a custom Builder

### ISSUE THREAD

**Issue by feinstein** [google/built_value.dart#927]
I think this library will benefit a lot from an expanded FAQ section, probably in a Wiki style, just like [auto value has](https://github.com/google/auto/blob/master/value/userguide/howto.md).

That being said, **I would like to change a property before the `build()` is done, like doing `myString.trim()`**. I found on the examples how to make my own builder, but the examples is [too simple](https://github.com/google/built_value.dart/blob/20fc5c92ceb8b31eb6bf46d6071a4c6e88af9c84/example/lib/values.dart#L136). I can't find how to override the `build()` method, so I can do any transformations there and then call the generated `build()` function.

I miss more docs on this, like, If I just override the one property that I want, the generator complains and ask me to include all of the other properties. Couldn't this be done automatically for me? I mean, if I use `extends`, couldn't the generator make a base class with all of the missing properties?

Are  there any considerations if I want to override any of he original builder functions?

Do I have to specify `@nullable` and `@BuiltValueField` on the builder, just like I did on the value object?

Again, I think we should have a `How do I` section just like auto value has, with all the corner cases that the library covers and their limitations and alternatives.

**Comment by feinstein** [comment]
I got it to work by making a builder and making my own getter and setter, changing the value on the setter.

I don't know if this is the proper way of doing it, but even if it is I will leave this open as I think its more about the missing docs than to make it work.

**Comment by davidmorgan** [comment]
There's no way to override the `build` method.

Custom builders were never very widely used--the feature is only just about useful enough for added hassle in using it. Extension methods were added to the language and that cuts out more cases where custom builders could be useful.

There's a newer way to do what you want: the `_initializeBuilder` and `_finalizeBuilder` methods. These are static methods that will be called with the builder, then first when it's created, the second when `build` is called.

```
static void _initializeBuilder(FooBuilder b)
static void _finalizeBuilder(FooBuilder b)
```

I agree, this needs docs :) will aim to do that when I next make a batch of improvements to built_value. Thanks for filing.

**Comment by feinstein** [comment]
Could you just answer for now, while the docs aren't ready, if I have to specify `@nullable` and `@BuiltValueField` on the builder, just like I did on the value object?

**Comment by feinstein** [comment]
FYI: `_initializeBuilder` and `_finalizeBuilder` go on the `Built` class, not on the `Builder`

**Comment by davidmorgan** [comment]
IIRC you don't need `@nullable` or `@BuiltValueField` on the builder.

Sorry, I should have said the initializers go on the `Built` class. Exactly: as well as doing what you want, they remove the need for the custom builder. I'm half hoping I can remove custom builders altogether, they add a lot of complexity to the generation for something that isn't used a lot. That would be a breaking change though so more likely they'll just be deprecated.

**Comment by davidmorgan** [comment]
Closing in favour of https://github.com/google/built_value.dart/issues/1051
