### ISSUE TITLE
Serializers for non-built_value

### ISSUE THREAD

**Issue by callingmybluff** [google/built_value.dart#930]
I have the class `GrandParent` which has a `Map<String, Parent>`. `Parent` is an abstract class with the two implementations: `Child1` and `Child2`. I wanted to make them all immutable, but I only managed to make `GrandParent` and children immutables. It's a nightmare to implement an interface in addition to `Built` class, so I left `Parent` as a normal class.

My problem started with serializers, where I needed to decode a JSON object into an object tree that is a mix of `Built` objects and other objects:

So `GrandParent` has a custom serializer (I'm not sure I needed one, but wanted to be sure of the workflow) 
```dart
...
grandParent.items.replace(serializers.deserialize(value,
              specifiedType: const FullType(BuiltMap, const [
                const FullType(String),
                const FullType(Parent)
              ])) as BuiltMap<String, Parent>);
...
```
Now I am aware that I can call either `Child1` or `Child2` from here, but that won't be good, as it is the job of `Parent` and not `GrandParent`.
I made a serializer for `Parent`, and the definition looks like the following
```dart
abstract class Parent {
  ...
  @BuiltValueSerializer(custom: true)
  static Serializer<Parent> get serializer => ParentSerializer();
}
```
The custom serialzer follows the same standard style:
```dart
class ParentSerializer implements StructuredSerializer<ParentModel> {
@override
Parent deserialize(Serializers serializers, Iterable serialized,
    {FullType specifiedType = FullType.unspecified}) {
  ...

@override
Iterable<Type> get types => [Parent];

@override
String get wireName => 'parent';
```

Both `Child1` and `Child` have the auto-generated serializer.  
Now for my `serlizaers.dart`
```dart

@SerializersFor([
  GrandParent,
  Parent,
  Child1,
  Child2,
])
final Serializers serializers =
    (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();

T deserialize<T>(dynamic value) =>
    serializers.deserializeWith<T>(serializers.serializerForType(T), value);
```
Which looks fine and all, but I was facing a problem where it does not know how to deserialize `Parent`:

> Unknown type on deserialization need either specifiedtype or discriminator field

I found that the problem is in the auto-generated file of the serializer: While it does not complain that I am using a non `Built` class, it simply does not add it to the serlizers:
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of serializers;

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(GrandParent.serializer)
      ..add(Child1.serializer)
      ..add(Child2.serializer)
      ...
      ..addBuilderFactory(
          const FullType(BuiltMap,
              const [const FullType(String), const FullType(Parent)]), /* It is here, but not on top. Look at the fix below */
          () => new MapBuilder<String, Parent>())
```
The fix was simple, but it is not maintainable as I need to re do it every time those files are regenerated again.
```diff
Serializers _$serializers = (new Serializers().toBuilder()
      ..add(GrandParent.serializer)
+     ..add(Parent.serializer)
      ..add(Child1.serializer)
      ..add(Child2.serializer)
```

The problem can be fixed in one of two ways:
- A solution for the serializers so we can mix `Built` classes and other classes.
- A solution for implementing another class next to `Built` (although I think this is a language limitation)

**Comment by davidmorgan** [comment]
Sorry for the slow response.

I think the answer that you're looking for is that `serializers` has a `toBuilder` method: you can take the generated `serializers` instance and add what you like to it. Then you won't have to edit generated code :)

**Comment by callingmybluff** [comment]
Nice, thanks! It is permanent like this, but as I understand now: it is behaving as intended, right? I assumed including the class in `@SerializerFor` should be enough.

For those coming later, the change that fixed it:

```diff
final Serializers serializers = (_$serializers.toBuilder()
+     ..add(FilterItemModel.serializer)
      ..addPlugin(StandardJsonPlugin()))
    .build();
```

**Comment by davidmorgan** [comment]
Glad that helps--I agree, it would also make sense for `SerializersFor` to either be more generous in what it picks up, or to tell you that it ignored something you added. I'll change this into a feature request for improvements there. Thanks.
