### ISSUE TITLE
_initializeBuilder should have option to initialize parent builder

### ISSUE THREAD

**Issue by vauvenal5** [google/built_value.dart#932]
In a polymorphism scenario, is it possible to somehow call the `_initializeBuilder` method of the parent class? In a deep hierarchy I want to avoid having to adapt all `_initializeBuilder` methods because my root class got a new field.

Basically I think the parent builder `_initializeBuilder` method should also be called.

**Comment by davidmorgan** [comment]
That sounds reasonable--although it would be a breaking change.

I'll take a look next time I get around to doing a batch of `built_value` improvements.

**Comment by vauvenal5** [comment]
For anyone interested there is also a workaround which is not ideal but better then the alternative:
Implement a custom protected `initBuilder` function which holds the init code and call it from the child classes. Only disadvantage is that every child needs to provide a `initBuilder` function which calls the parents function for this to work.

```dart
// root class
@protected
static T initBuilder<T extends RootBuilder>(RootBuilder b) =>
      b..enabled = true;

//child class between root and node
@protected
static T initBuilder<T extends ChildBuilder>(ChildBuilder b) => Root.initBuilder(b);

//node class
static void _initializeBuilder(NodeBuilder b) => Child.initBuilder<NodeBuilder>(b)
      ..value = true;
```

This will get a little prettier once `_initializeBuilder` is not a magic function anymore but an annotation. This way your `_initializeBuilder` could be a protected function removing the need for the duplicated `initBuilder`.

**Comment by davidmorgan** [comment]
Part of https://github.com/google/built_value.dart/issues/1051
