### ISSUE TITLE
Question: Is it possible to convert 0/1 to false/true with the fromJson method?

### ISSUE THREAD

**Issue by mrverdant13** [google/built_value.dart#934]
Hi!

I wonder if it is possible to convert an `int` field from a JSON response that can only take values of 1 or 0, to a model which uses this field as a `bool` member.

**Comment by davidmorgan** [comment]
You'll have to write either a customer serializer for your class or a custom serializer plugin to convert an int onto a bool field.

You could instead use an `EnumClass` with two enum values, for true and false, and mark one `@BuiltValueEnumConst(wireNumber: 0)` and the other `@BuiltValueEnumConst(wireNumber: 1)`.

**Comment by mrverdant13** [comment]
Thank you!!
I'll go for the `EnumClass` approach!
