### ISSUE TITLE
Support carrying data with enum class

### ISSUE THREAD

**Issue by deadsoul44** [google/built_value.dart#938]
Thank you for the great package.

Carrying data with enum class could be a very valuable feature. 

For example, I have a list of checkboxes and want to store user preferences in Firebase. Each checkbox may refer to an enum field and carry boolean data depending on user choice. This can be easily stored in Firebase. Currently, I had to create one BuiltValue class to carry boolean data and one EnumClass to hold checkbox labels and other constant data related to labels. If I change something in one class, I have to make corresponding changes in the other class which is not very safe and there is no IDE support.

**Comment by davidmorgan** [comment]
I'm not sure I follow; what kind of change would need a change to both the EnumClass and the BuildValue class? Thanks.

**Comment by deadsoul44** [comment]
Only change needed in EnumClass to carry data. For example, there will be boolean fields in enum class which can be set/rebuilt.

**Comment by davidmorgan** [comment]
I meant, when you said 'I have to make corresponding changes in the other class', what kind of changes did you mean?

It should be possible to do what you need without having enums with data :)

**Comment by deadsoul44** [comment]
```
class SubscriptionsEnum extends EnumClass {
  static Serializer<SubscriptionsEnum> get serializer => _$subscriptionsEnumSerializer;

  static const SubscriptionsEnum allProducts = _$allProducts;
  static const SubscriptionsEnum emptyProducts = _$emptyProducts;
  static const SubscriptionsEnum halfProducts = _$halfProducts;

  const SubscriptionsEnum._(String name) : super(name);

  static BuiltSet<SubscriptionsEnum> get values => _$values;

  static SubscriptionsEnum valueOf(String name) => _$valueOf(name);

  String get label => _labels[this] ?? (throw StateError('No label for SubscriptionsEnum.$name'));

  String get wireName =>
      _wireNames[this] ?? (throw StateError('No wireName for SubscriptionsEnum.$name'));

  static const _labels = {
    'allProducts': "All Products",
    'emptyProducts': "Empty Products",
    'halfProducts': "Half Products ",
  };

  static const _wireNames = {
    'allProducts': "all_products",
    'emptyProducts': "empty_products",
    'halfProducts': "half_products",
  };
}

abstract class Subscriptions implements Built<Subscriptions, SubscriptionsBuilder> {
  Subscriptions._();

  factory Subscriptions([Function(SubscriptionsBuilder b) updates]) = _$Subscriptions;

  @nullable
  @BuiltValueField(wireName: 'all_products')
  bool get allProducts;

  @nullable
  @BuiltValueField(wireName: 'empty_products')
  bool get emptyProducts;

  @nullable
  @BuiltValueField(wireName: 'half_products')
  bool get halfProducts;

  String toJson() {
    return json.encode(serializers.serializeWith(Subscriptions.serializer, this));
  }

  static Subscriptions fromJson(String jsonString) {
    return serializers.deserializeWith(Subscriptions.serializer, json.decode(jsonString));
  }

  static Serializer<Subscriptions> get serializer => _$subscriptionsSerializer;
}


Names are made up to give an example. There are a lot of duplicate fields and we could achieve this with a single EnumClass instead of both EnumClass and BuiltValue class.

**Comment by davidmorgan** [comment]
It looks like `Subscriptions` should have a field of type `BuiltList<SubscriptionsEnum>` or `BuiltSet<SubscriptionsEnum>`.

If it's possible to store it in firebase as a list instead of as boolean fields then that should work well.

**Comment by deadsoul44** [comment]
I will try it and close this issue if it works. Thank you again.
