### ISSUE TITLE
Ignore unmapped properties

### ISSUE THREAD

**Issue by felixwortmann** [google/built_value.dart#939]
It should be possible to deserialize json which has too much properties if all necessary properties exist.

For example if you have a class with the attribute:
```dart
int get foo;
```
(and without an attribute called `bar`)<br><br>
and you deserialize the json:
```json
{
    "foo":1,
    "bar":2
}
```

You should get an object of that class with just the attribute `foo = 1`

**Comment by davidmorgan** [comment]
As far as I know that's how it works :) did you hit a problem?

**Comment by felixwortmann** [comment]
Thanks for the fast response, I did have a problem, it was my mistake though.
