### ISSUE TITLE
Feature Request: default values

### ISSUE THREAD

**Issue by mars3142** [google/built_value.dart#944]
I would like to use the serializer/deserializer for built value classes, but if the input data doesn't contain all values, it would be helpful to initialize the values with a value, instead of null - so every property needs to be marked as **@nullable** which is bad behavior.. 

What's the best way to do it, if it's already possible? If it's not possible a new attribute for **@BuiltValueField** like **default** would be fine.

**Comment by davidmorgan** [comment]
You can use `_initializeBuilder` as shown here: https://github.com/google/built_value.dart/issues/212#issuecomment-632702910

It's not in the docs yet, sorry.

**Comment by mars3142** [comment]
Did you read my request complete? I want to use: 

    final object = serializers.deserializeWith(MyClass.serializer, json);

So it's not possible to use it that way. Right?

**Comment by davidmorgan** [comment]
Yes, it will work, the deserializer uses builders so setting a default on the builder affects it.

**Comment by mars3142** [comment]
@daohoangson So this code eg will do the trick?

    factory Account([updates(AccountBuilder b)]) =>
      new _$Account((b) => b..name = 'default'..update(updates));

**Comment by davidmorgan** [comment]
Not the factory--the `initializeBuilder` part

```
 static void _initializeBuilder(MessageBuilder builder) => builder
    ..id = ''
    ..userId = ''
    ..content = ''
    ..urlMedia = ''
    ..createdAt = DateTime(1970, 1, 1)
    ..type = MessageType.none
    ..localId = '';
```

**Comment by davidmorgan** [comment]
Should be documented as part of https://github.com/google/built_value.dart/issues/1051
