### ISSUE TITLE
Generate onGet similar to onSet

### ISSUE THREAD

**Issue by deadsoul44** [google/built_value.dart#948]
Similar to `onSet` parameter, `onGet` should also be generated in order to be able to use `built_value` with `MobX`. Thank you.

**Comment by davidmorgan** [comment]
Could you give a bit more detail please? `onSet` is for builders; I'm not quite sure how `onGet` on builders would be useful?

Thanks.

**Comment by deadsoul44** [comment]
Very similar to `onSet`:

```dart
  int get value() { 
     onGet();       // <-- this will be generated
     return _$this._value;
}
  set value(int value) {
    _$this._value = value;
    onSet();
  }
```
