### ISSUE TITLE
Copy&paste friendly error messages from BuiltValueGenerator

### ISSUE THREAD

**Issue by BlackHC** [google/built_value.dart#95]
It would be neat to have errors ala:
```
Please make the following changes to use BuiltValue:

1. Import generated part: part 'ast.g.dart';
2. Make class have exactly one constructor: Constant._();
3. Make class have factory: factory Constant([updates(ConstantBuilder b)]) = _$Constant;
```
formatted in a way that makes the suggestions easier to copy and paste by adding additional newlines:
```
Please make the following changes to use BuiltValue:

1. Import generated part: 
  
  part 'ast.g.dart';
 
2. Make class have exactly one constructor:
   
  Constant._();

3. Make class have factory:
  
   factory Constant([updates(ConstantBuilder b)]) = _$Constant;
```
It could also be an option just for people with bad mouse skills like me.

---

Or alternatively, could we apply patches right away after prompting the user? dart tool/build.dart is a somewhat manual process already, it could be nice to add the convenience of fixing stuff automatically :) 

Thanks,
 Andreas

**Comment by davidmorgan** [comment]
The "more whitespace" approach seems reasonable, I'll take a look at some point.

I'd suggest using a watch script instead of build.dart. It would be nice to apply fixes automatically. I'll create an issue for that one.

**Comment by davidmorgan** [comment]
https://github.com/google/built_value.dart/issues/100

**Comment by davidmorgan** [comment]
I'm going to close this one -- I think the final solution for this area will be an analyzer plugin that gives suggestions for fixes. So, no need to copy and paste.
