### ISSUE TITLE
How to distinguish map and list with Custom built_value Serializers

### ISSUE THREAD

**Issue by TomVista** [google/built_value.dart#952]
in `` deserialize `` always get a `` list ``,  but my source data type is ``Map`` or  ``List `` (``jsondecode(jsonStr) ``) , just want to deserialize item to String,how can i do that,

my Custom Serializers
```
import 'dart:convert';

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'jsonb.g.dart';

abstract class Jsonb implements Built<Jsonb, JsonbBuilder> {
  @BuiltValueSerializer(custom: true)
  static Serializer<Jsonb> get serializer => JsonbSerializer();

  @nullable
  String get value;

  @nullable
  BuiltList<String> get values;

  Jsonb._();

  factory Jsonb([updates(JsonbBuilder b)]) = _$Jsonb;
}

class JsonbSerializer implements StructuredSerializer<Jsonb> {
  @override
  Jsonb deserialize(Serializers serializers, Iterable serialized, {FullType specifiedType = FullType.unspecified}) {
    final result = new JsonbBuilder();

    print('serialized');
    print(serialized);

    Map<String, dynamic> jsonmap = {};
  
    final iterator = serialized.iterator;

    while (iterator.moveNext()) {
      if (iterator.current != null) {
        final key = iterator.current as String;
        iterator.moveNext();
        final dynamic value = iterator.current;
        // for each key, assign the correct value to the builder
        jsonmap.addAll({key: value});
      }
    }

    result.value = jsonEncode(jsonmap);

    return result.build();
  }

  @override
  Iterable serialize(Serializers serializers, Jsonb object, {FullType specifiedType = FullType.unspecified}) {
    final result = <Object>[];

    if (object.value != null) {
      var json = jsonDecode(object.value);
      if (json is Map) {
        json.forEach((key, value) {
          result.add(key);
          result.add(value);
        });
      }
      if (json is List) {
        /// todo
      }
    }

    return result;
  }

  @override
  // TODO: implement types
  Iterable<Type> get types => [Jsonb, _$Jsonb];

  @override
  // TODO: implement wireName
  String get wireName => 'Jsonb';
}

```

**Comment by davidmorgan** [comment]
By default serialization uses lists; use `StandardJsonPlugin` to make it use maps

https://medium.com/flutter-community/using-standardjsonplugin-with-built-value-for-flutter-4a4657b34737

**Comment by TomVista** [comment]
i use ferry ,and ferry use build_value, ferry default Serializers has ``StandardJsonPlugin``


a json like this

```
{
  userName:'tom',
  userAddress:[
    {},{}
   ]
}
```


at before deserializer ,`` StandardJsonPlugin `` turn Map to list,

```
["userName","tom","userAddress",[{},{}]]
```

and then  ferry do that
```
serializers.deserializer([{},{}])
```

after `` StandardJsonPlugin ``,custom deserializ funcation get

```
[{},{}],
```
but , my custom serializers also work for ``{}``, at this way ,got a ``Iterable`` ``List`` too

```
["name","name"]
```

Is there one way to serialize ``Iterable`` to `` List `` or `` Map ``,correctly

**Comment by davidmorgan** [comment]
Ah, sorry, my answer was backwards.

Custom serializers need to be written to handle lists, they won't get maps. This is by design, otherwise you'd need a different serializer implementation depending on whether `StandardJsonSerializerPlugin` was installed.

**Comment by TomVista** [comment]
so, you mean,i need remove ``StandardJsonSerializerPlugin ``?

**Comment by davidmorgan** [comment]
No, that won't help; custom `StructuredSerializer` instances _always_ accept and return lists, not maps.

A `PrimitiveSerializer` is allowed to use a single value which can be a list or a map, see e.g.

https://github.com/google/built_value.dart/blob/master/built_value/lib/src/json_object_serializer.dart

which serializes

https://github.com/google/built_value.dart/blob/master/built_value/lib/json_object.dart

**Comment by TomVista** [comment]
Thank you very much,its prerfect,I can get off work
