### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by thor-jc** [google/built_value.dart#953]
hello, 

I've been using the Built libraries for a while now and I think they are very powerful.  One of my next steps was to move to 'object validation' (not form field validation).  

For example,  in a concept like 'Effective' I'd like to ensure that the start is before the end.  Just that simple.  I've read this quote:
> It has first class support for validation via Built Values. An important part of a powerful data model is ensuring it's valid, so classes can make guarantees about what they can do. Other libraries also support validation but usually in a less prominent way.

But I can't seem to find anything to support this concept.  I'm fairly new to dart, flutter and these libs so I'd appreciate if you could point me in the right direction.  I'm looking for some sort of annotation or custom validators to ensure objects are valid 'during building'.

Regards,
John

**Comment by davidmorgan** [comment]
The simple way to do violation is to write anything you like in the class's private constructor :)

Instead of:

```
Foo._();
```

write a constructor body doing any checks you like:

```
Foo._() {
  if (!myField.startsWith('a')) throw 'myField must start with a';
}
```

This will run when `build` is called, rather than on the builder.

**Comment by thor-jc** [comment]
Thanks.  Makes sense.  I guess I was curious if there were annotations or validator methods or libraries that would have some more built in functionality.  If not, feel free to close.

**Comment by davidmorgan** [comment]
Other libraries could hook in here :) but there's nothing in `built_value`.

Thanks.
