### ISSUE TITLE
Flutter pub get versioning fails with build_runner 1.10.3+

### ISSUE THREAD

**Issue by jamesncl** [google/built_value.dart#956]
Using:

> environment:
>     sdk: ">=2.7.0 <3.0.0"
> dev_dependencies:
>     build_runner: ^1.10.3
>     built_value_generator: ^7.1.0

With Flutter stable channel v1.22.5 results in the following when running pub get:

> Because build_resolvers >=1.4.4 depends on analyzer >=0.40.1 <0.42.0 and build_resolvers >=1.4.0 <1.4.4 depends on analyzer ^0.40.1, build_resolvers >=1.4.0 requires analyzer >=0.40.1 <0.42.0.
> And because built_value_generator >=7.0.8 depends on analyzer ^0.39.3 and build_runner >=1.10.3 depends on build_resolvers ^1.4.0, built_value_generator >=7.0.8 is incompatible with build_runner >=1.10.3.
> So, because my_project depends on both build_runner ^1.10.3 and built_value_generator ^7.1.0, version solving failed.
> pub get failed (1; So, because my_project depends on both build_runner ^1.10.3 and built_value_generator ^7.1.0, version solving failed.)

**Comment by davidmorgan** [comment]
Sorry about that. You can get around it win a pin on analyzer until a new version is published, please see https://github.com/google/built_value.dart/issues/923

**Comment by jamesncl** [comment]
Thanks for the info. Unfortunately pinning analyzer causes other problems for me, so I'll just hold off for now.

**Comment by davidmorgan** [comment]
`built_value_generator` version `8.0.0-nullsafety.0` is now available.

**Comment by davidmorgan** [comment]
I think this issue can be closed--there is another version bump pending though, please see #987 for that one.
