### ISSUE TITLE
built_value_generator v8.0.0-nullsafety not on pub.dev?

### ISSUE THREAD

**Issue by jlewicki-nevo** [google/built_value.dart#957]
I don't see a prerelease version of `built_value_generator` that supports null safety at pub.dev, even though (based on pubspec.yaml in the repo) it looks like the package currently supports null safety.

I see that `built_value` and `built_collections` have nullsafety versions published to pub.dev, so I'm just wondering if it was an oversight to not yet publish `built_value_generator` v8.0.0-nullsafety?  Or is it by design?

Just thought I'd ask because in case it was an oversight, since it would be useful for migrating my own packages to null safety.

**Comment by jlewicki-nevo** [comment]
And now I see in the commit history that this was by design.  Never mind!

**Comment by deadsoul44** [comment]
So, are you able to generate code? I tried to run build runner with null safety flags but it didn't work.
