### ISSUE TITLE
`EnumClass` how to support upgrade

### ISSUE THREAD

**Issue by jerryzhoujw** [google/built_value.dart#959]
### Here's the question

For app's version 1:

- message have a type: NotifyMessageType
- message type is an enum: [SYSTEM, USER_FOLLOW]

For app's version 2:

- update message type as an enum: [SYSTEM, USER_FOLLOW, NEW_TYPE]

#### Now the upgrade situation

app version 1: can decode response contain enum version 1.
app version 2: can decode response contain enum version 2.

but, if app version 1 decode api response with version 2, it will failed. can exception the response handler. 

How to properly handle the EnumClass upgrade will exception the response decode ?

```dart
class NotifyMessageType extends EnumClass {
  static Serializer<NotifyMessageType> get serializer =>
      _$notifyMessageTypeSerializer;

  @BuiltValueEnumConst(wireName: 'SYSTEM')
  static const NotifyMessageType system = _$system;

 @BuiltValueEnumConst(wireName: 'USER_FOLLOW')
  static const NotifyMessageType userFollow = _$userFollow;

  static BuiltSet<NotifyMessageType> get values => _$values;
  static NotifyMessageType valueOf(String name) => _$valueOf(name);
}

abstract class NotifyMessage implements Built<NotifyMessage, NotifyMessageBuilder> {
  static Serializer<NotifyMessage> get serializer => _$notifyMessageSerializer;

  @nullable
  NotifyMessageType get msgType;

  @nullable
  String get content;

  NotifyMessage._();
  factory NotifyMessage([updates(NotifyMessageBuilder b)]) = _$NotifyMessage;
}
```

#### How I handle it now

I just use String to decode the Enum case for now, if the enum is new value in app version 1,  this way will not have exception in json decode.
But would be better if `EnumClass` can handle it.

```dart
abstract class NotifyMessage implements Built<NotifyMessage, NotifyMessageBuilder> {
  static Serializer<NotifyMessage> get serializer => _$notifyMessageSerializer;

  @nullable
  String get msgType;

  @nullable
  String get content;

  NotifyMessage._();
  factory NotifyMessage([updates(NotifyMessageBuilder b)]) = _$NotifyMessage;

  bool get isSystem => msgType == 'SYSTEM';
  bool get isUserFollow => msgType == 'USER_FOLLOW';
}
```

**Comment by jerryzhoujw** [comment]
maybe if `EnumClass ` can handle not listed type as nil would be better suit in this case ?

**Comment by dave26199** [comment]
You can mark one of the values as fallback for if an unknown value is
encountered using

https://pub.dev/documentation/built_value/latest/built_value/BuiltValueEnumConst-class.html

**Comment by jerryzhoujw** [comment]
Thank you @dave26199
