### ISSUE TITLE
Add live templates for BuiltValue classes

### ISSUE THREAD

**Issue by BlackHC** [google/built_value.dart#96]
I'm lazy. Here is a live template for adding new bare BuiltValue classes to our favorite IDE :)

It triggers from builtvalue to:
```
abstract class $NAME$ implements Built<$NAME$, $NAME$Builder> {
  $NAME$._();
  factory $NAME$([updates($NAME$Builder b)]) = _$$$NAME$;
}
```

I've attached the template. You can copy it to ~IntelliJ IDEA<version>/config/templates. I might update it with additional templates for the part file and imports.

[BuiltValue.xml.zip](https://github.com/google/built_value.dart/files/679363/BuiltValue.xml.zip)

**Comment by davidmorgan** [comment]
Nice. I'll add it to the repo somewhere with a README.

**Comment by davidmorgan** [comment]
This is now on the README.md.
