### ISSUE TITLE
Calculate a field based on another field in a parent built class

### ISSUE THREAD

**Issue by deadsoul44** [google/built_value.dart#960]
I tried to the something like the following but it did not work:

```dart
abstract class CounterParent implements Built<CounterParent, CounterParentBuilder> {
  factory CounterParent([Function(CounterParentBuilder b) updates]) = _$CounterParent;

  CounterParent._();

  @nullable
  @BuiltValueField(wireName: 'counter1')
  Counter get counterOriginal;

  @nullable
  @BuiltValueField(wireName: 'counter2')
  Counter get counterCalculated;

  String toJson() {
    return json.encode(serializers.serializeWith(CounterParent.serializer, this));
  }

  static CounterParent fromJson(String jsonString) {
    return serializers.deserializeWith(CounterParent.serializer, json.decode(jsonString));
  }

  static Serializer<CounterParent> get serializer => _$counterParentSerializer;

  static bool _inFinalizer = false;

  static void _finalizeBuilder(CounterParentBuilder b) {
    if (!_inFinalizer) {
      _inFinalizer = true;
      b.counterCalculated.value = b.build().counterOriginal.value * 2;
      _inFinalizer = false;
    }
  }
}
```

`counterCalculated.value` is always null. Is it possible to do something like this?

This is a simplified example. Actually, some fields are not available in some api endpoints. I want to generate some of them when they are not available.

**Comment by dave26199** [comment]
Is there any particular reason it needs to be a field? The usual way to do this would be with a getter annotated @memoized. E.g.

@memoized
int get twoX => x * 2;

That way the calculation runs just once and the result is stored.

**Comment by deadsoul44** [comment]
Sorry, anything related to calculation is misleading. Currently, it is working with something like the following:

```dart
  static void _finalizeBuilder(MBuilder m) {
    if (!_inFinalizer) {
      _inFinalizer = true;
      m.data.season = m.data.season ?? m._$this._seasons?.build()?.map((s) => s?.year)?.reduce(max);
      _inFinalizer = false;
    }
  }
```

`Data get data` is a `built_value` class and so is `BuiltList<Season> get seasons` in this `M` `built_value` class.

So, if `data.season` is not available in an endpoint, it will try to extract that info from `seasons` which might be available in other endpoints.

I am not sure if this is the best approach though.

**Comment by davidmorgan** [comment]
That seems reasonable.

**Comment by deadsoul44** [comment]
thank you.
