### ISSUE TITLE
Optimize primitive serialization/deserialization

### ISSUE THREAD

**Issue by ahmednfwela** [google/built_value.dart#962]
cross reference: https://github.com/OpenAPITools/openapi-generator/issues/8271

I think built value should handle primitives differently, instead of serializing bool/num/DateTime to objects with a discriminator field, it's probably better to just call `.toString()` on them.
Same goes for deserialization.

**Comment by davidmorgan** [comment]
`built_value` supports both; pass in `specifiedType` to serialize without a discriminator.

Bools are never serialized as strings though, they end up as primitive booleans. You could change this by installing your own boolean serializer if necessary.
