### ISSUE TITLE
Different DateTime serializer in a project

### ISSUE THREAD

**Issue by mzafer** [google/built_value.dart#965]
I have situation where some of the APIs return the time in milliseconds and another API returns in ISO8601. Is it possible to configure on Model class to use the default time serializer an another to use Iso8601DateTimeSerializer ?

**Comment by davidmorgan** [comment]
One `Serializers` instance can only keep a single serializer per type.

The only way to make this work within the same data model would be to have a different class to `DateTime` for one of the two.

**Comment by mzafer** [comment]
Got it. Thanks for the response
