### ISSUE TITLE
How to write `deserialize<T>(json)` for  a type 'either A or B'

### ISSUE THREAD

**Issue by jerryzhoujw** [google/built_value.dart#966]
GraphQL have this kind of query type:  

A list with 3 different kind of objects. 

```console
{
  search(text: "an") {
    __typename
    ... on Human {
      name
      eye
    }
    ... on Droid {
      name
      power
    }
    ... on Starship {
      name
      capacity
    }
  }
}
```

### How to write the `deserialize<T>(dynamic value)` and `deserializeListOf<T>(dynamic value)` for this object  ?

```dart
T deserialize<T>(dynamic value) => standardSerializers.deserializeWith<T>(
    standardSerializers.serializerForType(T), value);

BuiltList<T> deserializeListOf<T>(dynamic value) => BuiltList.from(
    value.map((value) => deserialize<T>(value)).toList(growable: false));
```

### And more: how to `define a property` in the way of `BuiltList<T>` if this kind of list is a property of other object  ?

This case is more like to appear in `TimeLine` of `Facebook / YouTube`, with different kind of `TimeLine`

```dart
abstract class SomeModel implements Built<SomeModel, SomeModelBuilder> {
  static Serializer<SomeModel> get serializer => _$someModelSerializer;

  String get searchKey;

  @nullable
  BuiltList<T> get searchResult;   =>  What should be T here ?
}
```

**Comment by davidmorgan** [comment]
Mapping from `T` to the right serializer needs a map or a `switch` statement for each type it could be.

`SomeModel` should be written `abstract class SomeModel<T>`, see e.g. 

https://github.com/google/built_value.dart/blob/master/example/lib/generics.dart

**Comment by avechuche** [comment]
I have same problem, any solution? Thx
