### ISSUE TITLE
Custom field serializer

### ISSUE THREAD

**Issue by jaripekkala** [google/built_value.dart#968]
Hi,

in short, we would like to define a custom serializer for one field only.

```dart
@BuiltValueField(type: FullType(IntOrString))
String get field;
```
```dart
// Generated
result.field = serializers.deserialize(value,
    specifiedType: const FullType(IntOrString)) as String;
```

This is already possible with a custom serializer for the model (lot of code, in big models) or by using custom primitives (+ custom builder for the model, if want to use the preferred primitive directly). Just proposing a shorthand for this.

**Comment by davidmorgan** [comment]
Thanks. This doesn't look like something I'll be able to add soon, but I'll consider it when adding the next batch of features.

**Comment by davidmorgan** [comment]
Same as https://github.com/google/built_value.dart/issues/1046
