### ISSUE TITLE
Support BuiltValue class hierarchies

### ISSUE THREAD

**Issue by BlackHC** [google/built_value.dart#97]
Not sure how feasible this is, but it would be neat if one could inherit in one BuiltValue class from another BuiltValue class and it would do the right thing.

Given `abstract class A implements Built<A, ABuilder> {...}`:
```dart
abstract class B implements Built<B, BBuilder>, A {
  ...
}
```

BBuilder would have to implement ABuilder and the generator would need to look at the super class chain.

---

As a simpler alternative, it would suffice to support implementing pure abstract base classes:
```dart
abstract class Statement {
  Label get label;
}

abstract class Axiom implements Statement, Built<Axiom, AxiomBuilder> { ... }
abstract class Proof implements Statement, Built<Proof, ProofBuilder> { ... }
```

Right now, I have to copy&paste the getters into the sub-classes for the generator to pick them up and then keep them up-to-date. (Not a lot of work for small hierarchies but still duplicated code.)

Thanks,
 Andreas

**Comment by davidmorgan** [comment]
Yes, properties to generate for should be pulled from all implemented interfaces / mixins. This is covered here

https://github.com/google/built_value.dart/issues/22 

-- I did the refactoring mentioned on that issue, so it should be possible to do this soon.

Closing this issue, please follow the linked one.
