### ISSUE TITLE
Add mixins to examples

### ISSUE THREAD

**Issue by larssn** [google/built_value.dart#971]
I've run into a scenario where the `on` keyword is highly beneficial.

Is that supported?

An example of the keyword:
```
abstract class Reptile with Swim, Crawl, Bite { // Swim, Crawl, Bite have the methods seen in the Hunt mixin.
  eat(food) {
    print('Eat $food');
  }
}

mixin Hunt on Reptile {
  void hunt(food) {
    swim();
    crawl();
    bite();
    eat(food);
  }
}

class Alligator extends Reptile with Hunt {
  // Alligator Specific stuff...
}

class Crocodile extends Reptile with Hunt {
  // Crocodile Specific stuff...
}
```

**Comment by davidmorgan** [comment]
Ehhm. I'm not sure I follow, how does this relate to `built_value`? :)

**Comment by larssn** [comment]
If a built value class can be a mixin with the on keyword? The inheritance example uses normal classes

**Comment by davidmorgan** [comment]
A `built_value` class can use mixins, but it can't itself _be_ a mixin, it has to be an abstract class.

**Comment by larssn** [comment]
Well that a shame. Can we change this to a feature request then? 🙂

**Comment by davidmorgan** [comment]
In you example `Alligator` and `Crocodile` can be `built_value` classes, isn't that already what you want?

**Comment by larssn** [comment]
Sorry, that was just a quick example I pulled off the web. Here is a bit more detail, which I should have left in the first place:

```
// My main built class.
abstract class Product extends Hidable
    with Visible
    implements Built<Product, ProductBuilder>
```

Visible:
```
mixin Visible on Hidable {
  // Simplified example
  bool shouldShow() {
    return this.hidden;
  }
}
```

And Hidable:
```
@BuiltValue(instantiable: false)
abstract class Hidable {
  bool get hidden;
}
```

Basically there's value in the mixin having access to the underlying class. It greatly simplifies a lot of our signature. Unfortunately, the `on` keyword does not support interfaces, so I can't have `Product` implement Hidable, as far as I can tell, and it needs to inherit from it instead.

**Comment by larssn** [comment]
Sorry, I seem to have proven myself wrong.
Dart actually does support the signature: `mixin Visible implements Hidable`, which seems to behave as I want. It wasn't mentioned in the Dart docs, so I made an assumption. Glad to be proven wrong on this! 🙂

It wont work with the `on` keyword though.

Is it possible that we add some of these examples to the docs?

**Comment by davidmorgan** [comment]
Yep yep, I think `mixin Visible implements Hidable` is what you want.

The current examples are from before the `mixin` keyword was added to the language :D so it certainly wouldn't hurt to update them. I'll turn this into a feature request. PRs welcome ;)

**Comment by larssn** [comment]
I'll see if I have the time to squeeze in a PR, no promises. 🙂

**Comment by davidmorgan** [comment]
pART OF https://github.com/google/built_value.dart/issues/1042
