### ISSUE TITLE
How to initialize generic fields

### ISSUE THREAD

**Issue by deadsoul44** [google/built_value.dart#973]
Since type parameter cannot be accessed from `static void _initializeBuilder` method, it is not possible to initialize generic fields. Is there any workaround? I want to initialize based on all possible types of the generic. For example if T is int, initial value will be 0, if T is String, it will be ''.

**Comment by davidmorgan** [comment]
It should work to pass the builder to a generic method:

```
static void _initializeBuilder(FooBuilder b) => _initializeBuilderG(b);
static void _initializeBuilderG<T>(FooBuilder<T> b) {
  if (T == int) ...
}
```
it would make sense to have `built_value` support making `_initializeBuilder` itself generic, I'll treat this issue as a feature request.

Thanks.

**Comment by deadsoul44** [comment]
I have to add type cast because analyzer is complaining about it.

```dart
  static void _initializeBuilder(FooBuilder b) => _initializeBuilderGeneric(b);
  static void _initializeBuilderGeneric<T>(FooBuilder<T> builder) {
    if (T == int) {
      builder
        ..field1 = (-1) as T?
        ..field2 = (-1) as T?;
    }
  }
```

**Comment by deadsoul44** [comment]
This doesn't seem to work. 

```dart
  static void _initializeBuilder(FooBuilder b) => _initializeBuilderGeneric(b);
  static void _initializeBuilderGeneric<T>(FooBuilder<T> builder) {
      builder
        ..field1 = ListBuilder<T>();
  }
```

I get this:

```
---------- ERROR ----------
Unsupported operation: explicit element type required, for example "new ListBuilder<int>"

------- STACK TRACE -------
#0      ListBuilder._checkGenericTypeParameter (package:built_collection/src/list/list_builder.dart:289:7)
#1      new ListBuilder._uninitialized (package:built_collection/src/list/list_builder.dart:267:5)
#2      new ListBuilder (package:built_collection/src/list/list_builder.dart:28:12)
```

**Comment by deadsoul44** [comment]
The first example does not work either.

**Comment by davidmorgan** [comment]
Sorry, yes, that doesn't work. You'll need to use 'is', like this

```
  static void _initializeBuilder(InitializeGenericValueBuilder b) {
    if (b is InitializeGenericValueBuilder<int>) {
      b.value = 3;
    }
  }
```
actually it looks like it _does_ work to get the generic type parameter, although I did not design this :) e.g.

```
  static void _initializeBuilder<T>(InitializeGenericValueBuilder<T> b) {
    if (T == int) {
      b.value = 3 as T;
    }
  }
```

you still to use `is` somehow to avoid casting to `T`, though, so it doesn't actually get you much.

I'll add some test coverage for this.

**Comment by davidmorgan** [comment]
https://github.com/google/built_value.dart/pull/999/commits/3d971e4edeb8af093516751fd6da3cddf1f9ec62
