### ISSUE TITLE
For testing: toCode(): like toString() but valid Dart code

### ISSUE THREAD

**Issue by BlackHC** [google/built_value.dart#98]
Assuming a BuiltValue only references other BuiltValues or BuiltCollections (or objects that implement toCode?), it would be really neat if there was a way to output mostly valid Dart code to recreate the BuiltValue.

Why? For testing. I write lots of expect(builtValue, CONSTANT) tests that work like golden tests. It would be very useful to have copy&paste-able output to update tests quickly. (Especially for complex objects.)

This is different than built_json etc. as this code lives in tests and doesn't get serialized/deserialized. Similar to `repr` in Python.

Thanks,
 Andreas

**Comment by davidmorgan** [comment]
Nice idea. I think the right way to do this is as a serializer plugin, so you can choose "code" as a serialization format.
