### ISSUE TITLE
Deserializing with sound null safety is broken

### ISSUE THREAD

**Issue by miDeb** [google/built_value.dart#984]
Deserializing doesn't seem to work with sound null safety.
Here's a small example
```dart
import 'dart:convert';

import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'built_value_test.g.dart';

@SerializersFor([Login])
Serializers serializers = _$serializers;

void main(List<String> arguments) {
  var login = Login((b) => b
    ..username = 'johnsmith'
    ..password = '123456');
  print(json.encode(serializers.serialize(login)));
  serializers
      .deserialize(json.decode(json.encode(serializers.serialize(login))));
}

abstract class Login implements Built<Login, LoginBuilder> {
  String get username;
  String get password;
  Login._();
  factory Login([void Function(LoginBuilder)? updates]) = _$Login;
  static Serializer<Login> get serializer => _$loginSerializer;
}
```

Running the above example with sound null safety results in:
```
$ dart run
["Login","username","johnsmith","password","123456"]
Unhandled exception:
Deserializing '[Login, username, johnsmith, password, 123456]' to 'unspecified' failed due to: type 'List<dynamic>' is not a subtype of type 'List<Object>' in type cast
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:143:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:121:18)
#2      main (file:///home/michael/devtestprojects/built_value_test/bin/built_value_test.dart:17:8)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Running with `dart --no-sound-null-safety run` works fine.

**Comment by miDeb** [comment]
This wasn't caught by tests because they all work according to this pattern:
```dart
var serialized = [1, 'one', 2, 'two', 3, 'three'];
test('can be deserialized', () {
  expect(serializers.deserialize(serialized, specifiedType: specifiedType),
      data);
});
```
Dart infers `List<Object>` as the type for `serialized`. The output of `json.decode` however only consists of an untyped `List<dynamic>`.
If I explicitly specify `dynamic` for `serialized` (i.e. `serialized = <dynamic>[]`) in all the tests, many of them fail.

**Comment by davidmorgan** [comment]
Thanks.

The problem is that json decode does not care about nullability, but the serializer code is written assuming there are no nulls. I think I added a workaround for this in a few places but apparently not everywhere.

One option would be to do a deep copy of the data, but that's quite expensive.

**Comment by miDeb** [comment]
Maybe `Iterable.castFrom` could be used instead of doing a deep copy?

**Comment by dave26199** [comment]
Unfortunately it needs to also work for nested lists.

I think the right approach is for the top level serialize methods on `Serializers` to traverse the collection replacing with cast wrappers as needed. I'll try to take a look at this soon.
