### ISSUE TITLE
EnumClass angular mixins should be deprecated

### ISSUE THREAD

**Issue by drstonebraker** [google/built_value.dart#985]
I'm assuming that [EnumClass angular mixins](https://github.com/google/built_value.dart/blob/cb4e34fa709ac62672af182aba4c4cf41f9ed265/example/lib/enums.dart#L40) should be deprecated now that [EnumClasses can be added to `exports`](https://github.com/angulardart/angular/issues/374) and [this is now preferred by the Angular style guide](go/angulardart/style/change-detection#do-use-exports-for-static-bindings).

**Comment by dave26199** [comment]
Good point, thanks :)
