### ISSUE TITLE
How to add custom object into Build_collection(builtList)?  

### ISSUE THREAD

**Issue by gusdoe** [google/built_value.dart#986]
Hi David,

Thank you for your kind answers to all the issues listed here. I can get most of the answers from these for my cases. 
But I have an issue with Build_collection. I have a list of my own calss(so not Primitive) in built_value class. I can create it and I can give an object into the builtlist, but when I use .add method in rebuild() to add additional objects into the builtlist, it gives back only the first object. I am not sure .add method is for this use. Any suggestion?

Regards,

Gus
__________________________ >>> Object; Message Class as blow <<< ___________________
```
library built_message;

import 'dart:convert';

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'serializers.dart';
part 'built_message.g.dart';

abstract class Message implements Built<Message, MessageBuilder> {
  String get message;
  String get senderId;
  String get time;

  Message._();

  factory Message([updates(MessageBuilder b)]) = _$Message;

  String toJson() {
    return json.encode(serializers.serializeWith(Message.serializer, this));
  }

  static Message fromJson(String jsonString) {
    return serializers.deserializeWith(
        Message.serializer, json.decode(jsonString));
  }

  static Serializer<Message> get serializer => _$messageSerializer;
}
```

__________________ >>> Built Collection as below   <<<_______________________________

```
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:test_message_hydrate/model/built_message.dart';
//import 'package:test_message_hydrate/utils/failure.dart';

import 'serializers.dart';
part 'message_state.g.dart';

abstract class MessageState
    implements Built<MessageState, MessageStateBuilder> {
  ChatStatus get status;
  BuiltList<Message> get messages;
  //@nullable
  //Failure get failure;

  MessageState._();

  factory MessageState([updates(MessageStateBuilder b)]) = _$MessageState;

  String toJson() {
    return json
        .encode(serializers.serializeWith(MessageState.serializer, this));
  }

  static MessageState fromJson(String jsonString) {
    return serializers.deserializeWith(
        MessageState.serializer, json.decode(jsonString));
  }

  static Serializer<MessageState> get serializer => _$messageStateSerializer;
}

class ChatStatus extends EnumClass {
  static const ChatStatus initial = _$initial;
  static const ChatStatus loading = _$loading;
  static const ChatStatus success = _$success;
  static const ChatStatus failure = _$failure;

  const ChatStatus._(String name) : super(name);

  static BuiltSet<ChatStatus> get values => _$values;
  static ChatStatus valueOf(String name) => _$valueOf(name);

  static Serializer<ChatStatus> get serializer => _$chatStatusSerializer;
}

```

**Comment by dave26199** [comment]
Happy to help :)

Could you please post example code showing the rebuild call?

**Comment by gusdoe** [comment]
When the object class(Message) and built collection is defined as the above previous comment, I expected the chat object to contains all three message object but I can only get the 1st object with a run code as below;

import 'package:test_message_hydrate/message_state.dart';
import 'package:test_message_hydrate/model/built_message.dart';

class CodeRunner {
  static void runCode() {
    var message1st = Message((m) => m
      ..message = 'Hello there'
      ..senderId = '1'
      ..time = DateTime.now().toString());

    var chat = MessageState((c) => c
      ..status = ChatStatus.initial
      ..messages.add(message1st));

    var message2nd = message1st.rebuild((m) => m
      ..message = 'Scan barcode'
      ..senderId = '2'
      ..time = DateTime.now().toString());

    var message3rd = Message((m) => m
      ..message = 'To ask Cloi if she likes it'
      ..senderId = '1'
      ..time = DateTime.now().toString());

    chat.rebuild((b) => b..messages.add(message2nd));
    chat.rebuild((m) => m..messages.add(message3rd));

    //print(message1st);
    print(chat);

    final messageJson = chat.toJson();
    print(messageJson);

    final chatFromJson = MessageState.fromJson(messageJson)
        .rebuild((b) => b..status = ChatStatus.loading);
    print(chatFromJson);
  }
}


output :
l/flutter (27654): MessageState {
I/flutter (27654):   status=initial,
I/flutter (27654):   messages=[Message {
I/flutter (27654):     message=Hello there,
I/flutter (27654):     senderId=1,
I/flutter (27654):     time=2021-02-22 18:21:16.371747,
I/flutter (27654):   }],
I/flutter (27654): }
I/flutter (27654): {"status":"initial","messages":[{"message":"Hello there","senderId":"1","time":"2021-02-22 18:21:16.371747"}]}
I/flutter (27654): MessageState {
I/flutter (27654):   status=loading,
I/flutter (27654):   messages=[Message {
I/flutter (27654):     message=Hello there,
I/flutter (27654):     senderId=1,
I/flutter (27654):     time=2021-02-22 18:21:16.371747,
I/flutter (27654):   }],
I/flutter (27654): }

**Comment by dave26199** [comment]
The problem is here

```
chat.rebuild((b) => b..messages.add(message2nd));
```

needs to be

```
chat = chat.rebuild((b) => b..messages.add(message2nd));
```

That's because `rebuild` returns a new instance, it doesn't modify the existing one :)
