### ISSUE TITLE
Nested BuiltList instantiation seem broken

### ISSUE THREAD

**Issue by felix-ht** [google/built_value.dart#989]
I fail to create an instance of nested Built lists. This is true for simple nested lists such as `BuiltList<BuiltList<double>> `as well as BuiltLists of Built Types such as `BuiltList<BuiltList<Foo>>`

```dart
  test("fails with type 'List<Foo>' is not a subtype of type 'BuiltList<Foo>'",
      () {
    BuiltList<BuiltList<Foo>>.from([
      [Foo((b) => b.bar = 1.0)]
    ]);
  });

  test("fails with type 'List<Foo>' is not a subtype of type 'BuiltList<Foo>'",
      () {
    BuiltList<BuiltList<Foo>>.from(
        BuiltList<Foo>.from([Foo((b) => b.bar = 1.0)]));
  });

  test(
      "fails with type 'List<double>' is not a subtype of type 'BuiltList<double>'",
      () {
    BuiltList<BuiltList<double>>.from([
      [1.0]
    ]);
  });

  test("fails with type 'double' is not a subtype of type 'BuiltList<double>'",
      () {
    BuiltList<BuiltList<double>>.from(BuiltList<double>.from([1.0]));
  });

abstract class Foo implements Built<Foo, FooBuilder> {
  double get bar;

  Foo._();
  factory Foo([void Function(FooBuilder) updates]) = _$Foo;
}
```

Is also created a minimal repo that showcases the issues:
https://github.com/felix-ht/built_value_list_nesting_bug

**Comment by kuhnroyal** [comment]
The `from` takes an `Iterable<BuiltList<double>>` but you are passing a singular instance of `BuiltList<double>`.

Try something like this: 
```dart
BuiltList<BuiltList<double>>.from([BuiltList<double>.from([1.0])])
```

**Comment by felix-ht** [comment]
@kuhnroyal somehow i missed that with all the nesting, thanks :+1: 

would still be nice this worked as well:
BuiltList<BuiltList<double>>.from([[1.0]]);

**Comment by kuhnroyal** [comment]
As with normal Dart lists the `from` is not type safe. Not sure if there is something like `List.of`  for `BuiltList`.

**Comment by dave26199** [comment]
You can do this:

```
[[1, 2, 3].build(),
 [2, 3, 4].build()].build()
```

--and you could use extension methods to create e.g. build2D() if you want.

Sorry for brevity, typed on phone :)

**Comment by felix-ht** [comment]
@dave26199 thats fantastic - no idea normals lists had build!  extension truly is a powerful  language feature !

**Comment by dave26199** [comment]
Agreed, it's really cool :)

**Comment by kuhnroyal** [comment]
Didn't know there were extensions for built_collection either, nice.
