### ISSUE TITLE
Generated code elides package imports

### ISSUE THREAD

**Issue by gavindoughtie** [google/built_value.dart#99]
If your class imports like this:

`import 'foo.dart' as foo;

abstract class AppState implements Built<AppState, AppStateBuilder> {
  foo.Bar get myBar;
  // etc.
}
`

Then the generated code will fail because it will generate something like:

`class _$AppState extends AppState {
  @override
  Bar myBar;
  // etc.
}
`

Without re-importing 'foo.dart' or re-declaring the namespace.

**Comment by davidmorgan** [comment]
Thanks, will take a look. Should be a straightforward enough fix -- but I have a pile of pending PRs that need to go in first.

FWIW I usually discourage "import as" for classes; it tends to make the code verbose, I've generally had better luck with show/hide and splitting into separate files. But of course there are valid use cases and built_value should support it.

**Comment by davidmorgan** [comment]
It looks like this is still an issue for custom builders.

**Comment by davidmorgan** [comment]
It's also an issue for `@memoized` getters.
