### ISSUE TITLE
built_value_generator incompatible with build_runner 1.11.2+

### ISSUE THREAD

**Issue by MichaelM97** [google/built_value.dart#990]
The version of `analyzer` that this package depends on is causing conflicts with `build_runner`

> Because built_value_generator >=8.0.0-nullsafety.0 depends on analyzer ^0.40.0 which depends on glob ^1.0.3, built_value_generator >=8.0.0-nullsafety.0 requires glob ^1.0.3.
> And because build_runner >=1.11.2 depends on glob ^2.0.0, built_value_generator >=8.0.0-nullsafety.0 is incompatible with build_runner >=1.11.2.

Can ofc use dependency overrides for now, but a package update would be appreciated whenever possible 😄

**Comment by MichaelM97** [comment]
It's also causing conflicts with Hive 2.0.0+

> Because built_value_generator >=8.0.0-nullsafety.0 depends on analyzer ^0.40.0 which depends on crypto ^2.0.0, built_value_generator >=8.0.0-nullsafety.0 requires crypto ^2.0.0.
> And because hive >=2.0.0 depends on crypto ^3.0.0, built_value_generator >=8.0.0-nullsafety.0 is incompatible with hive >=2.0.0.

**Comment by davidmorgan** [comment]
I'd like to fix #984 before releasing a new version--if I just bumped deps then you would likely hit the runtime issue with null safety described in that issue. In https://github.com/google/built_value.dart/pull/1001 I fix that and a few other issues, hoping to get that reviewed, tested and released over the next few days.

Thanks everyone for your patience, and for using `built_value` :)

**Comment by avechuche** [comment]
Another dependency problem :) 

Because built_value_generator >=5.5.5 depends on quiver >=0.21.0 <3.0.0 and turn_app depends on quiver ^3.0.0, built_value_generator >=5.5.5 is forbidden.

So, because turn_app depends on built_value_generator ^8.0.0, version solving failed.

**Comment by davidmorgan** [comment]
This should now be fixed, `8.0.2` is released. Please let me know if you have further problems.
